### ISSUE TITLE
Retrieve type fields only

### ISSUE THREAD

**Issue by iNaD** [vuex-orm/vuex-orm#100]
Currently the `$fields` method on the Model returns all kind of fields (as well as the static `fields` method) and there are methods to retrieve all `Increment` fields or all fields for `belongsToMany` relationships.

I only want to send modified values to the server and while iterating on the available fields I'm checking for their types (e.g. `field.constructor.name === 'Attr'`). This works fine and I can handle different types of fields differently before sending them to the server. But if I build my application for production it becomes uglyfied and `field.constructor.name` won't return `Attr` but `c` or a similar uglyfied class name hence the comparison won't work anymore.

So some solutions I can currently think of which would solve the problem:

1. I can import `Attr` (and all other types) check if the field is an instance of `Attr` (currently I wasn't able to import it via `import x from '@vuex-orm/core';` because the core doesn't export it neither via `import Attr from '@vuex-orm/core/attributes/types/Attr';`). Maybe I'm just doing it wrong?
2. A method returning all fields extending `Type` (currently `Attr` and `Increments`)
3. Additionally a method returning all modified fields (currently I'm comparing the Model from the store with the modified version field by field)
4. A way to do 3 with computed properties? Including something like a `isDirty` computed?

**Comment by kiaking** [comment]
OK, I didn't know that uglify do such thing!

> 1. I can import Attr (and all other types) check if the field is an instance of Attr (currently I wasn't able to import it via import x from '@vuex-orm/core'; because the core doesn't export it neither via import Attr from '@vuex-orm/core/attributes/types/Attr';). Maybe I'm just doing it wrong?

You could try importing `@vuex-orm/core/lib/attributes/types/Attr`. Notice `lib`. This is the directory where all of the files be placed. I don't think this should be the solution but maybe it can be a workaround until we implement something that solves this problem.

> 3. Additionally a method returning all modified fields (currently I'm comparing the Model from the store with the modified version field by field)
> 4. A way to do 3 with computed properties? Including something like a isDirty computed?

Vuex ORM itself doesn't provide any reactivity. It's achieved by Vuex and Vue.

Sorry if I'm wrong, but are you trying to hold modified value until like user presses `save` button? And you don't want to update the state (dispatching `update` action) as user type?

If this is the case, those value could be in Vue Component local state, or in Vuex Store outside of Vuex ORM.

If I'm correct, this is a very valid use case, and I too have faced such scenario. For now, I'm placing everything in Vue Component state, but if the form is very complex, I would like to use Vuex, but Vuex ORM doesn't have such feature right now.

I have an idea to add something like `workspace` feature to solve this issue. Where you can create new workspace entity and place all modified values there until the user finally commits the changes. Is this is what might help your use case?

> 2. A method returning all fields extending Type (currently Attr and Increments)

Regardless of the above my statement, I think this is a nice feature to have. I think there's a time user want to check what attribute type the model has.

How about introducing following methods?

```js
// Get type of the field.
User.getFieldType('name') // <- 'Attr'
User.getFieldType('posts') // <- 'HasMany'

// Check field type.
User.isAttr('name') // <- true
User.isHasMany('posts') // <- true
```

**Comment by iNaD** [comment]
Hmm thought I already tried importing from `@vuex-orm/core/lib/attributes/types/Attr`, but that seems to work. Thank you 🙂

Sadly the check for `field instanceof Attr` (or `Type`, because that includes `Increment`) doesn't work for me:
```js
import { Model } from '@vuex-orm/core';
import Type from '@vuex-orm/core/lib/attributes/types/Type';

class Foo extends Model {
    $changedFields() {
        const storedUser = this.$getters('query')().find(this.$id());
        const changes = {};
        const fields = this.$fields();

        for (let key in fields) {
            const field = fields[key];
            if ((field instanceof Type) && storedUser[key] !== this[key]) {
                changes[key] = this[key];
            }
        }

        return changes;
    }
}
```

`instanceof` is always returning false. Sometimes Javascript's behaviour is really confusing... 😕 Maybe I missed something and using `instanceof` the wrong way.

---

> Sorry if I'm wrong, but are you trying to hold modified value until like user presses save button?
 And you don't want to update the state (dispatching update action) as user type?

I'm retrieving the user from the store and then I modify the returned object (e.g. with `v-model="entity.field"`). This does NOT update the store state. Until the user hits `save` the changes shouldn't be persisted (neither locally nor remotely).

So I think this should be the right way to handle this. On saving the changes are sent to the backend and then the local state is updated via Vuex-ORM.

So this is more a "Model"-thing than an "ORM"-thing. I either need the functionality to retrieve all changed data or as you suggested some helper functions to implement this myself. If the `instanceof` check would work, this could event be handled as an extension of the Vuex-ORM Model instead of a core feature.

**Comment by kiaking** [comment]
Damn, I think imported class from `@vuex-orm/core/lib/attributes/types/Attr` has become different from uglyfied bundles... 

So I guess adding method such as `User.isAttr('name')` is the way to go. Those method should be useful regardless of your issue 🚀

**Comment by iNaD** [comment]
It doesn't even work in dev where it isn't uglyfied. That's what is even more confusing. Before encountering this error I used `field.constructor.name === 'Attr'` which obviously doesn't work anymore. But `instanceof` surprisingly doesn't even work in dev.

Would be `isAttr` also true for `Increment` fields?

**Comment by kiaking** [comment]
Hugh, I think that's because Vuex ORM bundles modules into one file when exporting. And it result in different object maybe.

Maybe, if you import Model from `@vuex-orm/core/lib/model/Model` and extend it, maybe it would work? But either way, I don'T think this is the recommended approach :/

> Would be isAttr also true for Increment fields?

No, so we should add `isType` which match all the type (Attr and Increment), and `isRelation` match all relation and so on.

**Comment by iNaD** [comment]
But `isType` seems pretty generic, doesn't it? Maybe we should elaborate on this a bit more before implementation.

**Comment by kiaking** [comment]
You mean the word `type` is too generic so that user may think it would return true for everything...? The word `type` is used internally, and indeed I was struggling on this naming, so I love to hear some idea on this!

Here is basic rule Vuex ORM currently has.

1. All fields are called `Attribute`.
2. Nonrelational fields are called `Type`. I have a plan to add more specific in future too, for example `string` and `number`. Those will be `Type` as well.
3. Relational fields are called `Relation`.

I couldn'T come up with better naming for `Type`. Do you have any idea on this?

**Comment by iNaD** [comment]
Hmm what do you think of this?

```js
Model.isTypeField('name')
Model.isRelationshipField('book')
Model.isIncrementsField('id')
```

or

```js
const fields = Model.$fields()
// foreach or whatever
field.isType()
field.isRelationship()
field.isIncrements()
```

In my opinion (if it worked for me) `field instanceof Type`, `field instanceof Number`, `field instanceof Relationship` would be the cleanest and most easily extensible solution. I just have to find the reason why it fails :/

**Comment by kiaking** [comment]
I've confirmed that if I expose Attribute classes, then `instanceof` operator will work. So, I released Vuex ORM 0.21.1 that enables this!
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.21.1

Could you try using following syntax and see if it works for you?

```js
import { Attr, HasOne } from '@vuex-orm/core'
```

**Comment by iNaD** [comment]
Yes it works 🎉 Even uglyfied in production. Thank you so much @kiaking

But I'm still wondering why this works and importing directly does not 🤔 Maybe one would have to dig deeper into the whole bundling, imports etc. of webpack to find the reason.

**Comment by kiaking** [comment]
Great it worked fro you! I think the reason is because `@vuex-orm/core` is bundled js file by Rollup and not exactly same as the source code. I guess the best practice is to don't import anything from `@vuex-orm/core/lib` but instead expose through `@vuex-orm/core` :p
