### ISSUE TITLE
Add `withAll` method that retrieve all relations

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#103]
Raised from #94. It would be nice to have method like `withAll` that will load all of the relation at once.

```js
store.getters['entities/users/query']().withAll().get()
```

**Comment by timoschwarzer** [comment]
That's funny, I was just about to create an issue for this... :sweat_smile:

**Comment by kiaking** [comment]
Haha, great, we should thank @clockworked247 for bringing this up I guess : )

**Comment by timoschwarzer** [comment]
Is there someone making a PR? If not; I'll do this one...

**Comment by timoschwarzer** [comment]
Implemented in https://github.com/vuex-orm/vuex-orm/pull/106

**Comment by kiaking** [comment]
Thank you so much for your great work! This is pure awesome!
