### ISSUE TITLE
Add Model validation feature

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#108]
Raises from #93 

Base idea from @razvanioan.

> I mean that the model to validate it's data upon update, and send back validation results, results that might be interpreted differently, depending on the view & business logic (mark some input fields as invalid, adding some error info around them, dispatching notifications, etc)

I would love to discuss this idea further to design the specifications.

**Comment by timoschwarzer** [comment]
I don't think that should be a part of vuex-orm. For things like that you can always define a `validate` method in your models and call it from somewhere. Since update returns the updated model, you should be able to chain it like this:

```javascript
(await Posts.dispatch('update', { data })).validate() ← this method gives back validation results of the updated model
```

**Comment by kiaking** [comment]
Yea, thinking about this I pretty much agree with you. Maybe it would be nice to have this feature as a plugin though. Things like default validators, clean way to define the rules, and maybe the easy way to define error messages too.

But yes, I don't think it should be implemented in the core since there'll be quite a bit of code. And it's going to be a waste as of the bundled file size if people chose to not use the implemented validation and went on their own.

@razvanioan What do you think?

**Comment by razvanioan** [comment]
Ok, I agree that validation maybe should not be part of the core, but as a plugin or custom code inside model definition, but my question to you would be:

- If the model doesn't validate, should the update be made ?

**Comment by timoschwarzer** [comment]
You maybe want to insert a custom action into your module:

```javascript
actions: {
  updateIfValid({ dispatch }, payload) {
    if (payload is valid) {
      return MyModel.dispatch('update', payload)
    } else {
      return false or whatever
    }
  }
}
```

**Comment by iNaD** [comment]
I would also go for module extension by a plug-in or yourself. And validation either as model extension or an extra validator.


Looking at Laravel, neither the model, nor the ORM handles this. It's done before processing, so the vuex module should be the right place or at component level.

My components use vuelidate, import a validator which contains vuelidate rules for the model, and check before dispatching update.

**Comment by kiaking** [comment]
> If the model doesn't validate, should the update be made ?

I would say it depends on the application you're building, but most of the case, I think the update should be made. This is same for other validators such as Vuelidate but on frontend, you would want update Vuex state even it has error so that user can input forms. What you would really want to prevent is to send those data to the server isn't it? It is actually safe to update local state since it's temporary data.

If model had validation logic, I imagine usage in Vue Component would be something like below.

```vue
<template>
  <div>
    <input :value="user.name" @input="update">
    <p v-if="user.hasError">{{ user.errors.name }}</p>

    <button @click="save">SAVE</button>
  </div>
</template>

<script>
export default {
  computed: {
    user () {
      return this.getters['entities/users/find'](1)
    }
  },

  methods: {
    update (e) {
      this.$store.dispatch('entities/users/update', {
        id: 1,
        name: e.target.value
      })
    },

    save () {
      // Validate if user has valid property.
      if (!this.user.isValid()) {
        return
      }

      API.post('persistUpdatedUserInfoToTheServer')
    }
  }
}
</script>
```

In this case, if we prevent a user from updating the user, then the user can't input any value to the field.

**Comment by kiaking** [comment]
This is quite old issue, and there's no plan to add this any time soon. So, I'll be closing this for now. Please feel free to reopen, or create another issue if anybody has request on this feature!
