### ISSUE TITLE
hasOne relationship return empty model object or null

### ISSUE THREAD

**Issue by kkyouhei** [vuex-orm/vuex-orm#111]
https://codesandbox.io/s/4x0qnn088w

### version 0.20.0
<img width="548" alt="_2018-03-07_16_30_50" src="https://user-images.githubusercontent.com/300724/37079207-21a147a6-2225-11e8-997a-ce0f2c1ced09.png">

### version 0.21.0
<img width="510" alt="_2018-03-07_16_30_59" src="https://user-images.githubusercontent.com/300724/37079209-259bfc34-2225-11e8-8393-2613f872fb72.png">

Which one is correct?

**Comment by kiaking** [comment]
HasOne should return `null` if the relation can't be found. so the 0.21.0 was wrong I guess.
