### ISSUE TITLE
question: custom actions

### ISSUE THREAD

**Issue by razvanioan** [vuex-orm/vuex-orm#112]
Is there an easy way to define custom actions for a Model / Module ?

I have a model, which is having a JSON field (which I don't want to define as a related submodel, as it can have various properties depending on different options of the model itself), that's why I also store it as JSON inside my DB (which is a traditional relational DB)

How can I safely update one (or more) properties from this JSON field, without erasing the others ?

The options I think of:

* have a **submodel** defined, but I've already mentioned I'd like to avoid this for simplicity
* use `getters` to obtain current value, and update entire JSON with the modified values
* build a custom `action` (on the Model or Module) to update just the specified values from the JSON leaving the rest alone. How would I do this ?

Thanks !

**Comment by kiaking** [comment]
With Vuex ORM 0.22.0, you can pass a closure to the `data` property of the update action to have full control in such case!

```js
store.dispatch('entities/users/update', {
  where: 1,
  data (user) {
    // Let's say `settings` is the JSON field.
    user.settings.role = 'user'
  }
})
```

Would this make sense for you?

**Comment by razvanioan** [comment]
Wow, that's working as expected !

I was starting to implement custom `actions` and `mutations` inside the `Module` (not `Model`), but this solution it's much simple ;)

Thx man ;)

**Comment by kiaking** [comment]
Glad I could help! Feel free to open another issue if you have any trouble 😃

**Comment by razvanioan** [comment]
So I ended up with this multipurpose update solution, valid for entire form / model, which handles dynamically both cases: direct model values or JSON attributes, maybe some others will embrace this solution

**model.js** - name it's a JSON object, but not a related model

```javascript
import { Model } from '@vuex-orm/core'

export default class MyModel extends Model {
  static entitiy = 'mymodule'

  static fields () {
    return {
      id: this.attr(1),
      name: this.attr({
        first: 'John',
        last: 'Doe'
      }),
      age: this.attr(18)
    }
  }
}
```

**component.vue**

```javascript
<template>
  <form>
    <input type="text" name="name.first" :value="user.name.first" @update="update" />
    <input type="text" name="name.last" :value="user.name.last" @update="update" />
    <input type="number" name="age" :value="user.age" @update="update" />
  </form>
</template>

<script>
// I am using `object-path` for simplicity of the update
import objectPath from 'object-path'

export default {
  computed: {
    user () {
      return this.$store.getters['entities/mymodule/find'](1)
    }
  },

  methods: {
    update (event) {
      this.$store.dispatch('entities/mymodule/update', {
        where: this.user.id,
        data (user) {
          // this would update `age` or `name.first` and `name.last` based on field `name`
          objectPath.set(user, event.target.name, event.target.value)
        }
      })
    }
  }
}
</script>
```
