### ISSUE TITLE
Can i detect change to use insert method

### ISSUE THREAD

**Issue by soutarrr7** [vuex-orm/vuex-orm#114]
Hi ! Thank you for make this module.

I wanna change data to use getter when use insert method. 

`
const data = await this.$axios.post('/api/admin/item/create', formData)
 dispatch('entities/items/insert', { data: data }, {root: true})
`

`
computed: {
    list () {
      return this.$store.getters['entities/items/query']().where('item_category_id', this.item_category_id).orderBy('id', 'desc').get()
    }
  }
`

thank you for read !!

**Comment by kiaking** [comment]
Hi! Thank you for your feedback.

Are you trying to load data depending on the data inserted via `insert` action? (You want to change `this.item_category_id` when new data is inserted?)

In that case, the insert action will return newly created data so you could use that info.

```js
const data = await this.$axios.post('/api/admin/item/create', formData)

const insertedItem = await dispatch('entities/items/insert', { data: data }, { root: true })

commit('someMutation', insertedItem.item_category_id)

// Maybe keep inserted data in store state and use it in your Vue Component.
someMutation (state, categoryId) {
  date.categoryId = categoryId
}

computed: {
  categoryId () {
    return this.store.state.entities.items.categoryId
  },

  list () {
    return this.$store.getters['entities/items/query']()
      .where('item_category_id', this.categoryId)
      .orderBy('id', 'desc')
      .get()
  }
}
```

**Comment by kiaking** [comment]
OK、せっかく言葉が通じるので日本で行きましょう！ 😃 

これって、新しくデータをinsertしても、computedなオブジェクト（この場合`list`）が画面上更新されないって問題でしょうか＠＠？

ちょっとまだ問題が完璧に理解できておらず｡･ﾟ･(ﾉД`)･ﾟ･｡ もう少し情報をいただけると幸いですm(_ _)m

**Comment by soutarrr7** [comment]
ありがとうございます！

はいその通りです！
新規でインサートした際にlistが更新されず画面にインサートしたものが表示されなくて困っています。

ややこしくて申し訳ないです・・。

**Comment by kiaking** [comment]
う〜ん、謎いですね。この[Example](https://github.com/vuex-orm/vuex-orm-examples)でも`insert`は使っていて、ちゃんと画面が更新されるのを確認してます。なので、なにか違いがあるのかもしれません。

こちら、より深い調査のために、差し支えなければ今のコードを動かせる形でいただけたりしますか？ ここに貼るのが問題なら、 kia.king.08@gmail.com に直接メールいただく形でもOKです！

**Comment by kiaking** [comment]
こちら、 due to inactivity ということで、一旦クローズとさせていただきますね＞＜ もし何かあればどうぞお気軽にReopenしたり、新規のIssueを立ててください！ よろしくお願いします　m(_ _)m
