### ISSUE TITLE
Add method to determine the field attribute type

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#127]
Currently, Vuex ORM uses `instanceof` operator to determine the model field's attribute type. A user could do the same for the app they're creating by importing attributes from the core package, ex. `import { HasOne } from '@vuex-orm/core'`.

However, there's a problem with this approach that when someone tries to do this in another package, for example, with Vuex ORM plugin, `instanceof` will fail. So it's better to do the duck typing to determine the attribute type.

So, I'm planning to add methods to check the types such as `isAttr` and `isHasMany` and so on.

**Comment by phortx** [comment]
Would love to see that as soon as possible. I think this will not work in production: https://github.com/vuex-orm/vuex-orm-apollo/blob/master/src/queryBuilder.ts#L302

Thanks for your help! :)

**Comment by kiaking** [comment]
Yeah that code might break. We should have this methods!

**Comment by kiaking** [comment]
Wow hey @phortx You know what, I think you can work around this issue simply using `instanceof`.

Get attribute like `HasOne` from the `component` object you can get from plugins `install` method.

```js
install (components) {
  if (field instanceof components.HasOne) {
    // This should work!
  }
}
```

This should work because the class included inside `components` is coming from vuex-orm/core that the end user uses.

I still think we should implement convenience method like `isAttr` but, until it's implemented, I think you can use above approach.

**Comment by phortx** [comment]
Very nice idea! :) I will try that ASAP

**Comment by kiaking** [comment]
Great! Yeah let me drop this one. If somebody else needs them in the future, we can think about it again 👍
