### ISSUE TITLE
How use it with JSON API specificaccion

### ISSUE THREAD

**Issue by aronwolf90** [vuex-orm/vuex-orm#130]
My idea is create kind of plugin for vuex-orm, to use this standart.  A JSON-APi call look something like this (more complex examples on http://jsonapi.org/): 

```
"data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "author": {
          "related": "http://example.com/articles/1/author"
      }
    }
```

Why pick something like vuex-orm for this? to use the information like hasMany to maintain the relationships consistent.

**what I need for this?** 
- a way to tell vuex-orm to use "relationships.author" as relationship 
- a way to access relationship information when create or update data or relationships

**Why I come to you with this question?**
I was creating a library for this (the idea was to publish it later as open source) for my project (and the library works), but the task to mantain the relationships consistent was/is horrible.

PS: if it is not possible, It is totaly ok for me, I only dont want to reinvent the wheel

**Comment by kiaking** [comment]
Hi! Thank you for the feedback. Did you find solution? I just wanted to check you in that you didn't close this issue accidentally.

**Comment by aronwolf90** [comment]
Hi, 
**It was not accidentally**; I closed  It because after thinking more about the problem I come to the conclusion that I have to use my implementation more time before I can decide how integrate vuex-orm into it. **Thanks for your interest** :)

**Comment by kiaking** [comment]
Thanks for the confirmation! Glad it wasn't unintended : ) Let me know if you have any request on Vuex ORM!

**Comment by morgler** [comment]
I have the same question as well. I have a JSON-API and I would love to use vuex-orm objects with relationships. Is there a way to make this work?

**Comment by kiaking** [comment]
Currently, there's no easy way to do this. You must restructure the JSON response before you pass them into Vuex ORM insert method. We're working on for improvement though!

**Comment by damienhollis** [comment]
@kiaking would this be any easier to do now? Is anybody using JSON-API with vuex-orm?

**Comment by damienhollis** [comment]
Actually, there seems to be an plugin now https://github.com/scalient/vuex-orm-json-api

**Comment by pasikonik** [comment]
Also this one https://github.com/guillaumebriday/json-api-response-converter
