### ISSUE TITLE
HasManyThrough get only last record

### ISSUE THREAD

**Issue by kkyouhei** [vuex-orm/vuex-orm#131]
## relastionship
Country -> User -> Post
Country  ---------> Post

## code example
https://codesandbox.io/s/3kz8jkpx1

### version v0.22.0
<img width="271" alt="2018-03-28 18 03 41" src="https://user-images.githubusercontent.com/300724/38019436-844160ce-32b2-11e8-813a-e94c2e255023.png">

### version v0.23.4
<img width="234" alt="2018-03-28 18 03 50" src="https://user-images.githubusercontent.com/300724/38019444-8860872a-32b2-11e8-8cec-d1d2dbcaeedf.png">

**Comment by kiaking** [comment]
Wow, thank you so much for the report! What the hell is going on here... This is a obviously the regression.
