### ISSUE TITLE
Order by in query with nested fields

### ISSUE THREAD

**Issue by Kleemer** [vuex-orm/vuex-orm#134]
Hi,

**Scenario :** I have a One-To-Many relationship between Step and Element.

I would like to have the possibility to orderBy (steps.elements.order, 'asc') for example, but I do not think it is something that exists right now.

The issue I have right now is that when I update the order of the entities and query Steps again the order returned is the same as the first time, even though the 'order' fields have been correctly updated in the state.

So first query returns :

```
Step {
    id: 1,
    elements: [
      Element: { id: 1, order: 1 },
      Element: { id: 2, order: 2 },
      Element: { id: 3, order: 3 }
    ]
}
```

and when I update the order of element 2 and 3 I get :

```
Step {
    id: 1,
    elements: [
      Element: { id: 1, order: 1 },
      Element: { id: 2, order: 3 },
      Element: { id: 3, order: 2 }
    ]
}
```

**Comment by kiaking** [comment]
Hi! When adding constraint to the relationship, you need to use nested query constraint. You can add `orderBy` to the `elements` like this 👍 

```js
store.getters['entities/steps/query']().with('elements', (query) => {
  query.orderBy('order')
}).get()
```

**Comment by Kleemer** [comment]
It was actually all in the documentation ... Thank you so much ! 👍 And keep up the great work !

**Comment by kiaking** [comment]
Glad I could help! Let me know if you face any other trouble 👍
