### ISSUE TITLE
Help with nested relations

### ISSUE THREAD

**Issue by CinKon** [vuex-orm/vuex-orm#135]
Sorry to bother via Git-Issue, didn't know where else to ask (can't imagine StackOverflow goes this far ;) )

I have a model with 3 Layers:

```javascript
[
    { // Category
      rows: [
        {
          cells: [{}, {}, {}]
        },
        {
          cells: [{}, {}, {}]
        },
        {
          cells: [{}, {}, {}]
        }
      ]
    },
    { // Category
      rows: [
        {
          cells: [{}, {}, {}]
        },
        {
          cells: [{}, {}, {}]
        },
        {
          cells: [{}, {}, {}]
        }
      ]
    },
    { // Category
      rows: [
        {
          cells: [{}, {}, {}]
        },
        {
          cells: [{}, {}, {}]
        },
        {
          cells: [{}, {}, {}]
        }
      ]
    }
]
```

I need a getter-query, where:

- I search for a term in the values of the cells
- I get only rows, which contains cells with matching search-term-contents (hope that's clear :D )
- I get only categories with rows left

I made it this far:

```javascript
return getters['entities/category/query']()
            .with('rows', (query) => {
              query
                .with('cells', (q) => {
                  q.where((record) => {
                    return (
                      (record.title !== null &&
                        record.title.toLowerCase().includes(searchTerm.toLowerCase())) ||
                      (record.comments !== null &&
                        record.comments.toLowerCase().includes(searchTerm.toLowerCase())) ||
                      (record.fId !== null &&
                        record.fId.toLowerCase().includes(searchTerm.toLowerCase()))
                    )
                  })
                })
                .has('cells')
            })
            .has('rows')
            .get()
```

But `has('rows')` and `has('cells')` won't work here.

Help please! :)

**Comment by kiaking** [comment]
Hi! You could join [Slack Channel](https://join.slack.com/t/vuex-orm/shared_invite/enQtMzMxMTY4MzcwOTYzLTYwZDFjNTgzZDk4MDJlODJmMzk5NmNmZDBiYjIyMTVjMDk1MGRkYTEyYmNkMGM4MjRkNGJmYTBhNTIxYTA5OWI) if you are the Slack guy : ) But filing a new issue is no problem too! ❤️ 

> But has('rows') and has('cells') won't work here.

Could you elaborate a bit more on how it should work? Are you getting an empty `rows`? Or are you getting `rows` without cells? It would be really helpful if you could give the expected JSON result and what is actually get returned.
