### ISSUE TITLE
Drop support for nested schema definition

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#138]
Is it OK to drop support for nested fields definition?

```js
class User extends Model {
  static fields () {
    id: this.attr(null),
    settings: {
      role: this.hasOne(Role, 'role_id'),
      sex: this.attr('')
    }
  }
}
```

This syntax is making things really complicated in many places since we have to go walk through whole nested schema every time we interact with the schema object. It would make everything much cleaner if we can restrict such definition.

If you need to store json (object) or even an array, you can always do that with `this.attr` attribute. The only reason this nested structure exist is because it can define relationships inside.

The API is a bit of mess too. Currently, there's no way to add for example `where` clause on those nested structure.

And in future, we could introduce attribute such as `this.json` like Laravel does in database migration.

**Comment by autobrain-stanley** [comment]
I feel like it should be fine especially considering that this could work just as well:
```javascript
class User extends Model {
  static fields () {
    id: this.attr(null),
    role: this.hasOne(Role, 'role_id'),
    sex: this.attr('')
  }
  
  get settings () {
    return {
      role: this.role,
      sex: this.sex
    }
  }
}
```
Perhaps there could even be something along the lines of:
```javascript
class User extends Model {
  static fields () {
    id: this.attr(null),
    role: this.hasOne(Role, 'role_id'),
    settings: this.hasOneBy(Settings, 'id')
  }
}

class Settings extends Model {
    static fields () {
      return {
		id: this.increment()
        role: this,
        sex: this.
      }
    }
  }
}
```

**Comment by timoschwarzer** [comment]
Exactly my opinion ↑

**Comment by kiaking** [comment]
So, I'll drop the support for this (and indeed it's already dropped). There're several place in the code where I have to delete but since it's already not working, I'll just close this issue to mark as this is already something that happened.

**Comment by Tronix117** [comment]
Has the `hasOneBy` solution been implemented, or any workaround to keep a clean schema without using `this.attr('')` ?

**Comment by kiaking** [comment]
`hasOneBy` would be equal to `belongsTo`! I'm thinking to add `this.json({ ... })` (or `this.object()` maybe) attribute in the future and provide some easier way to update the nested object, but not implemented yet.
