### ISSUE TITLE
Nested morphOne entity

### ISSUE THREAD

**Issue by Kleemer** [vuex-orm/vuex-orm#145]
Hi, I have a question about how the ORM is working right now.

**Scenario :** House hasMany Doors
Door morphOne to Post
Door morphOne to Video
(not the best naming I know)

Now when I get my data from my database, it looks like this :

```
House: {
  id: 1,
  doors: [
    { id: 1,
      body: 'door1',
      doorable_id: 1,
      doorable_type: 'posts' }
  ]
}
```

However, if I do a dispatch('entities/houses/create'), the entities created are in houses and in doors, but not in posts.
Would it be possible to do that or do I have to manually run through my list and add them myself ?
Thank you for the help !

**Comment by kiaking** [comment]
Ah, interesting. Currently, this is expected behavior, because, from that object, there isn't `post` object hence Vuex ORM will not create posts.

So for now, the easiest workaround is to fetch all posts from the server separately and store them in the ORM. Then, `doors` will automatically fetch related posts when retrieving through getters.

If we were to add a feature to implement `post` in this case, should Vuex ORM create empty post record with the ID of 1 and everything else in its default value?

It kinda relates to other relationships too, for instance when a user creates a belongsTo record which has a foreign key, let's say Post belongs to User.

```js
{
  id: 1,
  title: 1,
  user_id: 1
}
```

Should then `user` record be created with ID of 1...?

**Comment by Kleemer** [comment]
I think that the feature could create an empty post record with everything as default value, but if you receive something like :

```
House: {
  id: 1,
  doors: [
    { id: 1,
      body: 'door1',
      doorable: {
        id: 3,
        value: 'abc'
      }
      doorable_id: 3,
      doorable_type: 'posts' }
  ]
}
```
then it should update the fields automatically, so here we would have a Post :
```
Post: {
  id: 3,
  value: 'abc'
}
```
And a Door :
```
Door: {
  id: 1,
  body: 'door1',
  doorable_id: 3,
  doorable_type: 'Posts'
}
```
Does that makes sense to you ?

**Comment by kiaking** [comment]
Thanks for the confirmation. I thought that should be how it works right now. Do you define `this.morphTo` attribute at Door model? If you are defining it and if still Post is not created, then it is a defect.

```js
class Door extends Model {
  static fields () {
    return {
      id: this.attr(null),
      body: this.attr(''),
      doorable_id: this.attr(null),
      doorable_type: this.attr(''),
      doorable: this.morphTo('doorable_id', 'doorable_type')
    }
  }
}
```

**Comment by Kleemer** [comment]
I was not actually, but I added it and it did not change anything, all the Doors are correctly inserted, but nothing in the Post store.

Can it be a naming issue ? My Post entity is actually called PostTexts and the Door.doorable_type returned is 'post-text', but maybe it should be 'postText' ? I'm going to try that when I can

**Comment by kiaking** [comment]
Hmm.. Thanks for the confirmation! I'll test my self too and get back to you!

**Comment by kiaking** [comment]
@Kleemer Hi! Sorry for taking so long, but could you take a look at following code? I was trying to reproduce the issue and I failed. The following code is working as you would expect. Is this the equivalent setup to yours?

```js
it.only('can create data with nested morph one and morph to relationship', () => {
  class User extends Model {
    static entity = 'users'

    static fields () {
      return {
        id: this.attr(null),
        comments: this.hasMany(Comment, 'user_id')
      }
    }
  }

  class Post extends Model {
    static entity = 'posts'

    static fields () {
      return {
        id: this.attr(null)
      }
    }
  }

  class Comment extends Model {
    static entity = 'comments'

    static fields () {
      return {
        id: this.attr(null),
        user_id: this.attr(null),
        commentable_id: this.attr(null),
        commentable_type: this.attr(null),
        commentable: this.morphTo('commentable_id', 'commentable_type')
      }
    }
  }

  const store = createStore([{ model: User }, { model: Post }, { model: Comment }])

  store.dispatch('entities/users/create', {
    data: {
      id: 1,
      comments: [
        {
          id: 1,
          user_id: 1,
          commentable_id: 1,
          commentable_type: 'posts',
          commentable: { id: 1 }
        }
      ]
    }
  })

  const expected = createState('entities', {
    users: {
      '1': { $id: 1, id: 1, comments: [1] }
    },
    posts: {
      '1': { $id: 1, id: 1 }
    },
    comments: {
      '1': { $id: 1, id: 1, user_id: 1, commentable_type: 'posts', commentable_id: 1, commentable: null }
    }
  })

  expect(store.state.entities).toEqual(expected)
})
```js

**Comment by Kleemer** [comment]
My setup is the same as yours, and the only differences I can see are :
- Like I told you Post is PostText for me but I don't see that as being an error
- In the object I am adding to the store, I have ` commentable_type: 'post-text'`
- In my store, in Comments, commentable is not empty, it actually has the full PostText in it, and the PostText entity store is empty

It was because my commentable_type did not match the entity name my God I just realized that thank you so much ! And sorry for wasting so much time ...

**Comment by kiaking** [comment]
Oh OK! Glad you found a fix! It was nice for me to that I could add more tests : )  Feel free to open another issue if you have any other trouble!
