### ISSUE TITLE
create returns existing record

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#148]
A `create` call returns an already existing record instead of the new one (a new one is actually created in the store!). When I query the last record after creating it, I have he correct one ...

(will create a JSFiddle in the next days)

**Comment by phortx** [comment]
Ehm it might be that I have an old Vuex-ORM version ... I will upgrade and give it a try 😀

**Comment by kiaking** [comment]
Ah OK, gotcha! (Hoping it's a version issue lol

**Comment by phortx** [comment]
Yes it was! Sorry for bothering you, my friend :D

**Comment by kiaking** [comment]
OK! Nice! Thanks for the confirmation : )
