### ISSUE TITLE
Add save method to the model

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#150]
From Vuex ORM 0.25.0, it is now possible to do things like `User.create()` or `user.$update()`. However, those method are pretty much just an alias of store methods. To be able to do things bit more like active record implementation, I think it's nice to have `save` method where model field value gets saved to the Vuex Store.

```js
const user = new User()

user.name = 'John Doe'

user.$save()
```

**Comment by clockworked247** [comment]
+1 to this @kiaking I actually implemented this myself in all my Models.  It'd be nice to have this baked into the library.  Thanks!
