### ISSUE TITLE
TypeError: Cannot read property 'toString' of null  vuex-orm.esm.js Line 2817 

### ISSUE THREAD

**Issue by clockworked247** [vuex-orm/vuex-orm#151]
Hi @kiaking,

I just updated to v0.24.4 to see if the new version had a fix for another issue I'm facing.  Upon updating my app broke with the following error:

TypeError: Cannot read property 'toString' of null  vuex-orm.esm.js Line 2817 

Which is part of the new IdFixer class, method processRecords().  The issue is that my ID is ```null``` and the code assumes the value is NaN or a String.

----

You might be wondering why this is happening.  When my app loads, I need to make an initial call to the server to get data.  This call is powered by a ServerInteractions model & module, which get's created and attached to the App model AFTER pulling the initial data from the server.

```
  loadApp: ({ dispatch, getters }) => {
    return new Promise( (resolve) => {
      dispatch('entities/serverInteractions/getAllWorkspaces', {}, { root: true })
        .then((workspaces) => {
          dispatch('createAppFromWorkspaces', workspaces).then((app) => {
            // load app
            app.load();
            // load current workspace
            if (getters.currentWorkspace)
              getters.currentWorkspace.load();
            else getters.workspaces[0].load();
            resolve();
          });
        });
    });
  },
```

So this first dispatch call to "getAllWorkspaces" uses a temporary instance of a serverInteractions Model to make the call, then throws it away.  Since I don't go to the trouble of setting the ID, I get the error above.

```
  getAllWorkspaces: ({ rootGetters }) => {
    let app = rootGetters['entities/apps/app'];
    let serverIntDefaults = new ServerInteraction();
    var params = {};
    return new Promise(resolve => {
      var workspaceURL = serverIntDefaults.absoluteAppPath + 'endpoints/workspaces.xqy';
      serverIntDefaults._serverRequest(workspaceURL, 'GET', 'json', true, params).then(resolve);
    });
  },
```

Anyway, I'm filing this because I think there needs to be some increase resilience in the vuex-orm code for that particular method.  I should also change my code to properly create/use/delete the Object instance.

**Comment by clockworked247** [comment]
Feel free to close this if you think this is just bad form on my part.  :)

**Comment by kiaking** [comment]
Hah, interesting. I'm willing to fix this if I can. I'm not sure why this happening. Since if the id is null, it should be converted to `'_no_key_XX'` and become string on normalization process. Is it possible for you to create reproducible code for this issue?

**Comment by clockworked247** [comment]
I'm just going to close this since I fixed the issue on my end.

**Comment by kiaking** [comment]
OK, thank you! If you have any other trouble, please let me know : )
