### ISSUE TITLE
Terrible performance with belongsTo

### ISSUE THREAD

**Issue by Xcelled** [vuex-orm/vuex-orm#154]
I'm trying to use vuex-orm to manage a huge dataset. I've defined a belongsTo relation from one entity (`materials`) to another (`items`). There are approximately 28,000 items.

When selecting 4 materials using `with('item')`, the performance is so bad it hangs the page and I have to kill it with task manager. I did some digging and I found out that in the `load` method of `BelongsTo`, the query is not being limited. As a result, each load invocation is looking through all 28,000 items instead of the 4 or so it actually needs.

As a stopgap, I modified the `BelongsTo` to look like this:

```js
class B2 extends BelongsTo {
  load(query, collection, relation) {
    const relatedPath = this.relatedPath(relation.name)

    const fks = _.map(collection, x => x[this.foreignKey]);

    const relatedQuery = new Query(query.rootState, this.parent.entity, false)
      .where(this.ownerKey || 'id', fk => fks.indexOf(fk) != -1);

    this.addConstraint(relatedQuery, relation)

    const relatedRecords = this.mapRecords(relatedQuery.get(), this.ownerKey)

    return collection.map((item) => {
      const related = relatedRecords[item[this.foreignKey]]

      return this.setRelated(item, related || null, relatedPath)
    })
  }
}
```

By limiting the search to only referenced entities, the performance drastically improved (ie, goes from 'hangs' to 'completes in <1 second'). I haven't tested this at all beyond my limited case, so I don't know where it breaks down.

My hack is also supported by the fact that I'm using the primary key as the target of the foreign key, so (I believe) the lookup is indexed. If Vuex ORM doesn't create hash-tables for all targets of a foreign key, that could be something to look into.

As it stands now, this issue means it's going to be faster for me to use Vuex directly and write query logic myself using lodash and getters, which is a shame because this library is really nice.

**Comment by kiaking** [comment]
Oh thank you for the report! 28,000 is the biggest number I saw someone using Vuex ORM. I think this can be improved (thanks to your research!). Let's fix this.

**Comment by kiaking** [comment]
I've created PR #162 to address this issue! Now with 8 items loading belongsTo relation from 30,000 records finishes in about less than 300ms 🎉  I think it is solving the issue now. I'll make a release soon.
