### ISSUE TITLE
Create or Insert a model without touching relations

### ISSUE THREAD

**Issue by huy-tran** [vuex-orm/vuex-orm#156]
Hi,

Is there any way to **create** or **insert** a model without affecting its relations. My use case here is let's say I have a collection of `User` models. When click on a `User` I'll fetch its relation such as `Member`.

So now when I run (assuming I defined relationship between `User` and `Member`)

`store.dispatch['entities/member/create', { data: member }]`

It does create a `Member` model but also affect my `User` collection. Only one `User` associated with the created `Member` left.

Thanks for your helps in advance.

**Comment by kiaking** [comment]
Hi! So the `member` contains `user` record too right? In that case, you can pass `create` / `insert` / `update` / `insertOrUpdate` option to each preset methods. In your case you could do something like this.

```js
// `create` member, but `insert` user.
store.dispatch('entities/member/create', {
  data: member,
  insert: ['user']
})
```

**Comment by huy-tran** [comment]
Hi @kiaking ,

Since I fetched **users** already so when fetching **member** from the server, I don't want to include the associated **user** (to save a query to database).

That means there's no `userId` in my `member` model.

Hope it makes sense. Thanks for your reply!

**Comment by kiaking** [comment]
Ahah. Could you paste the `member` data that you're trying to save to the state? I'm wondering if there is a bug where user would get created even if there aren't users data in member's record that you're trying to save.

**Comment by huy-tran** [comment]
@kiaking Just checked the code. I do have `userId` but no related model from the Server. So I don't think any bug on your great plugin. I ended up creating via `new Member(data)` and store it different than Vuex-ORM `data` collection. By doing this I can use it on specific Vue component, without affecting the whole data.

Thanks for your prompt reply!

**Comment by kiaking** [comment]
Oh OK! Glad you found a fix : )
