### ISSUE TITLE
Slack link is inactive

### ISSUE THREAD

**Issue by UncertaintyP** [vuex-orm/vuex-orm#161]
Hey guys,

sadly the Slack invitation link in the Readme.md is inactive. Could you be so kind to update it?

Best regards

**Comment by kiaking** [comment]
Wow sorry about that and thank you so much for reporting! Here is the new link! 

https://join.slack.com/t/vuex-orm/shared_invite/enQtMzY5MzczMzI2OTgyLTAwOWEwOGRjOTFmMzZlYzdmZTJhZGU2NGFiY2U2NzBjOWE4Y2FiMWJkMjYxMTAzZDk0ZjAxNTgzZjZhY2VkZDQ

I'll update the README too!
