### ISSUE TITLE
0.25.1 forEach of null bug

### ISSUE THREAD

**Issue by transtone** [vuex-orm/vuex-orm#164]
when use 0.25.1, it get error when store is empty:

![image](https://user-images.githubusercontent.com/46688/40522797-119539da-6005-11e8-82af-0710ffebcb68.png)
![image](https://user-images.githubusercontent.com/46688/40522836-41fbc2ba-6005-11e8-8c19-c1a904ffe191.png)

I get version back to 0.25.0, the bug is gone.

**Comment by kiaking** [comment]
Wow thanks for the reporting! Let me look into this!

**Comment by kkyouhei** [comment]
It reproduced.
please look this project api.js line 29.
https://codesandbox.io/s/zk99v19044

@kiaking can i fix it ?

**Comment by kiaking** [comment]
If you can fix it YES!!! That would be super wonderful! Thank you so much for taking effort on reproducing the issue! 👍
