### ISSUE TITLE
Child relationship doesn't insert when updating parent

### ISSUE THREAD

**Issue by myleshyson** [vuex-orm/vuex-orm#175]
I'm having trouble getting data to normalize when updating oneToMany relationship. I'm trying to insert collection_items into a collection object. I don't want to replace all the collection data, so I'm using update. Its adding the collection_item to the collection_items array under the collection object, but it's not auto incrementing the id and it's not updating the collectionItem entity. Is this the default behavior?  

```js
this.$store.dispatch('entities/collections/update', {
       where: this.collection.id,
       insert: ['collectionItem'],
       data: {
         collection_items: [{
         collection_id: this.collection.id,
         title: 'New Stuff',
        }]
       }
     })
```

Here's a screenshot of the data from this

<img width="573" alt="vuex-orm-screenshot" src="https://user-images.githubusercontent.com/11747187/41823214-64acd7c2-77ca-11e8-9f2b-f0831e62efeb.png">

I was expecting collectionItems to not be empty or for at least the collection_items field in collections to have auto incremented id. 

Is there something I'm not doing right here? Thanks!

**Comment by kiaking** [comment]
Hi! Thank you for reporting!

Yeah the `collectionItem` becoming empty is strange... Could you paste the Model definition for both `collections` and `collectionItem`? It should get normalized if there's relationship defined at `collection_items` field.

**Comment by myleshyson** [comment]
Sure!

Here are both models

```js
import { Model } from '@vuex-orm/core'
import CollectionItem from './CollectionItem'
import Color from './Color'
import Image from './Image'

class Collection extends Model {
  static entity = 'collections'

  static fields() {
    return {
      id: this.increment(),
      title: this.string('New Collection'),
      colors: this.hasMany(Color, 'collection_item_id'),
      background_textures: this.hasMany(Image, 'collection_id'),
      collection_items: this.hasMany(CollectionItem, 'collection_id')
    }
  }
}

export default Collection
```
```js
import { Model } from '@vuex-orm/core'
import Collection from './Collection'
import Background from './Background'
import Color from './Color'
import TextObject from './TextObject'
import Hashtag from './Hashtag'
import Image from './Hashtag'

class CollectionItem extends Model {
  static entity = 'collectionItem'

  static fields() {
    return {
      id: this.increment(),
      collection_id: this.attr(null),
      collection: this.belongsTo(Collection, 'collection_id'),
      title: this.string('New Collection Item'),
      price_increase: this.number(0),
      size: this.string('normal'),
      has_lettering_option: this.boolean(false),
      lettering_ption: this.string('block'),
      shape: this.string('square'),
      backgrounds: this.hasMany(Background, 'collection_item_id'),
      selected_background: this.hasOne(Image, 'collection_item_id'),
      selected_color: this.hasOne(Color, 'collection_item_id'),
      selected_background_texture: this.hasOne(Image, 'collection_item_id'),
      text_objects: this.hasMany(TextObject, 'collection_item_id'),
      hashtag: this.hasOne(Hashtag, 'collection_item_id'),
      logo: this.hasOne(Image, 'collection_item_id'),
      approved: this.boolean(false)
    }
  }
}

export default CollectionItem
```

**Comment by kiaking** [comment]
Thanks! OK, this seems like a defect. I'll try to reproduce it and see if I can fix this!

**Comment by kiaking** [comment]
I've made a fix for this issue at #176. I'll merge this soon and make a new release!

**Comment by myleshyson** [comment]
Awesome thanks! This library is awesome.

**Comment by kiaking** [comment]
This issue is noe resolved at Vuex ORM 0.25.3 🎉
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.25.3

@myleshyson Thank you so much for the report!

**Comment by myleshyson** [comment]
@kiaking Hey so I'm actually having the opposite problem now. The **collectionItems** entity is being updated, but the collection_items field in the **collections** entity is showing '_no_key_2'.

**Comment by kiaking** [comment]
@myleshyson Hi! That might be expected behavior. Even the `collection_items` has `_no_key_*`, it should load correct relationship as long as you have correct foreign key. Do you have any trouble actually loading the items?

**Comment by myleshyson** [comment]
Oh! Ok i get it now. Yes it works fine like you said.

**Comment by kiaking** [comment]
Great! Thank you for confirming! 👍
