### ISSUE TITLE
Cannot read property 'hasPivotFields' of undefined

### ISSUE THREAD

**Issue by mbajur** [vuex-orm/vuex-orm#179]
Hello,
i'm trying to use One to One relationship in one of my models. Incoming request data has a following format:

![image](https://user-images.githubusercontent.com/581569/42047692-4cd331ca-7b01-11e8-8837-1366afb40033.png)

And my models looks like that:

```
import { Model } from '@vuex-orm/core'

export default class Account extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'accounts'

  // List of all fields (schema) of the post model. `this.attr` is used
  // for the generic field type. The argument is the default value.
  static fields() {
    return {
      id: this.attr(null),
      is_admin: this.attr(false),
      username: this.attr(''),
      display_name: this.attr(''),
      bio: this.attr(''),
      avatar_urls: this.attr({}),
    }
  }
}

export default class Comment extends Model {
  static entity = 'comments'

  static fields() {
    return {
      id: this.attr(null),
      body: this.attr(''),
      body_html: this.attr(''),
      children_count: this.attr(0),
      created_at: this.attr(null),
      depth: this.attr(null),
      is_voted: this.attr(false),
      votes_count: this.attr(null),
      story_id: this.attr(null),
      parent_id: this.attr(null),
      account_id: this.attr(null),
      closed: this.attr(false),
      replyOpened: this.attr(false),
      account: this.belongsTo(Account, 'account_id'),
      story: this.attr({}),
    }
  }
}

```

And i'm triggering:

```
dispatch('entities/comments/create', { data: resp.data }, { root: true })
```

This all gives me 

![image](https://user-images.githubusercontent.com/581569/42047771-86a2787a-7b01-11e8-88e2-1321a9410054.png)

What does this error means? Can you please advise me on what have i done wrong? :)

Thanks

**Comment by mbajur** [comment]
It was caused by the fact that vuex-orm is not auto-populating associations when using `create` - i need to fill the association store first.

**Comment by kiaking** [comment]
Hi! Glad you found fix! Let me know if you have any other trouble : )

**Comment by tinco** [comment]
I don't get it, how would you fill the associations store? Do you mean that your "accounts" are preloaded in a different request? I'm running into this issue as well, but I'm not sure whether it's due to my relationships being polymorphic or something else yet.

**Comment by tinco** [comment]
Never mind, I was an idiot and had forgotten to register the association model to my database. It populates the association stores automatically for me.

**Comment by kiaking** [comment]
@tinco Glad you found a way! Let me know if you have anything else 👍

**Comment by trickymast3r** [comment]
@tinco same here i wasted 3 hour to digg on vuex-orm source ... and after this read i know i forgot to register XD XD XD

**Comment by kiaking** [comment]
Yeah, we should have more friendly errors for sure :/
