### ISSUE TITLE
Reverse relation for hasMany()

### ISSUE THREAD

**Issue by isaiddestroy** [vuex-orm/vuex-orm#183]
Hi!
Few days ago I found your very useful plugin. And all of these days I trying to understand how I can create reverse relation for hasMany relationship, like belongsTo() in Eloquent?
For example, I have two models: 
```
class Project extends Model {
    
    static fields () {
        return {
            id: this.attr(''),
            name: this.attr(''),
            description: this.attr(''),
            tasks: this.hasMany(Task, 'project_id'),
        }
    }
}
Project.entity = 'projects'
```
and
```
class Task extends Model {
    
    static fields () {
        return {
            id: this.attr(''),
            name: this.attr(''),
            description: this.attr(''),
            project_id: this.attr(null),
            project: this.belongsTo(Project, 'project_id'),
        }
    }
}
Task.entity = 'tasks'
```
When I write in `projects` this:
```
{
    id: 1,
    name: "Name",
    description: "Description",
    tasks: [
        { id: 1, name: "Task Name", description: "Task Description", project_id: 1 },
        { id: 2, name: "Task Name", description: "Task Description", project_id: 1 }
    ]
}
```
and then I call `store.getters['entities/tasks/query']().with('projects').find(1).project`, I get `null`.
But I expected model of project, which relates on task width `id: 1`
Could you implement this functionality, please?
I hope you understand me :)
Thanks!

**Comment by kiaking** [comment]
@isaiddestroy Hi! You should use `with('project')` (not project**s**). The value passed to the `with` method should correspond to the field name defined at Task model which is `project: this.belongsTo(Project, 'project_id')`.

It is just like Eloquent defining relation with method and uses that method name to resolve relationship 👍

**Comment by isaiddestroy** [comment]
@kiaking Thank you, I understood that I had to read the documentation carefully :)

**Comment by kiaking** [comment]
No problem! Glad it helped : ) Feel free to open another issue if you have any other trouble! 👍
