### ISSUE TITLE
Removing relationship between two records without removing record from store

### ISSUE THREAD

**Issue by AELSchauer** [vuex-orm/vuex-orm#185]
Here is my data setup:

```js
export default class Deal extends Model {
  static entity = 'deals'

  static fields () {
    return {
      id:     this.attr(null),
      type:   this.attr('deals'),
      title:  this.attr(''),
      
      retailer_id:  this.attr(null),

      retailer: this.belongsTo(Retailer, 'retailer_id'),
      stores:   this.belongsToMany(Store, DealStore, 'deal_id', 'store_id'),

      // meta attributes
      retailer_queried: this.attr(false),
      stores_queried:   this.attr(false)
    }
  }
}

export default class Store extends Model {
  static entity = 'stores'

  static fields () {
    return {
      id:     this.attr(null),
      type:   this.attr('stores'),
      name:   this.attr(''),
      
      mall_id:      this.attr(null),
      retailer_id:  this.attr(null),

      deals:    this.belongsToMany(Deal, DealStore, 'store_id', 'deal_id'),
      mall:     this.belongsTo(Mall, 'mall_id'),
      retailer: this.belongsTo(Retailer, 'retailer_id'),

      // meta
      deals_queried:    this.attr(false),
      mall_queried:     this.attr(false),
      retailer_queried: this.attr(false),
    }
  }
}

export default class Retailer extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'retailers'

  // List of all fields (schema) of the post model. `this.attr` is used
  // for the generic field type. The argument is the default value.
  static fields () {
    return {
      id:       this.attr(null),
      type:     this.attr('retailers'),
      name:     this.attr(''),

      deals:  this.hasMany(Deal, 'retailer_id'),
      stores: this.hasMany(Store, 'retailer_id'),

      // meta
      deals_queried:  this.attr(false),
      stores_queried: this.attr(false),
    }
  }
}
```

Here is an example payload I'm working with:

```
{ data: 
  [
    {
      id: '100',
      title: 'deal a',
      retailer: {
        id: '100',
        name: 'retailer a',
        stores: [
          {
            id: '100',
            name: "store a"
          },
          {
            id: '101',
            name: "store b"
          },
          {
            id: '102',
            name: "store c"
          }
        ]
      },
      retailer_queried: true,
      stores: [
        {
          id: '100',
          name: "store a"
        },
        {
          id: '101',
          name: "store b"
        },
        {
          id: '101',
          name: "store c"
        }
      ],
      stores_queried: true,
    }
  ]
}
```

So here's the issue, I am using an api that follows the JSON API specification. It supports an endpoint that is exclusively for [managing relationships](http://jsonapi.org/format/#crud-updating-relationships) -- including deleting a relationship.

What I want to do is delete the relationship between a deal and a store (e.g. store 100), but I still want the relationship between that same store and the retailer to show up.

```
{ data: 
  [
    {
      id: '100',
      title: 'deal a',
      retailer: {
        id: '100',
        name: 'retailer a',
        stores: [
          {
            id: '100',
            name: "store a"
          },
          {
            id: '101',
            name: "store b"
          },
          {
            id: '102',
            name: "store c"
          }
        ]
      },
      retailer_queried: true,
      stores: [
        {
          id: '100',
          name: "store a"
        },
        {
          id: '101',
          name: "store b"
        }
      ],
      stores_queried: true,
    }
  ]
}
```

Issue 1) The directions for creating/inserting/updating relationships does not work here. As long the store 102 still exists in the $store because it is related to the retailer, then it will stay related to the deal.

Issue 2) I do not encounter issue 1 when trying to insert/update a deal record where the retailer database is empty. However, as soon as a retailer is in the database, I encounter problems. For example, I tried to work around this issue by deleting the deal record from the store, preserving the data as JSON, and then inserting the deal record with the payload above, but store 102 still appears as a related record to the deal.

Issue 3) The only way I have been able to work around this is that I must delete the entire store and then rebuild the records. It seems like the point of an ORM is that the model should manage even the most complex relationships. Deleting relationships without actually deleting the $store record seems like a pretty fundamental use case.

**Comment by kiaking** [comment]
Hi! Thank you for the report. I think this is happening because you there's a record in pivot entity (DealStore in your case). If you want to remove the relation between Deal and Store, you need to delete corresponding DealStore record.

Currently Vuex ORM doesn't offer any easy solution for this. Since it is creating pivot table, it could be nice to have option to delete pivot table records but it is quite complicated as well.

You could try deleting DealStore records before storing data, and that might work as a workaround!

**Comment by AELSchauer** [comment]
That worked great, thank you!

**Comment by kiaking** [comment]
Glad it worked! Thank you so much for your feedback. Please feel free to open another issue if you have any trouble! ❤️
