### ISSUE TITLE
Ability to Register Model / Module at Run Time

### ISSUE THREAD

**Issue by geraldbiggs** [vuex-orm/vuex-orm#187]
I have a large application with many relationships to manage where I think vuex orm could speed up my workflow. I searched the documentation to try and understand what is currently possible, below are my questions:

My use case falls under a circumstance where the user goes through complex interactions, which may result in additional modules (components, store modules, etc) being loaded in under the resulting context. 

Is there a method to register & load additional model & modules with vuex-orm after initial load? 

Additionally, are all vuex-orm modules "flattened" under entities?
 
entities/elements/earth, 
entities/elements/air, 
entities/elements/fire
vs.
entities/earth,
entities/air,
etc

Thank you.

**Comment by kiaking** [comment]
Hi! Currently, there are no ways to register model and modules at run time. I think it is nice feature to have though!

> Additionally, are all vuex-orm modules "flattened" under entities?

Yes, it will. Vuex ORM manages state as almost same as tables for the RDB. The nested structure should be managed as a relationships.

**Comment by SzNagyMisu** [comment]
I'd really love to have this feature too!
We have loads of models and it would be nice to extend [lazy loading routes](https://router.vuejs.org/guide/advanced/lazy-loading.html) strategy of vue-router to load only the models the current route (code chunk) needs.

For example with an API like

```js
database.add(MyModel)
// or
database.append(MyModel)
```

That would build up all the necessary things (schema, module state, getters, mutations, actions etc.) that is built by `database.start()` for pre-registered models.
Or perhaps `database.register()` could detect if the plugin has already been installed to vuex...

@kiaking what do you think? I think I could try to provide a PR for this.

**Comment by kiaking** [comment]
@SzNagyMisu Yeah it could be really nice to have this feature! 

> what do you think? I think I could try to provide a PR for this.

That would be awesome!!!

Maybe it could just be `database.register()`? We could set `database.isStarted` flag on initial start, and then kick start process if users adds a new model.

**Comment by kiaking** [comment]
This is now possible with Vuex ORM 0.35.0! 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.35.0
