### ISSUE TITLE
Reactive getters

### ISSUE THREAD

**Issue by mr-chick** [vuex-orm/vuex-orm#197]
Greetings.

Quick question,

Are getters reactive?

If i use `this.$store.getters['entities/user/find']('id')` to retreive an user, it won't change the fields if the user data changes.

**Comment by Gramatiik** [comment]
Hi @mr-chick, getters are reactive as long as you don't change the `id` field (which would mean changing the entity unique discriminator).

So if you update the user's informations, the getter will reflect the changes everywhere it is used and will be reevaluated everytime some of its informations are changed.

This is made possible with Vue's reactivity system (not especially related to VuexORM), you can read more on reactivity [here](https://vuejs.org/v2/guide/reactivity.html).

I would advise you to have a thorough understanding of Vue's reactivity as it helps a lot debugging common mistakes !

Have a good day.

**Comment by mr-chick** [comment]
OK, thank you

**Comment by kiaking** [comment]
@mr-chick Do remember to use getters by computed property inside Vue Component! Otherwise it won't re-render the DOM.

**Comment by kiaking** [comment]
Ahah, I never used `vue-persist` but interesting. Good hear that you found a solution though!

**Comment by Gramatiik** [comment]
Glad you found what was causing trouble @mr-chick !

I didn't replied to your second message as the code seemed to be just ok !

Have a nice day everyone.

**Comment by mr-chick** [comment]
Anyway, great job with the project, I use an laravel backend that returns models with their relations.

This plugin is perfect to parse the response and query the data.
