### ISSUE TITLE
Updating nested relationship

### ISSUE THREAD

**Issue by omarjebari** [vuex-orm/vuex-orm#198]
I have a relationship structure like this:

Complaint Model
id
...
person_id
person (foreign key relationship)

Person Model
id
...
address_id
address (foreign key relationship)

I am pulling in a bunch of person objects via ajax and simply loading them into a data property to display a list of people.
The user can then select a person from the list and i want to update the complaint with this person and ensure that the address is included with the person.

I have tried a bunch of different things to achieve this but it simply doesn't work.
What is the prescribed approach to achieve this in Vuex-ORM?

Thx

**Comment by omarjebari** [comment]
I think the problem is related to the fact that i'm initially creating a Complaint model then attaching and empty Person model (with empty Address model). Then when i come to update it with a different Person model i am using a 'create' to remove the original empty model at the same time. At some point the computed properties re-evaluate and i have a Complaint with no Person attached to it.

**Comment by kiaking** [comment]
@omarjebari Hi! Thank you for the feedback. I'm not sure how exactly the problem is occurring. If you are using `create` action, then the any existing record would be deleted so I think it is possible that you get Complaint with empty Person?

**Comment by omarjebari** [comment]
Yes essentially i want to be able to attach nested objects (eg person with address attached) to another object (eg complaint). Can this be achieved using 'update' on the complaint model or do i need to create the complaint model from scratch with the new person/address?

**Comment by kiaking** [comment]
@omarjebari Sorry for my late reply!

> Yes essentially i want to be able to attach nested objects (eg person with address attached) to another object (eg complaint).

Yeah, currently Vex ORM doesn't support nested field with relationship. You need to create complaint model to have relationship. If you only need to update the nested object and if that object doesn't have any relationship, you could do that by following syntax.

```js
store.dispatch('entities/users/update', {
  where (record) {
    return record.id === 2
  },

  data: { age: 24 }
})
```

**Comment by kiaking** [comment]
@omarjebari Hi! Did the answer above worked for you?

**Comment by omarjebari** [comment]
Not exactly but i did get to the bottom of the problem.
In order to do an update on a relationship i ended up using .then() to create the attached object 'then' attach it to the parent object. In other words if the whole relationship needs updating i just split it into separate steps and it seems to work ok.

Many thanks for your help once again :)

**Comment by kiaking** [comment]
OK great it worked for you! Feel free to open another issue if you encounter any other trouble : )
