### ISSUE TITLE
Unnecessary record is created to belongsToMany pivot table

### ISSUE THREAD

**Issue by kkyouhei** [vuex-orm/vuex-orm#201]
references object to insertOrUpdate
![_2018-07-25_23_35_15](https://user-images.githubusercontent.com/300724/43210527-5164a966-906a-11e8-9de9-9fcd3adf1223.png)
https://codesandbox.io/s/l3n381925l

this's problem of first aid
delete id field from  pivot table and separately 'insertOrUpdate' will fix it
https://codesandbox.io/s/kkm1x71wjo

**Comment by kiaking** [comment]
Thank you for the report and the PR!
