### ISSUE TITLE
Help setting up with Typescript

### ISSUE THREAD

**Issue by myleshyson** [vuex-orm/vuex-orm#204]
Hey! Do you have an example on how to setup this plugin within a Typescript project? I was able to setup Vue, Vuex, and Vue Router using typescript according to the Vuejs [docs](https://vuejs.org/v2/guide/typescript.html). I couldn't figure out how to setup this plugin however. Part of that is I'm VERY new to Typescript so I could be missing something simple. However if you have an example on how to use this plugin with Typescript that would be very helpful. Thanks!

**Comment by kiaking** [comment]
Hi! Thank you for the report! I haven't use Vex ORM with TS in the project I'm working on, but what kind of problem are you facing? I think it should work out of the box since all of the type declaration files are included.

**Comment by kiaking** [comment]
@myleshyson Hi! Did you have time to look into this?

**Comment by myleshyson** [comment]
Hey Sorry for the late response. So I just tried it on a fresh laravel install and with the Nuxt TS starter and it works great! I was trying to switch an existing project over so maybe there was something in there I was missing.

**Comment by kiaking** [comment]
Great it fixed for you! Please open a new issue if you have any other trouble : )

**Comment by kiaking** [comment]
@Robhult Oh thank you so much! Hah this might work yeah.
