### ISSUE TITLE
How to update relationships

### ISSUE THREAD

**Issue by pscheit** [vuex-orm/vuex-orm#207]
Hi there,

thanks so much for writing vuex-orm, it's great!
I think the documentation is lacking a little bit information (and that relates to my question): 
How can one update relationships?

E.g. my Usecase is the following:

```js
export default class Container extends Model {
  static entity = 'containers'

  static primaryKey = 'uid'

  static fields() {
    return {
      uid: this.attr(null), // is actually the binding.id but does not matter
 
      binding: this.hasOne(Binding, 'container_uid'),
    }
  }
}

export default class Binding extends Model {
  static entity = 'bindings'

  static fields() {
    return {
      "id": this.number(),
      "container_uid": this.attr(),

      "container": this.belongsTo(Container, 'container_uid')
    }
  }
}
```
I hope this is correct like this.

When I want to update now one container and replace a binding with another binding

```
// newBinding is an instance of Binding
// container is an instance of Container, it has a container.binding already set
// i like to modify the state in vuex-orm: container.binding === newBinding
swap({dispatch}, {container, newBinding}) {
  dispatch('entities/????/update', {
    ????
  })
}
```

That's all unclear to me:
- Which side of the relationship do I have to update? binding or container?
- Do i need to update the container_uid foreign key?
- Do i have to update the binding value in container?
- Do I have to update the binding.container value in container (as well)?
- Do I have to manage the inverse side as well?
- Can I use the model here directly? Or do I need to "reduce" them to uid/id? 

All examples in documentation for insert/update/insertOrUpdate are with json data, but I have the real models here.

Thank you so much!

**Comment by pscheit** [comment]
okay, i found my solution here - but some questions are still open

https://github.com/vuex-orm/vuex-orm-examples/blob/master/src/components/TodosAssignee.vue

**Comment by kiaking** [comment]
@pscheit Hi! Thank you for the feedback!

You should update the record you want to update. Currently Veux ORM doesn't offer any sugar syntax to update the relationship. The only value you have to update is the `container_uid` at `Binding` model in this case (because that is the key connecting two models).

So, it should be something like,

```js
swap({ dispatch }, { container, newBinding }) {
  // Delete old binding.
  dispatch('entities/bindings/delete', container.binding.id, { root: true })

  // Create new binding with correct container_uid.
  newBinding.container_uid = container.uid

  dispatch('entities/bindings/insert', {
    data: newBinding
  }, { root: true })
}
```

**Comment by pscheit** [comment]
In this code is newBinding a plain object or an instance of Model? (is both valid?)

**Comment by kiaking** [comment]
I think it's both valid (unless you set the property to `readonly`).

**Comment by pscheit** [comment]
thank you :)

**Comment by kiaking** [comment]
👍 🎉
