### ISSUE TITLE
Autoincrement leads to id clashes when fetching records

### ISSUE THREAD

**Issue by omarjebari** [vuex-orm/vuex-orm#211]
So the problem i have found can be understood by doing the following steps ...

Create a new model which has an autoincrement id. This will create a record with id: 1
Do an ajax call to pull in records from the server. If one of the records has an id of 1 then this clashes with the record already created. If we overwrite it then we lose the data that we used when creating the record on the client. If we create a new record from it then due to the autoincrement the fetched record will have an id of 2 instead of 1 so the ids on the client and server don't match.
If we don't use an autoincrement then this solves the problem but then how do we create new records on the client that don't have matching ids?

I guess we could use ajax to first create the record on the server then make sure that the server always returns the record with its id.
Another solution could be not to use the id as the primary key. Instead there could be a 'client_id' which doesn't exist on the server and is only used on the client side to identify records.

**Comment by autobrain-stanley** [comment]
I would use the model to create a new instance outside of your database. `const greg = new Person({ name: 'greg' })` Then submit that instance to your server end-point for storage and return the newly created row. Then add that row to your database.

**Comment by kiaking** [comment]
@omarjebari Yeah I think one way to solve this problem is to do the method @autobrain-stanley has explained. I used to create such temporary data with in Data object inside Due Component.

Or we could assign some kind of UID as an ID. But then, after saving data to the server side, you must be sure to refresh the ID of the data you just created at the client side.

So I would recommend @autobrain-stanley way. Create temporary data with `new Persion({ ... })` and then persist to the Store after saving it to the server side.

**Comment by kiaking** [comment]
@autobrain-stanley Hi! Do you have any progress on this issue?

**Comment by omarjebari** [comment]
It's an interesting problem. For me it is a bit confusing that the id field exists on both the server (db table) and the client side yet the client side id may have to be replaced with a different id once the data is saved on the server then this id needs to be passed back to refresh the id on the client side. Even if we immediately save the record on the server another user may have created a record in the meantime with the same id. Ultimately it seems that the id is only meaningful when it has been created on the server. If coders are conscious of this then it may be ok but it feels that there may be scenarios where extra caution is needed.
This is why i think using the name 'id' for the field could be misleading. Ultimately it would be good to have a field name which doesn't exist on the server side. A fixed name for this field could be tricky but what about declaring a primary key on the client side which can be auto incremented. Then i can choose a unique name for my PK and have it autoincrement but it gets ignored on the serverside.

**Comment by kiaking** [comment]
> This is why I think using the name 'id' for the field could be misleading. Ultimately it would be good to have a field name which doesn't exist on the server side.

I think this is a valid solution. If you have any unique key other than `id`, for example, `email`, then it should work quite good! I do have an idea of introducing the "workspace" feature where you can store temporary record and commit it once you finish editing them. Not sure exactly how it works but it could be cool to have.

**Comment by omarjebari** [comment]
Is it possible to declare a unique key (eg client_id) with an auto increment?

**Comment by kiaking** [comment]
@omarjebari Yes you can. You can use `this.increment()` to the any key you want : )

**Comment by omarjebari** [comment]
ok cool
i think this is the best option for my scenario.
many thanks :)

**Comment by kiaking** [comment]
Glad it works for you! Feel free to open another issue if you have any other troubles!
