### ISSUE TITLE
Can't access getters entities from associate module getters

### ISSUE THREAD

**Issue by alex83130** [vuex-orm/vuex-orm#212]
Is it possible to access entities getters in the associate module ?

Exemple : I have a model post, and a module posts, I would like use in the module : 

```js
const getters = {
    posts_filters: (state, getters) => getters['entities/posts/query']().filter((post) => post.type == 'example')
}
```
(Ps: This code is only a example)

Thanks in advance !

**Comment by autobrain-stanley** [comment]
@alex83130 could you set up an example in codesandbox.io ?

**Comment by kiaking** [comment]
@alex83130 You should use rootGetters for that!

```js
const getters = {
    posts_filters (state, getters, rootState, rootGetters) {
      return rootGetters['entities/posts/query']().filter(post => post.type == 'example')
    }
}
```

See the 4th argument : ) Detailed explanation is [here at Vuex Doc](https://vuex.vuejs.org/guide/modules.html#accessing-global-assets-in-namespaced-modules).

**Comment by alex83130** [comment]
I try your solution but I have this error : 
`vuex.esm.js:849 [vuex] unknown getter: parcours_creneaux_id`

With VueX Orm,  modules aren't refere in the VueX store instance, but I alsotrie with this but I have the same result : 
`export default new Vuex.Store({
  strict: true,
  modules: {
    posts
  },
  plugins: [VuexORM.install(database)]
});
`

To show you my issue I would like create a codesandbox  but I have a error that I don't in my local ...
it's on the this.$store.dispatch()
https://codesandbox.io/s/1z6wkn1913

**Comment by kiaking** [comment]
@alex83130 Hi! OK so there was a few fix needed. Here is the working example version of your code.
https://codesandbox.io/s/40mlnvpw10

1. Post models `id` field must be `id: this.attr(null)` instead of `id: 1`. The `null` doesn't have to be `null` since it is just default value so you could specify `id: this.attr(1)` if you want.

2. I misunderstood about your module needs. You can reference other getter like below.

  ```js
   posts_filters(state, getters, rootState, rootGetters) {
     return getters
       .query()
       .get()
       .filter(post => post.type == "example");
   }
  ```

Could you take a look at this?

**Comment by alex83130** [comment]
Yes it's exactly that, everything works, thank you very much !!

**Comment by kiaking** [comment]
Glad it helped! Feel free to open a new issue if you have any other questions!
