### ISSUE TITLE
Want to add http plugin, how to declare new methods or properties for Model

### ISSUE THREAD

**Issue by zhouchang2017** [vuex-orm/vuex-orm#214]
I am trying to add an http plugin for the extension,
now I am having a problem, how to use the 

> @vuex-orm/core => Model class

Declare new properties, for example, I have a Product model now.
 `Fetch:()=>Promise<any>`
, typescript will report **"Property 'fetch' does not exist on type 'typeof Product'.
"**

I am trying to add the`index.d.ts` declaration file
as follows

```
Import {Model} from '@vuex-orm/core'

Declare module '@vuex-orm/core' {

  Interface model {
    Fetch:() => any
  }

}
```

But no effect, ask for help

**Comment by kiaking** [comment]
Hi! thank you for the report. This is interesting. I have never tried extending the model class within plugin declaration with TypeScript. The following should work with plain JavaScript.

```js
const plugin = {
  install (components, options) {
    components.Model.fetch = () => {
      // Logic...
    }
  }
}
```

But well yeah I think it is true that this will throw the error since Model class doesn't have static indexed property...

I'm not sure what is the best way to implement (extend) model class within Plugin. Is this even possible...?

@phortx Hi! Have you ever experienced this issue on vuex-orm-graphql?

**Comment by phortx** [comment]
I'm doing it like this:

```
import ORMModel from '@vuex-orm/core/lib/model/Model';

export class PatchedModel extends ORMModel {
  static async fetch (filter: any, bypassCache: boolean = false): Promise<any> { return undefined; }
  static async mutate (params: ActionParams): Promise<any> { return undefined; }
  static async customQuery (params: ActionParams): Promise<any> { return undefined; }
}

(context.components.Model as (typeof PatchedModel)).fetch = async function (filter: any, bypassCache = false) { ... }
```

Maybe it helps :)

**Comment by kiaking** [comment]
Ah OK, thanks! Well, that's kinda cool. So when the user wants to use TypeScript at their project, they should import PatchedModel as an interface...?

It would be nice if we can just somehow extend the imported class and let the user just import Model from `@vuex-orm/core`. But not sure how to do that... Could we do that by providing declaration file as @zhouchang2017 stated...? I need TypeScript Pro for this :p

**Comment by zhouchang2017** [comment]
I think we can refer to the vue official ts type declaration. Since you look at your source code, 
Should declare an Interface for Model，


[https://vuejs.org/v2/guide/typescript.html#ad](url)
```
// vue/types/vue.d.ts

export interface Vue {
  readonly $el: HTMLElement;
  readonly $options: ComponentOptions<Vue>;
  readonly $parent: Vue;
  readonly $root: Vue;
  readonly $children: Vue[];
  readonly $refs: { [key: string]: Vue | Element | Vue[] | Element[] };
  readonly $slots: { [key: string]: VNode[] };
  readonly $scopedSlots: { [key: string]: ScopedSlot };
  readonly $isServer: boolean;
  readonly $data: Record<string, any>;
  readonly $props: Record<string, any>;
  readonly $ssrContext: any;
  readonly $vnode: VNode;
  readonly $attrs: Record<string, string>;
  readonly $listeners: Record<string, Function | Function[]>;

  $mount(elementOrSelector?: Element | string, hydrating?: boolean): this;
  $forceUpdate(): void;
  $destroy(): void;
  $set: typeof Vue.set;
  $delete: typeof Vue.delete;
  $watch(
    expOrFn: string,
    callback: (this: this, n: any, o: any) => void,
    options?: WatchOptions
  ): (() => void);
  $watch<T>(
    expOrFn: (this: this) => T,
    callback: (this: this, n: T, o: T) => void,
    options?: WatchOptions
  ): (() => void);
  $on(event: string | string[], callback: Function): this;
  $once(event: string, callback: Function): this;
  $off(event?: string | string[], callback?: Function): this;
  $emit(event: string, ...args: any[]): this;
  $nextTick(callback: (this: this) => void): void;
  $nextTick(): Promise<void>;
  $createElement: CreateElement;
}

# For example, to declare an instance property $myProperty with type string

// 1. Make sure to import 'vue' before declaring augmented types
import Vue from 'vue'

// 2. Specify a file with the types you want to augment
//    Vue has the constructor type in types/vue.d.ts
declare module 'vue/types/vue' {
  // 3. Declare augmentation for Vue
  interface Vue {
    $myProperty: string
  }
}

```

**Comment by phortx** [comment]
> Ah OK, thanks! Well, that's kinda cool. So when the user wants to use TypeScript at their project, they should import PatchedModel as an interface...?

I think you misunderstood my example. I've done this in the GraphQL Plugin in order to declare my own model class and to avoid any TypeScript errors. Don't know whether that's a good idea and what issues this may result in when someone has a typescript based project, but it least it works within the graphql plugin and allows me do modify the model without having the compiler beefing around :D

> It would be nice if we can just somehow extend the imported class and let the user just import Model from @vuex-orm/core

Not sure if this is possible with TypeScript 🤔 

> I need TypeScript Pro for this :p

Then I'm out :D Sorry

**Comment by kiaking** [comment]
@zhouchang2017 Hi! Thank you for trying out on creating http plugin. Now, @KaniRobinson has created [Vuex ORM Axios](https://github.com/vuex-orm/plugin-axios). Let's bring the discussion over there if this still needs attention.

**Comment by SargoDarya** [comment]
I would reopen this as it's not possible with TypeScript to augment classes in definition files. What @kiaking wrote actually should kind of work but only when the d.ts file of vuex-orm would specify it as an interface instead of a class.

**Comment by kiaking** [comment]
@SargoDarya Ah, you got point. Yeah it has to be interface. But the `d.ts` file should be in plugin package, not in Core isn't it?

**Comment by kiaking** [comment]
@SargoDarya Hi thank you so much for the proposal! The PR would be awesome!

Oh I didn't know we needed the interface not the class. Hmm...

**Comment by xaralis** [comment]
Any progress on this?

**Comment by kiaking** [comment]
@xaralis Not much! I haven't had time to check typings with plugin integrations.

**Comment by SargoDarya** [comment]
Same here, haven't had the time yet unfortunately.
