### ISSUE TITLE
Many to Many in another Many to Many

### ISSUE THREAD

**Issue by alex83130** [vuex-orm/vuex-orm#217]
Hi,

I'm trying to set up a double many to many.  Let me explain : 

![image](https://user-images.githubusercontent.com/15250423/44655541-c90db300-a9f5-11e8-8bda-cb42ddbc912d.png)

I have 3 primaries entities : Itinary, Slottime, Events
Itinerary and Slottime are in Many to Many relation (ItinerarySlottime).
And ItinerarySlottime have a Many to Many relation with Event (EventItinerarySlottime).

Next is data's API that I need to load : 

```js
export const itineraries = [
  {
    id: 1,
    slottimes: [
      {
        id: 1,
        events: [
          {
            id: 1
          },
          {
            id: 2
          }
        ]
      },
      {
        id: 2,
        events: [
          {
            id: 3
          },
          {
            id: 4
          }
        ]
      }
    ]
  },
  {
    id: 2,
    slottimes: [
      {
        id: 2,
        events: [
          {
            id: 2
          },
          {
            id: 3
          }
        ]
      },
      {
        id: 4,
        events: [
          {
            id: 1
          },
          {
            id: 4
          }
        ]
      }
    ]
  }
];
```

In my test I have succeeded to have Itineraries and Slottimes and the intermediate table (ItinerarySlottime),  but Event and the intermediate table EventItinerarySlottime are empty ...

I have create a sandbox : https://codesandbox.io/s/pkzvpx7j50

Maybe my data structure is wrong.. I'm looking since a moment but and I don't find :/

**Comment by alex83130** [comment]
The only solution that I found is to connect the ManyToMany relation directly in the Slottime table but it's not exatly the correct structure of my data...

![image](https://user-images.githubusercontent.com/15250423/44656172-27d42c00-a9f8-11e8-9931-a7e77467f468.png)

Sandbox: https://codesandbox.io/s/rjvk3n460o

**Comment by kiaking** [comment]
Hi! I think you have wrong order of argument setup at `belongsToMany` relationship. Could you change the order at the Itinerary and Slottime as below and see what happens?

```js
export default class Slottime extends Model {
  static entity = "slottimes";

  static fields() {
    return {
      id: this.attr(null),
      events: this.belongsToMany(
        Event,
        EventSlottime,
        "event_id",
        "slottime_id"
      )
    };
  }
}

export default class Itinerary extends Model {
  static entity = "itineraries";

  static fields() {
    return {
      id: this.attr(null),
      slottimes: this.belongsToMany(
        Slottime,
        ItinerarySlottime,
        "slottime_id",
        "itinerary_id"
      )
    };
  }
}
```

**Comment by alex83130** [comment]
@kiaking I do your change but I have the same issue : https://codesandbox.io/s/mm83j524xj

My data in enter is : 

```
export const itineraries = [
  {
    id: 1,
    slottimes: [
      {
        id: 1,
        events: [{ id: 1 }, { id: 2 }]
      },
      {
        id: 2,
        events: [{ id: 3 }, { id: 6 }] // <-------
      }
    ]
  },
  {
    id: 2,
    slottimes: [
      {
        id: 2,
        events: [{ id: 2 }, { id: 3 }] // <-------
      },
      {
        id: 4,
        events: [{ id: 1 }, { id: 4 }]
      }
    ]
  }
];
```

So normaly if I get the itineraries entities I sould have the same sructure but I have a error : 

```
[
  {
    id: 1,
    slottimes: [
      {
        id: 1,
        events: [{ id: 1 }, { id: 2 }]
      },
      {
        id: 2,
        events: [{ id: 2 }, { id: 3 }]  // <-------
      }
    ]
  },
  {
    id: 2,
    slottimes: [
      {
        id: 2,
        events: [{ id: 2 }, { id: 3 }] // <-------
      },
      {
        id: 4,
        events: [{ id: 1 }, { id: 4 }]
      }
    ]
  }
]
```
The Itinerary Id 2 -> Slottime Id 2 have overide The itinerary Id 1 -> Slottime Id 2

**Comment by kiaking** [comment]
Thank you for checking! OK, I need to look into this deeper, but I'm short of time, so I'll get back to you once I've time! Sorry for the inconvenience.

**Comment by kiaking** [comment]
@alex83130 Hi! So sorry for my late reply. I've looked into this.

Now I understand that this is happening because the slottimes with same ID gets merged by single nested layer, hence your comment 'The "Itinerary Id 2 -> Slottime Id 2" have overide the "Itinerary Id 1 -> Slottime Id 2"' is correct.

Now I'm not sure what is the right behavior for this one. Maybe we should do deep merging when normalizing the data...? But for me, it seems weird that the 2 same object has different property...

**Comment by kiaking** [comment]
Oh I see.

> I think that the best way to fix it, will be to could add a relation one-to-many in a table relation many-to-many.

Yeah it should fix and it should be possible with Vuex ORM, but maybe bit hard on server side...? Do you think you can fix the issue at your side? Or is there anything Vuex ORM can do to help solving this situation?

**Comment by alex83130** [comment]
It was for a past project, I had done differently in server side, so it's ok for me :)
But maybe It's a nice fix if the case recurs again in the future for someone else.

Thanks you for your time @kiaking !

**Comment by kiaking** [comment]
Great to hear that! Yeah if somebody can comeuppance with nice idea, we could tackle this issue again. Thank you for the confirmation 😃
