### ISSUE TITLE
New Model Functions: isDirty() and getDirty()

### ISSUE THREAD

**Issue by kpilard** [vuex-orm/vuex-orm#221]
Hey,

I would like to add two new methods to the model:

## isDirty(): boolean
This Method would check if some attributes in the model got changed:
```
let example = new Example({name: 'test'})
example.isDirty() // false
example.name = 'be dirty 😈'
example.isDirty() //true
example.name = 'test'
example.isDirty() //fase
```

## isDirty(attribute: string): boolean
This Method would check if the value of the specific key got changed

```
let example = new Example({name: 'test', foreverClean: 'test'})
example.name = 'be dirty 😈'
example.isDirty('name') //true
example.isDirty('foreverClean') //false
```

## getDirty(): object
This Method would return an Object with changed attributes

```
let example = new Example({name: 'test', foreverClean: 'test'})
example.name = 'be dirty 😈'
example.getDirty('foreverClean') // { name: 'be dirty 😈' }
```

I could create a Pull Request for this feature, if you want to add it to this library.

**Comment by kiaking** [comment]
Hi! Thanks for the proposal! I would love to see this implemented 👍 

However, we might have to be careful on usage on this feature. Since Vuex is basically immutable, people might get confused when this feature is used in conjunction with actions. Maybe we can still mark following example dirty if we store model instances directly to the store – which isn'T right now – but I think we can add some note to the documentation that this feature only works when you create model instance manually (not through getters).

```js
// Should this make the record dirty...?
store.dispatch('entities/users/update', {
  where: 1,
  data: { name: 'Jane Doe' }
})
```

**Comment by kpilard** [comment]
> Hi! Thanks for the proposal! I would love to see this implemented 👍
> 
> However, we might have to be careful on usage on this feature. Since Vuex is basically immutable, people might get confused when this feature is used in conjunction with actions. Maybe we can still mark following example dirty if we store model instances directly to the store – which isn'T right now – but I think we can add some note to the documentation that this feature only works when you create model instance manually (not through getters).
> 
> ```js
> // Should this make the record dirty...?
> store.dispatch('entities/users/update', {
>   where: 1,
>   data: { name: 'Jane Doe' }
> })
> ```

In our Project we use the Model as copy of the data at that moment. We would use this feature to send only changed data to our API. 
So your example wouldn't set the model as dirty. But maybe there are other use-cases.

If you compare it to a classic orm (databse-backend) the model is not dirty if you change a value directly in the database (Of course there are technical limitations here).

**Comment by tvillaren** [comment]
Hey, my 2 cents on this as we use the same behavior (IsDirty flag on an instance, to know if anything has been changed on the instance) on our home-baked ORM (and currently trying out Vuex ORM as a possible replacement). 

As in @kpilard's case, this is related to the back-end (and knowing if our store data is sync'ed to the persisted data, in the database).

I think this feature would be useful, but as @kiaking mentionned, it seems to me as well that strictly speaking (in term of Vuex Store), it doesn't make too much sense to add it, as you would need a point of reference different from the store. 

This is implemented in BreezeJS (http://breeze.github.io/doc-js/inside-entity.html#EntityState) which is an ORM tightly coupled to the fact that your data comes from a back-end. 
In the case of Vuex ORM, which is not currently coupled to any backend logic (which is good I think), would it make better sense to implement this behavior in a plugin ? With a way to define, when initializing the plugin, where / what is the reference (or adapter) for data-fetching?

**Comment by malinushj** [comment]
@kpilard A simple solution in your case would be to extend the Model class to have an isDirty property, this is what I use:
```js
import { Model as BaseModel } from '@vuex-orm/core';

export default class Model extends BaseModel {

  constructor(record) {
    super(record);
    this.$isDirty = false;
  }

  get isDirty() {
    return this.$isDirty;
  }

  static beforeUpdate(model) {
    model.$isDirty = true;
  }
}

```
You could also implement getDirty but it would imply a bit more logic.

**Comment by kiaking** [comment]
Yes, @malinushj That would work perfectly. Would this make sense to you? @tvillaren

**Comment by tvillaren** [comment]
> Yes, @malinushj That would work perfectly. Would this make sense to you? @tvillaren

Hello, 

Yes, this does make sense. 
I'm currently writing a small plugin which does that + add an `IsNew` flag. I'll push it to my github and we can see how to add to Vuex ORM (or keep it as plugin). 

I feel like a lot of things are being added to Vuex ORM (or at least planned to be) and it's hard to keep up :)

**Comment by kiaking** [comment]
@tvillaren Hi! thank you so much for your awesome work! Looking promising. Very simple!

I'm open for discussion but I'm thinking it should be a plugin...? Since there could be some discussion regarding isDirty feature.

For instance, while Vuex ORM treats Vuex Store somewhat like a database, some might feel wired to flag some record dirty when it is "committed" to the store. I mean if it's actually saved to the database, that is the true value at that moment.

But I do understand that some might also think that the Vuex Store is just a huge variable containing temporaly records. And this feature should be useful in many cases.

So I'm thinking we need a bit more time to discuss and consider about this feature going into the core or not.

Does anybody have any thoughts on this?

**Comment by kiaking** [comment]
@tvillaren Hi! Sorry for my late reply and not being so clear. What I meant by "it should be a plugin" is I thought at somewhere we were discussing to add this feature into the core or not. And I couldn't find it now :p

> If you mean, moving the repo to the "official" Vuex ORM Github organization, I don't mind, it would give it more visibility and more people could contribute.

It is all up to you! It would be an honor for me to see the plugin listed under vuex-orm namespace, but it's completely up to you. If you would like to, let me know at Slack or something and I'll give you permission to publish the packages under vuex-orm namespace!

**Comment by tvillaren** [comment]
The [Plugin Change Flag](https://github.com/vuex-orm/plugin-change-flags) is now an official Vuex ORM plugin, should we close this issue?

**Comment by kiaking** [comment]
Oh Yes! We should. I'm just gonna wait a bit more until the package gets published 👍

**Comment by kiaking** [comment]
Finally sorry for taking long, now the [Change Flags plugin](https://github.com/vuex-orm/plugin-change-flags) is available as @tvillaren mentioned! I'll be closing this issue out.

Thank you so much @tvillaren for this awesome work! 🎉
