### ISSUE TITLE
v0.26.1 field.make is not a function

### ISSUE THREAD

**Issue by huy-tran** [vuex-orm/vuex-orm#222]
@kiaking 

Hi Kia, thanks for your great work on this library again.

I have recently upgraded from **0.23.4** to **0.26.1** and this error pops up:

`Uncaught TypeError: field.make is not a function`

Had a look at the source code and I saw this:

```js
Model.fill = function (self, record, plain) {
        if (self === void 0) { self = {}; }
        if (record === void 0) { record = {}; }
        if (plain === void 0) { plain = false; }
        var fields = this.getFields();
        return Object.keys(fields).reduce(function (target, key) {
            var field = fields[key];
            var value = record[key];
            target[key] = field.make(value, record, key, plain);
            return target;
        }, self);
    };
```

I wonder if I missed anything from the upgrade. I tried to reverted to **0.23.4** and everything is working fine.

I am looking forward to hearing from you soon.

Thanks for your help again!

**Comment by kkyouhei** [comment]
@huy-tran 
Hi huy-tran.

I interested this issue.
Would you please code to reproduce this problem.

**Comment by huy-tran** [comment]
@kkyouhei 

Thanks for your prompt reply. I was out of my office last 2 days so couldn't reply.

Here is the full error log

```js
Uncaught TypeError: field.make is not a function
   at eval (vuex-orm.esm.js?0937:2283)
   at Array.reduce (<anonymous>)
   at Function.Model.fill (vuex-orm.esm.js?0937:2280)
   at Location.Model.$fill (vuex-orm.esm.js?0937:2407)
   at Location.Model (vuex-orm.esm.js?0937:1890)
   at new Location (Location.js?264f:3)
   at Function.fields (Practice.js?a6a6:28)
   at Schema.definition (vuex-orm.esm.js?0937:5225)
   at Schema.one (vuex-orm.esm.js?0937:5204)
   at Schema.many (vuex-orm.esm.js?0937:5212)
```

I checked my **Location** model

```js
import { Model } from '@vuex-orm/core'

export default class Location extends Model {
  static entity = 'location'

  static fields() {
    return {
      id: this.attr(null),
      locatableId: this.attr(null),
      locatableType: this.attr(null),
      isMailingAddress: this.attr(true),
      addresses: {
        primary: this.attr(null),
        secondary: this.attr(null)
      },
      country: this.attr(null),
      state: this.attr(null),
      city: this.attr(null),
      postcode: this.attr(null),
      suburb: this.attr(null),
      timestamps: {
        created: this.attr(null),
        updated: this.attr(null),
        deleted: this.attr(null)
      },
      locatable: this.morphTo('locatableId', 'locatableType')
    }
  }
}
```

I haven't changed anything in my **Location** model. Reverting to `0.23.4`  and it works.

Thanks!

**Comment by kiaking** [comment]
@huy-tran Hi! This is because you have nested object schema. This was deprecated by #138... Sorry for this but could you update your schema to not use nested object?

```js
export default class Location extends Model {
  static entity = 'location'

  static fields() {
    return {
      id: this.attr(null),
      locatableId: this.attr(null),
      locatableType: this.attr(null),
      isMailingAddress: this.attr(true),
      addresses: this.attr({
        primary: null,
        secondary: null
      }),
      country: this.attr(null),
      state: this.attr(null),
      city: this.attr(null),
      postcode: this.attr(null),
      suburb: this.attr(null),
      timestamps: this.attr({
        created: null,
        updated: null,
        deleted: null
      }),
      locatable: this.morphTo('locatableId', 'locatableType')
    }
  }
}
```

**Comment by huy-tran** [comment]
@kiaking 

Thanks for the update. It might break my application as I used it elsewhere. I might need to update my schema and upgrade then.

Thanks again!

**Comment by kiaking** [comment]
@huy-tran Thank you so much for your kind understanding. Sorry for the inconvenience 😢

**Comment by gonbi89** [comment]
@kiaking 

That's ok mate. Thank you and other contributors for your awesome works. 

It's my very first project that I build API. When I first did it I thought nested attributes would look cleaner and tidier. But now I can see it makes uncomfortable a little bit when updating data.

I will definitely use VueX-ORM again in next projects.

Btw, what's your thought on performing CRUD on Model itself? Something like User::fetch(), $user->update(), etc..

Thanks in advance!

**Comment by kiaking** [comment]
@gonbi89 Thank you for such a nice word!

> Btw, what's your thought on performing CRUD on Model itself? 

You can absolutely do that! 

```js
User.update({ ... })
```

It is actually documented over here : )
https://vuex-orm.github.io/vuex-orm/guide/advanced/interact-with-store-from-model.html

**Comment by johnrix** [comment]
The link above is now giving a 404 error. 

Has the ability to interact through the model instance been removed? the following currently throws an error:

`Reviewer.query().first().update({data: { name: this.name }})`

[Vue warn]: Error in v-on handler: "TypeError: _models_reviewer__WEBPACK_IMPORTED_MODULE_1__.default.query(...).first(...).update is not a function"

**Comment by kiaking** [comment]
@johnrix Oh no, it's still there! You must prefix the method with `$` when you calling **instance** method.

```js
Reviewer.query().first().$update({data: { name: this.name }})
```

**Comment by johnrix** [comment]
Aha, excellent, thanks!

**Comment by nagwan** [comment]
hi @kiaking, what is the reason behind deprecating **nested object schema**?

**Comment by kiaking** [comment]
@nagwan It was making many small things complicated... For example, query constraint looked wired and such.

```js
// Is it querying Setting model? or User with nested settings object?
Post.query().with('user.settings', (query) => { ... }).get()
```

Also, most of the time, I think you can use accessors to handle array or object field.

**Comment by nagwan** [comment]
@kiaking  aha, i see, thanks
