### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by mr-chick** [vuex-orm/vuex-orm#223]
Greetings,

I get this error and I'm not sure why.

When I try to run `$vm0.$store.getters['entities/employees/query']().with('projects').all();` in console I get: 

`Uncaught TypeError: Cannot read property 'reduce' of undefined`
```js
/**
     * Get related records.
     */
    HasManyBy.prototype.getRelatedRecords = function (records, keys) {
        return keys.reduce(function (items, id) {
            var related = records[id];
            related && items.push(related);
            return items;
        }, []);
    };
    return HasManyBy;
```
The model:

```js
import { Model } from '@vuex-orm/core'
import Project from '../Project'

export default class Employee extends Model {
  static entity = 'employees'

  static fields () {
    return {
      'id': this.attr(null),
      /* ... */
      'projects': this.hasManyBy(Project, 'projects'),
    }
  }
}
```

What could be the problem for this error?

**Comment by kiaking** [comment]
@mr-chick Hi! thank you for the report and sorry for my late reply.

Maybe this is a bug. Could you provide me how you created data?

**Comment by mr-chick** [comment]
Hey

Since projects is defined as a hasManyBy relation, can it not be set when using insertOrUpdate?

I see now that I only set it if the API response provides a list of projects

```js
const employee = {
      'id': obj.id,
      /* ... */
    }

    if (obj.projects) {
      employee.projects = obj.projects.map(project => project.id);
    }

    this.$store.dispatch('entities/employees/insertOrUpdate', { data: employee });
```

**Comment by kiaking** [comment]
@mr-chick Hi! Sorry for taking long on this issue. The Vuex ORM 0.27.0 has released and this problem might have gone away. Could you try it one more time? Also, I'm sorry to tell you but the definition for has many by has changed a bit, you must now define separate field for ids and actual relationship.

```js
class Cluster extends Model {
  static entities = 'clusters'

  static field () {
    return {
      id: this.attr(null),
      node_ids: this.attr(null),
      nodes: this.hasManyBy(Node, 'node_ids')
    }
  }
}
```

**Comment by mr-chick** [comment]
OK, thanks for the update.
I'll try it ASAP

**Comment by kiaking** [comment]
@mr-chick Thank you so much!

**Comment by kiaking** [comment]
@mr-chick Hi! Just wanted to check in. Did you have any progress on this 😀 ?

**Comment by mr-chick** [comment]
Hey, sorry for the late response.

As far as I can tell, the error is fixed.
I updated the relations too, and it's all good.

Thanks for the help.

**Comment by kiaking** [comment]
Thanks a lot for the confirmation! Let me know if you encounter any other troubles.
