### ISSUE TITLE
Retrieving relationships where field has no value set

### ISSUE THREAD

**Issue by sinasita** [vuex-orm/vuex-orm#224]
I try to do something like that:

```js
 emptyPages: (state, getters, rootState, rootGetters) =>
    rootGetters['entities/pages/query']().whereHas('contentElements', (query) => {
      query.where('texts', isEmpty)
    }).get(),
```
Where texts is defined as       

`texts: this.attr([]),`

in the contentElements-model. Is there a way to find all elements, where nothing is set?

**Comment by kiaking** [comment]
Yes I think what @tvillaren proposed should work!

**Comment by sinasita** [comment]
Oh thanks! It works perfectly

**Comment by kiaking** [comment]
Great it worked! Feel free to open another issue if you have any trouble.
