### ISSUE TITLE
Nested Where clauses don't handle mixed conditions

### ISSUE THREAD

**Issue by tvillaren** [vuex-orm/vuex-orm#225]
When trying to write nested conditions in the Where clauses, it seems that the results are off.

Syntax which I think should work (from reading the [documentation](https://vuex-orm.github.io/vuex-orm/guide/store/retrieving-data.html#query-builder)) is 
```    
// (A && B) || (C && D)
const users = store.getters['entities/users/query']()
      .where((_user, query) => {
        query.where('age', 20).where('active', true);
      })
      .orWhere((_user, query) => {
        query.where('age', 24).where('active', false);
      })
      .get()
```

I set up 2 different test cases, one for a `(A || B) && (C || D)` condition and one for `(A && B) || (C && D)` condition on a fork there: https://github.com/tvillaren/vuex-orm/commit/dfaae4c5ba6c535d05c258c45ede53c0223b1945

I did a bit of digging & debugging: it looks like the `where` clauses are pushed to the same `where` array without respect for the "priority" / nested-ness.

**Comment by tvillaren** [comment]
Pushed a fix on a branch https://github.com/vuex-orm/vuex-orm/compare/master...tvillaren:bugfix-nested-where

There were 2 issues: 
*  the nested queries were added to the root query `where` array (and not the `newQuery` one)
*  grouping AND & OR predicates at the same level on one query led to an issue when trying to check emptyness of results in case of closure

Will check coverage and perf tomorrow before opening a PR

**Comment by kiaking** [comment]
Thank you so much @tvillaren !
