### ISSUE TITLE
Defining a new specific type like this.array()

### ISSUE THREAD

**Issue by mithrilstar** [vuex-orm/vuex-orm#228]
Hello! First things first, thank you so much for this library, it will surely simplify a lot of things involved in building an app with even somewhat complex data schemas.

My question is about how to define a specific attribute type like this.string except i want it to be an array. The api response I have returns one field like this 
`pets : ["dog", "cat"]` etc

It'd be great if accessing person.pets directly gives me an array I can manipulate (add a 'snake' to the array for ex) instead of a string that I need to parse into an array and back into a string.

I looked at the accessors and mutators section but I don't think that's the way to go? Please let me know how to go about this. 

Thanks!

**Comment by kiaking** [comment]
@mithrilstar Hi! Thank you for trying out Vuex ORM!

There's no `array` or `object` attribute type at the moment, but you can use `attr` to put an Array!

```js
class User extends Model {
  static entity = 'users'

  static fileds () {
    return {
      id: this.attr(null),
      pets: this.attr([])
    }
  }
}
```

Then, the `pets` will return empty array if you don't provide any data.

**Comment by mithrilstar** [comment]
Thanks :) I'll use that tip

**Comment by kiaking** [comment]
Great! Let me know if you have any other questions or issues 👍
