### ISSUE TITLE
Save class instances directly to the store

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#231]
Save class instances directly to the store as discussed at #163. I've started working on to this and did few test implementations. It needs more work than I thought and there're many things to consider.

Implementation has started at #234.

There are many places we can refactor but to make development speed faster, I think we should go minimal on this.

### Breaking changes to the data structure

In most of the case it should be fine, but in certain situation, there will be a breaking change.

When saving class instance directly to the store, the relation field is going to be either `null` or `[]` depending on relationship type. Currently, the field contains the id of the related records that was passed into the persist methods. For example, if a user passes user record with posts, the record inside Vuex Store becomes like this.

```js
{
  users: {
    1: {
      id: 1,
      posts: [1, 2]
    }
  }
}
```

This behavior is going to change and it will become like this.

```js
{
  users: {
    1: {
      id: 1,
      posts: []
    }
  }
}
```

This is fine since Vuex ORM is not using those id values when looking up the relations. However, there's one use case where you could define HasManyBy relation to reference the same field (this is even documented!).

```js
class Cluster extends Model {
  static entities = 'clusters'

  static field () {
    return {
      id: this.attr(null),
      nodes: this.hasManyBy(Node, 'nodes')
    }
  }
}
```

This is not going to work anymore since the `nodes` will not contain any ids. So instead, a user must define field separately.

```js
class Cluster extends Model {
  static entities = 'clusters'

  static field () {
    return {
      id: this.attr(null),
      node_ids: this.attr([]),
      nodes: this.hasManyBy(Node, 'node_ids')
    }
  }
}
```

### Retrieving records by references

Currently, Vuex ORM is instantiating models from records when fething them via getters. We don't need to do this anymore when fetching records without relationships (without `with` method) since the record is already instantiated when saving them to the store. So now we can simply return store reference instead of recreating them.

However, we must recreate models when fetching records with relationships since Vuex State cannot be modified outside of mutation handler, we must create new instances and then attach related records to the newly created instances.

**Comment by kiaking** [comment]
This is done by #234 and released with Vuex ORM 0.27.0 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.27.0

**Comment by gegenschall** [comment]
This has been a breaking change for me. I cannot effectively upgrade Vuex-orm.
Is there any way to get back to the old behaviour where this works?

```
nodes: this.hasManyBy(Node, 'node_ids')
```

**Comment by kiaking** [comment]
@gegenschall Hi, sorry for the inconvenience. It was a necessary change to be able to store class instance directly to the store and there's no workaround without changing your model schema.

You need to change your schema to something like below.

```js
class Cluster extends Model {
  static entity = 'clusters'

  static fields () {
    return {
      id: this.attr(null),
      nodes: this.attr([]),
      node_instances: this.hasManyBy(Node, 'nodes')
    }
  }
}
```

Of course, you have to change wherever you use `nodes` property too...

**Comment by gegenschall** [comment]
Allright. It doesn't make my code look nice but I guess that's the only way :)
Thanks anyway!

**Comment by kiaking** [comment]
@gegenschall Sorry for that and so sorry for my late reply. I hope everything works for you.
