### ISSUE TITLE
update nested property

### ISSUE THREAD

**Issue by sinasita** [vuex-orm/vuex-orm#236]
I have a model looking like this:

    import { Model } from '@vuex-orm/core';

    export default class Text extends Model {
      static entity = 'texts';

      static fields() {
        return {
          id: this.increment(),
          text: this.string(''),
          style: this.attr({
             opacity: this.number(0),
             fontFamily: this.string(''),
             ....
          }),
        };
      }
    }

Is there a way to update the nested style properties?

I tried something like:

    export const setTextProperty = (id, value) => {
      Text.update({
        where: id,
        data: value,
      });
    }

And then:

    const value = { style: { opacity } };
    setTextProperty(item.id, value);

What works, but deletes the rest of my nested properties, so i would have to retrieve and assign them all before and it also passes the whole object as payload. Is there a better and more elegant way? Thanks for your help!

**Comment by kiaking** [comment]
@sinasita Hi! Thank you for the feedback! The easiest way to update the Object (or Array) is to define the data property at Update method as closure. You could update the Object like this!

```js
Text.update({
  where: id,
  update (text) {
    text.opacity = 1
  }
})
```

**Comment by sinasita** [comment]
Ok that helped me, thanks a lot! Anyway, there was a little mistake in in your proposal:

    setTextProperty =  (id, property, value) => {
      Text.update({
        where: id,
        data(text) {
          text.style[property] = value;
        },
      });
    };

I changed the update(text) for data(text)...
And i needed the property value to be flexible .

vuex-orm is great! thanks for all the effort!

**Comment by kiaking** [comment]
Oh sorry for my typo! And thanks for the fix. IT'll help somebody else having same trouble ;)
