### ISSUE TITLE
'$id' is not a valid attribute name

### ISSUE THREAD

**Issue by ozum** [vuex-orm/vuex-orm#257]
Hi,

I'm using ` v-bind` to pass all attributes as props from `vuex-orm-model` results in `v-for` like below:

```vue
<base-menu-item v-for="item in items" v-bind="item" :key="item.id"/>
```

Because of `$id` in records, I got following error:
`'$id' is not a valid attribute name.`

Except adding all attributes manually, how can I use results with `v-bind`?

```vue
<base-menu-item v-for="item in items" name="item.name" :id="item.id" ... prop-15="item.prop-15"  :key="item.id"/>
```

Thanks in advance,

**Comment by kiaking** [comment]
Hi! Thank you for the feedback! I think you must specify `v-bind` key!

```js
<base-menu-item
  v-for="item in items"
  v-bind:item="item" // <- add `item`. Or specify like `:item="item"` without `v-bind`.
  :key="item.id"
/>
```

**Comment by ozum** [comment]
Hi,

Thanks for the answer.

I'm also using your suggestion as a workaround (`:item`). However there are some pure components which expects attributes of the object as individual props. Also this is the reason `v-bind="someObject"` shortcut exist.

I think it is not easy job to refactor `vuex-orm` for this, but in next major iteration you may consider to change attributes starting with `$` with some other character to make `vuex-orm` compatible with `v-bind`.

**Comment by kiaking** [comment]
@ozum Thanks for the feedback!

> Also this is the reason v-bind="someObject" shortcut exist.

I didn't know that there're such syntax! Could you guide me to the docs?

**Comment by kiaking** [comment]
Oh thanks! Wow, I didn't know this. Hmmm... so maybe we should stop using `$` and `_` for the property hah... hmmmm. Well here's only `$id` which is affected in a record so we could come up with some another naming.
