### ISSUE TITLE
Calling insertOrUpdate() multiple times with the same set of records with a morphToMany relation duplicates the pivot records

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#258]
https://jsfiddle.net/nkcr48p5/

**Comment by kiaking** [comment]
Thanks for the report! I'll look into it!

**Comment by kkyouhei** [comment]
Hi @phortx 

I discovery first aid to this issue.
please look below at line 6.
https://jsfiddle.net/kkyouhei/efogj93a/7/
before
```
id: this.autoincrement(),
```

after
```
id: this.attr(null),
```

and I fix this issue continue.
