### ISSUE TITLE
Is this valid use of model?

### ISSUE THREAD

**Issue by ozum** [vuex-orm/vuex-orm#259]
Hi,

I'm using heavy key-lookup in a joined relation. So I created an instance method like below:

```js
export default class OptionGroup extends Model {
  static entity = "optionGroups";

  static fields() {
    return {
      id: this.string(""),
      ...
      options: this.hasMany(Option, "optionGroupId"),
    };
  }

  // Memoize on first use, then return memoized value
  get optionsById() {
    if (!this._optionsById) {
      this._optionsById = {};
      this.options.forEach(option => (this._optionsById[option.id] = option));
    }
    return this._optionsById;
  }
}
```

Basically, on first call I add an attribute to instance (`_optionsById`) and filled it with data. For the subsequent calls, I return that data.

```js
const optionGroups = OptionGroup.query().with("options");
const option = optionGroups[0].options[0];
const otherOption = optionGroups[0].optionsById["someId"];
```

It seems working as expected, but I wonder is there any problem with that approach?

EDIT 2: I don't want `_optionsById` stored in vuex store. Does adding this attribute to model instance cause addition of this to vuex-store?

**Comment by kiaking** [comment]
No, you wouldn't want to do this. The reason is because currently, Vuex ORM is storing the class instance as is to the Store. Which means, the behavior might violate Vuex immutability. Which is, you shouldn't mutate the store state outside of store mutation.

> I don't want _optionsById stored in vuex store. Does adding this attribute to model instance cause addition of this to vuex-store?

Yes it will. Because, Vuex ORM stores class instance as is to the Store.

**Comment by ozum** [comment]
Thanks for warning. I will not use it.
