### ISSUE TITLE
Fields interface for TypeScript

### ISSUE THREAD

**Issue by ozum** [vuex-orm/vuex-orm#264]
Using with typescript some of my model classes complains that `static fields()` does not have a return type.

I guess it required a return type of `Fields()`. How can we import and use it?

```ts
import { Model } from "@vuex-orm/core";

export default class OptionGroup extends Model {
  static entity = "optionGroups";

  static fields() {    // Expects: "static fields(): Fields {"
    return {
      id: this.string(""),
    };
  }
}
```

Edit:

Currently I'm using a workaround: `import { Fields } from "@vuex-orm/core/lib/model/Fields";`  but it should be a better way I guess.

Thanks,

**Comment by kiaking** [comment]
@ozum Ah, OK. Well, I guess we have to export all interfaces at `index.ts`. There're going to be a lot, so I don't know if that's the way to go... but. I wonder what other TS libraries are dealing with this.

**Comment by kiaking** [comment]
I just saw it! Thanks for your help!
