### ISSUE TITLE
No type check for models (TypeScript)

### ISSUE THREAD

**Issue by ozum** [vuex-orm/vuex-orm#266]
Hi,

I have an example model in TypeScript. However even I access wrong field names type-check does not detect those.

```ts
export default class Category extends Model {
  static entity = "categories";

  static fields(): Fields {
    return {
      id: this.string(""),
      name: this.string().nullable(),
      items: this.hasManyBy(Item, "itemIds"),
    };
  }

  id!: string;   // Notice `!`. Tell TS that this property is always defined in class.
  name: string | null;
  items!: Item[];
}

const categories = Category.query()
  .with("items")
  .get();

const direct = new Category();

// Below code passes typescript check without errors:
console.log(categories.xyz);  // I expected error: Property 'xyz' does not exists on "..."
console.log(direct.xyz);  // // I expected error: Property 'xyz' does not exists on "..."
```

One of the reasons of this is `[key: string]: any` usage in `Model.ts` and some other places. As you, of course, know this destroys all benefits of typescript.

How can we benefit type checks in `vuex-orm` models? Or is there any particular reason for current situation?

I'm not TS expert, but this may be solved using TypeScript Generics, `keyof` and `typeof keyof T` etc.

```ts
interface CategoryInterface {
...
}

export default class Category extends Model<CategoryInterface> implements CategoryInterface {
...
}
```

```ts
export default class Model<T> {
...
}
```

**Comment by kiaking** [comment]
Yes wonderful! I've checked the PR and will make a release soon!

**Comment by RomainLanz** [comment]
Hey all! 👋 

Has this been released yet?

**Comment by kiaking** [comment]
@RomainLanz Yes it should!

**Comment by yardley** [comment]
Related to this - is there any way we can get type safety when updating a record with a payload?

```
Category.update(
  { data: { name: 'category name' }, where: 1 }  // OK
)  
Category.update(
  { data: { madeUpProperty: 'value' }, where: 1 }  // Fails silently
)  
```

**Comment by kiaking** [comment]
Ah, currently not. We can't 100% make sure that to fail because there're no easy way of getting maps for schema properties. For example, if your model have public property called `mapUpProperty` (and not in fields definition), it will not throw type error but it will fail to update such a property.

Maybe we can do a bit better in Vuex ORM Next though.
