### ISSUE TITLE
Create two submodules

### ISSUE THREAD

**Issue by clementdubois** [vuex-orm/vuex-orm#271]
I have a big project and I would like to create two separate submodules in a vuex way but it seems like I can only register one database in one unique namespace.

I there a way to have to distinct modules (each containing different vuex orm models).

I really don't want to register all Models in the same module :(

thank you :)

**Comment by kiaking** [comment]
@clementdubois Hi! thank you for the feedback!

A long time ago, it was possible to register multiple databases to the store but I dropped it since it got quite messy in the code. Maybe it's time to rethink about this.

However, there are a few things we must consider before moving on. For example, I don't believe Vuex supports multiple store instance in a single application. So it kinda makes less sense to store multiple databases to the Store.

Could you elaborate a bit more about your use case? Why do you want to have multiple databases?

**Comment by clementdubois** [comment]
Hi, I don't necessarily want to have multiple databases, I just want to have a hierarchy of submodules (like in native vuex). And I don't know if it's possible with vuex-orm because we have to register the database in the plugin section (in the root modules). 

For instance I would like to be able to have two different modules, let's say "payment" module and "products" module and in each module I would like to register different vuex orm models. For payment it could be "cart" model and "item" and for "products" it could be "product" and "catagories" .

Happy new year :)

**Comment by kiaking** [comment]
@clementdubois Oh, I see. That use case is something I haven't thought about it yet. Might be interesting.

To make it clear, my understanding is it would be something like below. Correct me if I'm wrong.

```js
// Data inside the store.
{
  payment: {
    status: 'rerady', // Plain Vuex state for payment module.

    carts: { // Vuex ORM Model
      data: [...]
    },

    items: { // Vuex ORM Model
      data: [...]
    }
  }
}
```

If my understanding is correct, it might be interesting but to be honest, this is going to make things really complicated on Vuex ORM side :p  For instance, could `products.category ` have relationship with `payment.item`...?

It is a bit cumbersome, but maybe you could create some abstraction layer module that calls the appropriate Vuex ORM model. Something like below?

```js
// Item module nesting under Payment module. Plain Vuex.
const actions = {
  create ({ dispatch }, data) {
    // Call Vuex ORM actions.
    dispatch('entities/items/create', { data }, { root: true })
  }
}

// Then use it like this?
this.$store.dispatch('payments/items/create')
```

**Comment by kiaking** [comment]
@clementdubois Hi! have you ever had a chance to look into my comment? Let me know if it makes sense!

**Comment by kiaking** [comment]
I'll be closing the issue for inactivity. Please feel free to reopen it if there's any 🤝
