### ISSUE TITLE
Lifecycle hooks doesn't work in Model Class

### ISSUE THREAD

**Issue by djokone** [vuex-orm/vuex-orm#273]
Problem : Lifecycle hooks doesn't seem to work in Model Class
Hi, I've wrote my class like this :
```
export default class Interest extends Model {
  static entity = 'interests'
  static fields () {
    return {
      id: this.attr(null),
      name: this.attr(''),
      parent_id: this.attr(null),
      childrens: this.hasMany(this, 'parent_id'),
      parent: this.belongsTo(this, 'parent_id')
    }
  }
  static afterUpdate (model) {
     console.log(model)
     console.log('after update')
   }
}
```
And I'm expecting to see my console.log when I commit and update, but nothings append...
The only way hook works is with the global hook like this : 
```
Query.on('afterUpdate', (records, entity) => {
  console.log(records)
  console.log(entity)
  console.log('afterUpdate')
})
```

**Comment by kkyouhei** [comment]
Hi @djokone 

I don't reproduce your problem.
https://codesandbox.io/s/xz90ny3mxq

Can you give reproduce problem code ?

**Comment by kiaking** [comment]
@djokone Hi! Do you have any update on this? It would be helpful if you could provide a reproduction code.

**Comment by djokone** [comment]
Hi guys sorry for the delay, I've resolve the issue. When @kkyouhei send me the problem link I've saw that my vuex-orm package wasn't updated to the last version. I've done it and now everythings working has expected ;) Thx guys and sorry for the inconvenience.

**Comment by kiaking** [comment]
@djokone Ah, thank you so much for your update! Great to hear it worked for you. Please open another issue if there's anything!
