### ISSUE TITLE
How to design with states which are no relationship with each.

### ISSUE THREAD

**Issue by victor0210** [vuex-orm/vuex-orm#274]
best practice of ActiveRecord in frontend? 
how do I design state better like columns in db?

**Comment by kiaking** [comment]
@victor0210 Hi! Thanks for the interest on Vuex ORM!

Sorry, I'm not sure what your question is. You can definitely design your state like DB column. Like this?

```js
class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.number(),
      name: this.string('')
    }
  }
}
```

**Comment by victor0210** [comment]
To put it simply, when we design the table structure on the server side, most of the time we are integrating business data and dividing the dimensions, but the front end will have a lot of non-business related states, so how can they not pollute ORM?

**Comment by kiaking** [comment]
Oh OK. Well, the schema you define at Vuex ORM doesn't have to match the server side DB schema. So you can define those non-business related state however you want. You could define either field properties or just define plain class properties.

Let's say you have backend Post model and the schema looks like below.

```js
{
  id: 1,
  title: 'title'
}
```

It is perfectly fine for you to define Vuex ORM schema like this.

```js
class Post extends Model {
  static entity = 'posts'

  static fields () {
    return {
      id: this.attr(null),
      title: this.string(''),
      status: this.string('')
    }
  }
}
```

Or you can just define class property.

```js
class Post extends Model {
  static entity = 'posts'

  status = ''

  static fields () {
    return {
      id: this.attr(null),
      title: this.string('')
    }
  }
}
```

Would this make sense?

**Comment by victor0210** [comment]
all right, thks

**Comment by kiaking** [comment]
I hope you found a way! Please don't hesitate to open another issue if you have anything else! ✋
