### ISSUE TITLE
Multiple with, with multiple closures

### ISSUE THREAD

**Issue by Kleemer** [vuex-orm/vuex-orm#276]
Hi Vuex-ORM community, and happy new year !

I was trying to do something like:

```js
const videoId = 1

this.$store.getters['entities/users/query']()
  .where('company_id', this.company.id)
  .with('posts', (query) => {
    query.with('comment.likes')
    query.orderBy('order')
  })
  .with('videos', (query) => {
    query.where('id', this.videoId)
  })
  .orderBy('order')
  .get()
```

What I expected from that is a list of users, with all the posts and their likes, but also the videos attached to the user that has the videoId as their ID. If I try this with only one of the `with` I have part of what I want (because it's missing the other `with`) but the data looks good, however both together does not seem to work for me ?

I have to say that I do not have the latest version, trying currently with *0.25.6* but I was wondering if this use case has been thought. Thank you !

**Comment by kiaking** [comment]
@Kleemer Hi! Thank you so much for the report!

Yes, that use case – Multiple `with` – is expected to work. And your method calls look good to me and it should get what you would expect.

Is it possible for you to create a reproduction code for this issue? Or can you try if anything changes if you remove where query?

**Comment by kiaking** [comment]
@Kleemer Hi! Do you have any update on this? It would be helpful if you could provide a reproduction code.

**Comment by Kleemer** [comment]
@kiaking hi, sorry I really did not have time to try again since last time ! Updating my whole codebase would take me too much time for now, so I will just guess that I missed something silly.
I will close this issue for now, and re-open if needed, is that fine with you ?

Again thanks for all the help !

**Comment by kiaking** [comment]
@Kleemer Oh OK! Sorry I didn't know that the issue went away for you :p  Glad to hear you found a way out!

> I will close this issue for now, and re-open if needed, is that fine with you ?

Yes! Please don't hesitate to open another issue if there's anything.
