### ISSUE TITLE
Support some kind of Query Language

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#277]
It would be really nice when Vuex-ORM would support some kind of simple query language to write queries instead of the current query API.

**Comment by kiaking** [comment]
Hah, never thought of that! What kind of language? Like SQL? (Might be very tough though).

**Comment by phortx** [comment]
Yes, just like SQL. Maybe something more simple. And we don't have to support everything. And maybe there's already a parser lib vor something like that, don't know :D

**Comment by kiaking** [comment]
@phortx Any idea how would the API look like?

**Comment by tvillaren** [comment]
> ```
> Query().select('*').from('users').where('id', 1)
> ```

Seeing this makes me think that Vuex ORM already has a Query language, which is the Query API. 
It is not too complicated, except maybe the for filtering data (as part of a project, I actually built a Predicate Model with an adapter to Vuex ORM queries). 

I'm curious about what would be this other QL. Something like LINQ ?

**Comment by phortx** [comment]
I thought of something like SQL. But a object oriented approach is sexy as well. I just think of something which is more powerful then the current query API :)

**Comment by kiaking** [comment]
Hmm. OK. I'm not sure here either 😀  I'l let this issue be open for couple more weeks and see if someone gonna come up with crazy idea.

**Comment by kiaking** [comment]
And couple of weeks has passed. I think it's interesting idea, though I guess we should focus on version 1 release and other higher priority issues. Anyway, thank you for the feedback! 🤝
