### ISSUE TITLE
this.morphMany field default value is undefined when trying to retrieve it

### ISSUE THREAD

**Issue by Kleemer** [vuex-orm/vuex-orm#281]
Hi,

Came across this bug yesterday while updating to the latest version (v0.31.2).
One of my model has a standard morphMany : `media: this.morphMany(Media, 'model_id', 'model_type')`
However, it looks like whenever the back-end does not fill the field, and I'm trying to query my model using `.with('media')` that this one is `undefined`.  It looks like the default value of this kind of relationship is `undefined` ? I guess it's because with other types of field you can add a default value, e.g. `name: this.attr('')` but here you cannot ?

Thanks !

**Comment by kiaking** [comment]
Hmmm. maybe. Could you provide me the reproduction code so that I can first make failing test case for this? Like model definition and insert records.

**Comment by kiaking** [comment]
@Kleemer Thank you so much! let me check if I can make failing test case for this.

**Comment by cuebit** [comment]
This has since been resolved. 👍
