### ISSUE TITLE
Bidirectional tree hirarchy query with recursiveAll explode  

### ISSUE THREAD

**Issue by clementdubois** [vuex-orm/vuex-orm#288]
Hello there,

I tried to have a tree hierarchy (with nodes, child and parent) but when I try to query the structure with withAllRecursive it quickly explode in memory.

here is a model example : 
```javascript
export default class Node extends Model {
  static fields() {
    return {
      id: this.string(""),
      parentId: this.string().nullable(),
      parent: this.belongsTo(Node, "parentId"),
      children: this.hasMany(Node, "parentId"),
    };
  }
}
```

And the query to fetch the nodes : 
```
Node.query()
          .withAllRecursive(10)
          .find(nodeId)
```

The first problem is that I just want node's children but I can't control that with withAllRecursive method. Maybe a withRecursive(fields, depth) would help me.

The second problem is memory size explosion, I haven't investigate but I suppose that each time a Node is found, the algorithm will search for his parents and children nodes and it will do the same for each node, even though the node has already been fetched.

**Comment by kiaking** [comment]
@clementdubois Hi! Thank you for the report!

> The first problem is that I just want node's children but I can't control that with withAllRecursive method. Maybe a withRecursive(fields, depth) would help me.

Ah yeah. That could be nice feature addition.

> The second problem is memory size explosion, I haven't investigate but I suppose that each time a Node is found, the algorithm will search for his parents and children nodes and it will do the same for each node, even though the node has already been fetched.

OK, currently that is how it works. It fetches nested relationship as a new relationship each time. It might fix when we implement index hash spamming discussed at #163. Just for curiosity, how many records do you have?

**Comment by HenryTabima** [comment]
watching your code I realized that your `parent: this.belongsTo(Node, "parentId"),` should be `parent: this.belongsTo(Node, "id"),`

**Comment by kiaking** [comment]
@clementdubois Hi! Any updates on this?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. If this is performance issue, it might be fixed by implementing index hash mapping discussed at #163.

Though please feel free to reopen the issue if there's anything! 🤝
