### ISSUE TITLE
hasMany not storing array of child ids in parent

### ISSUE THREAD

**Issue by ajgagnon** [vuex-orm/vuex-orm#289]
Hi There!

Thanks for a fantastic library! There seems to be an issue with the hasMany method not storing child ids in the parent. I just ran a test on the Todo Example application and it seems to have this issue. Here's the todo item:

![image](https://user-images.githubusercontent.com/2569725/52509808-23bf5380-2bbf-11e9-90f6-cc9aa3890038.png)

And you can see the Use has an empty array for the Todos:

![image](https://user-images.githubusercontent.com/2569725/52509846-4baeb700-2bbf-11e9-8988-4d7c1b0c0acd.png)

I put up some code on codesandbox too so you can take a look more quickly!

Result:
https://2oqlm763r0.codesandbox.io/

Source: 
https://codesandbox.io/s/2oqlm763r0

Any insight you might have I'd appreciate!

**Comment by kiaking** [comment]
@ajgagnon Hi! thank you for the feedback!

Actually this is how it should be. The parent will not store ids for children. Vuex ORM will lookup for the relationship when fetching it.

Does this explanation make sense to you?

**Comment by ajgagnon** [comment]
Ah, okay, makes sense! So I'll need to do a relationship query for that? 

Maybe I could submit a pull request for the documentation here if you're up for it

https://vuex-orm.github.io/vuex-orm/guide/prologue/what-is-vuex-orm.html#what-is-it-like-to-use-vuex-orm

![image](https://user-images.githubusercontent.com/2569725/52643760-46918680-2ea3-11e9-847c-7dd2b21d8150.png)

But maybe not necessary if I'm the only one that reads this wrong!

Anyway, thanks for the awesome library and the quick response!

**Comment by kiaking** [comment]
@ajgagnon Yes! You should use `with` chain when you need to load the relationships.

```js
User.query().with('posts').get()
```

> But maybe not necessary if I'm the only one that reads this wrong!

That would be more than welcome! ❤️

**Comment by kiaking** [comment]
Closing this issue since it seems to be resolved by the comments. Please feel free to reopen it if you have any additional issues! 🤝
