### ISSUE TITLE
auto-increment on create only

### ISSUE THREAD

**Issue by bertBruynooghe** [vuex-orm/vuex-orm#296]
I have an issue with long keys where an auto-increment on create only would be very handy, or perhaps there's another solution?

The issue is as follows: say my `Post` has a GUID as id, and the `Comment` has a concatenation of the post's GUID with some id that is unique in the context of the Post, and this is the way I get it from the backend. With lots of comments, the store takes up a lot of memory.

My first attempt was to create a auto-incrementing key `index` on `Post`, and use `postIndex` as foreign key in `Comment` and make the primary key of `Comment` a combination of this index together with the id that is unique in the context of `Post`. However, each update to `Post` increments the index, and the link between the two is broken.

My second approach was using `beforeCreate` and set the index there manually, but then again, I can't create posts with comments in one go anymore: `Post.insertOrUpdate({ data: { id, posts: [{ id }] } }`, as adapting the Post model in `beforeCreate` seems too late.

Any suggestions how I can tackle this problem?

**Comment by bertBruynooghe** [comment]
FYI: I fixed the problem as follows; in multithreaded systems it might create issues, but in javascript it seems save to me:

```
const Vue = require('vue')
const Vuex = require('vuex')
const VuexORM = require('@vuex-orm/core')

Vue.use(Vuex)

class Post extends VuexORM.Model {
  static beforeCreate (model) {
    if (typeof model.id === 'string') {
      model.longId = model.id
      model.id = Post.lastIndex++
    }
  }

  static fields () {
    return {
      id: this.attr(),
      longId: this.attr(),
      comments: this.hasMany('comments', 'postId')
    }
  }
}
Post.entity = 'posts'
Post.lastIndex = 1

class Comment extends VuexORM.Model {
  static beforeCreate (model) {
    if (typeof model.postId === 'string') {
      const post = Post.query().where('longId', model.postId).first()
      model.postId = post ? post.id : Post.lastIndex
    }
  }
  static fields () {
    return {
      id: this.attr(),
      postId: this.attr(),
      post: this.belongsTo(Post, 'postId')
    }
  }
}
Comment.entity = 'comments'

describe('VuexORM', () => {
  beforeEach(() => {
    const database = new VuexORM.Database()
    database.register(Post, {})
    database.register(Comment, {})
    new Vuex.Store({ // eslint-disable-line no-new
      plugins: [VuexORM.install(database)],
      strict: true
    })
  })

  it('supports nested comments', async () => {
    const { posts: [post], comments: [comment] } =
      await Post.insertOrUpdate({ data: { id: 'post', comments: [ { id: 'comment' } ] } })
    expect(comment.postId).toEqual(post.id)
  })

  it('supports nested comments inverted', async () => {
    const { comments: [comment], posts: [post] } =
      await Comment.insertOrUpdate({ data: { id: 'comment', post: { id: 'post' } } })
    expect(comment.postId).toEqual(post.id)
  })
})

```

**Comment by kiaking** [comment]
@bertBruynooghe Hi! thank you for the tips! And I'm glad you found a way out. I think this is safe because currently Vuex ORM runs synchronously. So the order of beforeCreate hook execution should be always same 👍
