### ISSUE TITLE
[ Documentation ] Retrieving Data typo

### ISSUE THREAD

**Issue by jasonpolito** [vuex-orm/vuex-orm#297]
> Of course, you may combine these ~methos~ *methods* with other clauses.

https://vuex-orm.github.io/vuex-orm/guide/store/retrieving-data.html#query-builder

![image](https://user-images.githubusercontent.com/2179946/52820530-3da6dd80-307a-11e9-808c-a01c9abcdcaf.png)

**Comment by kiaking** [comment]
Ah thanks! I'll fix it!

**Comment by kiaking** [comment]
I've fix the doc, and deployed it. thank you so much for the report! 🤝

**Comment by jasonpolito** [comment]
Great package 👍

**Comment by kiaking** [comment]
Thank you so much for the such a nice word! ❤️
