### ISSUE TITLE
natural ordering

### ISSUE THREAD

**Issue by getriebesand** [vuex-orm/vuex-orm#300]
Is threre a way to use a custom comparer on orderBy? e.g. with localeCompare?

I need to order like this:
1
2
5
21 a
105

**Comment by kiaking** [comment]
@getriebesand Ah, not at the moment. I think this is going to be nice feature addition to the orderBy method. Maybe custom callback as the 1st argument 👍  There are few bugs I have to tackle so implementing this might take a while. But I'll mark this as an enhance meant issue!

**Comment by leearaneta** [comment]
hi,

i [took a stab](https://github.com/vuex-orm/vuex-orm/pull/501) at allowing `.orderBy()` to take in `(T => any) | string` as the first argument.  @kiaking let me know if you have any questions, and thanks for maintaining this wonderful library :)

**Comment by kiaking** [comment]
@leearaneta Thanks a lot for the PR! Wonderful! I've made few comments on the PR so please take a look. Thank you so much for your hard work!

**Comment by kiaking** [comment]
Now you can pass function to the 1st argument of `orderBy`. Thanks to @leearaneta! for this wonderful PR!
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.34.1

**Comment by adrianrudnik** [comment]
Not sure how this could be used for natural sort. The above-mentioned JS client method [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) would require this new callback function to receive the bare minimum of .sort() to solve this use-case (el1, el2, order), or am I missing something?

Right now the only way seems to be something like this to order by title, german locale, including numbering:

```javascript
Book.query()
      .where('available', true)
      .get()
      .sort((a, b, order) => !order
        ? a.title.localeCompare(b.title, 'de', { numeric: true })
        : b.title.localeCompare(a.title, 'de', { numeric: true })
      );
```

Though I have no clue if using .sort on a result is safe in a reactive sense.
