### ISSUE TITLE
this.$store.getters.entities/auth/find is not a function

### ISSUE THREAD

**Issue by lucasgonzalez0** [vuex-orm/vuex-orm#301]
Hi! 

```sh
    computed: {
      auth: {
        get () {
          return this.$store.getters['entities/auth/find'](1)
        },
        set (val) {}
        },
```
Error in render: "TypeError: this.$store.getters.entities/auth/find is not a function"

Now, if i remove 

> (1)

it does not generate an error, but no working.
Why does not it work?

**Comment by kiaking** [comment]
@lucasgonzalez0 I'm not sure. It should work. Are you sure you've registered Auth model to the database?

**Comment by kiaking** [comment]
@lucasgonzalez0 Hi! any news on this issue? Just checking in.

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to reopen it if you gave anything 🤝
