### ISSUE TITLE
Is there a way to sort by the order inserted

### ISSUE THREAD

**Issue by danielnolan** [vuex-orm/vuex-orm#308]
I'm trying to use this with vuedraggable and I need to be able to sort by the array index not by id or some other model attribute.

**Comment by kkyouhei** [comment]
Hi @danielnolan 

I use vuedraggable and vuex-orm by my project and It is usable no problem.
Could you tell me your problem please ?

```
      <draggable
        element="div"
        class="draggable"
        :list="entries"
        :options="dragOptions"
        :move="onMove"
        @end="onEnd"
        :data-entry-status-id="entryStatus.id">
          <card-block
            :entry="entry"
            v-for="(entry, index) in entries"
            :key="index" />

          <q-card class="bg-white" v-if="loading">
            <q-card-main class="q-mb-sm">
              <qf-card-loading />
            </q-card-main>
          </q-card>
      </draggable>
```

**Comment by danielnolan** [comment]
@kkyouhei My issue is persisting the order to the store. I have a group of lists, if I move one of the lists and try to save the order, when the lists are reloaded they are in order by id, since the orm orders by model id by default. I'm using v-model like the vue-draggable docs show for using with vuex. 
``` js
  computed: {
    lists: {
      get() {
        return this.$store.getters['entities/lists/query']().with('magnets').get();
      },
      set(value) {
        this.$store.dispatch('entities/lists/create', { data: value });
      },
    },
  },
```
```vue
    <draggable
      v-model="lists"
      :move="checkMove"
      :options="options"
      class="drag-area"
      @start="onDraggableStart"
      @end="listMoved"
    >
      <board-list
        v-for="(list, index) in lists"
        :key="index"
        :ref="'list-'+list.id"
        :list="list"
      />
    </draggable>
```

**Comment by kiaking** [comment]
@danielnolan Ah, currently no. You need to have field to determine the order so you can sort by that.

I agree that there is a situation you might want keep the order of records that has been inserted, but not sure if this can be easily done. Because Vuex ORM works kinda like DB, any component can insert record to the Store.

So even you can preserve the inserted order, another component might just gonna break it. I would recommend defining something like `order` field at the model and use that to orderBy records.

**Comment by kiaking** [comment]
I'll be closing the issue due to inactivity. Lets come back if there're more needs on saving insert order!

**Comment by milad-alizadeh** [comment]
You can always add new field such as "order" or weight ". 
```
    dataTransformer: (response) => {
      return response.data.posts.map((post, index) => ({ ...post, weight: index }))
    },
```

**Comment by spyc-cloudadmin** [comment]
So is the insertion order preserved now?
I've tried inserting data into a model with random ids, and then call Model.all() to retrieve an array of data. I see that the order in the array is the same as my insertion order.
I'm confused by this post, is the insertion order guaranteed to preserve? This is important to my use case.

**Comment by d-mok** [comment]
So is the insertion order preserved now?
I've tried inserting data into a model with random ids, and then call Model.all() to retrieve an array of data. I see that the order in the array is the same as my insertion order.
I'm confused by this post, is the insertion order guaranteed to preserve? This is important to my use case.
