### ISSUE TITLE
[Error] Reflect is undefined in  IE

### ISSUE THREAD

**Issue by Leruiz** [vuex-orm/vuex-orm#314]
When use the latest version, e.g. v0.31.6, there is an error ``` Reflect is undefined```  when running in IE. Polyfill has been imported into the project, however, which did not work. So I used an older version, v0.30.0, then solved this problem.

**Comment by kkyouhei** [comment]
Hi @Leruiz

Thank you for your report.
I research this problem.

**Comment by okatsuralau** [comment]
I was able to fix this issue including a pollyfil for the Reflect object.

https://github.com/okatsuralau/vuex-orm/blob/master/src/polyfills/index.ts#L3

**Comment by SebastianSmolorz** [comment]
I am still seeing this problem in 0.31.8 running in ie11

**Comment by kkyouhei** [comment]
Hi @okatsuralau @SebastianSmolorz 
@SebastianSmolorz  Thank you for PR.
By the way, Is it fixed to Reflect.keys change to `const keys = Object.getOwnPropertyNames` ?

**Comment by kiaking** [comment]
Hmmm. maybe we should import core-js stuff for all possible polyfills...

**Comment by kiaking** [comment]
I think this is resolved by #320 and it is included in Vuex ORM 0.31.10. Please let me know if you find any further issue on IE!
