### ISSUE TITLE
Usage of Object.assign is not polyfilled properly

### ISSUE THREAD

**Issue by dtkahl** [vuex-orm/vuex-orm#317]
The files in `dist/` are using `Object.assign` and most of the time it is polyfilled properly. However in the function `mapValues` its used without the polyfill which causes IE11 to stop working.

```js
function mapValues(object, iteratee) {
    var newObject = Object.assign({}, object);
    return Object.keys(object).reduce(function (records, key) {
        records[key] = iteratee(object[key], key, object);
        return records;
    }, newObject);
}
```

There is a workaround for this issue but I think this should be fixed to be compatible with IE11.

**Workaround**
Add this to the `vue.config.js` of your project:
```
transpileDependencies: ['@vuex-orm/core']
```

**Comment by kiaking** [comment]
This is now solved with Vuex ORM 0.31.8 thanks to @kkyouhei. Thank you @dtkahl for the report!
