### ISSUE TITLE
Insert custom pivot Fields

### ISSUE THREAD

**Issue by jpenaroche** [vuex-orm/vuex-orm#327]
Hi, First at all... awesome library!!! But i have a huge problem. How can i insert custom fields in my Many To Many Polimorphic Relation.
This is my gist of relationships...
https://gist.github.com/jpenaroche/16d289a97c2cedd889d7172ec41a92d4

**Comment by jpenaroche** [comment]
I have two custom fields in my pivot Table (Mediable) but when i pass my api data vue-orm doesn't insert these fields (order, tag) :\

**Comment by malinushj** [comment]
hi @jpenaroche !
I experienced a similar issue because vuex-orm will query the `mediable_type` by the entity name when making the relationship. In your case `mediable_type = 'users'`. If you don't have that in your data then it won't work

**Comment by malinushj** [comment]
As per the order and tag, are those just primitve data types? int and string?
Can you add a gist of an API response example?

**Comment by jpenaroche** [comment]
thanks @malinushj for your answer, this is a link to another posted issue with my classes and with the response data that i received from api..., you can see in my screenhots, how the esctructure of my model, when i set primaryKey Array, the model is ok, but vuex-orm doesn't retrieve that model, instead it gives me another ghost model  (second photo) with the pivot data doesn't setted :\ , so my primaryKeys only works to seed the model, but not for retrieve data from $store :(
 
https://github.com/vuex-orm/vuex-orm/issues/312#issuecomment-479912240

**Comment by malinushj** [comment]
@jpenaroche The pivot models are added twice because once you are receiving your pivot from the api as `mediable_type = 'App\Src\Domain\Models\User'` which is different from your entity name set in the User model

**Comment by malinushj** [comment]
I'll leave you an example of what works for me:
```js
class Tag extends Model {
  static entity = 'App\\Tag';

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(''),
      slug: this.attr(null),
      type: this.attr(null),
      pivot: this.attr(null),
      ...timestamps,
    };
  }
}
```
```js
class Taggable extends Model {
  static entity = 'App\\Taggable';

  static primaryKey = ['tag_id', 'taggable_id', 'taggable_type'];

  static fields() {
    return {
      tag_id: this.attr(null),
      taggable_id: this.attr(null),
      taggable_type: this.attr(null),
    };
  }
}
```
```js
class Post extends Model {
  static entity = 'App\\Post';

  static fields() {
    return {
      id: this.attr(null),
      title: this.attr(''),
      user_id: this.attr(null),
      folder_id: this.attr(null),
      pivot: this.attr(null),
      media: this.hasMany(Media, 'model_id'),
      user: this.belongsTo(User, 'user_id'),
      tags: this.morphToMany(Tag, Taggable, 'tag_id', 'taggable_id', 'taggable_type'),
      comments: this.morphMany(Comment, 'commentable_id', 'commentable_type'),
    };
  }
}
```
```js
class Media extends Model {
  static entity = 'App\\Media';

  static fields() {
    return {
      id: this.attr(null),
      media_url: this.attr(null),
      thumb_url: this.attr(null),
      thumb_square_url: this.attr(null),
      model_id: this.attr(null),
      mime_type: this.attr(null),
      post: this.belongsTo(Post, 'model_id'),
      custom_properties: this.attr(null),
      size: this.attr(null),
      ...timestamps,
    };
  }
}

```

**Comment by jpenaroche** [comment]
@malinushj  well, i changed my mediable_type attribute from Api to User and i setted my entity attribute to User, but i'm still having the same result..., i mean, those attributes.., tag and order doesn't load from response, now vuex-orm doesn't create ghost model, but tag and order attributes still are null :( 
Anyway , in your example you don't set any exlusive attribute in Taggable Model, you only set id_keys, that is my problem when i try to set other attributes over id keys :\ vuex-orm doesn't set those attributes.

//Response gist:
https://gist.github.com/jpenaroche/907929e6738b201c0be6c8fa3cdf75c7

//Store screenshot
![Screenshot at 2019-04-12 10-05-22](https://user-images.githubusercontent.com/17749214/56043201-cbb1e400-5d0a-11e9-8392-c8449794ea96.png)

**Comment by jpenaroche** [comment]
Try to set other attributes in Taggable on pivot model, an then watch in devTools the store...

**Comment by jpenaroche** [comment]
Now, testing i discovered that when i set tag and order attributes in relathionship declaration...

`export class User extends Model {
    static entity = 'User'

    static fields() {
        return {
            id: this.attr(null),
            name: this.string(''),
            email: this.string(''),
            active: this.boolean(true),
            is_admin: this.boolean(false),
            locale: this.string('es'),
            created_at: this.attr(''),
            updated_at: this.attr(''),
            remember_token: this.string(''),
            profile: this.hasOne(Profile, 'user_id'),
            media: this.morphToMany(Media, Mediable, 'media_id', 'mediable_id', 'mediable_type','tag','order'),
            roles: this.morphToMany(Role, Roleable, 'role_id', 'model_id', 'model_type'),
            permissions: this.morphToMany(Permission, Permissionable, 'permission_id', 'model_id', 'model_type'),
        }
    }
}`

... well, vuex-orm fill
![Screenshot at 2019-04-12 10-40-30](https://user-images.githubusercontent.com/17749214/56045537-6ca29e00-5d0f-11e9-9d31-e897be55fe91.png)
 those attributes but, it doesn't retrieves the model.... ahhh so frustrating!!!

**Comment by malinushj** [comment]
Hmm, here a possible fix:
```js
// Media.js model
export class Media extends Model {
  ...
  static fields() {
    return {
       ...
       // Add the pivot so that vuex-orm saves that data even though you won't directly need it
       pivot: this.attr(null),
       ...
    }
  }
  static beforeCreate(model) {
    // Create the pivot model manually if it exists on the Media model
    if (model.pivot) {
      Mediable.insertOrUpdate({ data: model.pivot })
    }
  }
}
```

I'm using this pattern quite often, hope it does the trick for you as well

**Comment by jpenaroche** [comment]
Ok, thanks @malinushj  , with your fix I inserted all pivot data inside pivot attribute, but i can't make a query with pivot attributes so, i included another attribute which contains the relation with Mediable model, and i tested with my query and it works!!!, but only works when i don't set the primaryKey array in Mediable model. 
To summing up, with your fix and the another attribute to set the relationship works, but data is written twice with primaryKeys and without them..., and if i pass my primaryKey array well..., the query builder doesn't work with pivot data... :\ ...code below:

```javascript
export class Media extends Model {
    static entity = 'Media'

    static fields() {
        return {
            id: this.attr(null),
            disk: this.string(''),
            directory: this.string(''),
            filename: this.string(''),
            extension: this.string(''),
            mime_type: this.string(''),
            attributes: this.string(''),
            aggregate_type: this.string(''),
            size: this.number(0),
            created_at: this.attr(null),
            updated_at: this.attr(null),
            pivot:this.attr(null),// Pivot data attr
            mediable:this.hasOne(Mediable,'media_id') // Mediable relation
        }
    }

    static beforeCreate(model) {
        // Create the pivot model manually if it exists on the Media model
        if (model.pivot) {
            Mediable.insertOrUpdate({ data: model.pivot })
        }
    }
}

export class Mediable extends Model {
    static entity = 'Mediable'
    // Only works query builder with 
    // static primaryKey = ['mediable_id','media_id','mediable_type']

    static fields() {
        return {
            media_id: this.attr(null),
            mediable_id: this.attr(null),
            mediable_type: this.attr(null),
            tag: this.attr(null),
            order: this.attr(null)
        }
    }
}

//Query
User.query().with('media',(query)=>{
                 query.with('mediable').whereHas('mediable',(query)=>{
                     query.where('tag','profile')
                })
            }).find(7)
```

**Comment by jpenaroche** [comment]
Ok i did it with this fix... is a little tricky and i think is not optime but i couldn't find another way to make it.
```javascript
export class Mediable extends Model {
    static entity = 'Mediable'

    static primaryKey = ['mediable_id','mediable_type','media_id']

    static fields() {
        return {
            media_id: this.attr(null),
            mediable_id: this.attr(null),
            mediable_type: this.attr(null),
            tag: this.attr(null),
            order: this.attr(null)
        }
    }

     static beforeCreate(model)
     {
        // Create the pivot model manually if it exists on the Media model
        const {tag,order} = Media.find(model.media_id).pivot;
        model.tag = tag;
        model.order = order;
    }
}
```

**Comment by kiaking** [comment]
I think this issue is as same as #321? Correct me if I'm wrong but I think it's now about accessing field at pivot record... right?

If so, I would like to close this issue and process this at #321.

**Comment by jpenaroche** [comment]
@kiaking no, it's not the same issue; this is about to insert fields in pivot table that are not among the basics fields on morphable type table.  In this case tag, and order fields. 
But i have another doubt, i have in this case n elements in mediable table, but these elements are matched by those attributes (media_id, mediable_id, mediable_type, tag, order), but vuex-orm can only set elements with (media_id, mediable_id, mediable_type) like primary key., so... i can only save in store those elements with primaryKey array (media_id, mediable_id, mediable_type), order and tag attributes can't be included like primaryKey, how can i solve this.

**Comment by kiaking** [comment]
@jpenaroche Ahh OK, I think I'm getting close to understanding your issue... But not 100%. Sorry for my lack of understanding but could you give me the input and output you wish to get from the model declaration? So that I can create failing test case for this and tackle on.

Like when you insert some object, what should be stored, and how you're trying to retrieve the data.

**Comment by jpenaroche** [comment]
@kiaking ok;
models:
Media model

```javascript
export class Media extends Model {
    static entity = 'Media'

    static fields() {
        return {
            id: this.attr(null),
            disk: this.string(''),
            directory: this.string(''),
            filename: this.string(''),
            extension: this.string(''),
            mime_type: this.string(''),
            attributes: this.string(''),
            aggregate_type: this.string(''),
            size: this.number(0),
            video_id:this.attr(null),
            video_url:this.attr(null),
            video_thumbnail:this.attr(null),
            active:this.boolean(true),
            created_at: this.attr(null),
            updated_at: this.attr(null),
            pivot:this.attr(null),
            mediable:this.hasOne(Mediable,'media_id')
        }
    }
}
```

Mediable model
```javascript
export class Mediable extends Model {
    static entity = 'Mediable'

    static primaryKey = ['mediable_id','mediable_type','media_id']

    static fields() {
        return {
            media_id: this.attr(null),
            mediable_id: this.attr(null),
            mediable_type: this.attr(null),
            tag: this.attr(null),
            order: this.attr(null)
        }
    }

     static beforeCreate(model)
     {
        // Create the pivot model manually if it exists on the Media model
        const {tag,order} = Media.find(model.media_id).pivot;
        model.tag = tag;
        model.order = order;
    }
}
```
```javascript
export class User extends Model {
    //El nombre de entidad debe coincidir con el nombre del atributo "type"
    // en las relaciones polimorficas que se setean en el AppServiceProvider de Laravel
    static entity = 'User'

    static fields() {
        return {
            id: this.attr(null),
            name: this.string(''),
            email: this.string(''),
            email_verified_at: this.attr(null),
            active: this.boolean(true),
            is_admin: this.boolean(false),
            locale: this.string('es'),
            created_at: this.attr(''),
            updated_at: this.attr(''),
            remember_token: this.string(''),
            profile: this.hasOne(Profile, 'user_id'),
            //Media relation
            media: this.morphToMany(Media, Mediable,'media_id','mediable_id', 'mediable_type'),
            //roles: this.morphToMany(Role, Roleable, 'role_id', 'model_id', 'model_type'),
            //permissions: this.morphToMany(Permission, Permissionable, 'permission_id', 'model_id', 'model_type'),
        }
    }
}
```
Response Data:
```javascript
{
    "status": "success",
    "result": {
        "id": 85,
        "name": "gonzalo",
        "email": "tomasino@localhost.com",
        "email_verified_at": null,
        "locale": "es",
        "is_admin": 0,
        "active": 1,
        "created_at": "13/04/19",
        "updated_at": "2019-04-25 13:40:37",
        "media": [
            {
                "id": 730,
                "disk": "public",
                "directory": "uploads/user/img/original",
                "filename": "c4ca4238a0b923820dcc509a6f75849b",
                "extension": "jpg",
                "mime_type": "image/jpeg",
                "attributes": "{\"title\":\"gonzalo\"}",
                "video_id": null,
                "video_url": null,
                "video_thumbnail": null,
                "aggregate_type": "image",
                "size": 288386,
                "active": 1,
                "created_at": "2019-04-25 12:16:03",
                "updated_at": "2019-04-25 13:40:37",
                "pivot": {
                    "mediable_id": 85,
                    "media_id": 730,
                    "mediable_type": "User",
                    "tag": "img",
                    "order": 1
                }
            },
            {
                "id": 730,
                "disk": "public",
                "directory": "uploads/user/img/original",
                "filename": "c4ca4238a0b923820dcc509a6f75849b",
                "extension": "jpg",
                "mime_type": "image/jpeg",
                "attributes": "{\"title\":\"gonzalo\"}",
                "video_id": null,
                "video_url": null,
                "video_thumbnail": null,
                "aggregate_type": "image",
                "size": 288386,
                "active": 1,
                "created_at": "2019-04-25 12:16:03",
                "updated_at": "2019-04-25 13:40:37",
                "pivot": {
                    "mediable_id": 85,
                    "media_id": 730,
                    "mediable_type": "User",
                    "tag": "profile",
                    "order": 1
                }
            }
        ]
    }
}
```
Query:
```javascript
User.query().with('media',(query)=>{
                query.with('mediable').whereHas('mediable',(query)=>{
                    query.where('tag','thumb')
                })
            }).find(1)
```
As you can see, in my Mediable model declaration, i have to set manually (tag,order) pivot attributes for use in queries later..., and using this way well it worked, but vuex-orm set mediable elements using primary key with keys type id which are setting on declaration of the relationship, so, like vuex-orm doesn't set the others attributtes (tag, order) like primary_keys values well, it only set the first elements with same id, but not the others elements with other tags (Screenshots below).
![Screenshot at 2019-04-26 11-06-57](https://user-images.githubusercontent.com/17749214/56817691-0f7d1100-6814-11e9-958d-5175f5d7ec0f.png)
![Screenshot at 2019-04-26 11-10-11](https://user-images.githubusercontent.com/17749214/56817701-1441c500-6814-11e9-9bef-35bbe0c0ac03.png)

**Comment by kiaking** [comment]
Ahhhh Finally I see! Yeah I get it. You got point. I wasn't thinking about this use case. But surely yeah we need this.

We have other issue where adding feature to map response structure to some custom object tree. I think we can keep in mind about this issue. Since clearly, to achieve this, we need some way to tell Vuex ORM that the key `pivot` inside Media belongs to intermediate table.

**Comment by kiaking** [comment]
This is now possible with Vuex ORM 0.36.0! 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.36.0
