### ISSUE TITLE
How to define fields that will not be serialized ?

### ISSUE THREAD

**Issue by stygmate** [vuex-orm/vuex-orm#328]
all is in the title !

**Comment by tvillaren** [comment]
Hello @stygmate,

You want to add "internal fields" to your models that will not be exposed when using `toJSON`?
You can read this issue exposing which fields are serialized: https://github.com/vuex-orm/vuex-orm/issues/319 

If you want to have other fields, just don't add them to the `static fields()` definition :)

**Comment by stygmate** [comment]
@tvillaren 
> If you want to have other fields, just don't add them to the `static fields()` definition :)

where and how ?

**Comment by tvillaren** [comment]
```
export default class Address extends Model {
	static fields() {
	...
	}
	$_your_internal_field = null
}
```

**Comment by stygmate** [comment]
@tvillaren that simple 😭 ! thank you !
is there a way to enforce typing ?

**Comment by tvillaren** [comment]
You mean, like when using the `this.string(null)` from Vuex ORM?

If so, I'm not sure to understand fully what is the use for the internal field you want. 
If you want it to still be handled by Vuex ORM, you probably want to keep it in the `static fields()` definition and maybe create a plugin to ignore some fields for serialization.

What is more precisely your need?

**Comment by stygmate** [comment]
@tvillaren don't bother with that, I have found my way.

out of scope question:
how to avoid collision between id created by increment by vuex-orm and id coming from my api ?
Any sort of general guideline ?
I see that $id become "_no_key_x" when id is null.

Have i to create relation filling the localkey with $id ?

like:
``` javascript
export default class Dossier extends Model {
    static entity = 'dossiers'

    static fields() {
        return {
            id: this.attr(null),
            ...
            bien_id: this.attr(null),
            bien: this.belongsTo(Bien, 'bien_id'),
            individus: this.hasMany(Individu, 'dossier_id', '$id'),
            fichiers: this.hasMany(Fichier, 'dossier', '$id'),
        }
    }
```

**Comment by tvillaren** [comment]
I'm not familiar with Vuex ORM auto-increment feature (I use GUIDs for all my IDs). 
You can join us on [Slack](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTI0YjE5YmNmMDIxNWZlNmJhM2EyMDg1MDRkODA4YmQwMDU5OWRkZmNhN2RmOTZkZGZkODQxZTRkYjhmYmJiNTY), probably more people will be able to help there.
