### ISSUE TITLE
.toJson() not always serializing relation.

### ISSUE THREAD

**Issue by stygmate** [vuex-orm/vuex-orm#329]
I'm wondering why when i do `MyModel.find(x).toJson()` not all my relation are serialized. and it work with `MyModel.query().withAll().whereId(x).first().toJson()`

**Comment by tvillaren** [comment]
You need to load the relation you want to serialize.   
That's why it works in the second case. 

If you want to load specific relations, you can use `with('bars')` (see https://vuex-orm.github.io/vuex-orm/guide/relationships/retrieving-relationships.html)
