### ISSUE TITLE
Model query using the with handler returns always all entities

### ISSUE THREAD

**Issue by pimeo** [vuex-orm/vuex-orm#330]
I found that there is a mistake when making a condition using the `with` handler. To better understand the issue, I have covered the problem by creating a test based on yours owns. It is possible that I haven't understood the way to use the with handler but to be sure I prefer to share you my test to detect if it is or not a critical issue.

I have seen that in order to query a model relationship to get posts, the mechanism of the `with` handler seems to be broken and returns by default all entries from an entity.

Tested on release v0.31.7.

```js
import { createStore } from 'test/support/Helpers'
import Model from 'app/model/Model'

describe('Feature – Relations – Retrieve – Constraint', () => {
  class User extends Model {
    static entity = 'users'

    static fields () {
      return {
        id: this.attr(null),
        posts: this.hasMany(Post, 'user_id')
      }
    }
  }

  class Post extends Model {
    static entity = 'posts'

    static fields () {
      return {
        id: this.attr(null),
        user_id: this.attr(null),
        published: this.boolean(false),
        user: this.belongsTo(User, 'user_id')
      }
    }
  }

  
  const store = createStore([{ model: User }, { model: Post }])

  store.dispatch('entities/users/create', {
    data: [{ id: 1 }, { id: 2 }, { id: 3 }]
  })

  store.dispatch('entities/posts/create', {
    data: [{ id: 1, user_id: 1, published: true }, { id: 2, user_id: 1, published: true }, { id: 3, user_id: 2, published: false }]
  })


  /*
    * Reminder:
    * user_1 has published posts [1, 2]
    * user_2 has no published post
    * user_3 has published post [4]
  */

  // only user_1 has at least one published post
  const expected_value = 1

  it('can resolve constraint using with orm query statement', () => {

    // get users who have post id 1 in their posts relationship
    const users = store.getters['entities/users/query']()
      .with('posts', (query) => {
        query.where('published', true)
      })
      .get()

    expect(users.length).toEqual(expected_value)

  })

  it('can resolve constraint using with native query statement', () => {

    const users = store.getters['entities/users/query']().with('posts').get().slice()
    const results = users.filter( (user) => {
      return user.posts.some( (post) => {
        return post.published == true
      })
    })

    expect(results.length).toEqual(expected_value)
  
  })


})

```

Mocha output

```txt
  Feature – Relations – Retrieve – Constraint
    1) can resolve constraint using with orm query statement
    ✓ can resolve constraint using with native query statement


  1 passing (65ms)
  1 failing

  1) Feature – Relations – Retrieve – Constraint
       can resolve constraint using with orm query statement:
     Error: expect(received).toEqual(expected)

Expected: 1
Received: 3
      at Context.<anonymous> (.tmp/mocha-webpack/1554412366220/webpack:/test/feature/relations/Retrieve_Constraint.spec.js:60:1)

```
As you can see, the orm query statement has returned all entities instead of returning only one entity.

BTW : the test file `https://github.com/vuex-orm/vuex-orm/blob/master/test/feature/relations/Retrieve_Constraint.spec.js#L51` is wrong because it returns more than one result but you couldn't see that before because it was tested only on the first entry result. 

Thanks!

**Comment by kiaking** [comment]
@pimeo Hi! thank you for the feedback!

The result is expected. To get the "users" which has matching relation constraints, you should use `has` or `hasWhere`.

The `with` constraint limits the number of relation, not the model that is queried.

So for your example, it is expected that you get all users. To get only the users that have posts with `published` value of `true`, you need to do this.

```js
const users = store.getters['entities/users/query']()
  .with('posts')
  .whereHas('posts', (query) => {
    query.where('published', true)
  })
  .get()
```

This is documented here:
https://vuex-orm.github.io/vuex-orm/guide/relationships/retrieving-relationships.html#querying-relationship-existence

**Comment by pimeo** [comment]
Hi @kiaking 

Thanks for you answer. I will test your example to verify that the expected value is right (and I can provide you the test if you want to add to the current tests).

Also to be clear with the documentation when I see the following example:

```js
// Get all users with posts that have `published` field value of `true`.
const user = User.query().with('posts', (query) => {
  query.where('published', true)
}).get()

/*
  [
    User {
      id: 1,
      name: 'john',
      posts: [
        Post: { id: 1, user_id: 1, body: '...', published: true },
        Post: { id: 2, user_id: 1, body: '...', published: true }
      ]
    },

    ...
  ]
*/
```

Can you confirm me that this is a valid and expected code/output result, and that we won't have posts as results with published state set to false (via a test file by example)?

Section of the documentation linked: [Relation Contraints](https://vuex-orm.github.io/vuex-orm/guide/relationships/retrieving-relationships.html#relation-constraints)

**Comment by kiaking** [comment]
Ohh sorry yeah that documentation's comment is a bit confusing. It sounds like it returns only the matching "users" rather than "posts".

> Can you confirm me that this is a valid and expected code/output result, and that we won't have posts as results with published state set to false (via a test file by example)?

Yes. We have a simpler test case for this.

```js
  it('can resolve relation constraint', () => {
    const store = createStore([{ model: User }, { model: Post }])

    store.dispatch('entities/users/create', {
      data: [{ id: 1 }, { id: 2 }, { id: 3 }]
    })

    store.dispatch('entities/posts/create', {
      data: [{ id: 1, user_id: 1 }, { id: 2, user_id: 1 }, { id: 3, user_id: 2 }]
    })

    const expected = {
      $id: 1,
      id: 1,
      posts: [
        { $id: 1, id: 1, user_id: 1, user: null }
      ]
    }

    const users = store.getters['entities/users/query']()
      .with('posts', (query) => {
        query.where('id', 1)
      })
      .first()

    expect(users).toEqual(expected)
  })
```

Here there are 2 posts relates to the user with id of 1 but we only retrieve the post with the id of 1. If we were to fetch all users on above test case, then the result would be like below.

```js
[
  {
    id: 1,
    posts: [
      { id: 1, user_id: 1 }
    ]
  },
  {
    id: 2,
    posts: []
  },
  {
    id: 3,
    posts: []
  }
]
```

**Comment by pimeo** [comment]
Ok now it's clear ! Thank you for your response. I will close the ticket.

**Comment by kiaking** [comment]
Great! Sorry for the confusion. I'm planning to rewrite the whole documentation before hitting v1.0.0 so I'll make sure to update doc to be easier to understands. Thank you for the feedback! 🤝
