### ISSUE TITLE
TS Error : Cannot find module 'normalizr'

### ISSUE THREAD

**Issue by kevinmarrec** [vuex-orm/vuex-orm#349]
# Description
When using VuexORM in a TypeScript project, there are errors regarding `normalizr` module not found. I checked `package.json` and the package is in `devDependencies`, instead of (I guess) `dependencies` ?

# Screenshot
![Screenshot from 2019-04-25 15-37-39](https://user-images.githubusercontent.com/25272043/56739913-1d795600-6770-11e9-86d4-e9af030303c0.png)

**Comment by kiaking** [comment]
@kevinmarrec Hi! thank you so much for your report!

This is interesting. Since the published package are bundled into single JS file so it should include Normalizr. Or maybe TypeScript loads things from different place...? Maybe the type declaration file is imported from source of Normalizr... Let me check on this!

**Comment by spaceemotion** [comment]
@kiaking I got the same error(s) when using the vue-cli's TS setup + installed vuex-orm on top of that.

**Comment by kiaking** [comment]
@spaceemotion Thx for the info!

**Comment by kevinmarrec** [comment]
@kiaking You're right, TypeScript is indeed looking for the declaration file of `normalizr` which is missing as it's not a dependency.

Only workaround I found is installing `normalizr`.

The package being light and 0 dependencies itself, I think it can be kept under `dependencies` as logic fix.

**Comment by kiaking** [comment]
@kevinmarrec Thanks! Yeah I think that's the way to go about it. Let me just check on this by setting up typescript project at my side and see if everything works.

**Comment by kevinmarrec** [comment]
@kiaking I've checked on 2 projects where I installed `normalizr` dependency, everything worked.
It just don't feel smooth having `normalizr` dep in my project's `package.json` files, as it should be in `vuex-orm` one :)

**Comment by kiaking** [comment]
@kevinmarrec Thank you for the confirmation! I just want to make sure if moving `normalizr` to `dependencies` at Vuex ORM side would really solve the problem. I agree with you too that it should, but just to make sure.

**Comment by kevinmarrec** [comment]
@kiaking Well I don't think there really is other solution, as the issue is about a missing dependency.
If a package (`vuex-orm`) uses type definitions of an external `package`, it must have them shipped. It could have been `@types/normalizr` but types are not under such repo but in the same package as code source : `normalizr` (https://github.com/paularmstrong/normalizr/blob/master/index.d.ts).

**Comment by kiaking** [comment]
Sorry it tool long but this issue should been fixed with Vuex ORM 0.31.12 🔥 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.31.12

Thank you so much for your report 🤝
