### ISSUE TITLE
Clear data without "deletion"

### ISSUE THREAD

**Issue by spaceemotion** [vuex-orm/vuex-orm#350]
I've been testing this plugin for a bit now and would like to integrate it into my project, but got a question regarding managing state.

Showing a table with thousands of records (let's say "users") is usually done via server-side pagination.

The problem I am having is how I can fetch the new data from the backend and replace the current state with it - without calling any of the delete actions.

This is simply so I don't have megabytes of data on the users phone later down the line, when they have been using the app for quite a while.

Any ideas? Have I been missing something?
Thanks in advance!

**Comment by tvillaren** [comment]
Hello,

How do you insert data currently in your store?
If you use the `create` method (as described here: https://vuex-orm.github.io/vuex-orm/guide/store/inserting-and-updating-data.html#inserts), the store data is flushed before inserting the new one. 

Is that what you're looking for?

**Comment by spaceemotion** [comment]
Yes, seems like I've missed that! Does it only affect the User model though, or does it also clean up their relationships?

**Comment by kiaking** [comment]
@spaceemotion It only affects User model! However, if you have nested relationship, say user has many posts, then the posts will also be cleared. In that case, you can control the behavior by passing an option.

```js
// `create` user but `insert` posts.
User.create({
  data: users,
  insert: ['posts']
})
```

**Comment by spaceemotion** [comment]
Nice, so in case I want to paginate through my data, but keep the currently opened User (let's say a sidebar view), with all its relationships I can do the following?

```js
User.create({
  data: [
    ...users,
    currentUser,
  ],
})
```

In which case it would properly merge all models and relationships?

Let's say I got a company assigned to each user (many users share the same company), will the company model then be taken from the new data or my existing instance?

**Comment by kiaking** [comment]
@spaceemotion Oh yes that should work just fine. The relationship should work as expected too. Just be careful not to include company relation in that users data. Or if you do, remember to do:

```
User.create({
  data: [
    ...users,
    currentUser,
  ],
  insertOrUpdate: ['company']
})
```

**Comment by spaceemotion** [comment]
Thanks! that insertOrUpdate should do the trick then.

Closing this as the question was answered. Cheers!

**Comment by kiaking** [comment]
Glad you found the answer! Feel free to open another issue if you have anything.
