### ISSUE TITLE
hasManyThrough with string IDs doesn't work

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#352]
... probably.

I've discovered it while implementing https://github.com/vuex-orm/plugin-graphql/pull/91.

https://github.com/vuex-orm/plugin-graphql/pull/91/files#diff-73279083556e37e12ba8818c5e2d8b00R999 because `tariff.tariffOptions` is undefined.
With integer IDs the tests pass.

https://travis-ci.org/vuex-orm/plugin-graphql/builds/524843410

**Comment by kiaking** [comment]
@phortx Hi! I've added test case for this at PR #361, but it is passing. Can you find any difference between your test case...?

**Comment by phortx** [comment]
Hmm still failing. I've created a jsfiddle :9

https://jsfiddle.net/8qg13e4n/8/

**Comment by kiaking** [comment]
@phortx Thanks for the confirmation! I've confirmed the fiddle too. Hmm... it might be something to do with custom primary key... Let me add another test to check that!

**Comment by kiaking** [comment]
@phortx Oh wait a minute, that fiddle is defining `belongsToMany`, not `hasManyThrough`. (still it's an issue though). Is this issue about `belongsToMany` at first place?

**Comment by kiaking** [comment]
And I think there was issues in the fiddle. I think I've got it fixed.
https://jsfiddle.net/cq73agos/

You were referencing the key which didn't exist.

```js
class Tariff extends VuexORM.Model {
  static entity = "tariffs";
  static primaryKey = ["uuid"];

  static fields() {
    return {
      uuid: this.string(""),
      name: this.string(""),

      tariffOptions: this.belongsToMany(
        TariffOption,
        TariffTariffOption,
        "tariffUuid", // <- I've changed this one to `uuid`.
        "tariffOptionId"
      )
    };
  }
}
```


Also, Vuex ORM was version 0.30.0 so I upgraded to 0.31.11.

Could you take a look at it?

**Comment by phortx** [comment]
Oh you're right I think mixed hasManyThrough with belongsToMany.

It's about belongsToMany here.

Looking at your change, I think I misunderstood how this works at all. I thought I have to pass the primary key field of the model, but rather I have to pass the foreign key. 

I will try this in my test and close the issue when it works :)

**Comment by phortx** [comment]
It works! Thank you very much :) We need more builtin warnings :P

**Comment by kiaking** [comment]
Great! Nice to hear that!
