### ISSUE TITLE
Two Vuex Orm Instances On same Page Error

### ISSUE THREAD

**Issue by wkasem** [vuex-orm/vuex-orm#355]
```Js
const database = new VuexORM.Database()

database.register(User)
Vue.use(Vuex);

export default new Vuex.Store({
     plugins: [VuexORM.install(database)],
     ...store
})
```

```js
let packageDB = new orm.Database()

packageDB.register(Package)
Vue.use(Vuex);

export default new Vuex.Store({
     plugins: [orm.install(packageDB)],
     ...store
});
```

```bash
vendor.js:12347 TypeError: this.getters(...) is not a function
    at Function.webpackJsonp../node_modules/@vuex-orm/core/dist/vuex-orm.esm.js.Model.query
```

but works fine if there only on usage of vuex orm

**Comment by kiaking** [comment]
@wkasem Hi! Thank you for the feedback. I'm not sure what is the issue here. Are you trying to install 2 databases to 2 Vuex Store instance?

**Comment by wkasem** [comment]
yes , i have two vue instances each one with it's own database

**Comment by kiaking** [comment]
@wkasem Just checking in. Do you had any progress on this?

**Comment by wkasem** [comment]
No , no Fix For This issue

**Comment by kiaking** [comment]
OK. I'm not sure if having multiple Vuex Store instance will ever be supported, but supporting multiple Vuex ORM Database instance are planned at issue #360. Let's follow up there!
