### ISSUE TITLE
with not working with many to many

### ISSUE THREAD

**Issue by Uysim** [vuex-orm/vuex-orm#357]
When I use Post.query().with("tags").get(). Tags will return empty array for many to many

**Comment by kiaking** [comment]
@Uysim Hi! Thank you for the report! Sorry but I need more info on this. The test is passing so I think here's something wrong with either data, or Model schema definition.

Could you provide us a reproducible code for the issue?

**Comment by Uysim** [comment]
@kiaking  Sorry I think it is my mistake. Now it is working fine. Thank you for you time. I'll close this issue

**Comment by kiaking** [comment]
Oh OK. Glad to hear you found a solution! Feel free to open another issue if there's anything 🤝
