### ISSUE TITLE
Mapping nested Objects 

### ISSUE THREAD

**Issue by eladyaniv01** [vuex-orm/vuex-orm#358]
Assuming my API returns Nested Objects like so 

```js
{
  // Parent
  "id": 130,
  "children": [ array of objects here, each one is a children],            
}
```

and my models are like so

```js
export default class Parent extends Model {
    // This is the name used as module name of the Vuex Store.
    static entity = 'parents'
    static primaryKey = 'id'
    // List of all fields (schema) of the post model. `this.attr` is used
    // for the generic field type. The argument is the default value.
    static fields() {
        return {
            id: this.attr(null),
            childrent: this.attr(null),
        }
    }
}

// And a Child model 
export default class Client extends Model {
    // This is the name used as module name of the Vuex Store.
    static entity = 'children'
    static primaryKey = 'id'
    // List of all fields (schema) of the post model. `this.attr` is used
    // for the generic field type. The argument is the default value.
    static fields() {
        return {
            id: this.attr(null),
            parent: this.attr(null),
        }
    }
}
```
Now,  i want to end up with 2 sets,  but construct binding relationships between them like so

- Parent  ->  The Parent Object
- Parent.Child -> the Children SET belonging to the Parent
- Child -> All of the Children of all Parents 

How is it possible verify that if i update some entry in Child, lets say the first so
Child[0] ,  and that same Child[0]  is also Parent.Child[2]

>  (same objects in the data base, just two ways to fetch it from store)

* so  if i change the attributes of one, will the other be updated and treated as exactly the same object ? i assume the answer is no

i have tried variands of 
`hasMany` `hasOne` `belongsTo`
instead of `parent: this.attr(null),`
none of them worked
is this the intended behavior ?  am i missing something in the docs ? 
Thanks, 
Elad.

**Comment by kiaking** [comment]
Resolved at Slack conversation. Starting at https://vuex-orm.slack.com/archives/C9QRJRVA7/p1557219763140700
