### ISSUE TITLE
Question: why Vuex ORM and not just JS ORM?

### ISSUE THREAD

**Issue by davestewart** [vuex-orm/vuex-orm#366]
Hey there,

Just having a quick scan of the project, and it looks super-advanced, clearly it solves the problem it set out to. I've not used any code yet, or delved deep, but I do have one question, which leads to some follow-on questions:

Why is this based on Vuex?

Pretty much all of the code looks like pure JavaScript - why muddy it with the Flux pattern and Vuex?

Does basing it on Vuex provide more advantages than disadvantages?

Thanks.

**Comment by kiaking** [comment]
@davestewart Hi! Thank you for the interest in Vuex ORM!

The biggest reason is because it depends deeply on Vuex's (and Vue's) reactivity system. For that, we must go through Vuex Mutation. For example, Model methods is actually calling Vuex Mutation, it's not manipulating JS object directly.

It might be cool to have similar library for plain JS object instead of Vuex Store. I have a strong interest and maybe we could use that library behind Vuex ORM for instance.

> Does basing it on Vuex provide more advantages than disadvantages?

If we ditch Vuex, it's going to be much harder to use the library with Vuex : )

**Comment by kiaking** [comment]
@davestewart Hi! Did my answer made sense? If so maybe we could open another issue for creating ORM system for the plain JS object. It might make sense to have that to use as backend for Vuex ORM.

**Comment by davestewart** [comment]
Hey @kiaking!

Sorry for the lack of reply - craaaazy busy at work and home at the moment, I'm just not keeping up with things.

Yeah, your explanation does make sense. I know Vuex pretty well as well. I created [Vuex Pathify](https://github.com/davestewart/vuex-pathify) so I imagine we have tackled similar problems!

I have to say, the TypeScripting looks very impressive. I wish I had your knowledge!

Yes, I have moved away from using Vuex in every project these days. Various reasons:

- I find the amount of setup and boilerplate to be cumbersome
- the different syntaxes are cumbersome to juggle (hence, writing Pathify!)
- the string based syntax is not as editor-friendly as direct JS classes
- the constraints of the generally single-level state / module structure can be limiting
- for some situations (CRUD / forms) it makes no sense to put this in a global store you can only access via a string-based API 
- the single global store > mapping constraints aren't flexible (ideally you would be able use a store locally or globally, like a Vue model)
- time travel debugging and so on, whilst clever, is not relevant to 99.9% of the development I do
- When a project scales REALLY large (50 - 100 stores) a single store just doesn't feel as useful

However, what I do find useful is:

- a design pattern that everyone knows
- great devtools support
- single state tree is really useful for medium projects

So with that in mind, yeah, I think breaking the tech out to a vanilla lib would be really cool.

I imagine that in a few years, another pattern will replace Flux. Hopefully based on direct class access, perhaps TypeScript and decorators will come to the rescue here, injecting state or what have you.

Anyway - great to talk!

Are you on any discord channels or twitter?

**Comment by kiaking** [comment]
@davestewart Woooow You are the author of Pathify!? So cool. It's an honor to hear from you.

I understand your point very much. I'm really looking forward to Vuex 4 as well, and I too think this FLUX pattern could be better in many ways.

> Are you on any discord channels or twitter?

Not on discord but Yes at [Twitter](https://twitter.com/KiaKing85). I'm at [Vuex ORM Slack channel](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTI0YjE5YmNmMDIxNWZlNmJhM2EyMDg1MDRkODA4YmQwMDU5OWRkZmNhN2RmOTZkZGZkODQxZTRkYjhmYmJiNTY) mainly.

Do you wanna discuss on creating ORM for plain object? I'm very interested though : )

**Comment by davestewart** [comment]
>  It's an honor to hear from you

Awww - thanks! Well, the admiration is mutual :P

> Do you wanna discuss on creating ORM for plain object?

To be honest, I don't do much nested DB stuff like that at the moment, so it's not so relevant to me – *at this time*. Though maybe another time!

Also, I'm stacked with work and trying to release a commercially-based side project right now, so I'm getting no time to do any open source!

But let's connect for sure :D

**Comment by kiaking** [comment]
@davestewart OK sure no worries. I'm very excited to hear from someone like you. Maybe we can work together some day : )

I'll close this issue for now, the plain JS thing are always on my mind so maybe I'll start doing thing in the future.

Thank you so much for the contact anyway! 🤝

**Comment by davestewart** [comment]
> Maybe we can work together some day : )

I'd love that!
