### ISSUE TITLE
Morph To Many not working when combining with increment id

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#367]
Report from @phortx at Slack.

Fiddle:
https://jsfiddle.net/ukhLncq7/1/

When defining all model with `increment` primary key, this is happening. We don't have test for this.

**Comment by phortx** [comment]
I need this. Do you have any plans when this will be fixed? :)

**Comment by kiaking** [comment]
I'll try look into it soon!

**Comment by kiaking** [comment]
I've reproduced it, and fixed it. Stay tuned I'll be making release soon.

**Comment by kiaking** [comment]
@phortx This issue should be fixed at Vuex ORM 0.31.12 🔥 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.31.12

**Comment by phortx** [comment]
Works! Thank you :)

**Comment by kiaking** [comment]
Wonderful! 🎉
