### ISSUE TITLE
How to add data to entities?

### ISSUE THREAD

**Issue by jimmiejackson414** [vuex-orm/vuex-orm#372]
I apologize for the noob question, but I _really_ want to get this to work! I come from a Rails background and vuex-orm will make it so much easier for me to work with Vuex, as well as normalizing my data structure as it's coming in deeply nested. I know Issues is not where you'd normally ask these types of questions, however I asked a [question on Stack](https://stackoverflow.com/questions/56204515/vuex-orm-entity-data-is-always-empty) and didn't receive a response. 

Since I've posted that question, I was able to add an item to the TodoItem entity as a test in the computed property of one of my components. I'm wondering though where loading in the data should actually occur? I've got a fairly extensive Vuex module system already built out, would it require me to refactor all of that into modules described in the docs, or am I able to reuse what I've got? Any help would be greatly appreciated. Thank you!

**Comment by kiaking** [comment]
@jimmiejackson414 Hi! Thank you for the feedback!

> I'm wondering though where loading in the data should actually occur?

Usually at Vuex Component's computed property. If you want to fetch all data, you could do like:

```vue
export default {
  computed: {
    users () {
      return this.$store.getters['entities/users/all']()
    }
  }
}
```

> I've got a fairly extensive Vuex module system already built out, would it require me to refactor all of that into modules described in the docs, or am I able to reuse what I've got?

You should be able to reuse what you have. You can call your module just like you would do normally.

**Comment by kiaking** [comment]
@jimmiejackson414 Hi! Just checking in. Did you had any progress on this?

**Comment by jimmiejackson414** [comment]
I'm so sorry, I must've missed the initial response! I ended up going a different route (I had a lightbulb moment and realized that I don't actually need to store _everything_ in Vuex). I would like to revisit this library though in the future as I do think it'll be immensely helpful!

**Comment by kiaking** [comment]
@jimmiejackson414 Thank you for the response! Sorry to see you go but I'm glad you found a way! I hope to see you soon though. Good luck for you project 👍
