### ISSUE TITLE
Why vuex-orm returns null in relationship field?

### ISSUE THREAD

**Issue by wizardnet972** [vuex-orm/vuex-orm#378]
I followed the guide of [Defining Relationships](https://vuex-orm.github.io/vuex-orm/guide/relationships/defining-relationships.html) in Vuex ORM.

I did everything like the guide, so why I get null value in the category field in Article Model?

[codesandbox](https://codesandbox.io/embed/vue-template-v1beu?fontsize=14)

This is how I defining my models (category on article is: hasOne/belongTo):
```
export class Category extends Model {
  static entity = "categories";

  static primaryKey = "_id";

  static fields() {
    return {
      _id: this.attr(null),
      name: this.attr("")
    };
  }
}


export class Article extends Model {
  static entity = "articles";

  static primaryKey = "_id";

  static fields() {
    return {
      _id: this.attr(null),
      name: this.attr(""),
      category: this.hasOne(Category, "_id")
    };
  }
```

Config Vuex-orm with vuex in main.js:
```
import VuexORM from "@vuex-orm/core";
import { Article, Category } from "./models";

Vue.use(Vuex);

const database = new VuexORM.Database();

const Articles = {
  namespaced: true,

  actions: {
    test() {
      console.log(this);
    }
  }
};

const Categories = {
  namespaced: true,

  actions: {
    test() {
      console.log(this);
    }
  }
};

database.register(Article, Articles);
database.register(Category, Categories);

const store = new Vuex.Store({
  plugins: [VuexORM.install(database)]
});
```
Inside app component I have the data that I insert to vuex and get the values like so:
```
 const articleData = [
      {
        _id: "6ce9bae00000000000000000",
        name: "article-1",
        category: "5ce9acd00000000000000000"
      }
    ];
    const categoryData = [
      { _id: "5ce9acd00000000000000000", name: "category-1" }
    ];

    const x = await Article.insertOrUpdate({ data: articleData });
    const y = await Category.insertOrUpdate({ data: categoryData });

    const a = Article.query()
      .with("category")
      .first();

    console.log({ a });
    console.log({ type: a.category });
    console.log("why a.category is null???");
```

I have been trying to understand this for several days without success. I would much appreciate any help.

**Comment by paparent** [comment]
Hi ! 

Try with this model definition:

```js
export class Article extends Model {
  static entity = "articles";

  static primaryKey = "_id";

  static fields() {
    return {
      _id: this.attr(null),
      name: this.attr(""),
      category: this.belongsTo(Category, "category_id"),
      category_id: this.attr('')
    };
  }
}
```

You then need to use `category_id` in App.vue.

It happens to me too to be confused. Especially because in the docs it's in the One to One section. I'm sure we can improve this.

Hope it helps !!

**Comment by wizardnet972** [comment]
Works! @paparent  Thank you!!!

And yes, this issue is common and the docs are very confusing about that. Thank you and the whole team, for the effort and it's really appreciated.

**Comment by emahuni** [comment]
I actually think there are bugs in Vuex ORM and using belongsTo is circumventing the issues. I did the same thing; followed the tutes, and banged my head on the wall several times over a Sails to Vuex ORM model transform package. I  even contributed something with a PR in the documentation section. However, I am still yet to use Vuex ORM without issues. I then thought maybe my code is bad somewhere let me try the example code. So I cloned it and ran it. The Todo app seems to work when you run and add a few tasks, but my reason was bug hunting: 

![Screenshot 2019-05-27 at 07 41 47](https://user-images.githubusercontent.com/7290508/58397876-1f765380-8053-11e9-9fed-9f30ff43170f.png)

And, closer inspection in Vue-DevTools revealed this issue:

![Screenshot 2019-05-27 at 07 42 27](https://user-images.githubusercontent.com/7290508/58397892-2ac97f00-8053-11e9-8087-9b0b653f565b.png)

Notice the other inserted tasks' assignee are ok, but the ones I inserted are null. This is the bug!

**Comment by emahuni** [comment]
It seems like this issue is really wrecking havoc there are many duplicates about it and people are not seeing it as the same thing... please use #356 to further this.

**Comment by emahuni** [comment]
coming from #356 ...

> @emahuni I think yes, we should use #378 maybe, I haven't looked into it just yet. But the `null` issue we had on your screen shot is not happening on latest version. We need to have some kind of reproduction code to tackle further.

It's still happening. I completely deleted the example I had on my machine and cloned the example again, then ran `yarn && yarn serve` after which point I visited `localhost:3000` and opened vuex in devtools:
![Screenshot 2019-06-06 at 19 30 59](https://user-images.githubusercontent.com/7290508/59053539-f5623400-8891-11e9-90ca-eaa0dafb94ba.png)
This time around it's even worse, the initial data is also null, unlike the initial one which had something on assignee. Take a look at the two screenshots, notice that the first one has assignee 2 on record 3, but on the last screenshot the same record now has null.

**Comment by emahuni** [comment]
https://codesandbox.io/embed/vue-template-q44el

That's a codesandbox of the issue, but based on getting started

**Comment by kiaking** [comment]
@emahuni Hi! Thanks for the code. But this is expected. Within store, the relationship field should be `null` or empty array. In your example, the `author` field should always be null inside store.

Are you having trouble loading the relationship...? Then you must fetch data by `with` query chan.

```js
Post.query().with('author').get()
```

With above code, you'll get all Post with related User nested.

**Comment by emahuni** [comment]
no, you don't get it I guess. Did you see the codesandbox? I am not fetching anything. This is just the representational store data. In documentation you said it should have 1 not null.

**Comment by kiaking** [comment]
Ohhh sorry for that. The documentation is wrong. It should be fixed. So sorry for that. It should be `null`, not 1.

**Comment by emahuni** [comment]
I am not fetching anything on the state, the state has null on author, shouldn't it have an id that relates to the author in the store? Anyway I have updated the codesandbox and still there is null

**Comment by emahuni** [comment]
can you play with it and make it work as expected?

**Comment by kiaking** [comment]
It is already working as expected. So you want to fetch posts "with" user (author) right? If so you should be doing this. https://codesandbox.io/embed/vue-template-q44el

**Comment by emahuni** [comment]
ohhhh, I updated again with `Post.query().with('author').get()`, it's working

**Comment by emahuni** [comment]
So you mean the state should have associations with id's null?

**Comment by kiaking** [comment]
Associations id's should be at foreign key, not relation field. For that example, the association id is at `user_id` field at Post. Not at `author` field at Post.

**Comment by emahuni** [comment]
so it means that author field is useless then?

**Comment by kiaking** [comment]
It depends. Sometime it's useless, sometime it's useful. If you only want fetch Post but without author, then you don't need author field. If you want fetch Post with User, then you access User object at post.author so it's very useful.

**Comment by emahuni** [comment]
it's useful even if it's null? Can you please put an example in the sandbox?

**Comment by kiaking** [comment]
@emahuni I have no idea what you are trying to do... what example do you want?

**Comment by emahuni** [comment]
exmple of this: 
>  If you want fetch Post with User, then you access User object at post.author so it's very useful.

coz I don't get what you mean or how to use that feature

**Comment by emahuni** [comment]
I am trying to see how this is useful since we followed the documentation with wrong assumptions.

**Comment by kiaking** [comment]
Like this. https://codesandbox.io/embed/vue-template-hpp7e

**Comment by emahuni** [comment]
I don't know what you changed, but there is an error with the sandbox. It can't import some files. You moved the models folder. I fixed it by just renaming references. Ok, I think I get what you mean, but I think the documentation needs heavy work on. Things need to be clarified correctly. Let me see if I am actually having an issue in my project then. I will get back to you here, but in the meantime have a look at this issue's initial post before you close this issue altogether. Will go through the documentation once more and see if I can help with it.

**Comment by kiaking** [comment]
@emahuni Yeah sorry for the documentation, but the initial issue is solved already. It's about specifying correct foreign key. Please open another issue if you have anything by describing the specific issue so that other people can understand things better 👍
