### ISSUE TITLE
How to use query within nested deep object?

### ISSUE THREAD

**Issue by wizardnet972** [vuex-orm/vuex-orm#380]
I have two objects: `Article` and `Company`. 
Company has a list of articles in group array.

I hope to get help with 
1. How to define the model (`Company.groups`) (schema) to meet this structure of data? (right now is null and should be complex object according to data).. 

2. **most important:** how to populate `company.groups[].items[]` with `articles` objects by using `query` method?
This is what I have tries, but not works.. its return list of string-ids .

```js
const company = Company.query().with("article").first();
// company.groups[0].items[0] === "6ce9bae00000000000000000"
```
I expect to get the article object that mach to this id, `items` will be list of article objects instend of list of id string.

[codesandbox demo](https://codesandbox.io/s/vue-template-fy270)

![image](https://user-images.githubusercontent.com/4997825/58426261-a7387e00-80a4-11e9-8c8b-adb2a1573220.png)

I would much appreciate any help.

**Comment by kiaking** [comment]
@wizardnet972 Hi! Thank you for the feedback! Here you go.
https://codesandbox.io/s/vue-template-0mfit

Added Group model, and made `hasManyBy` relationship. Vuex ORM needs to have foreign keys and relation field separately so i created `articles` field at Group.

I hope this makes sense for you but if you having trouble understanding it, please let me know!

**Comment by kiaking** [comment]
@wizardnet972 I think this issue is solved...? I'll be closing this issue but if you have anything, please feel free to reopen it, or create another one! 🤝
