### ISSUE TITLE
How does this handle nested data/relationships when defining a model?

### ISSUE THREAD

**Issue by Alig96** [vuex-orm/vuex-orm#381]
Just came across this plugin and it seems awesome and just the thing I've been looking for.

Scanning briefly over the documentation I can see that I can define the fields & relationships of a model as:

```js
return {
      id: this.attr(null),
      user_id: this.attr(null),
      age: this.attr(''),
      sex: this.attr(''),
      user: this.belongsTo(User, 'user_id')
}
```

However, my server returns the data nested as follows:

```js
{
    "data": {
        "id": "...",
        "type": "post",
        "attributes": {
            "title": "...",
            "body": "..."
        },
        "relationships": {
            "user": {
                "id": "...",
                "type": "user",
                "attributes": {
                    "name": "TestUser"
                },
                "relationships": []
            }
        }
    }
}
```

How would I define the relationships for the model using this response since my server doesn't actually return the user_id field in the response but rather the entire user object? 

My current idea is to change my server response to actually return the foreign keys under the 'relationships' key, and move the actual returned model to new 'related' key like:

```js
{
    "data": {
        "id": "...",
        "type": "post",
        "attributes": {
            "title": "...",
            "body": "..."
        },
        "relationships": {
            "user_id": "..."
        },
        "related": {
            "user": {
                "id": "...",
                "type": "user",
                "attributes": {
                    "name": "TestUser"
                },
                "relationships": []
            }
        }
    }
}
```

If I implemented this change, could I then define the relationships as (using a dot notation) like below:

```js
user: this.belongsTo(User, 'relationships.user_id')
```

Or if I don't change the response, could I do it as:

```js
user: this.belongsTo(User, 'relationships.user.id')
```

**Comment by kiaking** [comment]
@Alig96 Hi! Thank you so much for the feedback! I'm sorry to tell but currently there're no way to map custom structure, so you can't insert data as is. There's an open issue #326 about this one and if we can implement that, then this becomes possible.

**Comment by mr-chick** [comment]
I have something similar in my app too, the server returns the models and their relations (other models).

My solution was to make a helper function to parse the API respose recursively and add relation keys if needed.

In your example, i would check if relationship is empty, if not, for each model, get the id and add it to the post object.

Then continue with inserting process.

**Comment by kiaking** [comment]
@Alig96 I'll be closing the issue because I think we can follow this feature at #326. Please feel free to reopen this if there's anything that is not covered by #326 and needs discussion.
