### ISSUE TITLE
[Feature Request] New Attribute for Primary Key, allowing for Expansive UID Options

### ISSUE THREAD

**Issue by geraldbiggs** [vuex-orm/vuex-orm#382]
Currently, the user will use this.increment() to populate IDs of new entries and let vuex-orm manage insertion of ids into relationships. 

```
class User extends Model {
  static fields () {
    return {
      id: this.increment(null),
      name: this.attr(null),
      posts: this.hasMany(Post, 'user_id')
    }
  }
}

class Post extends Model {
  static fields () {
    return {
      id: this.increment(null),
      user_id: this.attr(null),
      body: this.attr(null),
    }
  }
}

//insert
user: {
    name: "John",
    posts: [{ body: "John's post"}, { body: "Another post"}]
}
```

However, in some use cases - the end user may prefer a different strategy for generating their UIDs. Such cases may occur when using other endpoints than a SQL database or other special rules may apply.

Upon research into the source code - it appears that vuex-orm is tied to fields marked as Increment attribute type, when handling relationships. 

I propose adding an attribute Primary, to be used as the attribute for this purpose. It's default behavior would be auto-increment. Custom strategies could then potentially be loaded as plugins, when registering an instance of the database, or dropped in on the models themselves.

```
//per model - requires code duplication
class User extends Model {
  static fields () {
    return {
      id: this.primary(myFancyUidGenerator()),
      name: this.attr(null),
      posts: this.hasMany(Post, 'user_id')
    }
  }
}

//universal setting - would centralize UID behavior
const database = new VuexORM.Database({
   primaryStrategy: myFancyUidGenerator
})
```

At the most minimal and maybe easy to implement, this.primary() default behavior being increment, or uses the resulting string / integer from the UID generator per model. Whenever an ID is manually supplied upon create or insert - it prefers the submitted ID.

**Comment by kiaking** [comment]
@geraldbiggs Hi! Thank you so much for the feedback! Yeah, this is good idea and we should have this 👍

**Comment by kiaking** [comment]
@geraldbiggs This is now possible with Vuex ORM 0.34.0! Please read the docs about new UID attribute 👍 
https://vuex-orm.github.io/vuex-orm/guide/model/defining-models.html#uid-type
