### ISSUE TITLE
hasMany relationship causing empty entities states

### ISSUE THREAD

**Issue by emahuni** [vuex-orm/vuex-orm#385]
I have put the whole thing into this codesandbox https://codesandbox.io/s/vuex-orm-hasmany-test-ethv2.

I have specified all models and inserted data as expected by the documentation. Somehow the hasMany relationship in user model makes the entities states empty... {}

If I comment it out every works but without the relationship. Am I missing something or is the documentation missing something or it's a bug?

models: 
```js
// Post Model
import { Model } from "@vuex-orm/core";

export default class Post extends Model {
  static entity = "posts";

  static fields() {
    return {
      id: this.attr(null),
      user_id: this.attr(null),
      title: this.attr(""),
      body: this.attr(""),
      published: this.attr(false)
    };
  }
}
```
```js
// User model
import { Model } from "@vuex-orm/core";
import { Post } from "./Post";

export default class User extends Model {
  static entity = "users";

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(""),
      email: this.attr(""),
      posts: this.hasMany(Post, "user_id") // if I comment this everything works, but wout relationship
    };
  }
}
```
insertion:
```js
User.create({
      data: [
        {
          id: 1,
          name: "John Doe",
          email: "john@example.com",
          posts: [
            {
              id: 1,
              title: "Hello, world!",
              body: "Some awesome body..."
            },
            {
              id: 2,
              title: "Ok I see, world!",
              body: "Some nice body here, curvey even!"
            }
          ]
        }
      ]
    });
```
retrieve:
```js
User.query()
        .with("posts")
        .get();
```

**Comment by tvillaren** [comment]
Hello @emahuni,

I changed the `import { Post } from ...` into a `import Post from ...` statement and it seems to work fine. 
The code is there: https://codesandbox.io/embed/vuex-orm-hasmany-test-77whz

Don't hesitate to come to the [Slack Channel](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTI0YjE5YmNmMDIxNWZlNmJhM2EyMDg1MDRkODA4YmQwMDU5OWRkZmNhN2RmOTZkZGZkODQxZTRkYjhmYmJiNTY) if you have more questions!

**Comment by emahuni** [comment]
Cool man, just don't know why I was doing that
