### ISSUE TITLE
belongsToMany relationship array does not return null when Related Model is empty

### ISSUE THREAD

**Issue by havardthom** [vuex-orm/vuex-orm#386]
Hi, I'm having a problem with the `belongsToMany` relationship

#### Code example: https://codepen.io/anon/pen/KjKeJX

The console.log's in codepen highlights the problem.

### Actual Behavior
As you can see in the example, we have `Users` that belongs to many `Roles` through `RoleUser`. If I add a `User` and a `RoleUser`, then query `User` withAll relationships, I will get back a `User` with a `roles` array that contains one default `Role`, even though I have not added any roles to the store. It seems like it connects to a default `Role` object which does not exist in the store.

### Expected Behavior
I expect that the `roles` array should return `null` when no data exist in `Role` store, the same way as if there was no roles with matching id's.

**Comment by kiaking** [comment]
Hi! @havardthom. Thank you so much for the report! Well, thank you for finding this out. Yeah, it's wired, and it shouldn't return any roles in this case... Let me mark this as a defect and fix it!

**Comment by kiaking** [comment]
This issue has been fixed with Vuex ORM 0.31.13! 🔥 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.31.13

Thank you for the report! Please feel free to open another issue if there's anything!
