### ISSUE TITLE
How can I get access to Vue.filter from model?

### ISSUE THREAD

**Issue by mrFANRA** [vuex-orm/vuex-orm#393]
Hello.

Im not understand, how can I get access from model method to vue filters.

somethink like this:
```
someMethod()
{
   this.$options.filters.DoSomething(this.title)
}
```

**Comment by tvillaren** [comment]
Hello,

Vuex ORM Models are not instances of Vue Components so filters are not accessible through the `$options` object.
You can probably do something like this StackOverflow answer: https://stackoverflow.com/a/53067353

**Comment by kiaking** [comment]
@mrFANRA As @tvillaren said, Vuex ORM Model instance is not Vue Component instance so you don't have access to Vuex Filters. However, since Due Filters are just a function, you could share them like this perhaps?

```js
// Filter function `capitalize.js`.
export default function capitalize (value) {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

// Vue Registration.
import capitalize from './capitalize'

Vue.filter('capitalize', capitalize)

// Vuex ORM Model.
import { Model } from '@vuex-orm/core'
import capitalize from './capitalize'

export default class User extends Model {
  // ...
  
  capitalizedName () {
    return capitalize(this.name)
  }
}
```

**Comment by mrFANRA** [comment]
@kiaking @tvillaren Thank, Im using this way, but hoped ORM has Vue instance. 

PS Thanks for awesome Vuex-ORM!

**Comment by kiaking** [comment]
Thank you @mrFANRA! It could convenient to have Vuex Component instance access in Model, but technically it's really hard to do. I suppose you might already know but you could just pass `this` too ✋ 

```js
export default class User extends Model {
  // ...
  
  capitalizedName (vm) {
    return vm.$options.filters.capitalize(this.title)
  }
}

export default {
  methods: {
    capitalize () {
      return User.capitalizedName(this)
    }
  }
}
```

Anyway, thank you so much for your report! Feel free to open another issue if you have anything! 👍
