### ISSUE TITLE
Ability to have the entity name and related data member key different

### ISSUE THREAD

**Issue by miraclebg** [vuex-orm/vuex-orm#394]
I have a model and a one-to-one relationship to another model like the example below:

`
export default class Member extends Model {
    static entity = "members";

    static fields() {
        return {
            id: this.attr(null),
            username: this.string(""),
            email: this.string(""),
            url: this.string(""),
            isCoach: this.boolean(false),
            preferences: this.hasOne(MemberPreferences, "memberId")
        };
    }
}

export default class MemberPreferences extends Model {
    static entity = "memberPreferences";

    static fields() {
        return {
            memberId: this.attr(null),
            locale: this.string(""),
            measurementSystem: this.string("")
        };
    }
}
`

The issue i am facing is that the relationship does not work (upon inserting a new object for example) unless i name the 'preferences' key from 'Member' to 'memberPreferences' - as the entity name of the second object.

This works perfectly:

```
export default class Member extends Model {
    static entity = "members";

    static fields() {
        return {
            id: this.attr(null),
            username: this.string(""),
            email: this.string(""),
            url: this.string(""),
            isCoach: this.boolean(false),
            memberPreferences: this.hasOne(MemberPreferences, "memberId")
        };
    }
}

export default class MemberPreferences extends Model {
    static entity = "memberPreferences";

    static fields() {
        return {
            memberId: this.attr(null),
            locale: this.string(""),
            measurementSystem: this.string("")
        };
    }
}
```

Is this a requirement? I don't see it stated anywhere?

My understanding is that once we define the relationship - even if the data key name is different vuex-orm would figure it out?

Or am i getting it wrong?

**Comment by miraclebg** [comment]
Nevermind that! I've just figured it out :) I am not querying the data properly!

Another final comment - is there a way to fetch the object data - including all related ones (for example i have a model with several one-to-one relationships) - without asking for each relationship (with 'with')?

**Comment by tvillaren** [comment]
Hello @miraclebg,

You can use `withAll` or `withAllRecursive` (see https://vuex-orm.github.io/vuex-orm/guide/relationships/retrieving-relationships.html#load-all-relations).

Don't hesitate to join us on the [Slack Channel](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTI0YjE5YmNmMDIxNWZlNmJhM2EyMDg1MDRkODA4YmQwMDU5OWRkZmNhN2RmOTZkZGZkODQxZTRkYjhmYmJiNTY) if you have any questions!

**Comment by miraclebg** [comment]
Thank you so much! Adding it now!
