### ISSUE TITLE
Model.update overwrites id field

### ISSUE THREAD

**Issue by ITsolution-git** [vuex-orm/vuex-orm#398]
This is how I implemented the duplication logic of a model.

```js
const menu = await Menu.new()
this.menuId = menu.id

const originalMenu = Menu.query()
  .with('media')
  .find(idToCopy)
  .$toJson()

const newMenu = {
  ...originalMenu,
  created_at: null,
}

Menu.update({
  where: this.menuId,
  data: newMenu
})
```

Basically, when update is executed, it ignores `id` field of newMenu and update `{id: this.menuId} `with `newMenu` without `id`.
This used to work fine with v0.31.2. 

Today I just installed the dependency again(it's v0.31.13), and Model.update now updates `{id: newMenu.id}` with `newMenu` instead of updating `{id: menuId}`. As a result, `this.menuId` remains new object instead of copying `originalMenu`.

I had to rollback to original version but is this an issue or expected behavior?

**Comment by kiaking** [comment]
@ITsolution-git Hi! thank yo use much for the report!

Just to make sure, you updated from 0.31.2 to 0.31.13 right...? Not from 0.31.12 (just wanted to make sure if you missed 12 with 2 or not).

> Today I just installed the dependency again(it's v0.31.13), and Model.update now updates {id: newMenu.id} with newMenu instead of updating {id: menuId}. As a result, this.menuId remains new object instead of copying originalMenu.

I'm not 100% sure if I get your issue correct here... It sounds maybe like a defect...? Could you give me your expected input, and output?

**Comment by ITsolution-git** [comment]
Yes I updated from 0.31.2 to 0.31.13.

```
Menu.update({
  where: 2,
  data: {
     id: 4,
     name: 'brown'
  }
})```

Expected: Updated menus where id is 2 with { name: 'brown' }
New behavior after update: Updated menus where id is 4 with {name: 'brown' }

I am not sure if I described it right but please let me know if you are still confused. Thank you!.

**Comment by ITsolution-git** [comment]
@kiaking Do you have any updates on this please?

**Comment by kiaking** [comment]
@ITsolution-git Thank you for the confirmation. Well, that sounds very bad. I'll try to make a test case for that and reproduce!

**Comment by kiaking** [comment]
@ITsolution-git Hi! I've looked into this and find out that we do have test case for this and it's passing. The test is shown as below.

```js
it('updates index key when primary key gets updated', () => {
  class User extends Model {
    static entity = 'users'

    static fields () {
      return {
        id: this.attr(null),
        name: this.attr('')
      }
    }
  }

  createStore([{ model: User }])

  User.create({
    data: { id: 1, name: 'John Doe' }
  })

  User.update({
    where: 1,
    data: { id: 2 }
  })

  const user = User.find(2)

  expect(user.$id).toBe('2')
  expect(user.id).toBe(2)
})
```

Do you see any difference between your case and the test code?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to reopen it if there is anything! 🤝
