### ISSUE TITLE
plugin - extending Mutations

### ISSUE THREAD

**Issue by SzNagyMisu** [vuex-orm/vuex-orm#401]
Hi,

I'm using version `v0.32.0` and planning to write a small plugin.
In my plugin I would like to add mutations in the entities' namespaces, but I don't find how it is possible. In the first parameter of the `install` function I get access to the `RootActions`, `Actions`, `RootGetters`, `Getters` and `RootMutations` too, but, for some reason, `Mutations` is out of the functions scope.
Is this intentional (and if it is, why)?

What I want to do is to create a state `originalData` alongside with `data` for each entity (which is possible by overwriting the `Model.state`) and I need mutations to handle its content (like `entities/[entity_name]/createOriginal`, `entities/[entity_name]/insertOriginal` etc.)
All I can do now is extending `RootMutations` with mutations like `entity/createOriginal` etc. and pass the `entity_name` in the payload, which is a much less clean way of doing it.

Any ideas are welcome!

**Comment by tvillaren** [comment]
Hello @SzNagyMisu,

If you look at Vuex ORM source, you'll see that there is no `Mutation` class: all commits are handled through the RootMutation object with an `entity` payload (corresponding to the entity name to access the right state in the store). 

It is possible through the Actions though, and that's how it is implemented in Vuex ORM: when `distpatch`ing to an action specific to an entity (`store.dispatch('entities/users/create')` for instance), the action calls another "root action" with the right payload (i.e. the name of the entity) and the root action commits to the root mutation.
If you look at Vuex ORM documentation, you never commit anything to the store from the Vue components, you always go through the `dispatch` (action) or the static / instance implementation of those actions.

**Comment by SzNagyMisu** [comment]
Wow, I feel super idiot... I read the docs and the source code too, but somehow the absence of a `Mutations` class escaped me. Well, thanks for the quick reply and for pointing me in the direction of `Actions` and `RootActions`.
You helped  me a lot!
