### ISSUE TITLE
'where' with function argument ignores falsy result

### ISSUE THREAD

**Issue by bertBruynooghe** [vuex-orm/vuex-orm#402]
See below test that is failing: 
```
class Post extends VuexORM.Model {
  static fields () {
    return {
      id: this.attr(),
    }
  }
}

Post.entity = 'posts'

describe('VuexORM where', () => {
  beforeEach(() => {
    const database = new VuexORM.Database()

    database.register(Post, {})

    new Vuex.Store({ // eslint-disable-line no-new
      plugins: [VuexORM.install(database)],
      strict: true
    })
  })

  it('supports lambda expression returning falsy', async () => {
    const data = [{ id: 1 }]
    await Post.create({ data })
    const comments = Post.query().where(p => undefined).get()
    assert(comments.length === 0)
  })
})
```
https://repl.it/@bertbruynooghe/another-VuexORM-issue

**Comment by tvillaren** [comment]
Hello @bertBruynooghe, 

I think that is on purpose: it makes sense to be expecting strictly a boolean for a condition. 
You can always cast your falsy results using `!!` when writing your closure.

**Comment by bertBruynooghe** [comment]
That's a bit against the javascript spirit, AFAIK. But if that's the way it is, I'm going to put this in mu plugin...

**Comment by tvillaren** [comment]
Actually, digging into the code (https://github.com/vuex-orm/vuex-orm/blob/master/src/query/filters/WhereFilter.ts#L41) shows that it comes from the fact that closure are handled the same way whether they have one argument (the record) or 2 arguments (record and query). 

You can see more about this on the documentation, on the last example of the [where section](https://vuex-orm.github.io/vuex-orm/guide/data/retrieving.html#where-clauses):

```js
const user = User.query()
  .where('role', 'user')
  .where((_record, query) => {
    query.where('age', 20).orWhere('id', 1)
  })
  .get()
```

Here, the fact that we use nested queries makes the `(_record, query) => ...` closure return `undefined` which we don't want to handle as a falsy value in that case. 

Maybe this bit needs a bit of redesign / improvement. We're always open to ideas!

**Comment by kkyouhei** [comment]
Hi @tvillaren @bertBruynooghe 

I'm fix this problem but destructive change.
Where's closure must always return a value. 

I want to hear @tvillaren @bertBruynooghe opinion of this fix.

**Comment by bertBruynooghe** [comment]
I'm afraid I'm not sure what you want to do. Can you post some pseudo-code on how my above example would look with your change?

**Comment by kkyouhei** [comment]
@bertBruynooghe 

> Can you post some pseudo-code on how my above example would look with your change?

okay, record will not hit if where closure return undefined or null.
but where closure must return value.
I want to discuss this interface.

```
const user = User.query()
  .where('role', 'user')
  .where((_record, query) => {
    return query.where('age', 20).orWhere('id', 1)
  })
  .get()
```

sorry for my ugly english.

**Comment by bertBruynooghe** [comment]
As too the example @tvillaren gave, I guess it's okay.
One of the points of arrow functions is that it's more concise, so - if I am not mistaken - your example boils down to :

```
const user = User.query()
  .where('role', 'user')
  .where((_, query) => query.where('age', 20).orWhere('id', 1))
  .get()
```
(mind the brackets)

it looks elegant to me, but you have backwards compatibility issues.

What if you 'proxy' query in some way instead? If something has been called on proxy, ignore the `undefined`, otherwise consider the return value as falsifiable...

**Comment by kiaking** [comment]
Hi all. Thank you for the issue report and PR! I think always to return something (including query) is good. It7s breaking change, though I think we should go that path because:

1. Even we wrap query with observable (like Proxy), there could be a wired situation where the user set something to query, plus return some value. We can avoid this case if we force users to return something always.
2. Proxying stuff is more complicated, and might not add much value anyway.

However, I think if we were to do this, I think other similar API should also act the same way. I think those are `whereHas`, `whereHasNot`, and nested relationship constraints. All of them should return the query object as well.

Though, other than `where` clause, we might not need any implementation and could just update doc examples to return query.

The biggest problem is that this change **might break someone's app without them noticing**.  Maybe it's a necessity to change, but still, it's a dangerous one.

Do you guys any opinion in this?

**Comment by bertBruynooghe** [comment]
Mmm, I see you point, @kiaking.

OTOH, by simply checking the return type, you're doing strange stuff again: if somebody has to return something, one can expect something to happen with it. e.g.: What would happen if the api user returns a brand new query?

Also, the solution looks quite neat when using arrow functions, but not so using regular functions.

For me, the breaking change you're suggesting is replacing one awkward thing with another (maybe slightly less annoying), and so it does not justify the breaking change for me. I'd rather not solve this for now and adapt the documentation...

**Comment by kiaking** [comment]
> OTOH, by simply checking the return type, you're doing strange stuff again: if somebody has to return something, one can expect something to happen with it. e.g.: What would happen if the api user returns a brand new query?

Ah... Yeah, I wasn't thinking about that, and that is a good point.

> For me, the breaking change you're suggesting is replacing one awkward thing with another (maybe slightly less annoying), and so it does not justify the breaking change for me. I'd rather not solve this for now and adapt the documentation...

OK, now I feel that too. I'll keep this issue open for a few more days and see if we get any other feedback. If not, I'll add documentation and then close this issue.

**Comment by tvillaren** [comment]
Hello, 

Sorry I missed the discussion here but, in all, I also think adding this breaking change is not worth it here. 
In particular, I know the nested query (with closure) pattern is not that efficient (it basically browses the all data array as many time as there are closures) and even though I started using it, I tend know to create one function which returns a boolean to have a more efficient search.

**Comment by kiaking** [comment]
@tvillaren Thank you for the comment! OK, I think few days has passed, and seems like everybody is agreed on one thing. I'll add documentation about this issue and close this one. Thank you all for your feed back!

**Comment by kiaking** [comment]
I've just added the note in the doc about this issue. Thank you all so much for the help! 👍
