### ISSUE TITLE
Axios Plugin InsertOrUpdate after REST call fails

### ISSUE THREAD

**Issue by w4mike** [vuex-orm/vuex-orm#405]
Hi all,

I've been playing around now with the vuex-orm which went very well, next step was to use the Axios plugin together with the django + drf testserver.
The calls from my vue instances thru Axios seem well: when calling User.$fetch, I get a 'entities/auth/users/onRequest' promise, the 'entities/auth/users/onSuccess' and finally 'entities/auth/users/insertOrUpdate' in my browser's (Chromium/Firefox) Vue-Dev-Tools.

The data object of the 'insertOrUpdate' contains the correct JSON data from the server, but in the store's entities the data for e.g. 7 correct returned data sets is always incremented by 1 '_no_key_XX' with empty/False values.

Somehow I must be missing something.

Also I would like to have server side filtering, limiting and searching.
Is there a way to bypass the vuex-orm functions transparently to the Axios-plugin functions, so my server can do the work ?
Later I guess there will be thousands of datasets within each model, with a lot of relations.
I don't want the browser to load all the data and do the work client side.

Many thanks.
Mike

**Comment by w4mike** [comment]
Just saw I got a ReferenceError: 'User not found'.
But it's imported to store/index.js, here I do all the database stuff, import in main.js and go.

**Comment by kiaking** [comment]
@w4mike Hi! Thank you so much for the feedback! Hm... you get `_no_key_XX` when you pass in records without primary key. It's a bit hard to tell what is going on. Is it possible for you to create reproducible code?

**Comment by w4mike** [comment]
This is my Model:

`_import { Model } from '@vuex-orm/core'

import Site from './Site'
import UserSiteRelation from './UserSiteRelation'
import ObjectPermission from './ObjectPermission'
import UserObjectPermissionRelation from './UserObjectPermissionRelation'
import RoleUserRelation from './RoleUserRelation'
import Role from './Role'
import GroupUserRelation from './GroupUserRelation'
import Group from './Group'

export default class User extends Model {
  static entity = 'auth/users'

  static fields () {
    return {
      id: this.number(null),
      created_timestamp: this.attr(null),
      created_user: this.attr(null),
      modified_timestamp: this.attr(null),
      modified_user: this.attr(null),
      username: this.attr(''),
      is_active: this.boolean(false),
      is_staff: this.boolean(false),
      is_superuser: this.boolean(false),
      last_login: this.attr(null),
      date_joined: this.attr(null),
      sites: this.belongsToMany(Site, UserSiteRelation, 'user', 'site'),
      permissions: this.belongsToMany(ObjectPermission, UserObjectPermissionRelation, 'user', 'permission'),
      roles: this.belongsToMany(Role, RoleUserRelation, 'user', 'role'),
      groups: this.belongsToMany(Group, GroupUserRelation, 'user', 'group')
    }
  }

  static methodConf = {
    http: {
      url: this.entity
    },
    methods: {
      $fetch: {
        name: 'fetch',
        http: {
          url: '',
          method: 'get'
        }
      },
      $get: {
        name: 'get',
        http: {
          url: '/:id',
          method: 'get'
        }
      },
      $create: {
        name: 'create',
        http: {
          url: '',
          method: 'post'
        }
      },
      $update: {
        name: 'update',
        http: {
          url: '/:id',
          method: 'put'
        }
      },
      $delete: {
        name: 'delete',
        http: {
          url: '/:id',
          method: 'delete'
        }
      }
    }
  }
}_`

Module is not defined for now, just using the default one.

This is my index.js in store for vuex:

`_import Vue from 'vue'
import Vuex from 'vuex'
import VuexORM from '@vuex-orm/core'
import VuexORMAxios from '@vuex-orm/plugin-axios'
import VuexORMSearch from '@vuex-orm/plugin-search'
import VuexORMisDirtyPlugin from '@vuex-orm/plugin-change-flags'

import ContentType from '../models/db/base/auth/ContentType'
import Group from '../models/db/base/auth/Group'
import GroupObjectPermissionRelation from '../models/db/base/auth/GroupObjectPermissionRelation'
import GroupUserRelation from '../models/db/base/auth/GroupUserRelation'
import ModelPermission from '../models/db/base/auth/ModelPermission'
import ObjectPermission from '../models/db/base/auth/ObjectPermission'
import Role from '../models/db/base/auth/Role'
import RoleModelPermissionRelation from '../models/db/base/auth/RoleModelPermissionRelation'
import RoleUserRelation from '../models/db/base/auth/RoleUserRelation'
import Site from '../models/db/base/auth/Site'
import User from '../models/db/base/auth/User'
import UserObjectPermissionRelation from '../models/db/base/auth/UserObjectPermissionRelation'
import UserSiteRelation from '../models/db/base/auth/UserSiteRelation'

import AxiosRequestConfig from './AxiosRequestConfig'

Vue.use(Vuex)

const database = new VuexORM.Database()

database.register(ContentType)
database.register(Group)
database.register(GroupObjectPermissionRelation)
database.register(GroupUserRelation)
database.register(ModelPermission)
database.register(ObjectPermission)
database.register(Role)
database.register(RoleModelPermissionRelation)
database.register(RoleUserRelation)
database.register(Site)
database.register(User)
database.register(UserObjectPermissionRelation)
database.register(UserSiteRelation)

VuexORM.use(
  VuexORMAxios,
  {
    database,
    http: AxiosRequestConfig
  }
)

VuexORM.use(
  VuexORMSearch,
  {
    searchPrimaryKey: false,
    location: 0,
    distance: 100,
    threshold: 0.3,
    maxPatternLength: 32,
    caseSensitive: false,
    tokenSeparator: '/ +/g',
    findAllMatches: false,
    minMatchCharLength: 1,
    keys: 'Model.$fields()',
    shouldSort: false,
    tokenize: false,
    matchAllTokens: false,
    verbose: false
  }
)

VuexORM.use(VuexORMisDirtyPlugin)

/*
 * If not building with SSR mode, you can
 * directly export the Store instantiation
 */
export default function (/* { ssrContext } */) {
  const store = new Vuex.Store({
    namespaced: true,
    plugins: [VuexORM.install(database)],
    modules: {
      // example
    },

    // enable strict mode (adds overhead!)
    // for dev mode only
    strict: false // process.env.DEV
  })

  return store
}_`

Here is a (not nice) Users.vue file to just try to get the data shown:

`_<template>
  <q-page class="flex flex-center">
    <div class="q-pa-md">
      <q-tabs>
        <q-tab name="users-list" label="Users" left-icon="settings" align="left">
          <q-table :columns="columns" :data="users" row-key="id"/>
        </q-tab>
      </q-tabs>
    </div>
  </q-page>
</template>

<script>
import User from '../../../models/db/base/auth/User'

export default {
  data () {
    return {
      name: 'Users',
      columns: [
        {
          name: 'id',
          label: 'id',
          field: 'id',
          required: true,
          align: 'right',
          sortable: true
        },
        {
          name: 'created_timestamp',
          label: 'Created on',
          field: 'created_timestamp',
          required: true,
          align: 'right',
          sortable: true
        },
        {
          name: 'created_user',
          label: 'Created by',
          field: 'created_user',
          required: true,
          align: 'right',
          sortable: true
        },
        {
          name: 'modified_timestamp',
          label: 'Modified on',
          field: 'modified_timestamp',
          required: true,
          align: 'right',
          sortable: true
        },
        {
          name: 'modified_user',
          label: 'Modified by',
          field: 'modified_user',
          required: true,
          align: 'right',
          sortable: true
        },
        {
          name: 'username',
          label: 'Username',
          field: 'username',
          required: true,
          align: 'left',
          sortable: true
        },
        {
          name: 'is_active',
          label: 'Active',
          field: 'is_active',
          required: false,
          align: 'center',
          sortable: true
        },
        {
          name: 'is_staff',
          label: 'Staff',
          field: 'is_staff',
          required: false,
          align: 'center',
          sortable: true
        },
        {
          name: 'is_superuser',
          label: 'Superuser',
          field: 'is_superuser',
          required: false,
          align: 'center',
          sortable: true
        },
        {
          name: 'last_login',
          label: 'Last Login',
          field: 'last_login',
          required: true,
          align: 'right',
          sortable: true
        },
        {
          name: 'date_joined',
          label: 'Date Joined',
          field: 'date_joined',
          required: true,
          align: 'right',
          sortable: true
        }
      ],
      users_list: [ { 'id': 1, 'created_timestamp': '2019-06-18T15:26:43.975083Z', 'created_user': null, 'modified_timestamp': '2019-06-18T15:26:44.094793Z', 'modified_user': null, 'username': 'mike.waldeyer@videlco.eu', 'is_active': true, 'is_staff': true, 'is_superuser': false, 'last_login': null, 'date_joined': '2019-06-18T15:26:43.975130Z' } ],
      computed: {
        users: () => User.all()
      }
    }
  },
  computed: {
    users: () => User.all()
  },
  created () {
    User.$fetch()
  }
}
</script>

<style scoped>

</style>_`


**users_list works, when using users computed, not. Anyway created get's called, the promise is generated and the result can be seen in this screenshot, but the data is not updated correctly:**

![Bildschirmfoto_2019-07-23_21-30-34](https://user-images.githubusercontent.com/51969156/61741457-3efad580-ad91-11e9-8ca0-734fe47dfded.png)

![Bildschirmfoto_2019-07-23_21-31-15](https://user-images.githubusercontent.com/51969156/61741469-4621e380-ad91-11e9-92d5-9d69a1179bfc.png)

**Comment by kiaking** [comment]
@w4mike Maybe this is because your server response is returning following structure?

```js
{
  count: 7,
  next: null,
  previous: null,
  results: [...]
}
```

And maybe you7re passing the whole response instead of `results` key. Could you try returning `results` only from the server and see what happens?

**Comment by w4mike** [comment]
@kiaking Many thanks for the hint, yes of course this was the server side pagination. I assumed this was created client side ...
Without this it works.
Would it be possible to tell the axios plugin to use this pagination scheme ?

How would I fetch only a subset of data from the server ? In some tables I will have thousands of rows.

**Comment by kiaking** [comment]
@w4mike I don' think you can pass it right now... Currently, we're planning to rewrite Axios plugin quite a bit. Sorry for the inconvenience but it would be great if you can separately call API request for now.

**Comment by w4mike** [comment]
@kiaking many thanks for your response. OK, will use API requests for now.

**Comment by kiaking** [comment]
@w4mike Thanks for your understanding! 🤝  I hope we can make Axis work soon.
