### ISSUE TITLE
How to get Id after insert?

### ISSUE THREAD

**Issue by Uysim** [vuex-orm/vuex-orm#409]
if i have model
```jsx
class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.increment(),
      name: this.attr('')
    }
  }
}
```
Then i insert 
```jsx
User.insert(data: { name: "unknown id" })
``` 
How can i get user id that I inserted?

**Comment by kiaking** [comment]
@Uysim Hi! The Insert method will return all entities created by the method. So you can access the newly created records like this.

```js
const entities = await User.insert(data: { name: "unknown id" })

entities.users[0] // <- Created user
```

Here is the documentation for this. 👍 
https://vuex-orm.github.io/vuex-orm/guide/data/inserting-and-updating.html#inserts

**Comment by Uysim** [comment]
@kaiking thank you
