### ISSUE TITLE
hasManyThrough returns [undefined] when empty

### ISSUE THREAD

**Issue by ldiebold** [vuex-orm/vuex-orm#410]
Hey!

Was just doing a tutorial video on hasManyThrough and may have found a bug.

If the target model is empty, the result is an array with undefined in it:

![image](https://user-images.githubusercontent.com/1305724/61995120-50145100-b0c7-11e9-9fc4-9a5184c5a16b.png)

The relation works fine if the target model isn't empty.

Here's a codesandbox that hits the error:
https://codesandbox.io/embed/vue-template-j9ghk

**Comment by kiaking** [comment]
@ldiebold Hi! Thank you so much for the report! We need to look into this. It could be a bug I think.

**Comment by kiaking** [comment]
I've made a fix at #421. Will make a new release very soon!

**Comment by kiaking** [comment]
The issue has been fixed by Vuex ORM 0.32.2! 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.32.2
