### ISSUE TITLE
Relationship reactivity issue

### ISSUE THREAD

**Issue by nmihaica** [vuex-orm/vuex-orm#411]
I seem to have trouble with nested relationship reactivity.

```
...mapGetters({
  items: 'entities/item/all',
  itemsWithUnits: 'entities/item/query'
}),
```
I am displaying items in bulma table. However when I use nested relationship reactivity stops. Insert or updates are running correctly because when inspected, the state changes, however I cannot seem to have a getter which will include reactive relationship. When I have no relationships fetched inside table the reactivity is fine.
```
<!-- when run via 
:data="items()"
without nested relationship, reactivity is fine-->

<b-table :data="itemsWithUnits().with('unit').get()">
</b-table>
```
I am doing something wrong. Can anybody help?

**Comment by tvillaren** [comment]
Hello @nmihaica,

Not sure if it comes from the syntax your using or your model.
What happens if you create a computed which does the same?

```js
computed: {
    itemsWithUnits() {
        return this.$store.getters['entities/item/query']().with('unit').get()
    }
}
```

**Comment by nmihaica** [comment]
Did as you said.
```
:data="itemsWithUnits()"
```
Got following error:
![Screenshot from 2019-07-31 17-42-23](https://user-images.githubusercontent.com/12017390/62226491-97962800-b3ba-11e9-8840-257990e5eaa2.png)

Dropped the parentheses`()`, changed it to 
```data="itemsWithUnits"```

Items are located fine, but reactivity still not there. Same problem.

**Comment by tvillaren** [comment]
Yes, computed are not methods so you do not need the parentheses. 

When you say "reactivity" is not here, you mean when adding / removing a `unit` or also with the `item` entity? Do you have a bit more code (on a JSFiddle for instance) to dig into?

**Comment by nmihaica** [comment]
I mean reactivity of object, whole entity. If I change for example other attributes, none of them are reactive. When component is mounted again it *refreshes* as I `Item.$fetch()` on mount. I have other relationships in my schema, and I've looked at it, I've solved in kind of a hacky way. 

I purposely did not over elaborate problem as then potential reader/help would get discouraged and did not want to introduce more code than needed.

Here is potential solution from my other model, for example,
```javascript
import { Model } from '@vuex-orm/core'
import compositionItem from '$models/compositionItem'

export default class Composition extends Model {
  static entity = 'composition'

  static fields () {
    return {
      id: this.attr(null),
      spaceId: this.attr(null),
      name: this.attr(null),
      description: this.attr(null),
      compositionItems: this.attr('null'),
      //compositionItems: this.hasMany(compositionItem, 'composition_id'),
      createdAt: this.attr(''),
      updatedAt: this.attr(''),
    }
  }
```

As you see with the line that is commented out, I did not *connect* it via vuex-orm relationship. While it seems hacky it is actually more natural this way, as `compositionItem` cannot is bound to `composition` and is never used outside of that context. So it is natural that when `Composition.$fetch()`, the backend response will include `compositionItem` inside. Also, I will never update on it's own so there is no need even for vuex-orm to containt `compositionItem` object. 

Now, it worked for that model, but as you can notice, `Unit` model is combined with other models so naturally I want to have it's entity and connection naturally. When I do that I cannot find a way to show reactivity while updating entity.

**Comment by tvillaren** [comment]
I understand the issue here is :
> If I change for example other attributes, none of them are reactive

How do you change those attributes? Do you use the Vuex-ORM `update` method?

**Comment by nmihaica** [comment]
Mind the croatian language here is working example how I managed to solve it.
With the following model:

```javascript
static fields() {
 return {
  id: this.attr(null),
  spaceId: this.attr(null),
  code: this.attr(null),
  name: this.attr(''),
  description: this.attr(''),
  unit: this.belongsTo(Unit, 'unitId'),
  unitId: this.attr(''),
  createdAt: this.attr(''),
  updatedAt: this.attr(''),
 }
}
```

# Example 1 (working)

```javascript
data() {
 return {
  dataItems: Item.query().with('unit').get(),
 }
}
```
![dataItems](https://user-images.githubusercontent.com/12017390/62297397-747a7f80-b471-11e9-9d01-21e255471b4a.gif)

# Example 2 (NOT working)

```javascript
computed: {
 getterItems(){
    return Item.query().with('unit').get() 
 }
 getterItems2() {
  this.$store.getters["entities/item/query"]()
   .with("unit")
   .get();
 },
}

```

![getterItems](https://user-images.githubusercontent.com/12017390/62297403-76444300-b471-11e9-893b-ef0fe024ee58.gif)

**Comment by kiaking** [comment]
This is wired. The computed property pattern is the way to go, and you have set it up correctly. I never had this issue. In fact, we have a [example app](https://github.com/vuex-orm/vuex-orm-examples) that does all update on both entity and its relation.

Is it possible for you to create a minimum reproduction code for the issue? Or maybe it's got to do something when you update the model.

**Comment by nmihaica** [comment]
I will close it for now as you provided example app where I can look into implementation. Thanks.

**Comment by Tofandel** [comment]
I can confirm there is an issue, any relationship queried with `with()` will not be reactive, the current workaround is to use a second query on the related model and do the link manually.. This is less than ideal

Eg:
```
computed: {
 items(){
    return Item.query().get();
 }
},
methods: {
  itemUnit(item) {
    return Unit.query().where('item_id', item.id).first();
  }
}
```

**Comment by cuebit** [comment]
@Tofandel could you provide a minimal reproduction on [codesandbox.io](https://codesandbox.io) or alike?

**Comment by Tofandel** [comment]
Sure do you have a premade template with vuex orm?

**Comment by cuebit** [comment]
@Tofandel [here's one](url) of many. Might need to update dependencies.

**Comment by cuebit** [comment]
@Tofandel [here's one](https://codesandbox.io/s/vuex-orm-pxdu4) of many. Might need to update dependencies.

**Comment by Tofandel** [comment]
There you go
https://codesandbox.io/s/angry-sara-glxc7?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.vue

**Comment by Tofandel** [comment]
Never mind, my issue was way deeper after some debug, I had a component mounted programmatically with an assigned slot and this apparently made it non reactive because when the parent update a new VNode is created but the assigned slot keeps the old reference
