### ISSUE TITLE
[Documentation] records should always be created with a primary key

### ISSUE THREAD

**Issue by SzNagyMisu** [vuex-orm/vuex-orm#417]
I didn't know that.
It's logical, though.

I tried to insert new records without a primary key and have them assigned after the backend generated the values, but had all kinds of headaches because the **primary key** and the **index** were not the same.

```javascript
{
  _no_key_1: {
    id: null,
    name: 'John'
  }
}
```

Then I found this [piece of advice](https://github.com/vuex-orm/vuex-orm/issues/78#issuecomment-366424803) in #78 from @kiaking.
I think it has a place in the documentation.

**Comment by kiaking** [comment]
Thank you for the feedback! Oh yes, we should have documented this.

And maybe in the future, we could have the option to make this kind of records invalid at insertion time.

**Comment by SzNagyMisu** [comment]
I can implement this if you like.

I would add a subtitle to `guide/model/defining-models#primary-key` and place a note at the end of `guide/data/inserting-and-updating#default-values`

Also, this means that `Model.new()` should only be used when primary key is of type `increment`, is that correct? If so, that should be mentioned too.

**Comment by kiaking** [comment]
@SzNagyMisu 

> I can implement this if you like.

That would be awesome!


> Also, this means that Model.new() should only be used when primary key is of type increment, is that correct? If so, that should be mentioned too.

I would say setting id field to `increment` is "recommended", instead of "should" because you can create a record of id `null`. This might not be the desired behavior in many cases, but maybe someone will find benefit with it.

So maybe we should also mention about this `_no_key_X` behavior as well.

**Comment by kiaking** [comment]
And it's done! Thank you so much @SzNagyMisu for the wonderful PR! 🎉
