### ISSUE TITLE
[works as designed] override model primaryKey does not reflect in entity data object

### ISSUE THREAD

**Issue by snaphuman** [vuex-orm/vuex-orm#420]
Hello, 

I'have defined a Student model with a custom primaryKey as follows:

```
export default class Student extends Model {
    static entity  = 'students';
    static primayKey = 'publicKey';
    static fields () {
        return {
            publicKey: this.attr(null),
            secretKey: this.attr(''),
            name: this.attr(''),
            lastname: this.attr(''),
            email: this.attr(''),
            course: this.attr(''),
            isCandidate: this.attr(false),
            votedAt: this.number(0)
        };
    };
};
```
As a result, the data object does not reflect the provided value for the custom primaryKey, and instead of it shows _no_key_1. Note that the object also aggregates an `id` property with null value that was not defined in the model.

```
{
  "$connection": "entities",
  "$name": "students",
  "data": {
    "_no_key_1": {
      "$id": "_no_key_1",
      "id": null,
      "publicKey": "ak_2JbMSYzHaryq4v144qkfhb1M7hVBLqUC5KxxKTGZUBdB2hsKq1",
      "secretKey": "e8d30f278890e0fd6eac4dc197d3135d2e27af1da646654c8c8bc0ebd891f87aaba43b120a5321a10b1de626527e3e1977a97b2d8005a9a7efdbdf459854941e",
      "name": "testname",
      "lastname": "testlastname",
      "email": "testemauk",
      "course": "testcourse",
      "isCandidate": false,
      "votedAt": 0
    }
  }
}
```
Do i'm missing something in the model definition?

Thanks in advance.

**Comment by tvillaren** [comment]
Hello @snaphuman, what code do you use to insert data into your store?

**Comment by snaphuman** [comment]
Hi @tvillaren, I have a save() method in the Student component that gets the data from the reactive variables `student: {}`, `candidateData: {}` and `keypair: {}`.

```
save() {
    Object.assign(this.student, this.keypair);
    try {
        Student.insert({ data: this.student });
            if (this.student.isCandidate)
                Candidate.insert({
                    data: this.candidateData});
             this.flash('Student Saved', 'success');
        } catch (err) {
            this.flash('Something went wrong', 'error');
            console.log(err);
        }
    }
}
```
In vuex-orm documentation it states that: 

> to create a new data, you can use insert, create , and new method. They all insert new records to the Vuex Store but behaves in a slightly different manner.

I have tried to save the data into the store with insert, create and new methods but the result is the same.

Greetings

**Comment by petertoth** [comment]
Hey @snaphuman . I have already raised this issue in the [slack channel](https://vuex-orm.slack.com/archives/CA0AXG66L/p1564496124042600) and it appears it will take some legwork to get this fixed. cc @kiaking 

There's a related issue already opened here https://github.com/vuex-orm/vuex-orm/issues/382

In your particular case, you might have the extra `id` field because you have a typo in your model definition:
`static primayKey = 'publicKey';`

**Comment by snaphuman** [comment]
Hi @petertoth.
Thank you for pointing me out the typo. That resolved my issue. The custom primaryKey of my entities are now reflecting as object id.```

{
  "$connection": "entities",
  "$name": "students",
  "data": {
    "ak_qUzJtFwPicm7bgQicaLfqgfoQKTs6kDYqSJay2XU8w6gmusUF": {
      "$id": "ak_qUzJtFwPicm7bgQicaLfqgfoQKTs6kDYqSJay2XU8w6gmusUF",
      "publicKey": "ak_qUzJtFwPicm7bgQicaLfqgfoQKTs6kDYqSJay2XU8w6gmusUF",
      "secretKey": "81fb8e06927a0bc041958cd6df4817397840a649db3d401c2db11cceac1c7ac76e15e7c2bbdddf4222659294e699f95f8c3ce07b42f624fb2574a852f1d32eb4",
      "name": "sdfsdfgsdfg",
      "lastname": "segsdg ",
      "email": "sdfgsdgd",
      "course": "10A",
      "isCandidate": false,
      "votedAt": 0
    },
    "ak_23hS2qCeMB4bcxMeKxqhve3y2JYrrdn7H6uiwX8yxamQH4ULZf": {
      "$id": "ak_23hS2qCeMB4bcxMeKxqhve3y2JYrrdn7H6uiwX8yxamQH4ULZf",
      "publicKey": "ak_23hS2qCeMB4bcxMeKxqhve3y2JYrrdn7H6uiwX8yxamQH4ULZf",
      "secretKey": "b32cddb12a2ee2fefee80ca141af2feb922f72c18bfee5acf80c69d39ffa385789d1f77519a92b5cd253f1e5a1c2a543f7bd5a4d451162777f1c17f79215c19d",
      "name": "fgfblmlkm",
      "lastname": "lkmlkmv ",
      "email": "sdfglkmm ",
      "course": "10A",
      "isCandidate": true,
      "votedAt": 0
    }
  }
}
```

I should look better before posting this issue.  :sweat:
