### ISSUE TITLE
Vue library with vuex-orm models 

### ISSUE THREAD

**Issue by Botz** [vuex-orm/vuex-orm#423]
Hi,

i am writing a vue library for an internal project, we are using vuex-orm. Now i want to outsource a model class from the project into the library. If i register this model from the library i get the following error:

![Bildschirmfoto 2019-08-19 um 10 11 57](https://user-images.githubusercontent.com/2706678/63249496-dc023e80-c269-11e9-9b49-89853aa96e5d.png)

The `Container.database` is undefined. Do you have any solution for this?

**Comment by Botz** [comment]
One possible solution would be to pass the database to the Schema.create and Schema.constructor function. I will provide a PR, then you can have a look at this.

**Comment by Botz** [comment]
My PR only fixed the new Schema problem.

I solved the whole problem by removing the vuex-orm dependency from my lib package.json dependency and declare @vuex-orm/core as [external](https://webpack.js.org/configuration/externals/)

But maybe we can find a better solution?

**Comment by kiaking** [comment]
#423
Hi! Thank you so much for the feedback and PR!

I'm not quite sure if I understand the issue 100%. Could you provide some simple code that shows where you're registering models from the library?

**Comment by kiaking** [comment]
@Botz Just checking in. Could you take a look at my comment above?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything! 🤝
