### ISSUE TITLE
Question: Can vuex-pathify be made to work with vuex-orm?

### ISSUE THREAD

**Issue by JasonLandbridge** [vuex-orm/vuex-orm#427]

**Comment by kiaking** [comment]
@JasonLandbridge Hi! Thank you for the feedback!

I think it would be hard since Vuex ORM needs its own API to do all of the normalizations of data, I don't think we can directly integrate with vuex-pathify.

Could you elaborate more on what you mean by "work with Vuex ORM"?

**Comment by JasonLandbridge** [comment]
Thanks for responding, well let's say we have a getter 

`// getters
const getters = {
  resumeData: (state: any) => (id: number) =>    Resume.query().whereId(id).withAll().first()
};`

and then with vuex-pathify:

`get('resumeData', this.id)`

As I have understood it the order is:

Vuex-orm -> Vuex store -> Vuex Pathify

Should this be working?


Overall I am very happy with vuex-orm and makes mangaing complex objects alot easier, using pathify would be the cherry on top for me. :D

**Comment by kiaking** [comment]
@JasonLandbridge Ah, I see. Thank you for the clarification.

I've never used vuex-pathify myself, but looking at your example code, I think it should work since it is just hitting plain getter. I would love to see you to try it!

**Comment by kiaking** [comment]
Closing the issue for now. Please feel free to reopen it if there is anything! 🤝
