### ISSUE TITLE
Dispatch from model not working

### ISSUE THREAD

**Issue by cdrandin** [vuex-orm/vuex-orm#428]
I get the following error [vuex] unknown action type: entities/posts/setNext.

I check the store._mutations and it does in fact exist. I also can call it with `store.commit("entities/posts/setNext", "jkahsdjaksd");` and it works.

which leads me to believe that `Post.dispatch` isn't working or I set up my vuex module incorrectly.

```javascript
// model/Post.js

export const postVuex = {
    state: {
        next: null,
        previous: null,
    },
    mutations: {
        setNext(state, next) {
            state.next = next;
        },
        setPrevious(state, previous) {
            state.previous = previous;
        },
    },
    getters: {
        next: (state) => state.next,
        previous: (state) => state.previous,
    },
};

export default class Post extends Model {
    static entity = "posts";

    static fields() {
        return {
            id: this.attr(null),
            user_id: this.attr(null),
            content: this.attr(""),
            images: this.attr([]),
            view_count: this.attr(0),
            created: this.attr(""),
            is_private: this.attr(false),
            created_by: this.belongsTo(User, "user_id"),
            comment_count: this.attr(0),
        };
    }
}

// database/index.js

database.register(Post, postVuex);

```

Also, is there a better way to get state from a model than having to do `post.$store().state.entities.posts.next`. I understand getters are a thing, but it feels like a pain to include it for every property in my state.

And it feels like doing 

```javascript
getters: {
        $state: (state) => state,
    }
```

Just feels like I am going through obstacles. 

Maybe something like `$state` similar to how `$store` is available through the model?

Edit:

I just realized something confusing in the documentation.
[call-module-methods-fom-model](https://vuex-orm.github.io/vuex-orm/guide/digging-deeper/vuex-module.html#call-module-methods-fom-model).

dispatch is for calling actions in vuex. 

IN the docs 

```
An alternative to calling store methods directly, you may access the store instance from a model as well to dispatch actions or call getters.

const user = User.dispatch('add', 3)
The above code is exactly same as below.

store.dispatch('entities/users/add', 3)
```

It is trying to call an action, but according to the docs (above it), it is a mutation.

**Comment by kiaking** [comment]
Hi! Thank you for the report!

> I get the following error [vuex] unknown action type: entities/posts/setNext.

It seems like your trying to `dispatch` instead of `commit`? You must have `setNext` *action* at module, but you only have `setNext` *mutation*. Maybe this could be the reason?


> Also, is there a better way to get state from a model than having to do post.$store().state.entities.posts.next.

Yeah I would like to have that as well. Just have to come up with good name because `state` is taken at Model definition and we can't use it. Maybe `$state` is good! But `static state` is taken it is going to be incosistent through out other model method names.

> It is trying to call an action, but according to the docs (above it), it is a mutation.

Not sure what you mean. It is calling action, and I believe docs don't mention anything about mutations isn't it?

**Comment by cdrandin** [comment]
You are right on that. I just misunderstood the docs. The Call Module Methods fom Model part of the docs mentions `const user = User.dispatch('add', 3)` and I assumed `add` was trying to call the mutation, but it is in fact the action.

It was just the previous Vuex module was

```javascript
const users = {
  state: {
    count: 0
  },

  mutations: {
    add (state, count) {
      state.count = state.count + count
    }
  }
}
```

which didn't have an action so I didn't immediately think of it. So may bad on that.

**Comment by kiaking** [comment]
Thank you for the confirmation! I'm glad you found a way out.

Please let us know if you have anything else! 👍
