### ISSUE TITLE
Recursive Relation Query

### ISSUE THREAD

**Issue by zzachattack2** [vuex-orm/vuex-orm#436]
Is there a way to query specific relationships recursively? _withAllRecursive_ works okay, but its not always desirable to load ALL relationships like this. Use case might be a self-referential one-to-many relationship, with a "children" relation field, where you want to pull the parent/child tree.

**Comment by kiaking** [comment]
@zzachattack2 Thank you for the feedback! Currently there are no ways to do this. It could be nice feature addition though 👍  I'll mark this one as enhancement issue.

**Comment by Kinvaras** [comment]
Hi ! 

I was facing a similar situation today and found something interesting to do exactly what you are looking for.

Consider the following models:

- Item
- Category

such as an **Item** _belongs to_ a **Category** (and thus a **Category** _has many_ **Items**).

Furthermore, a **Category** has a self-referential relationship (a **Category** _belongs to_ another parent **Category** and _has many_ child **Categories**).

The following example uses Typescript:

```typescript
// Component.vue
import { Item } from "@/models"; // Item is a vuex-orm model

const recursiveLoadParent = (query: Query): void => {
  query.with("parent", recursiveLoadParent);
};

@Component
export default class extends mixins(SomeUsefulMixin) {
  // [...]

  // This is a Vue computed property
  get items(): Item[] {
    return this.Item
      .query()
      .with("category", (query) => {
        query.with("parent", recursiveLoadParent);
      })
      .get();
  }

  // [...]
}
```

Please note the use of a recursive function **recursiveLoadParent**. 
I've had a hard time working on avoiding an infinite recursion before I eventually realize it didn't !

Maybe @kiaking could confirm it is an intended solution ?

I'm interested in getting your feedback !

Thx

**Comment by unknown1337** [comment]
> Hi !
> 
> I was facing a similar situation today and found something interesting to do exactly what you are looking for.
> 
> Consider the following models:
> 
> * Item
> * Category
> 
> such as an **Item** _belongs to_ a **Category** (and thus a **Category** _has many_ **Items**).
> 
> Furthermore, a **Category** has a self-referential relationship (a **Category** _belongs to_ another parent **Category** and _has many_ child **Categories**).
> 
> The following example uses Typescript:
> 
> ```ts
> // Component.vue
> import { Item } from "@/models"; // Item is a vuex-orm model
> 
> const recursiveLoadParent = (query: Query): void => {
>   query.with("parent", recursiveLoadParent);
> };
> 
> @Component
> export default class extends mixins(SomeUsefulMixin) {
>   // [...]
> 
>   // This is a Vue computed property
>   get items(): Item[] {
>     return this.Item
>       .query()
>       .with("category", (query) => {
>         query.with("parent", recursiveLoadParent);
>       })
>       .get();
>   }
> 
>   // [...]
> }
> ```
> 
> Please note the use of a recursive function **recursiveLoadParent**. I've had a hard time working on avoiding an infinite recursion before I eventually realize it didn't !
> 
> Maybe @kiaking could confirm it is an intended solution ?
> 
> I'm interested in getting your feedback !
> 
> Thx

wow, this helped a lot!!
