### ISSUE TITLE
incorrect field initialization 

### ISSUE THREAD

**Issue by drkwolf** [vuex-orm/vuex-orm#438]
Hi,
I've a model with field defined like this

`items: this.attr([])`

if items is not present in  some record feed to dispatch/create's data  `model.items.push('item')` will be the same on all records where items was not set

here is a demo
https://codesandbox.io/s/vue-template-8i23d

**Comment by kiaking** [comment]
@drkwolf Hi! thank you so much for the report! Wow this is strange behavior... Looks very much like defect. Need to look into it.

**Comment by cuebit** [comment]
This issue has been resolved since [v0.34](https://github.com/vuex-orm/vuex-orm/releases/tag/v0.34.0)
