### ISSUE TITLE
Feature/Question - this.boolean support casting user defined "false" values

### ISSUE THREAD

**Issue by tripflex** [vuex-orm/vuex-orm#449]
**update:** I just realized i completely forgot about the second arg being the mutator -- which i'll just use my own fn to convert "false" values, but i'll leave this open for now to see your thoughts on it .. if not, please feel free to close it.

First let me say, I understand that standards for almost any framework for **Boolean** would not consider `"false"` (string) to be `false` ... but maybe we could possible add an argument that can be set when calling `this.boolean` that can define additional values to be considered false?

Maybe like:
`this.boolean( false, [ "false", "no" ] )`

Reason I ask is this framework is great for type casting values, but in some situations there may be a need to consider (string) `false` or (string) `no` to be a boolean value.

In my situation, when values are saved to the database, they are all casted to strings (can't change that), so when the data is pulled from the server, a (boolean) `false` actually gets returned as (string) `false`

I resolved most of these by having to switch everything to use `1` or `0` ... but what are your thoughts about the ability to define `false` considered values?  I think this would be a great addition to the type casting handling to help with reducing the amount of code required to **cast** one value to another

**Comment by tvillaren** [comment]
I think that for the sake of consistency, the best way to answer your problem is the solution you found: using "default value mutators" for specific cases such as yours (as anybody could want different default behavior). 
I believe that is the reason we implemented this default mutator method: to give developper the ability to implement their own rule !
