### ISSUE TITLE
4 questions on setup

### ISSUE THREAD

**Issue by rconstantine** [vuex-orm/vuex-orm#456]
I've been using Vuex in my application and am adding something new which could really use this ORM. I'm hoping to just slot this next to the existing modules. My code for the store setup is below with code for a base and extended model below that. My questions are these:

1) Can I simply add the database along side like I'm doing?
2) Calendar, Event and Time are extended from Trigger. Should I be registering them like I am below? Or do I only register the parent? Or what?
3) Same question for Exec and EMail which extend Action.
4) Registering/importing them (3 & 4 above) doesn't seem to work. And if I try to export them, I get different errors about proper inheritance. How do we register extended models?

```javascript
import Vue from 'vue'
import Vuex from 'vuex'
import VuexORM from '@vuex-orm/core'
import Task from './database-taskSchedule/task'
import RegInfo from './database-taskSchedule/regInfo'
import Settings from './database-taskSchedule/settings'
import Principal from './database-taskSchedule/principal'
import Action from './database-taskSchedule/action'
import Exec from './database-taskSchedule/actionExec' // error
import EMail from './database-taskSchedule/actionEmail' // error
import Trigger from './database-taskSchedule/trigger'
import Calendar from './database-taskSchedule/triggerCalendar' // error
import Event from './database-taskSchedule/triggerEvent' // error
import Time from './database-taskSchedule/triggerTime' // error

import reports from './module-reports'
import pharmAssist from './module-pharmAssist'
import users from './module-users'
import account from './module-account'
import usage from './module-usage'
import manageSchedule from './module-manageSchedule'

Vue.use(Vuex)

// Create new instance of Database.
const database = new VuexORM.Database()

// Register Models.
database.register(Task)
database.register(RegInfo)
database.register(Settings)
database.register(Principal)
database.register(Action)
database.register(Exec) // error
database.register(EMail) // error
database.register(Trigger)
database.register(Calendar) // error
database.register(Event) // error
database.register(Time) // error

/**
 *
 * @type {Store}
 */
const store = new Vuex.Store({
  modules: {
    reports,
    pharmAssist,
    users,
    account,
    usage,
    manageSchedule
  },
  plugins: [VuexORM.install(database)]
})



export default store

```

Trigger Model
```javascript
import { Model } from '@vuex-orm/core'

export default class Trigger extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'trigger'

  // List of all fields (schema) of the post model. `this.attr` is used
  // for the generic field type. The argument is the default value.
  static fields () {
    return {
      id: this.increment(),
      task_id: this.attr(null),
      type: this.string(''),
      enabled: this.boolean('')
    }
  }
}
```

Calendar Model
```javascript
import Trigger from './trigger'

// Derived entity. You should extend the base entity.
class Calendar extends Trigger {
  static entity = 'calendar'

  // Reference to base entity name.
  static baseEntity = 'trigger'

  // Call `super.fields()`` to merge fields.
  static fields () {
    return {
      ...super.fields(),
      randomDelay: this.string(''),
      startBoundary: this.string(''),
      scheduleByDay: this.attr({ daysInterval: '' }),
      scheduleByWeek: this.attr({ days: [], weeksInterval: '' })
    }
  }
}
```

**Comment by kiaking** [comment]
@rconstantine Hi! Thanks for the feed back.

> 1. Can I simply add the database along side like I'm doing?

Yes! You can.

> 2. Calendar, Event and Time are extended from Trigger. Should I be registering them like I am below? Or do I only register the parent? Or what?

You should register everything, as you do.

> Registering/importing them (3 & 4 above) doesn't seem to work. And if I try to export them, I get different errors about proper inheritance. How do we register extended models?

I think you're missing out [Discriminator Field
](https://vuex-orm.github.io/vuex-orm/guide/model/single-table-inheritance.html#discriminator-field) setup. Could you take a look at it? Also, you need be careful about [Circular Imports
](https://vuex-orm.github.io/vuex-orm/guide/model/single-table-inheritance.html#notes-on-circular-imports) as well.

**Comment by rconstantine** [comment]
I did read both the Discriminator Field and Circular Imports, but I will re-read them and try to figure out what I'm missing. I may have further questions if I can't get it working.

**Comment by rconstantine** [comment]
Managed to get the errors to go away. Now I have to make sure I can use it all. Thanks.

**Comment by kiaking** [comment]
@rconstantine Great to hear it worked! Please let us know if you have any further questions 👍

**Comment by kiaking** [comment]
I'll be closing the issue since I think there are no further questions. Please open another issue if there's anything! 👍
