### ISSUE TITLE
Type of whereHas constraint argument (as given in vuex-orm examples) is not assignable to type parameter of type 'Constraint'

### ISSUE THREAD

**Issue by Emily-RoseSteyn** [vuex-orm/vuex-orm#458]
## Expected Behavior
When using the `whereHas` method on a model query, the constraint parameter should not expect a return value such that the following code can run in a Typescript environment without causing any warnings or errors.

`Post.query().whereHas('comments', (query) => {
  query.where('user_id', 1)
}).get()`

## Current Behavior
When running vuex-orm in a Typescript environment, the `whereHas` method expects the constraint parameter to be of type `Options.HasConstraint` which maps to the type: `Constraint = (query: Query) => boolean`. However, according to the documentation, the constraint parameter in `whereHas` is used to append a where clause to the query and thus the constraint parameter would have no return type. This means that a typing error is displayed when using the `whereHas` method in a Typescript environment. Note that this does not prevent the application from running. 

Example in CodeSandbox: 

![Example in CodeSandbox](https://user-images.githubusercontent.com/20258546/65592659-4c019400-df8f-11e9-8059-088209e3108c.png)

## Possible Solution
The easiest solution would be to adjust the typing of **Constraint** to something like:
`export declare type Constraint = (query: Query) => boolean | void;`
(found in HasConstraint.ts)

## Steps to Reproduce
[Reproduction Link](https://codesandbox.io/s/vuex-orm-wherehas-bug-z2fnz)
* Open pages/index.vue

_Note: It seems that the linting error does not always appear in CodeSanbox and as mentioned previously, it does not prevent the application from running_

## Context (Environment)
* Using the `whereHas` method in a Nuxt Typescript project in order to filter a set of records by a constraint on a relation

**Comment by kiaking** [comment]
@Emily-RoseSteyn Thank you so much for the report! Uhhh this is bad one. Need to fix.

**Comment by Emily-RoseSteyn** [comment]
@kiaking My pleasure! Just a bit snowed under at the moment, but if the fix hasn't been implemented by early November, I will have time to make a pull request then or otherwise maybe contribute a bit to the project.

**Comment by kiaking** [comment]
@Emily-RoseSteyn Thank you so much. Uhh I would like to fix but... if not, I'm counting on you :p

**Comment by kiaking** [comment]
This issue is now fixed at Vuex ORM 0.34.0! 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.34.0
