### ISSUE TITLE
Slack: This invite link is no longer active.

### ISSUE THREAD

**Issue by kosirm** [vuex-orm/vuex-orm#464]
Just wanted to report this...

**Comment by kiaking** [comment]
What!? Thanks! I've updated the link. Very strange, that link should never be expired but when I checked the Slack, the URL was slightly different : (

Anyway, could you check if it's fixed?

**Comment by kosirm** [comment]
Thanks @kiaking ! I just checked link on documentation page and I can confirm that I'm now officialy part of vuex-orm community on slack :)

**Comment by kiaking** [comment]
Great! See you at Slack 🚀
