### ISSUE TITLE
withCredentials and DELETE request

### ISSUE THREAD

**Issue by Tarasovych** [vuex-orm/vuex-orm#467]
Does DELETE request supports `withCredentials`?

My `store/index.js` looks like
```js
VuexORM.use(VuexORMAxios, {
  database,
  http: {
    baseURL: '...',
    url: '/',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    withCredentials: true
  }
})
```
, but there are no attached cookies (with auth token inside) while sending DELETE reqeusts.

My current usage is:
```js
deleteSomeRecord(id) {
  Entity.$delete({
    params: {
      id: id
    }
  })
```

**Comment by kiaking** [comment]
Ah, this is Axios plugin right? Sorry but please be patient. The new Axios plugin in on the way...!
