### ISSUE TITLE
How to order by position on Pivot table

### ISSUE THREAD

**Issue by cizza** [vuex-orm/vuex-orm#469]
Hello, 

Thank you for the fantastic plugin!!

How do you order by an attribute, which is in a pivot table of a Many-to-Many relationship?

I thought this would do, but it doesn't seem to pick up on the position in the pivot:

```
Layout.query().where('isInLayoutTree', true).with('components', (query) => {
      query.orderBy('position')
}).first()
```

The position is in the ComponentLayout pivot table and I'm trying to order the 'components'. 

Any advice would be appreciated.

Thank you.

**Comment by kiaking** [comment]
@cizza Hi! Thank you so much for trying out Vuex ORM!

Unfortunately, there's no way to access pivot table data from a related entity, which in this case `components`. There is an issue about this, and we're planning to add that support.

For now, you could fetch `ComponentLayout` with nested `components` to achieve this. It needs to have 1 level deep nesting, and querying is going to be a bit dirty though...

**Comment by cizza** [comment]
Hi kiaking, 

thank you for your reply.  I'm glad I know now that it's not possible at the moment. I've resolved the ordering in a different way, but it would be a really nice functionality to have. I think you've mentioned you are using Laravel on projects and the Eloquent ORM has got this baked it. It's a really useful functionality. 

Let me thank you one more time for creating Vuex-ORM, I find it the best addition to the Vue.js ecosystem ever. I wish I knew about it a year ago.

**Comment by kiaking** [comment]
@cizza Ah, OK! Great hear you found a way out. There is an issue to resolve this one, so I'll be closing this issue and let the other issue do the tracking.

> Let me thank you one more time for creating Vuex-ORM, I find it the best addition to the Vue.js ecosystem ever. I wish I knew about it a year ago.

Thank you so much! Those words are what makes us keep moving! Please feel free to open other issues if there's anything! 🤝
