### ISSUE TITLE
Load nested relation

### ISSUE THREAD

**Issue by paparent** [vuex-orm/vuex-orm#47]
Hi,

I'd like to know how to load multiple nested relation.

```
_getters['entities/project/query']()
    .with('activity.period')
    .with('activity.activityType') // <--
    .all(),
```

What's the syntax ?

Thanks !!

**Comment by kiaking** [comment]
Aha, in such case you need to use closure.

```js
_getters['entities/project/query']()
    .with('activity', (query) => {
        query.with('period').with('activityType')
    })
    .all(),
```

Probably I should add this to the doc.

**Comment by paparent** [comment]
Thanks a lot ! It works 👍

**Comment by kiaking** [comment]
Glad I could help!

**Comment by paparent** [comment]
@kiaking  Hi ! 

I have similar issue like this one. Instead of a belongsTo relation, it's hasMany ! 

So, I can do: 

```
_getters['entities/activities/query']()
    .with('projects.owner')
    .all(),
```

But this doesn't work:

```
_getters['entities/activities/query']()
    .with('projects', (query) => {
      query.with('owner').with('projectType')
    })
    .all(),
```

Is it possible ? :)

**Comment by kiaking** [comment]
Hm... That's strange. Can you give the model schema so I can look into it more?

**Comment by kiaking** [comment]
@paparent I'll close this issue due to inactivity. Please feel free to reopen it if you still having trouble! Thanks.
