### ISSUE TITLE
find vs query

### ISSUE THREAD

**Issue by mr-chick** [vuex-orm/vuex-orm#476]
Greetings.

I have an user model

```
export default class User extends Model {
 [...]
  static fields () {
    return {
      'id': this.attr(null),
      'first_name': this.attr(null),
      'last_name': this.attr(null),
      [...]
    }
  }

  get fullName () {
    return `${this.first_name} ${this.last_name}`
  }
```

If I use the query, it returns a User instance.
`user = $vm0.$store.getters['entities/users/query']('id', '123').first()`
`user.fullName` is Jon doe

If I use the find method it returns an object
`let user = $vm0.$store.getters['entities/users/find']('123')`
`user.fullName` is undefined, since fullName is not present in the object.

Am I doing something wrong?

**Comment by kiaking** [comment]
@mr-chick Uhh... this is bad. But not sure why this is happening... I need to look into it

**Comment by mr-chick** [comment]
OK, let me know if you need more info from me

**Comment by marafee1243** [comment]
`fullName` is a function, need to call `user.fullName()`
I tried on my local, it works fine.

**Comment by marafee1243** [comment]
works fine with version `0.34.1`. May I know, what version were you using?

**Comment by kiaking** [comment]
@mr-chick Do you have any updates on this? Perhaps v0.34.1 might have fixed?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything! 🤝
