### ISSUE TITLE
hasOne not update relation

### ISSUE THREAD

**Issue by alexandrmiee** [vuex-orm/vuex-orm#477]
I have 2 models with hasOne relations
```js
export default class Session extends Model {
  static entity = "quiz/sessions";

  static fields() {
    return {
      id: this.increment(),
      isActive: this.boolean(false),
      event: this.hasOne(Event,"session_id"),
      room: this.hasOne(Room,"session_id"),
    };
  }
}
```

```js
export default class Event extends Model {
  static entity = "events";

  static fields() {
    return {
      id: this.number(0),
      name: this.string(0),
      user_id: this.number(0),
      start_at: this.string(0),
      finish_at: this.string(0),
      request_room_number: this.boolean(0),
      session_id: this.number(),
    };
  }
}
```
Event creates from Vuex ORM Axios plugin. Then I create Session

```js
Session.create({
     data:{
       event: Eventt.find(event.id),
       room: Room.find(room.id),
    }
  });
```

But session.event is null
![image](https://user-images.githubusercontent.com/8451506/67358739-00c8aa00-f56a-11e9-99a6-3b497aff15aa.png)
![image](https://user-images.githubusercontent.com/8451506/67358761-1047f300-f56a-11e9-85f5-e512f9a29566.png)

**Comment by kiaking** [comment]
@alexandrmiee I assume you're dumping whole store state. Then this is expected behavior! You must use `with` query to retrieve relationships.

```js
Session.query().with('event').get()
```

Then, you'll the `event` key is filled with its related Event records.

**Comment by alexandrmiee** [comment]
Thanks!
