### ISSUE TITLE
Feature request: add support for dynamic database registration

### ISSUE THREAD

**Issue by kamwing** [vuex-orm/vuex-orm#478]
Dear vuex-orm team,

First of all, Thank you for developing this  amazing plugin!

And I'm requesting that to register a database after the VuexORM.Database has been created.

feature like vuex **Dynamic Module Registration**
https://vuex.vuejs.org/guide/modules.html#dynamic-module-registration

I would appreciate any comments on this feature consideration.

Many thanks.

**Comment by kiaking** [comment]
Hi! Thank you for the feed back! Yeah this would be nice to have.

Let me mark this as an enhancement issue and see if we can work on.

**Comment by SzNagyMisu** [comment]
Is this related to #187?

**Comment by kiaking** [comment]
Oh yeah indeed. Let's close this one and continue discussion over there.
