### ISSUE TITLE
Support for composite primary keys

### ISSUE THREAD

**Issue by sigmoidbigfoot** [vuex-orm/vuex-orm#48]
For some datasets, the primary key may not be a single field, but a composite of multiple fields.

For example, in SQL you might define a table with a composite primary key like
```sql
CREATE TABLE `voting` (
  `QuestionID` int(10) unsigned NOT NULL,
  `MemberId` int(10) unsigned NOT NULL,
  `vote` int(10) unsigned NOT NULL,
  PRIMARY KEY  (`QuestionID`, `MemberId`)
);
```

It would be nice if vuex-orm supported composite primary keys so existing datasets with these keys don't need to be altered to include a single field primary key.

**Comment by kiaking** [comment]
Good point! This won't be hard to implement so I'll work on to it. I'm thinking to enable `primaryKey` to accept array of key.

```js
class Voting extends Model {
  static primaryKey = ['QuestionID', 'MemberId']

  static fields () {
    return {
      QuestionID: this.attr(null),
      MemberId: this.attr(null),
      vote: this.attr(0)
    }
  }
}
```

**Comment by kiaking** [comment]
This feature was added by PR #52. It will go into next release!

**Comment by sigmoidbigfoot** [comment]
Thanks for the quick turn around on this!

**Comment by kiaking** [comment]
@sigmoidbigfoot No problem! Hope it works for your needs!

This is now possible with Vuex ORM 0.16.0 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.16.0
