### ISSUE TITLE
Model.prototype.$save() does not save relations

### ISSUE THREAD

**Issue by SzNagyMisu** [vuex-orm/vuex-orm#482]
I guess this is because of

```js
if (fields[key] instanceof Attributes.Type)
```

L757 in

https://github.com/vuex-orm/vuex-orm/blob/c7009b9f3931a925eb6e614ddacce71e9f4eb505/src/model/Model.ts#L753-L769

Is it intentional? If so, is there any way to `$save()` a record with its relations?

Thanks in advance!

**Comment by kiaking** [comment]
@SzNagyMisu Yes, this is intentional. `$save` method will not save any relationships.

The easiest way is to just pass whole models into pure `insertOrUpdate` function.

```js
const user = User.query().with('posts').first()

User.insertOrUpdate({ data: user })
```

**Comment by SzNagyMisu** [comment]
Ok, I see. Thanks!
