### ISSUE TITLE
Custom id not set when inserting data

### ISSUE THREAD

**Issue by petertoth** [vuex-orm/vuex-orm#485]
Hi,

When I define a model with custom uuid id attribute like this:

```js
class User extends Model {
  static fields() {
    return {
      id: this.attr(() => uuid())
      name: this.attr(''),
      email: this.attr('')
    }
  }
}
```
And then insert new data into the store:

```js
User.insertOrUpdate({
  data: {
    name: "John Doe",
    email: "email@example.com"
  }
}).then(result => {
  const idOnInsert = result.users[0].id
  console.log('result', result)

  /* 
  users: Array[1]
    0: User
    $id: "_no_key_1"
    id: "ab2ac650-00d6-11ea-b6ef-f116801352a9"
    name: "John Doe"
    email: "email@example.com"
  */

  console.log(`User with id: ${idOnInsert}`, User.find(idOnInsert))
  /*
  User with id: ab2ac650-00d6-11ea-b6ef-f116801352a9 
  null
  */
})
```

The custom id attribute(uuid in this case) is simply not set.

As you can see the `$id` attribute on the `User` is `"_no_key_1"` after the user is inserted. However, the `id` attribute is correct and that is the generated uuid.

Right now, I work around this issue by instantiating the model first `data = new User(user)` and then inserting into the store `User.insertOrUpdate({ data })`.
This is rather inconvenient for example when loading data from the API with the axios plugin.

Here's the repro sandbox: https://codesandbox.io/s/vuex-orm-uuid-bug-wmmjc

Thanks a lot for looking into this!

**Comment by kiaking** [comment]
Oh yeah, this is true. This is happening because the callback within `this.attr` is called after the $id is set. We should be fixing this.

**Comment by cuebit** [comment]
@kiaking this is resolved with `id: this.uid(() => uuid())`?

**Comment by kiaking** [comment]
@cuebit In fact yes, that should work! Id will be generated when instantiating the model so both $id and id should have the same value when using `this.uid()` 👍

@petertoth Canyon check the above method and see if everything works correctly?

**Comment by cuebit** [comment]
@kiaking Looking at some closed issues I believe `uid` attribute was designed with this in mind. I have tested this and works perfectly. 

Would be keen to get @petertoth’a feedback before closing.

**Comment by petertoth** [comment]
Yes I can confirm it works as expected now. Thanks for looking into it!

**Comment by kiaking** [comment]
Niiiice 👍
