### ISSUE TITLE
Add method to check model existence

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#486]
Add `exists` method on Model and Query to check if the record exists in the store.

```js
// Check if there's at least 1 record in the store.
User.exists()

// Check if there's at least 1 user with the name of 'John' in the store.
User.query().where('name', 'John').exists()
```

**Comment by kiaking** [comment]
This feature is now added to Vuex ORM 0.36.0 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.36.0

**Comment by canhkieu** [comment]
How to use it in nuxt with: this.$store.dispatch
