### ISSUE TITLE
findIn with relation not work

### ISSUE THREAD

**Issue by mean-cj** [vuex-orm/vuex-orm#488]
Hello

the findIn() method relation is not work
`User.query().with('photos').findIn([1,2,3,4])`
photos result is null

```
export default class User extends Model {
  static fields = () => {
    return {
      id: this.attr(null),
      photos: this.hasMany(Photo, 'user_id'),
     }
  }
}
```

if i use find() method relation is ok
`User.query().with('photos').find(1)`
photos result is photo lists

Thank you.

**Comment by mean-cj** [comment]
can be use whereIdIn() 
`User.query().with('photos').whereIdIn([1,2,3,4]).get()`

**Comment by lukaslaskovski** [comment]
This thread should have been re-opened because in fact `findIn` is also not returning a relationship for me and using `whereIdIn` is currently impossible because it does not support composite keys (#459).
