### ISSUE TITLE
One To Many - Define without explicit parent keys?

### ISSUE THREAD

**Issue by donovanhare** [vuex-orm/vuex-orm#489]
I have been running into issues trying to get this package to work in conjunction with the [axios plugin](https://vuex-orm.github.io/plugin-axios/). 

The docs aren't entirely clear when it comes to what is required when you have one-to-many relationships - so I have a couple of questions...

Is vuex-orm (or axios plugin) able to normalise nested JSON without explicitly defined parent keys? e.g. 
```json
{
  "id": 1,
  "name": "Category",
  "articles": [
    {
      "id": 1,
      "name": "Article Name",
      "comments": [
        {"id": 1, "content": "Comment"}
      ]
    }  
  ]
  
}
```
Is it expecting the data I am providing to have the relationship id(s) present already? i.e. Category --> Article (which contains category_id) or is vuex-orm able to map the id as the Article it is nested within the Category?

How would I go about defining these relationships?

**Comment by mcastagnetti** [comment]
I'm not sure to understand the full problem (and i'm not a maintainer) but I'll try to respond :) 

In the docs it says `Additionally, Vuex ORM assumes that the foreign key should have a value matching the id (or the custom static primaryKey) field of the parent.` So all you have to define is the foreign key name in the `hasMany` definition, and the field name `category_id` in your child Model.

Also, in the [Inserting and updating](https://vuex-orm.github.io/vuex-orm/guide/data/inserting-and-updating.html#generating-missing-foreign-keys) section, it says that `If data is missing its foreign keys, Vuex ORM will automatically generate them during the inserting process` so it doesn't matter whether your article contains the `category_id` value as long as you define the relationship correctly.

So my guess is, you should define your relationship like so : 

```js
// Category.js
export default class Category extends Model {
  static fields () {
    id: this.increment(),
    name: this.string(''),
    articles: this.hasMany(Article, 'category_id')
  }
}

// Article.js
export default class Article extends Model {
  static fields () {
    id: this.increment(),
    name: this.string(''),
    category_id: this.attr(null) // Or whatever type you need
  }
}
```

When using `Category.insert(data)`, all relationships should be mapped correctly

**Comment by donovanhare** [comment]
Thanks for clearing that up for me!
