### ISSUE TITLE
$id field not converted to string in pivot table for many to many relationship

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#493]
Reproduction: https://codesandbox.io/s/vuex-orm-sample-application-r7fxh

`threadUsers` entity have `$id` value of array, not string. Hence when fetching them, it throws error telling invalid JSON format.

**Comment by moravecjakub** [comment]
Hello,
  any progress for this issue?

Some fix, like this, can help in Query.prototype.$fill method:
`if (hydrated.$id instanceof Array) {
    hydrated = {...hydrated, $id: '[' + hydrated.$id.toString() + ']'};
}`

**Comment by moravecjakub** [comment]
@kiaking When I upgrade to 0.34.1 version it works, I can see that $fill method was refactored.
So, can this issue be closed?

**Comment by kiaking** [comment]
Thanks for the confirmation! Yap, seems like this is fixed 👍
