### ISSUE TITLE
Support defining field types.

### ISSUE THREAD

**Issue by Fnxxxxo** [vuex-orm/vuex-orm#494]
When use the lib the typescript vuex. The type of query result last types of Field interface. Any idea to support generic field types?

```js
...
computed: {
  currentChat(): any {
    // const data: Item<ChatModel> = ChatModel.find(11)
    // return data
    return ChatModel.query().with('messages').with('target').find(11)
  },
  printMessages(): any {
    // Error: messages not defined.
    return this.currentChat
      ? this.currentChat.messages
      : []
  }
},
...
```

**Comment by kiaking** [comment]
Not sure what you mean by "last type"...? Wouldn't that query typed as ChatModel instance...? Can I see the model definition of ChatModel as well?

**Comment by Fnxxxxo** [comment]
Sorry for the late. Here the definition:
```
export class ChatModel extends Model {
  static entity = 'chats'

  static fields() {
    return {
      id: this.attr(null),
      type: this.string(null),
      name: this.string(null),
      channel: this.string(null),
      updateTime: this.attr(new Date()),
      unread: this.number(0),
      target_id: this.attr(null),
      target: this.belongsTo(UserModel, 'target_id'),
      messages: this.hasMany(MessageModel, 'chatId'),
      status: this.attr(ChatStatusEnum.Offline)
    }
  }
}

export const ChatStore = {
  actions: {}
}

export default function initialize(database: Database) {
  if (database) {
    database.register(ChatModel, ChatStore)
  }
}
```
The "last type", I means, is that the type of the query is same as the type of the last chaining model.
In my case, the type is MessageModel when chaining using ```with('messages')``` not ChatModel, which is weird

**Comment by Fnxxxxo** [comment]
Finally find the solution. I get fields type using ```Item<InstanceOf<EditorModel>>```

**Comment by Fnxxxxo** [comment]
@kiaking still find it wired to explicit declare type for each query result, like
```
// Use const context directly raise a type error: 
// TS2339: Property 'userId' does not exist on type 'ChatContextModel'.
const context: Item<InstanceOf<ChatContextModel>> = ChatContextModel.query().where('login').first()
console.log(context.userId)
```
Any way to simply it? Can each query infer its return type?

**Comment by lukaslaskovski** [comment]
If you want to use it together with TypeScript you have to do a small hack which consists in additional definition of field types.

```
public static fields () {
  return {
    id: this.number (0),
    name: this.string (''),
    productsIds: this.attr([]),
  }
}

public id !: number;
public name !: string;
public productsIds: number [];
```
Then you can go like:

```
const context: ChatContextModel = ChatContextModel.query().where('login').first();
```

It is not beautiful but works temporarily until ORM starts to support TypeScript :)

**Comment by cuebit** [comment]
@lukaslaskovski what Typescript support are you looking for

**Comment by lukaslaskovski** [comment]
@cuebit  Excuse me. Actually, it will be rather an ESlint / TSlint problem that does not see the definition of the fields and throws errors like:
`Property 'name' does not exist on type 'ProductModel'.`

**Comment by cuebit** [comment]
@Fnxxxxo @lukaslaskovski I accidentally closed this issue mid comment. Sorry for the confusion.

It's often best practice to create your own type-guards that a third-party library is otherwise unaware of. Models are suspect to this especially as they are populated during runtime but nothing an interface won't resolve.

**Comment by Fnxxxxo** [comment]
@lukaslaskovski I use eslint. 
@cuebit So you meas something like
```
interface ModelInterface {
  propA: string;
}
class MyModel extends Model implements ModelInterface {
  // ...
}
function isMyModel(instance: any): instance is ModelInterface {
  // How to check if isntance is MyModel ?
}
```

**Comment by bestickley** [comment]
I found this package helpful for using VuexORM with TS: https://github.com/scotley/vuex-orm-decorators#readme

**Comment by Fnxxxxo** [comment]
@bestickley Great solution! Hope this type system to be supported by the official, @kiaking

**Comment by cuebit** [comment]
Decorators will be shipped with the next iteration of vuex-orm, see the [vuex-orm-next](https://github.com/vuex-orm/vuex-orm-next) repo for more details. 

Closing this since it’s not an issue per-se. If you have any further questions, feel free to join the slack channel, or open a new issue. 👍

**Comment by thopiddock** [comment]
Just thought I'd drop my wee discovery to shortcut this by defining a `<Model>Def` `@typedef` annotation in the model file.

I'm sure there should be a way to type declare this in `.d.ts` files somewhere or even add it to the original Model declaration somehow but this is my work around to get a quick and dirty Intellisense prompt for the Models.

```js
// src/models/post.js

// Definition to pass for intellisense
/** @typedef {ReturnType<Post.fields> & Model} PostDef */ 

export default class Post extends Model { 
  static entity = "posts";
 
  static fields() {
    return {
      id: this.attr(null),

      /** @description The post title */
      title: this.string(null),
      /** @description The post content */
      content: this.string(null)
    };
  }
}
```

You can now ref this in your components:
```vue
<script>
/**@typedef {import('src/models/post').PostDef} PostDef */  // Create Shorthand
import Post from "src/models/post";

export default {
  name: "Post",
  props: {
    postId: { type: Number, required: true }
  },
  computed: {
    /** @returns {PostDef}  */ // Reference Shorthand
    post() {
      return Post.find(this.postId);
    },
    
    /** @returns {String}  */
    uppercaseTitle() {
      return `${this.post.name}`.toUpperCase(); // This should now work with vetur auto-complete/intellisense
    }
  }
}
</script>

<template>
  <v-card  
    class="post-card"
  >
    <!-- These post refs should work with intellisense now -->
    <h1 :id="post.id">{{ post.title }}</h1>
    <p>{{ post.content }}</p>
  </v-card>
</template>
```

![image](https://user-images.githubusercontent.com/1750619/129350973-1c7228c6-e862-42c4-bbd1-322e4e1b0443.png)

  Notice that although this works - you'll still need to annotate *all* your computeds with return types or Vetur will struggle with the experimental template interpolation.
  
  Hope this helps!
