### ISSUE TITLE
$id attribute and $delete action 

### ISSUE THREAD

**Issue by phiny1** [vuex-orm/vuex-orm#495]
- When object is created, Vuex ORM set $id attribute with primaryKey definition (Single or Array) or id attribute as default. 
- When id is null, Vuex ORM create your own key using NoKey class.

**ProcessStrategy.ts**
```
static create (model: typeof Model): Strategy {
    return (value: any, _parentValue: any, _key: string): Record => {
      const id = model.getIndexIdFromRecord(value)

      return { ...value, $id: id === null ? NoKey.increment() : id }
    }
  }
```

- When I call model.$delete() from object that has _no_key_id , the function doesnt work because try to find de object by primaryKey... and primaryKey is null, only $id has the object identification. This occur with primaryKey as ID or compose primaryKey.

```
async $delete (): Promise<Item<this>> {
    const primaryKey = this.$primaryKey()

    if (!Array.isArray(primaryKey)) {
      return this.$dispatch('delete', this[primaryKey])
    }

    return this.$dispatch('delete', (model: this): boolean => {
      return primaryKey.every(id => model[id] === this[id])
    })
  }
```

Why dont use $id to delete?

```
async $delete (): Promise<Item<this>> {
    return this.$dispatch('delete', this.$id)
  }
```

**Comment by kiaking** [comment]
@phiny1 I think this should work with latest Vuex ORM 0.34.0 now. Since now Vuex ORM will generate any missing primary key fields. Could you try it out?

But even if it works, I think this code can be refactored to adopt to new architecture. I think I'll do that too.

**Comment by phiny1** [comment]
Thank you for the update, it worked with 0.34.0.

Uid attribute accept number and string, but awalys return as string? The related attribute has to be string?

**User.js**
`id: this.uid()`

**Post.js**
`userId: this.string("")`

**Comment by kiaking** [comment]
@phiny1 The default UID will be string. But UID could be a number too. For example, if you have your own UID implementation, it could be a number.

If you're using the default UID behavior, then yes your `userId` at Post should be `this.string("")`! It could be `this.string(null).nullable()` too. Because maybe there's a chance where Post doesn't have author yet 😃

**Comment by phiny1** [comment]
Thank you very much.

**Comment by bikeshaman** [comment]
I have a quick clarifying question you can maybe answer — I'm updating to 0.34.1, and notice that `src/schema/NoKey.ts` is now gone. Is it intended/expected that `$id: null` will now be present on all my records as the return value of `record.$toJson()`?

Previously:
```json
{
  "id": "card_foobar",
  "type": "CREDIT",
  "isDefault": true,
  "brand": "VISA",
  "lastFour": "1234",
  "expiryMonth": 6,
  "expiryYear": 2066
}
```
Now:
```json
{
  "$id": null,
  "id": "card_foobar",
  "type": "CREDIT",
  "isDefault": true,
  "brand": "VISA",
  "lastFour": "1234",
  "expiryMonth": 6,
  "expiryYear": 2066
}
```

**Comment by kiaking** [comment]
@bikeshaman On no it shouldn't I think. Thanks for the report!
