### ISSUE TITLE
Question about morph with Laravel

### ISSUE THREAD

**Issue by bpuig** [vuex-orm/vuex-orm#499]
Hello, 
I've got one question, in morphs, vuexORM takes `entity` to use it as value for `exampleable_type` relationship, but for example, in Laravel, `exampleable_type` is stored in database as `App\exampleable_type`.
How can I solve this? Any ideas?

**Comment by kiaking** [comment]
Oh yeah this is the hard one... You must first convert the API request to have `entity` as a value.

I'm planning to add these kinds of structure mapping functionality, though I don't think I can do it anytime really soon...

**Comment by bpuig** [comment]
Always happens the same to me, seems that the solution is in the docs :sweat:  : https://laravel.com/docs/6.x/eloquent-relationships#custom-polymorphic-types , I'll try when I have time and get my results back

**Comment by mr-chick** [comment]
I had the same problem, morphMap solved it.
```
Relation::morphMap([
     'ActivityLog' => \App\API\ActivityLog::class,
     'Article' => \App\API\Article::class,
     'Company' => \App\API\Company::class,
]);
