### ISSUE TITLE
how can I write a query that returns entities that match multiple many-to-many relationships?

### ISSUE THREAD

**Issue by vesper8** [vuex-orm/vuex-orm#507]
I seriously tried to write something that worked for over an hour and had to give up

I have a model "Item" and a model "Attribute" and I have a pivot model "ItemAttribute" and there is a many-to-many relationship between Item and Attribute

Example of items:

Apple
Brick
Computer

Example of attributes:

Round
Edible
Hard
Electric

Attributes can belong to many items, and items can have many attributes

How do I write a query that will return items that have attributes both 'round' and 'edible' ?

For my attributes model, I made the primary key 'slug' and those are unique

Seems simple but I couldn't get it to work

using

```
      const query = Item.query().withAll();
      
      const attributes = ['round', 'edible'];

        query.whereHas('attributes', (subQuery) => {
          subQuery.whereIdIn(attributes);
        });

      this.items = query.get();
```

This will returns all items that have either 'round' or 'edible' as attributes.. but it will include items that have only 'round' or only 'edible'. I want a query that will return items that have ALL attributes.. in this case that are both 'round' AND 'edible'

I'm using whereIdIn based on the slug being the primary key, but I tried other variations as well using a simple where. I tried subqueries.. it's very easy to return items that match ONE attribute but so far it's impossible to return items that match ALL attributes.

Would love some help here.. I'm totally suck

Thank you

**Comment by kiaking** [comment]
@vesper8 Hi! Sorry for my late response. Maybe you could use ordinary where clause?

```js
query.whereHas('attributes', (subQuery) => {
  subQuery.where('slug', attributes);
});
```

**Comment by vesper8** [comment]
@kiaking I appreciate the reply but your suggestion does not apply to my inquiry... that is.. I want a query that will return parent models that contain multiple children

as in my examples above, I want a query that will return items that contain both relationships that are "round" and "edible"

An apple is an item that has a many-to-many relation to attributes "round" and "edible"

How can I write this specific query that will return all items who contain both specified attributes? This doesn't seem to be possible currently, I have already tried many syntaxes with no solution found

**Comment by kiaking** [comment]
Ah OK, maybe you've tried but if you want relationship filtering, then you should be using `with`.

```js
query.with('items', (subQuery) => {
  subQuery.where('slug', attributes);
});
```

Maybe I'm not getting your question here... sorry. Could you provide me simple model definition, existing data, and the result you would like to get?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything! 🤝
