### ISSUE TITLE
Single record

### ISSUE THREAD

**Issue by renatovaler** [vuex-orm/vuex-orm#508]
Is it possible to create a "model" that has a single record without a "primary key"?

**Comment by kiaking** [comment]
@renatovaler Model must have primary key. Because models are stored in the store by index key. But if you only need one record, you can just set fixed value as primary key though. Like, you always pass `1` or something.

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything! 🤝
