### ISSUE TITLE
Relation without foreignKey – Add hasOneBy relation

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuex-orm/vuex-orm#51]
Hi,
Is there a way to define unilateral hasOne relation without foreignKey ?

Great package!
Thanks.

**Comment by CookieJon** [comment]
Seems to work using just the primaryKey, despite the docs using foreign key as the example.

**Comment by kiaking** [comment]
Hi! I'm not sure if I understand the issue correctly here. You need foreignKey to determine if that record is related to the others. Are you looking for something like `hasManyBy` method for `hasOne`?

[Has Many By Doc](https://revolver-app.gitbooks.io/vuex-orm/model/relationship.html#has-many-by)


@CookieJon Your example is still using foreignKey which is `id`, which is fine because foreignKey could be anything. The Bitmap model will search for Platte which has same `id` value of Bitmap. With your example;

```js
// When you have this kind of records in the store.
{
  entities: {
    bitmaps: {
      data: {
        '1': { id: 1, ... },
        '2': { id: 2, ... }
      }
    },
    palettes: {
      data: {
        '1': { id: 1, ... },
        '2': { id: 2, ... }
      }
    }
  }
}

// And fetch palettes through bitmap.
const bitmaps = store.getters['entities/bitmaps/query']().with('palettes').get()

// You get this.
[
  Bitmap {
    id: 1,
    ...
    palette: { id: 1, ... }
  },
  Bitmap {
    id: 2,
    ...
    palette: { id: 2, ... }
  }
]
```js

**Comment by AlexandreBonaventure** [comment]
Hi, yes I’m exactly looking for the `hasManyBy` version of `hasOne`

**Comment by CookieJon** [comment]
@kiaking Yikes! I see you're right - my example only worked by coincidence, with incorrect palettes being returned that happened to have the same content.  :-S

**Comment by kiaking** [comment]
@AlexandreBonaventure OK! Yeah, we should have that feature (I don't know why I didn't make it when I implemented hasManyBy relation). Let me work on to it.

@CookieJon It could work in some situation I guess? Especially with hasOne relation since there will always be only one related record so having an exactly same ID (primary key) for both models could make sense :p (I wouldn't recommend though 😈

**Comment by kiaking** [comment]
Oh wait minute. Isn't `hasOneBy` exactly same as `belongsTo` relation? I've added `hasManyBy` because there was no inverse relation of `hasMany` like `belongsToMany`.

@AlexandreBonaventure Would `belongsTo` method satisfy your needs? Or are looking for something different?

```js
// Let's say User has a Phone and Phone has an User.
class User extends Model {
  static fields () {
    return {
      id: this.attr(null),
      phone: this.hasOne(Phone, 'user_id')
    }
  }
}

class Phone extends Model {
  static fields () {
    return {
      id: this.attr(null),
      user_id: this.attr(null), // <- Contains the ID of related user.
      user: this.belongsTo(User, 'user')
    }
  }
}
```

**Comment by AlexandreBonaventure** [comment]
@kiaking Not exactly, this is what I meant by `unilateral`. My use-case goes like this
```
class User extends Model {
  static fields () {
    return {
      id: this.attr(null),
      bookCurrentlyReading: this.hasOneBy(Book)
    }
  }
}

class Book extends Model {
  static fields () {
    return {
      id: this.attr(null),
      // user_id: this.attr(null), <- In my case i don't have a foreign key, cause a book isnt belonging to user
    }
  }
}
```
You see, if I insert this data 
```
dispatch('entities/user/insert', {
  id: 1, 
  bookCurrentlyReading: {
    id: 'xxx', 
    title: 'a Book'
  }
})
```
I expect to have 
```
getters['entities/users/query']().find() 
=> 
{
  id: 1,
  bookCurrentlyReading: 'xxx'
}


getters['entities/users/query']().with('bookCurrentlyReading').find() 
=> 
{
  id: 1,
  bookCurrentlyReading: {
    id: 'xxx', 
    title: 'a Book'
  }
}

```

**Comment by kiaking** [comment]
OK I see. I've checked it and your use case can still work with `belongsTo`.

```js
class User extends Model {
  static fields () {
    return {
      id: this.attr(null),
      // Just specify own field name as the foreign key. 'bookCurrentlyReading' is the field of User model.
      bookCurrentlyReading: this.belongsTo(Book, 'bookCurrentlyReading')
    }
  }
}

class Book extends Model {
  static fields () {
    return {
      id: this.attr(null)
      // No need for user_id here. If you want, you can even setup hasOne relation to User.
      // user: this.hasOne(User, 'bookCurrentlyReading')
    }
  }
}
```

If you define your model like above, you should get what you want with `create` action and also when fetching data. Even I didn't know that you can actually specify the same field as foreign key but, it works :)

However, it is indeed one way relation. What I mean is that if you create data through `users` modules, it's fine. `bookCurrentlyReading` gets filled by corresponding book ID. But if you create through `books` module, the `bookCurrentlyReading` field gets null. Well it is same for `hasManyBy` right now though.

```js
// Say you have following models.

class User extends Model {
  static fields () {
    return {
      id: this.attr(null),
      bookCurrentlyReading: this.belongsTo(Book, 'bookCurrentlyReading')
    }
  }
}

class Book extends Model {
  static fields () {
    return {
      id: this.attr(null)
      user: this.belongsTo(User, 'user') // or this.hasOne(User, 'bookCurrentlyReading')
    }
  }
}

// If you create data through `users module`.
dispatch('entities/users/create', {
  id: 1,
  bookCurrentlyReading: {
    id: 1, 
    title: 'a Book'
  }
})

// State becomes like this.
{
  users: {
    data: {
      '1': { id: 1, bookCurrentlyReading: 1 }
    }
  },
  books: {
    '1': { id: 1, title: 'a Book', user: null } // <- `user` is null!
  }
}

// You can fetch user with book.
store.getters['entities/users/query'].with('bookCurrentlyReading').find()
=>
{
  id: 1,
  bookCurrentlyReading: {
    id: 1, 
    title: 'a Book'
  }
}
```

So, for your specific use case, belongsTo relation should work. But if you need multidirectional relation, we need to implement feature that sets foreign key for both user and book when creating a new record.

**Comment by AlexandreBonaventure** [comment]
Yes, it is indeed working for my use-case, thanks for your answer. Issue can be closed to me.

**Comment by kiaking** [comment]
@AlexandreBonaventure Thank you for the confirmation! Maybe I should add to the doc that you can specify foreign key to the same field being defined.

Please feel free to reopen this issue or open another issue if you have any trouble 🕶

**Comment by thhan** [comment]
Hello @kiaking, I'm trying the same.

```class User extends Model {

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(null),
      current_reading: this.belongsTo(Book, 'current_reading')
    };
  }

}```

```class Book extends Model {

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(null)
    };
  }
}```

This is what I try to insert in Vuex ORM.

```
{
  id: 1,
  name: 'Bob',
  current_reading: {
    id: 1
  }
}
```

When I try to access this model I get no `current_reading`.

```
User.query().with('current_reading).get();
```

Result:
```[{
  id: 1,
  name: 'Bob',
  current_reading: null
}]```

I hope someone can help me to find the bug in my code.

**Comment by cuebit** [comment]
@thhan the value of `current_reading` should be the foreign key, not an object, since you’re referencing a foreign key lookup on the parent model. 

In other words, your input data should read as follows:

```json
{
  "id": 1,
  "name": "Bob",
  "current_reading": 1
}
```

**Comment by thhan** [comment]
@cuebit look at this comment

> @kiaking Not exactly, this is what I meant by `unilateral`. My use-case goes like this
> 
> ```
> class User extends Model {
>   static fields () {
>     return {
>       id: this.attr(null),
>       bookCurrentlyReading: this.hasOneBy(Book)
>     }
>   }
> }
> 
> class Book extends Model {
>   static fields () {
>     return {
>       id: this.attr(null),
>       // user_id: this.attr(null), <- In my case i don't have a foreign key, cause a book isnt belonging to user
>     }
>   }
> }
> ```
> 
> You see, if I insert this data
> 
> ```
> dispatch('entities/user/insert', {
>   id: 1, 
>   bookCurrentlyReading: {
>     id: 'xxx', 
>     title: 'a Book'
>   }
> })
> ```
> 
> I expect to have
> 
> ```
> getters['entities/users/query']().find() 
> => 
> {
>   id: 1,
>   bookCurrentlyReading: 'xxx'
> }
> 
> 
> getters['entities/users/query']().with('bookCurrentlyReading').find() 
> => 
> {
>   id: 1,
>   bookCurrentlyReading: {
>     id: 'xxx', 
>     title: 'a Book'
>   }
> }
> ```

This is the same, what I try to use. Didn't support Vuex ORM any more?
