### ISSUE TITLE
Freature suggestion: auto increment field.

### ISSUE THREAD

**Issue by Fnxxxxo** [vuex-orm/vuex-orm#517]
Currently, the auto-increment is replaced by uid fields. But it's not convenient for sorting. Is it OK to release both UID and auto increment?

**Comment by kiaking** [comment]
@Fnxxxxo Maybe as plugin yeah. I wasn't thinking about sorting, but it could nice indeed. The reason we removed it was because it was really complex to implement...

**Comment by Fnxxxxo** [comment]
That's fine. Not all users need it.

**Comment by kiaking** [comment]
@Fnxxxxo Thank you for your kind understanding! 💓
