### ISSUE TITLE
Vuex-orm + graphQl plugin

### ISSUE THREAD

**Issue by codeturn** [vuex-orm/vuex-orm#518]
Hey guys! I want write simple CRUD system base on this cool libary. I succesful setup it: 
-vuex-orm
-graphql-plugin
-laravel with lighthouse-php 

So I can fetch data from db and make delete row. But I can't update and insert new raw.
May be you can give me link to simple example of any CRUD system?

**Comment by kiaking** [comment]
Hah, it should be same as how you delete or update. Could you give me the update code you have?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything! 🤝
