### ISSUE TITLE
Polymorphic Many-to-Many relationship constraint

### ISSUE THREAD

**Issue by NickSeger** [vuex-orm/vuex-orm#530]
Hey,

Getting great results with this package so far just coming across some difficulty trying to do a relationship constraint when using a polymorphic, many-to-many type.

Here's my morphToMany structure (hidden auxiliary fields in the models for brevity):

    
    export default class User extends Model {

	static entity = 'users';

	static fields() {
		return {
			id: this.uid(),
                    .....
			roles: this.morphedByMany(
				Role,
				RoleUser,
				'user_id',
				'role_id',
				'user_type',
			),
		};
	}
    }

    export default class Role extends Model {

	static entity = 'roles';

	static fields() {
		return {
			id: this.uid(),
                    .....
			users: this.morphedByMany(
				Role,
				RoleUser,
				'role_id',
				'user_id',
				'user_type',
			),
		};
	}
    }

    export default class RoleUser extends Model {

    static entity = 'roleUser';

    static primaryKey = ['role_id', 'user_id', 'user_type'];

	static fields() {
		return {
		  role_id: this.attr(null),
		  user_id: this.attr(null),
		  user_type: this.attr(null),
		};
	}
    }
   
My query is super simple for testing:

      const users = User.query()
		.whereHas('roles', query => {
			query.where('id', 1);
		})
		.get();

However this query doesn't filter the users AND it breaks the roles relationship, the user records are returned with empty role objects.

If I simply do a:

      const users = User.query()
			 .withAll()
			 .all();

It works fine and all the records are returned with relations in tact, is there something simple I'm missing or is there an issue with filtering polymorphic many-to-many relationships?

Thanks,
Nick

**Comment by NickSeger** [comment]
Solved my problem on the back end, no need to do complex querying on client side.

**Comment by kiaking** [comment]
@NickSeger Glad to hear that! Sorry for my late response 😓
