### ISSUE TITLE
High priority bug! When setting the entities, it does not go deep inside the object itself.

### ISSUE THREAD

**Issue by allocenx** [vuex-orm/vuex-orm#531]
For example, i make an API call to the server which fetches me a list of users and each user has an object attached with his profile and this library when it sets the entity for the users it sets all the fields except the nested profile object.

Please help :(

**Comment by petertoth** [comment]
Do you have a reproduction for this bug?
Could you post code with your problem and also expected behavior? Thanks!

**Comment by allocenx** [comment]
Sure, gimme few minutes to prepare it. Thank you kindly!

**Comment by allocenx** [comment]
Oh, you've got to be kidding me... . Just now wondered to take a better look at the static fields within my Model, seems like i was not declaring that field aswell LOL.

Seems like, its all fine now, hahaha, my bad for not paying better attention.

Thank you for the quick reply tho and Merry Christmas! This issue can be closed.

**Comment by kiaking** [comment]
Merry Christmas! Happy to hear it fixed 👍
