### ISSUE TITLE
vuex-orm.esm.js undefined probs:    Uncaught TypeError: Cannot read property 'localKey' of undefined at **Function.**Model.belongsTo**** (vuex-orm.esm.js?0937:2127) 

### ISSUE THREAD

**Issue by wocdamjack** [vuex-orm/vuex-orm#533]
Uncaught TypeError: Cannot read property 'localKey' of undefined at **Function.**Model.belongsTo**** (vuex-orm.esm.js?0937:2127)

Changed to:
        if(parent) {
            return new BelongsTo(this, parent, foreignKey, this.relation(parent).localKey(ownerKey));
        }

Then, similarly:
Model.prototype.$fill = function (record) {
at line 2672, (**Model.prototype.$fill**),  changed: 
            this[key] = field.make(value, data, key);
to:
            if (field) {
                this[key] = field.make(value, data, key);
            }

**Comment by kiaking** [comment]
Hah, not sure what this is. So sorry for my late reply but could you elaborate a bit more?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything! 🤝
