### ISSUE TITLE
this in static function

### ISSUE THREAD

**Issue by Heckayel** [vuex-orm/vuex-orm#538]
In the documentation you indicate to use "this" in a static function and that's not a good OOP action

Why don't you use Model.attr("") or <className>.attr(""); ?

![image](https://user-images.githubusercontent.com/6170793/72059418-3f047880-32d2-11ea-85f1-97eb29b984f4.png)

**Comment by cuebit** [comment]
You say it's not good OOP but it's not bad either. If you want to use `Model.attr` then there's nothing stopping you, OOP is a design, not a technicality. This is an opinion not an issue.

**Comment by qyloxe** [comment]
I do not see this as bad either. Using this.attr in derived class suggests that it is possible to override 'attr' method (ie you can have your own attr factory) and also 'attr' method has access to local (User Model) methods (ie validation, annotation etc). I totally agree, that it is a matter of convention or design and the main purpose is a communication between developers (and not between developer and mythical all wise compiler). Author properly suggested, in this code (without words, just by code), that the local User model could be extended and global Model class will respect those extensions. All OK for me.

**Comment by Heckayel** [comment]
I agree, opinions in OOP exist when it's about architecture but here I speak about a technicality that shouldn't work but that works because Javascript is too much permissive

"static" is a class method, not a method of an instance of the class. "this" refer to the current instance. Or in a static context, there is no question about "current instance" because it's the class not an instance. So that shouldn't be possible to call a current instance method in a static context

With this code, in Typescript, that doesn't work. So if vuex-orm or / and a user of vuex wants to migrate from JS to TS, he will have to correct this.

But you're right, this is maybe not an issue for the moment because "that works"

**Comment by Heckayel** [comment]
Well, I found https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static and it's written we can use this here and tested in typescript (I was sure that couldn't work on TS but that works)

That's really weird and I don't understand why js / ts permits to do that and has not created "self" for example but that is another subject that doesn't impact vuex-orm

Sorry for the issue
