### ISSUE TITLE
Can't insert hasMany relationship

### ISSUE THREAD

**Issue by AdrienPoupa** [vuex-orm/vuex-orm#539]
Hello,

This is my first time using VuexORM so my question may be really dumb.

I have an entity, Portfolio, that hasMany Positions.

My models:

```js
import { Model } from '@vuex-orm/core'
import Position from "./position";

export default class Portfolio extends Model {
    static entity = 'portfolios'

    static fields() {
        return {
            id: this.attr(null),
            title: this.attr(''),
            positions: this.hasMany(Position, 'portfolio_id'),
        }
    }
}
```
```js
import { Model } from '@vuex-orm/core'
import Portfolio from "./portfolio";

export default class Position extends Model {
    static entity = 'positions'

    static fields() {
        return {
            id: this.attr(null),
            portfolio_id: this.attr(null),
            name: this.attr(''),
        }
    }
}
```

In my component, I call
```js
            Portfolio.insert({
                data: {
                    id: 81,
                    title: "Portfolio Title",
                    positions: [
                        {
                            id: 106,
                            portfolio_id: 81,
                            name: "Position Title",
                        }
                    ],
                }
            });
```

like in the documentation: https://vuex-orm.github.io/vuex-orm/guide/data/inserting-and-updating.html#inserting-relationships

My store fills the portfolio properties when it has no relationships but I get the following error when I try to load the positions:

```js
TypeError: query.getModel(...) is undefined
```

```js
var Attacher = /** @class */ (function () {
    function Attacher() {
    }
    /**
     * Attach missing relational key to the records.
     */
    Attacher.process = function (query, data) {
        Utils.forOwn(data, function (entity, name) {
            var fields = query.getModel(name).fields();
```

Am I missing something obvious?

Thanks!

**Comment by janoveoyen** [comment]
Can you show the bit of code where you're calling Attacher.process? What is the query parameter you're passing?

**Comment by AdrienPoupa** [comment]
I showed you all my code. I am not calling the Attacher this is just the error I am getting when trying to insert a Portfolio with Positions

**Comment by janoveoyen** [comment]
My apologies, I didn't realize that was the stack trace for the error so I thought you had written your own Attacher :)

Your code looks pretty much identical to the docs. Have you registered both Portfolio and Position to the Database (as per [/guide/model/database-registration.html](https://vuex-orm.github.io/vuex-orm/guide/model/database-registration.html))?

**Comment by AdrienPoupa** [comment]
I only registered the Portfolio but forgot to register the Position. Told you it was going to be stupid :)

Thank you so much.

Maybe there could be a more explicit error message, like when one tries to enter objects directly in the model?

**Comment by AdrienPoupa** [comment]
OK, now I have no more error but the relationship is still not inserted. Do you have any idea?

![image](https://user-images.githubusercontent.com/15086425/72162164-6e2cef80-338f-11ea-9f23-9b51ad82a43b.png)

**Comment by AdrienPoupa** [comment]
Interestingly, if I do the following:

```js
            Portfolio.insert({
                data: {
                    id: 81,
                    title: "Portfolio Title",
                    positions: [
                        {
                            id: 106,
                            portfolio_id: 81,
                            name: "Position Title",
                        }
                    ],
                }
            });

            console.log(Portfolio.query().with('positions').all());
```

then I am getting the expected result:

![image](https://user-images.githubusercontent.com/15086425/72164149-27d98f80-3393-11ea-9025-bc8aa7abbac8.png)

The issue seems to be with the Vuejs devtools.

If I disable the new Vuex backend it works... so I guess the bug is theirs.

Thanks for the help!

**Comment by janoveoyen** [comment]
That's good then!

Are you sure the state in the DevTools was updated (button somewhere in the bottom right corner, or you can set it to auto update in the settings)?

**Comment by cuebit** [comment]
Vuex ORM has struggled to work with the new vue-devtools backend for a long time. In fact, I don’t think I’ve ever got it working. But then I don’t really see a huge difference between the two backends so it’s always disabled.

**Comment by AdrienPoupa** [comment]
Got it. Maybe it would be worth it to put it in the docs?

Yes @janoveoyen it does not matter.

It is actually related to https://github.com/vuex-orm/vuex-orm/issues/166

I can see the relationships once I load them.
