### ISSUE TITLE
Getting all data for a model isn't returning relationship data

### ISSUE THREAD

**Issue by tjsteinhaus** [vuex-orm/vuex-orm#54]
I'm trying to get all data that's related to a model and then also all the relationship data as well. When outputting this: `this.$store.getters['entities/evaluations/query']().get()` my relationship attribute returns undefined.

If I run: `this.$store.getters['entities/evaluations/query']().with( 'assessors' ).get()` It returns an empty array for the attribute's value.

However if I run: `this.$store.getters['entities/evaluations/query']().find()` It returns the first record with the relationship value just fine so I know I set it up correctly.

I've been trying to debug the issue for a couple hours now and I can't seem to find the issue.

**Comment by kiaking** [comment]
Hi!

If `this.$store.getters['entities/evaluations/query']().find()` is returning relationship, that's a defect. I haven't check this yet but sorry if this is happening. You must use `with` method if you want to load relationship.

So, `this.$store.getters['entities/evaluations/query']().with( 'assessors' ).get()` should work as you expected.

The test for this function is passing so it's hard for me to look into this. Could you paste the model definition and how you created or inserted data?

**Comment by tjsteinhaus** [comment]
Odd, for some reason it's not returning the data on finding just one now.

Here is my Evaluations Model:
`import { Model } from '@vuex-orm/core'

import Assessors from './Assessors';

export default class Evaluations extends Model {
  static entity = 'evaluations'

  static fields () {
    return {
      id: this.attr(null),
      userId: this.attr(null),
      name: this.attr(''),
      dairy_location_id: this.attr(null),
      contact_id: this.attr(null),
	 company_id: this.attr(null),
	 assessors: this.hasMany(Assessors, 'id')
    }
  }
}`

And here is my Assessors Model:
`import { Model } from '@vuex-orm/core'

import AssessorsIndex from './AssessorsIndex';
import Evaluations from './Evaluations';


export default class Assessors extends Model {
  static entity = 'assessors'

  static fields () {
    return {
      id: this.attr(null),
      assessor_data: this.hasOne(AssessorsIndex, 'id'),
      evaluationId: this.hasOne(Evaluations, 'id'),
      order: this.attr(null)
    }
  }
}`

And my AssessorsIndex table:
`import { Model } from '@vuex-orm/core';


export default class AssessorsIndex extends Model {
  static entity = 'assessors_index'

  static fields () {
    return {
      id: this.attr(null),
      name: this.attr(''),
      enabled: this.attr('')
    }
  }
}`
None of the queries I'm running are returning any relationship data. Am I doing something wrong in my Models?

**Comment by kiaking** [comment]
OK I found it. Your foreign key is wrong. For example `Evaluations` should have foreign key of `evaluationId`. So I think you should change relation definition as below and it will work.

```js
import { Model } from '@vuex-orm/core'
import Assessors from './Assessors'

export default class Evaluations extends Model {
  static entity = 'evaluations'

  static fields () {
    return {
      id: this.attr(null),
      userId: this.attr(null),
      name: this.attr(''),
      dairy_location_id: this.attr(null),
      contact_id: this.attr(null),
      company_id: this.attr(null),
      assessors: this.hasMany(Assessors, 'evaluationId') // <- Change!
    }
  }
}
```

```js
import { Model } from '@vuex-orm/core'
import AssessorsIndex from './AssessorsIndex'
import Evaluations from './Evaluations'

export default class Assessors extends Model {
  static entity = 'assessors'

  static fields () {
    return {
      id: this.attr(null),
      evaluationId: this.attr(null), // Add this.
      assessor_data: this.hasOne(AssessorsIndex, 'id'), // AccessorsIndex needs to have foreign key.
      evaluations: this.belongsTo(Evaluations, 'evaluationId'), // <- Change!
      order: this.attr(null)
    }
  }
}
```

To have relationship between Accessors and AssessorsIndex, AssessorsIndex need to have field that hold the id value of Assessors. Do you have one?

**Comment by tjsteinhaus** [comment]
Of course! Can't believe I missed that, thank you!

**Comment by kiaking** [comment]
Glad I could help! Let me know if you have any other questions 👍
