### ISSUE TITLE
Retrieve from Model - Fetch from Database issue.

### ISSUE THREAD

**Issue by NickSeger** [vuex-orm/vuex-orm#545]
Hey there,

Hoping this is a simple issue, I'm trying to access the database instance as documented in the Retrieve Models section, trying the example via ```this.$store.$db()``` but getting an error that $db isn't a function.

Everything else works, I can hit the store and the entities with no issue and if I import directly it's fine too but I am doing a dynamic page and need to pass the model through to the component each time and was looking to use the string base access method as shown in the release notes.

Is there any extra steps that are needed, or should the database instance inject directly once Vuex-ORM is initialized.

Thanks,
Nick

**Comment by cuebit** [comment]
The store method was released with v0.35.0

Are you using the latest version?

**Comment by NickSeger** [comment]
@cuebit yes running on v0.35.1.

I'm wondering if it's got to do with how my database and models are registered, 

I currently have a database index file where i instantiate the database, register the models and modules, attach the VuexORM plugins:

```
//resources/js/stores/database/index.js

import VuexORM, { Database } from '@vuex-orm/core';
import VuexORMSearch from '@vuex-orm/plugin-search';
import VuexORMisDirtyPlugin from '@vuex-orm/plugin-change-flags';
import VuexORMSoftDeletePlugin from '@vuex-orm/plugin-soft-delete';
...

import Client from '../models/Client';
import Country from '../models/Country';
import Currency from '../models/Currency';
...

const database = new Database();

database.register(Client, Clients);
database.register(Country, Countries);
database.register(Currency);
...

VuexORM.use(VuexORMSearch, { threshold: 0.3 });
VuexORM.use(VuexORMisDirtyPlugin);
VuexORM.use(VuexORMSoftDeletePlugin);

export default database;
```

I then use the exported database and inject it into the Vuex Store in a separate file.

```
//resources/js/stores/index.js

import Vue from 'vue';
import Vuex from 'vuex';
import VuexORM from '@vuex-orm/core';
import auth from './modules/Auth';
import database from './database';
import VuexPersistence from 'vuex-persist';

Vue.use(Vuex);

const vuexLocal = new VuexPersistence({
	storage: window.localStorage,
});

export default new Vuex.Store({
	modules: {
		auth,
	},
	plugins: [VuexORM.install(database), vuexLocal.plugin],
});
```

Up until now haven't had any other issues (that aren't of my own creation) but just can't access the $db store as per the docs.

Thanks for the assist,
Nick

**Comment by NickSeger** [comment]
Ok... so I completely overlooked something really minor, just had to step away and come back and it wasn't anything to do with VuexORM at all.

Thanks for the help, works perfectly for my use case,
Nick

**Comment by cuebit** [comment]
@NickSeger 

Out of curiosity and to help better understand common pitfalls, what was the cause and how did you resolve it? 

Your feedback is much appreciated.

**Comment by NickSeger** [comment]
@cuebit I was incorrectly using this.store() and this.$store and a couple of other Vuex parts in a few places, so I was refactoring about 6 components into a single one now that I can get the model through the $db instance, and I just made some typo errors, wasn't really to do with the $db instance call itself.

Thanks,
Nick
