### ISSUE TITLE
It seems like 0.35 has broken `orderBy` when used with number fields

### ISSUE THREAD

**Issue by lorenzki** [vuex-orm/vuex-orm#549]
I got a model with the number field `rank`: 
`static fields() {
    return {
      ID: this.string(''),
      rank: this.number(0),
}`

When using `orderBy` until 0.34.x the query result was correctly sorted:

`TestModel.query().orderBy('rank').get();`

sorted the data in the correct numerical order: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,...

with the update to 0.35.x the number field is sorted alphabetically: 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9,..

I already took a look at the changes but sadly could not find the source of this bug.

**Comment by kiaking** [comment]
Fixed with Vuex ORM 0.35.2! 🎉 Thanks to @cuebit!
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.35.2
