### ISSUE TITLE
Add Database to plugin argument

### ISSUE THREAD

**Issue by SzNagyMisu** [vuex-orm/vuex-orm#557]
So, I was sooo happy when #535 was merged and with [v0.35](https://github.com/vuex-orm/vuex-orm/releases/tag/v0.35.0) came the possibility to register models at run time. Then I started to use this feature to be able to split my models into chunks, and import only models required by the component on screen.

Then I realized (through a bunch of nice error messages) that I use vuex-orm plugins that extend the module of entities with state, getters, mutations and actions. These plugins rely on the fact that every entity is already registered and extend modules by iterating through `database.entities`. Now, if I register my model in-the-fly, it won't get the module extension and will crash.

Re-reading the docs a bit I found that I could use the `static state ()` method to add state and the `static commit ()` method to modify it. Not my favorite, though. I find that `Model.commit()` is not really debug-friendly, and anyway, I would prefer to keep getters and actions too, to remain as clean in code as possible.

Another idea of mine was to extend `Database` from within my plugin. I could, then, extend the method `register` to add the required vuex-parts after executing its original task. But `Database` is not extendable by plugins.

**Questions:**
* Is it intentional that `Database` is not extendable? Is it due to some security issue?
* Or, is there any other possibility to achieve my goal?

@kiaking what do you think?

Thanks in advance!

**Comment by kiaking** [comment]
@SzNagyMisu Actually there's no reason why Database shouldn't be extended. I just didn't thought through about the use case. But yea we should include the Database class to the plugin argument 👍 

And I think to achieve your use case, extending Database might be the fastest way. In the future, maybe it's better for Vuex ORM to have some hooks that would be called when a new entity is added. Not sure.

Either way, I think Database should be included to plugins, so let's do that...!

**Comment by SzNagyMisu** [comment]
Truly sorry, I must be really tired...

Of course, I will use `Model.state()` and extend `Getters`, `RootGetters`, `Actions`, `RootActions` and `RootMutations` to have a clean code...

So my use case seems to be irrelevant. Thanks for the feedback, though.

@kiaking feel free to close this issue.

**Comment by kiaking** [comment]
Ah OK. Though I still think we should add Database to plugin, so I'll rename the title and keep it open!

I'm happy to hear you found a solution! Thanks for the feedback anyway 😃

**Comment by cuebit** [comment]
This will be available in 1.0.0

**Comment by kiaking** [comment]
This feature is now added to Vuex ORM 0.36.0 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.36.0
