### ISSUE TITLE
Can't use alternative id since update

### ISSUE THREAD

**Issue by Vercoutere** [vuex-orm/vuex-orm#560]
The added UID feature in 0.34.0 breaks the following code defined on a model:

```js
// Define property to use if there's no id
static getIndexIdFromRecord (record) {
    return record.id || record.other_attribute;
}
```

Though no id is present (or is null) on my record's source data, the id is already replaced by a generated UID at this point.
As far as I can tell, there is no other easy way to replicate this type of functionality.

**Comment by cuebit** [comment]
Is that a method added to a model you're defining or are you referring to the underlying code @Vercoutere?

**Comment by Vercoutere** [comment]
That's a method added to a model.

**Comment by cuebit** [comment]
Could it be that this method is conflicting with [getIndexIdFromRecord](https://github.com/vuex-orm/vuex-orm/blob/465b4686ae42edde5664d8743ac809913dce51d4/src/model/Model.ts#L489) that’s relevant to the underlying model functionality or are you intentionally overriding?

**Comment by kiaking** [comment]
@Vercoutere Do you have any updates on this?

**Comment by Vercoutere** [comment]
> @Vercoutere Do you have any updates on this?

The way I'm currently solving this is by adding a closure to the uid method call that explicitly returns null as the default value. Feels like a bit of a hack, but it gets the job done.

`id: this.uid(() => null),`

**Comment by cuebit** [comment]
Correct me if I’m wrong, could you not use `id: this.attr(null).nullable()` instead of the UID attribute?

**Comment by Vercoutere** [comment]
Sure, the outcome would be the same.

**Comment by kiaking** [comment]
Do we have any updates on this? Perhaps we need reproduction code I guess.

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything!
