### ISSUE TITLE
Confused about relationships

### ISSUE THREAD

**Issue by sarahdayan** [vuex-orm/vuex-orm#561]
Hi, and thanks for the great package!

I'm having trouble with what seems to be a quite simple use case. I have two models; `User` and `Message`. A `Message` belongs to a `User`. They're both registered in my Vuex store.

I'm trying to insert a new message and its associated user from a method in a Vue component. When this is called, both entities are effectively created in the store (the `Message` and the `User`), but the relationship doesn't exist. The `Message` saved in Vuex has `userId` set to `1`, but `user` is `null`. I have no idea what I'm doing wrong.

Here's a [reproducible CodeSandbox](https://codesandbox.io/s/confident-johnson-cikb9). As you can see, when adding a message, the `user` in the retrieved message is `null`, but a new user has still been added.

Another thing I'm having trouble with is finding out how to insert a `Message` from a `User` who is already in my store. Do I always need to provide the entire `User` object (which would mean querying it from the store, serializing it and passing it down)? Isn't it possible to simply pass the foreign key and for Vuex ORM to resolve it from store data? I couldn't find much in the docs in that regard.

Thanks in advance, and let me know if I should be more specific about anything.

**Comment by petertoth** [comment]
In your example you have a typo in querying user relationship on message model:

It should be `this.$store.$db().model("messages").query().with("user").get()` instead of  `this.$store.$db().model("messages").query().with("users").get()`

Hope it helps 👍

**Comment by cuebit** [comment]
> Another thing I'm having trouble with is finding out how to insert a Message from a User who is already in my store. Do I always need to provide the entire User object (which would mean querying it from the store, serializing it and passing it down)? Isn't it possible to simply pass the foreign key and for Vuex ORM to resolve it from store data? I couldn't find much in the docs in that regard.

If a user already exists, i.e. `this.$store.$db().model('users').find(userId)`, then just the `userId` field is sufficient for Vuex ORM to map the message to that user without having to supply the entire user data.

**Comment by sarahdayan** [comment]
Wow, I can't believe myself 🤦‍♀
Thank you @petertoth and @cuebit this was exactly the problem! That's what you get for coding late at night I guess.

I'll close this but I will open a PR to clarify that in the docs 🙂
