### ISSUE TITLE
Update and insert not working as expected

### ISSUE THREAD

**Issue by Braincoke** [vuex-orm/vuex-orm#566]
Hi,

I fail to insert and update models with their relationships.

I have a User and a Todo model heavily inspired by [Nuxt ORM example](https://github.com/vuex-orm/vuex-orm-examples-nuxt).
When I try to insert a Todo by giving it a `user_id`, the Todo is created but my User does not get updated with the new Todo.

I use the following code to insert a new Todo : 
```js
      this.Todo.insert({
        data: {
          title: this.newTodoTitle,
          user_id: this.selectedUserId
        }
      }
```

The issue is even worse when I try to update the user instead of inserting the Todo. In this case the Todo is not created:

```js
      this.User.update({
        where: this.selectedUserId,
        data: {
          todos: [
            {
              title: this.newTodoTitle,
              user_id: this.selectedUserId
            }
          ]
        }
      }
```

I have created a [test application](https://github.com/Braincoke/vuex-orm-update-issue) if you want to take a look. I also serve it [online](http://test.braincoke.fr/) if you want to test it quickly.

I am using the following versions :
- "@vuex-orm/core": "0.35.2"
- "nuxt": "2.11.0"

I am using the library incorrectly or is this an issue ?

**Comment by JasonLandbridge** [comment]
I think you forgot adding[ primary keys ](https://vuex-orm.github.io/vuex-orm/guide/model/defining-models.html#primary-key)in your models

**Comment by Braincoke** [comment]
According to the documentation:
> Vuex ORM will assume that each data has a primary key named id

From what I understand my models both have this id:

```js
import { Model } from '@vuex-orm/core'
import Todo from './Todo'

export default class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.uid(),
      name: this.string(''),
      todos: this.hasMany(Todo, 'user_id')
    }
  }
}
```

Is there something else missing ?

**Comment by JasonLandbridge** [comment]
You need to define and tell Vuex-ORM which property is your primary key:
`  static primaryKey = 'id'`

**Comment by Braincoke** [comment]
Ok I'll try that.
If that is the issue the documentation can be confusing since it lets us believe that adding `static primaryKey = 'id'` should only be used to override the convention.

> Vuex ORM will assume that each data has a primary key named id. You may define a static primaryKey property to override this convention.

**Comment by Braincoke** [comment]
I tried your suggestion but unfortunately it didn't work.

**Comment by JasonLandbridge** [comment]
> Ok I'll try that.
> If that is the issue the documentation can be confusing since it lets us believe that adding `static primaryKey = 'id'` should only be used to override the convention.
> 
> > Vuex ORM will assume that each data has a primary key named id. You may define a static primaryKey property to override this convention.

Ah I missed that one, looking closer to your question I realize i am having the same problem. I'm also working in Nuxt with Vuex-orm but none of my relationships are updated when inserts are happening.

**Comment by kiaking** [comment]
The update will not create relationships in that syntax. You must use

```js
this.User.update({
  id: this.selectedUserId
  todos: [
    {
      title: this.newTodoTitle,
      user_id: this.selectedUserId
    }
  ]
})
```

However, not sure why insert is not updating. Do you have any reproduction code?

**Comment by Braincoke** [comment]
Are the resources I provided when creating the issue not enough ?
Not that the online version has devtools activated.

> I have created a [test application](https://github.com/Braincoke/vuex-orm-update-issue) if you want to take a look. I also serve it [online](http://test.braincoke.fr/) if you want to test it quickly.

**Comment by cuebit** [comment]
Your inserts are working fine. You're not seeing the results because you are not eager loading the required relationships.

In your `InsertTodo.vue` and `UpdateTodo.vue` replace `all()` with:
- `this.User.query().with('todos').get()` in `users()`
- `this.Todo.query().with('assignee').get()` in `todos()`

Your updates won't work with the syntax you're using, as mentioned by @kiaking. Updates to records are designed to update existing data – however your objective is to _insert_ relations for an existing user. To do this, you can pass in the `insert: [...]` option.

```js
this.User.update({
  data: {
    id: this.selectedUser,
    todos: [
      {
        title: this.newTodoTitle
      }
    ]
  },
  insert: ['todos']
})
```

Honestly, this is quite verbose. You could simplify by inserting a new todo and passing the `user_id` and the relation will be created for you.

```js
this.Todo.insert({
  data: {
    title: this.newTodoTitle,
    user_id: this.selectedUser
  }
})
```

**Comment by Braincoke** [comment]
Thank you all for taking the time to detail your answers.
After rewriting the reproduction code according to your code I can see that the relationships are being created.

As stated by @cuebit, in the end the problem was that I was not eager loading the required relationships. After changing that the insertion code showed me the updates.

Regarding the update code, the attribute `insert: ['todos']` was mandatory. I have updated the reproduction code and will leave it [here](https://github.com/Braincoke/vuex-orm-update-issue) for anyone interested.
