### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by JasonLandbridge** [vuex-orm/vuex-orm#569]
Hey, 

In the [has-many-through paragraph](https://vuex-orm.github.io/vuex-orm/guide/model/relationships.html#has-many-through) there is a link at the end that is broken. 

> NOTE: When creating data that contains hasManyThrough relationship without intermediate relation, the intermediate record will not be generated. See -> here <- for more details.

Thanks!

**Comment by cuebit** [comment]
Good spot @JasonLandbridge. Thanks!
