### ISSUE TITLE
Feature Request: Getter in Model with Relation data

### ISSUE THREAD

**Issue by tjsteinhaus** [vuex-orm/vuex-orm#58]
I have a getter setup in my model and I'm trying to get data that is being used in a relation but it's not appearing. I think it would be great for this data to appear in the getter.

I also have the relation setup in my query so the data is there.

<img width="740" alt="screen shot 2018-01-28 at 9 35 01 pm" src="https://user-images.githubusercontent.com/5176701/35492547-250983ce-0473-11e8-8e69-127cb0095bf0.png">

**Comment by kiaking** [comment]
Oh, have you resolved this? Just wanted to check in if you closed this issue by mistake or it was intended : )
