### ISSUE TITLE
Update not working (doing insert?)

### ISSUE THREAD

**Issue by fractalf** [vuex-orm/vuex-orm#580]
I'm playing around with vuex-orm and stumbled upon something weird when trying to update a record..

What am I missing here?

```js
import Vue from 'vue'
import Vuex from 'vuex'
import VuexORM from '@vuex-orm/core'
import { Model } from '@vuex-orm/core'

Vue.use(Vuex)

class Test extends Model {
    static entity = 'test'
    static fields() {
        return {
            a: this.attr(null),
            b: this.attr(null),
        }
    }
}
const database = new VuexORM.Database()
database.register(Test)

export default new Vuex.Store({
    plugins: [VuexORM.install(database)]
})

const debug = async function () {
    let res = await Test.create({
        data: { id: 1, a: 'A', b: 'B' }
    })
    console.log('create', res)

    res = await Test.update({
        where: 1,
        data: { a: 'C' }
    })
    console.log('update', res)
}
debug()
```
console:
![image](https://user-images.githubusercontent.com/5707457/75387680-fa658880-58e3-11ea-9421-092892d09581.png)

vuex:
![image](https://user-images.githubusercontent.com/5707457/75387815-2e40ae00-58e4-11ea-83ae-ffb3bf42f61a.png)

I'm expecting record with id 1 to be updated, instead a new record is inserted?!

**Comment by cuebit** [comment]
You're missing `id` in your `fields` declaration.

**Comment by fractalf** [comment]
Gaaaawd... Thanks @cuebit , I guess I somehow thought that was a build in field..
