### ISSUE TITLE
findIn not work with relation

### ISSUE THREAD

**Issue by lukaslaskovski** [vuex-orm/vuex-orm#588]
BookModel relation definition:
```
author_id: this.number(0),
author: this.belongsTo(AuthorModel, 'author_id'),
```
author is null when using findIn like:
`BookModel.query().with('author').findIn([1, 2])`
and works well with whereIdIn:
`BookModel.query().with('author').whereIdIn([1, 2]).get()`

**Comment by cuebit** [comment]
Thanks for reporting this @lukaslaskovski. This looks like a bug that's been hiding behind the sofa.
