### ISSUE TITLE
Migrate unit tests from JS to TS

### ISSUE THREAD

**Issue by cuebit** [vuex-orm/vuex-orm#593]
There is a mixture of TS and JS unit tests, the latter being more prominent.

We should aim to migrate all tests to TS because:

- The codebase is written in TS
- Will encourage the use of [Prettier](https://prettier.io) (may impact #555)
- Allow collaborators to dissect any type issues
- Promote consistency between source code and real time usage
- Bridges coding practices adopted by Vue 3

Unit tests are also a great source of information about the deeper workings of Vuex ORM and may aid users who are looking to adopt or already have adopted TS in their projects.

**Comment by kiaking** [comment]
One thing I would also like to consider is whether we should have decorator integrated to the tests. Defining models without decorator is bit overwhelming. In that case, maybe we should integrate decorator to the core as well... not sure.

I was thinking creating a dedicated TypeScript section once we have decorators.

> Unit tests are also a great source of information about the deeper workings of Vuex ORM and may aid users who are looking to adopt or already have adopted TS in their projects.

This is very true, and for those users, maybe it would be nice to have clean TS writing experience.

Well, in this case, we need to bring decorator priority up, but I think we need it before v1.0.0 anyway.

**Comment by cuebit** [comment]
Oh of course, @kiaking!! I completely overlooked decorators. This will definitely bode well with decorator integration.

**Comment by kiaking** [comment]
Oh no it's my fault. I think I can work on wth decorators after finishing up the Repository pattern issue #591. 👍

And interns of whether to include decorators to core or not... I think it's OK to have it as a separate package, but still use it within the tests. It might look like testing decorator package inside core package, but when we think of it as a mono-repo, it does make sense as a feature tests.

**Comment by cuebit** [comment]
OK cool. Given that most tests have been migrated, mentioned elsewhere, I think we can introduce decorators once you've had a chance to look into it. Could mean that Prettier may be implemented without decorators in the meantime.

**Comment by kiaking** [comment]
> Could mean that Prettier may be implemented without decorators in the meantime.

Ah, yea. That true. We could do that upper hand 👍
