### ISSUE TITLE
Delete Data With relations

### ISSUE THREAD

**Issue by kpilard** [vuex-orm/vuex-orm#595]
Hey,

it would be nice to delete a model from the store with specific relations.

```ts
// Delete all User with their posts
User.delete(1, {with: 'posts'})

// at the moment
User.delete(1)
Post.delete(post => post.user_id === 1)
```

Or maybe allow deleting with the querybuilder

```ts
// Delete all User with their posts
User.query().where('id', 1).with('posts').delete()
```

**Comment by cuebit** [comment]
Cascading is a nice feature, for sure. Something that is currently not supported by Vuex ORM but we may dip our toes to test the waters on this feature.

There is an issue open related to this (#345) – we'd be happy to listen to your suggestions over there.

**Comment by kiaking** [comment]
Thanks for the feedback! yea this is some thing we would need. Closing the issue due to duplication, though feel free to add your ideas to #345 👍
