### ISSUE TITLE
How to setup many to many relations?

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#61]

**Comment by kiaking** [comment]
Good question! You can't, currently. I have plan to add it (ref #50). And guess I need to hurry 🚄

**Comment by phortx** [comment]
oh oh 😱 

When do you think, you can finish that? :)

**Comment by kiaking** [comment]
Soon I guess. Maybe I can finish them at weekend.

**Comment by phortx** [comment]
> Maybe I can finish them at weekend.

You Sir are my personal hero of the week :)

**Comment by kiaking** [comment]
Now Many To Many relation `belongsToMany` is available at Vuex ORM 0.17.0!

Please refer [documentation](https://vuex-orm.gitbooks.io/vuex-orm/relationships/defining-relationships.html#many-to-many) on how to define the relationship.
