### ISSUE TITLE
[DOC] Getters static methods example mistake

### ISSUE THREAD

**Issue by NZX-DeSiGN** [vuex-orm/vuex-orm#618]
#### Describe the bug

The example in the documentation of the static Model method getters call the wrong method
```js 
const users = User.$getters('all')()
```
#### Steps to reproduce the bug

Goto https://vuex-orm.org/api/model/model.html#getters

#### Expected behaviour

The example should be :
```js 
const users = User.getters('all')()
```

**Comment by cuebit** [comment]
@NZX-DeSiGN thank you for reporting this! 🙌
