### ISSUE TITLE
[Question] How to keep the order in which data comes from API

### ISSUE THREAD

**Issue by sanjitkung** [vuex-orm/vuex-orm#619]
I am using axios plugin with orm

My Api is returning sorted records,

```
[
   { id: 2}
   { id: 1}
   { id: 3 }
]
```
but when I query the orm it given me the data which is ordered by id.

1, 2, 3

How can I keep the order in which data comes from API?

**Comment by cuebit** [comment]
@sanjitkung this is an excellent question!

Vuex ORM stores records by Primary Key (PK), for example `[PK]: Record`, which helps to speed up model and relation lookup. Plain objects, sadly, are an unreliable source of order preservation. In the case of integers, you're more likely to experience this as a result.

There are many solutions to work around this but which one works for you will depend primarily on your use-case.

For example, let's assume all of your models have PK declared as `id: number` – you could accumulate all PK for an entity and store them in a [static state](https://vuex-orm.org/guide/digging-deeper/vuex-module.html#defining-state) to preserve order. Using [lifecylce hooks](https://vuex-orm.org/guide/digging-deeper/lifecycle-hooks.html) you could then manage this process to populate, remove and the order PK values from a collection.

**Comment by sanjitkung** [comment]
Thank you for the response. 

How can access static state from with in the model?

**Comment by kiaking** [comment]
@sanjitkung Currently, you need to reference whole store.

```js
class User extends Model {
  someFunc () {
    this.store().state.entities.users.yourState
  }
}
```

**Comment by sanjitkung** [comment]
Thank you very much @kiaking.
This solves the problem.
