### ISSUE TITLE
Add last() 

### ISSUE THREAD

**Issue by tjsteinhaus** [vuex-orm/vuex-orm#62]
Would you be able to make a quick way of getting the last item? Like first() but create one called last(). Or if possible, when creating/inserting new data, it could return the last id that was created? Or return the whole object?

**Comment by kiaking** [comment]
Yea I could. I'll work on to it.

> Or if possible, when creating/inserting new data, it could return the last id that was created? Or return the whole object?

This is nice to have! I think returning whole object would be more flexible so I'll go with that path.

**Comment by tjsteinhaus** [comment]
Awesome! Yes, it saves me from doing another query every time I'm inserting new data into a model to get the last or object.

**Comment by kiaking** [comment]
Both returning newly created object from action and the `last` method has been implemented at Vuex ORM 0.18.0 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.18.0

Thank you for the feedback! I hope this will help strip down your code a bit : )
