### ISSUE TITLE
Speed up files rows delete from vuex orm by making it in a batch process

### ISSUE THREAD

**Issue by rassokhina-e** [vuex-orm/vuex-orm#621]
I have a task to delete a bunch of files from vuex orm, but not all. Every file which I should delete looks like an object which has a general attribute `streamId` as a string. The example with using of File.deleteAll() doesn't fit. Also as an example with  File.delete(id) by using the loop, because it takes a lot of time to work with array of files. So the question is: How can we speed up files rows delete from vuex orm by making it in a batch process? Thank you for the help!

**Comment by cuebit** [comment]
Have you tried deleting by condition?

```js
const deleteByStreamId: string[] = [...]

await File.delete((file) => deleteByStreamId.includes(file.streamId))
```

**Comment by rassokhina-e** [comment]
> Have you tried deleting by condition?
> 
> ```ts
> const deleteByStreamId: string[] = [...]
> 
> await File.delete((file) => deleteByStreamId.includes(file.streamId))
> ```

Thank you for your suggestion! Sure, I've tried to use this condition:

```
let ids = this.files.map((file) => { return file.id })
await File.delete((file) => { 
  console.log('file', file)
  file.includes(file.id) 
})
```
I haven't any output data from console.log in that case.

BTW, I have the latest version of vuex orm --> "@vuex-orm/core": "^0.36.3"

**Comment by cuebit** [comment]
The condition passed to `delete` is a predicate, therefore must return a boolean.

```js
await File.delete((file) => { 
  console.log('file', file)
  return ids.includes(file.id) 
})
```

Do you get a console log now?

**Comment by rassokhina-e** [comment]
> The condition passed to `delete` is a predicate, therefore must return a boolean.
> 
> ```js
> await File.delete((file) => { 
>   console.log('file', file)
>   return ids.includes(file.id) 
> })
> ```
> 
> Do you get a console log now?

Unfortunately no, I haven't see console.log message. Do you know which other reasons can be for that issue?

**Comment by cuebit** [comment]
The only possible reason for no console log is an empty dataset.

Can you confirm the File entity has any data?

Perhaps paste the result from the following:

```js
console.log(File.query().first())
```

**Comment by rassokhina-e** [comment]
> ```js
> console.log(File.query().first())
> ```
I've just got from console.log:

<img width="786" alt="Screenshot 2020-04-17 at 20 52 48" src="https://user-images.githubusercontent.com/31901584/79599142-ad38b280-80ed-11ea-85dd-082cb1e98b95.png">

I check the rows of the files in the vuex.json file every time and they exist.
Anyway, the loop of deleting with the condition doesn't work. I haven't console.log from it.

**Comment by cuebit** [comment]
@rassokhina-e sorry this is causing your trouble. I'm struggling to see what could be stopping the library from performing a delete, as anything I can reproduce seems to execute deletes perfectly well.

Let's try another option, so we can be sure of the real issue by process of elimination. Could you execute the following?

```js
const id = File.query().first().id

await File.delete((file) => id === file.id)

console.log(`expect "${id}" to be null: ${File.find(id) === null}`)
```

Let me know the result? You should see `expect "..." to be null: null`.

**Comment by rassokhina-e** [comment]
> ```js
> const id = File.query().first().id
> 
> await File.delete((file) => id === file.id)
> 
> console.log(`expect "${id}" to be null: ${File.find(id) === null}`)
> ```

Hello! Thank you for your help! 
Two messages from console.log:
first id 3d0861a08c3f2e00b48b75031575d9f2
expect "3d0861a08c3f2e00b48b75031575d9f2" to be null: false

**Comment by rassokhina-e** [comment]
The issue with the loop of the method File.delete((file) =>... But other methods work well (insert, update, find, etc.)

**Comment by cuebit** [comment]
Oh wow. I wasn't expecting that.

Here's a [sandbox](https://codesandbox.io/s/peaceful-archimedes-ruxyi) that demonstrates conditional deletes.

Is it possible for you to fork this sandbox and attempt to reproduce your issue?

**Comment by rassokhina-e** [comment]
I've updated all dependencies from as in your package.json. Also `database`, `main`, `models` files. And I haven't a good result. The same issue with batch deleting. I have "vuex-electron": "^1.0.3" in dependencies. Perhaps, that layer is a problem for batch deleting from `vuex-orm`.

**Comment by cuebit** [comment]
@rassokhina-e now that you mention `vuex-electron` I can confirm this behaviour. It seems everything you’ve mentioned thus far is accurate. 

In Vuex ORM, both deleting by id and deleting by condition run the same mutation code. I cannot tell you why one works and the other doesn’t but I suspect it may be related to setup or the third party plugin. 

Unfortunately, the aforementioned library is no longer maintained so there’s very little to offer in terms of a solution. But I don’t envisage this to be a Vuex ORM issue at this stage of debugging. 

Sorry that I cannot be of any further assistance. If it’s of any consolation, other users of that particular library have migrated to `vuex-persistedstate`. 

Let me know if I can help with anything else.

**Comment by rassokhina-e** [comment]
When I hide createSharedMutations() plugin (vuex-electron), the batch deleting method will work (I see the loop by the condition is starting work), but in vuex.json file won't be any changes.

**Comment by rassokhina-e** [comment]
Thank you for your help. That got me knowledge, I'll continue to find the way for the batch deleting.

**Comment by rassokhina-e** [comment]
Hello! I want to share with you the result of my research on combining `vuex-orm` and `vuex-electron` for the issue above. I've figured out that the method of batch deleting with condition works well in the Main process of Electron. So I moved that function to the main process:

ipcMain.on('deleteFiles', async function (event, ids) {
    await File.delete((file) => { return ids.includes(file.id) })
    event.sender.send('filesDeleted')
  }
})

**Comment by cuebit** [comment]
Thank you so much for sharing your solution, @rassokhina-e. I’m really glad you got to the bottom of it. 👍
