### ISSUE TITLE
[Question] How can I update hasManyBy relationship?

### ISSUE THREAD

**Issue by sanjitkung** [vuex-orm/vuex-orm#622]
I am trying to update hasManyBy relationship which is not working.

Part Model
```
export default class Part extends Model {
  static fields () {
    return {
      id: this.number(null).nullable(),
      vendor_ids: this.attr(() => []),
      vendors: this.hasManyBy(Vendor, 'vendor_ids'),
    }
  }
  static entitiy = 'part'
}
```

Vendor Model
```
export default class Vendor extends Model {
  static fields () {
    return {
      id: this.string(null).nullable(),
      ven_no: this.string(null).nullable(),
      name: this.string(''),
    }
  }

    static entity = 'vendor';
}
```

I tried to update in couple ways

```
Part.update({
    where: this.part.id,
    data: (part) => {
      part.vendors = [
        ...part.vendors,
        ...result.response.data,
      ]
    },
  })

Part.update({
    where: this.part.id,
    data: {
       vendors: result.response.data
    }
  })
```
but it does not attach updated vendor to part.

I want to merge new vendors to existing part vendors.

**Comment by cuebit** [comment]
@sanjitkung, `where` cannot be used to update relational data, it only updates the data on the entity it was invoked on. See the [documentation](https://vuex-orm.org/guide/data/inserting-and-updating.html#updating-relationships) regarding this.

However, providing your response data includes primary keys for vendors, then you can simply build your update structure like so:

```js
Part.update({
  data: {
    id: this.part.id,
    vendors: result.response.data
  }
})
```

This will ensure your relations are updated too. 👍

**Comment by sanjitkung** [comment]
Thank you. That works
