### ISSUE TITLE
How to use with react

### ISSUE THREAD

**Issue by bastienrobert** [vuex-orm/vuex-orm#628]
#### Is your feature request related to a problem? Please describe...

How about a React compatibility?

#### Describe alternatives you've considered

TypeORM (not maintained), MikroORM or Prisma.

#### Additional context

Maybe we could do something cool that everybody likes?

**Comment by kiaking** [comment]
No, Vuex ORM is only for Vuex, as its name states. For react, they do already have Redux ORM 👍
