### ISSUE TITLE
belongsToMany merges duplicate entries

### ISSUE THREAD

**Issue by hako-studio** [vuex-orm/vuex-orm#629]
#### Describe the bug

I have two models with a pivot table in Laravel:
Editions <-> Contacts

There's additional data stored on the pivot, and the same location can be assigned multiple times to an artwork. However, when inserting the data into Vuex ORM you can only retrieve _one_ instance of the Contact Model.

#### Steps to reproduce the bug

Edition Model:

```js
import { Model } from '@vuex-orm/core';

export default class Edition extends Model {
    static entity   = 'App\\Artwork\\Edition';

    static fields () {
        return {
            id: this.uid(),
            locations: this.belongsToMany(Contact, ArtworkEditionLocation, 'edition_id', 'contact_id'),
        }
    }
}
```

N.B. Many fields omitted for brevity.

ArtworkEditionLocation Model:

```js
import { Model } from '@vuex-orm/core';

export default class Location extends Model {
    static entity = 'App\\Artwork\\Edition\\Location';

    static primaryKey = ['contact_id', 'edition_id'];

    static fields() {
        return {
            contact_id: this.string(),
            edition_id: this.string(),

            specific_location: this.string(null).nullable(),
            ownership_date: this.attr(null).nullable(),
            reason: this.string(null).nullable()
        }
    }
}
```

Contact Model:

```js
import { Model } from '@vuex-orm/core';

export default class Contact extends Model {
    static entity = 'App\\Contact';

    static fields() {
        return {
            id: this.uid(),
        }
    }
}
```

N.B. Many fields omitted for brevity.

#### Versions

- Vuex ORM: 0.35.2 (But tried in 0.36.3)
- Vue: 2.6.11

#### Additional Information

I'm really hoping someone's going to tell me I'm using the wrong relationship method, or that there's a simple way to achieve this.

I've tried using a triple composite key, but that didn't work. I've tried added a `id: this.uid()` to the pivot model, but that didn't work.

The data out of Laravel has multiple entries, so it's happening at the Vuex ORM step.

Any help would be massively appreciated.

**Comment by kiaking** [comment]
I think the model setup is good. Could you give us your input data you're trying to store?

**Comment by hako-studio** [comment]
@kiaking — of course, please see below:

```
{
    "id":"8ea55127-2b07-40dc-aeee-4fd70ce720f7",
    ...
    "locations":[
        {
            "id":"8e148f06-e263-41ea-a680-e928ba61961c",
            ...
            "pivot":{
                "edition_id":"8ea55127-2b07-40dc-aeee-4fd70ce720f7",
                "contact_id":"8e148f06-e263-41ea-a680-e928ba61961c",
                "specific_location":null,
                "ownership_date":"2020-06-11 11:39:00",
                "reason":null
            },
        },
        {
            "id":"8e148f06-e263-41ea-a680-e928ba61961c",
            ...
            "pivot":{
                "edition_id":"8ea55127-2b07-40dc-aeee-4fd70ce720f7",
                "contact_id":"8e148f06-e263-41ea-a680-e928ba61961c",
                "specific_location":null,
                "ownership_date":"2020-04-17 11:38:45",
                "reason":null
            },
        }
    ],
}
```

Again, I've only included the relevant information for brevity.

**Comment by kiaking** [comment]
Ah I see. Hmmm. This is tough one. Vuex ORM will merge records with the same ID, so that's the reason you're only getting one.

This is really hard to solve, because if we can't merge records with the same ID, there's no way to deduplicate the record. You need to have another primary key outside of `pivot` for now.

**Comment by kiaking** [comment]
Maybe include `specific_location` or `ownership_date`. The point is to make primary key unique somehow. `['contact_id', 'edition_id', 'id']` will not be enough since all 3 could be the same ids right?

```js
import { Model } from '@vuex-orm/core';

export default class Location extends Model {
    static entity = 'App\\Artwork\\Edition\\Location';

    // Add one more!
    static primaryKey = ['contact_id', 'edition_id', 'id', 'ownership_date'];

    static fields() {
        return {
            id: this.uid(),
            contact_id: this.string(),
            edition_id: this.string(),

            specific_location: this.string(null).nullable(),
            ownership_date: this.attr(null).nullable(),
            reason: this.string(null).nullable()
        }
    }
}
```

**Comment by hako-studio** [comment]
Thanks for the reply, I'll give it a go and report back!

**Comment by hako-studio** [comment]
I'm afraid it didn't work:

This is my new model:
```js
import { Model } from '@vuex-orm/core';

export default class Location extends Model {
    static entity = 'App\\Artwork\\Edition\\Location';

    static primaryKey = ['contact_id', 'edition_id', 'unique_id', 'ownership_date', 'specific_location'];

    static fields() {
        return {
            unique_id: this.uid(),
            contact_id: this.string(),
            edition_id: this.string(),

            specific_location: this.string(null).nullable(),
            ownership_date: this.attr(null).nullable(),
            reason: this.string(null).nullable()
        }
    }
}
```

This is a specific response:
```json
$id:"["8e165c32-9971-4803-a8e6-231ef84208d6","8f6a1036-79a9-402d-99a9-ffde2d6d7a05"]"
contact_id:"8e165c32-9971-4803-a8e6-231ef84208d6"
edition_id:"8f6a1036-79a9-402d-99a9-ffde2d6d7a05"
ownership_date:null
reason:null
specific_location:null
unique_id:"$uid12"
```
Looking at the data in the Vuex store, it seems inconsistent.
![image](https://user-images.githubusercontent.com/51338923/80817284-0eba5000-8bc9-11ea-948a-7d0beff7b65c.png)

---

If it's of any relevance, I'm retrieving the pivot as so (using pre 0.36 version of Vuex ORM)

```js
    computed: {
        pivot() {
            return Location.query().withAll().find([this.location.id, this.$route.params.id])
        }
    },
```

Which, thinking about it, could be the cause of the problems. It may be worth trying 0.36 again with this and accessing the pivot data directly. _Although_, does the `pivot` attribute get assigned on the actual models or on the pivot model?

**Comment by cuebit** [comment]
@hako-studio see #602 and #623 and see if they corroborate with the issues you're experiencing.

**Comment by hako-studio** [comment]
@cuebit There’s a possibility, although I’m using 0.35 not 0.36 and therefore having to get my pivot data myself.

**Comment by hako-studio** [comment]
@cuebit @kiaking — I don't think this is the same issue as #602 and #623, however I've resolved it (albeit in a non-Vuex ORMy way!)

```diff
++locations: this.attr(Array),
--locations: this.belongsToMany(Contact, ArtworkEditionLocation, 'edition_id', 'contact_id'),
```

I've removed the `belongsToMany` relationship and just pass in the array. In order to make the entries "reactive", I've done the following:

My Loop:
```js
<artwork-locations-location-row v-for="(location, index) in locations" :location="location" :key="`location_${ location.id }_${ index }`" />
```

"ArtworkLocationsLocationRow.vue"
```js
computed: {
    pivot() {
        return this.location.pivot;
    },
    contact() {
        return Contact.find(this.pivot.contact_id);
    }
},
```

--- 

I may re-look at this in the future, but this works for now. Thank you both for your help.

**Comment by kiaking** [comment]
Glad you found a way out 🙌 Feel free to give us any feedback if there's anything 👍
