### ISSUE TITLE
Relations not working

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#63]
Probably I'm doing something wrong, but I'm sure you know what ;)

https://jsfiddle.net/51vrmud1/1/

Generates: `TypeError: Cannot read property 'name' of null` because `user.agency` is null.

**Comment by tjsteinhaus** [comment]
@phortx On line 70 change it to this `this.users = store.getters[`entities/users/query`]().with('agency').get()` You need to tell it that you want to use the relationship in your query.

**Comment by phortx** [comment]
Oh I think, I missed that point in the docs 🙈 

Thank you very much :)
