### ISSUE TITLE
Create Method with persist option, relaton data is disappear

### ISSUE THREAD

**Issue by mean-cj** [vuex-orm/vuex-orm#632]
#### Describe the bug

Hello , 

when create data with relation (PersistOptions) 
relation data is disappear

#### Steps to reproduce the bug

**1. Define models [...]**

```js
import { Model } from '@vuex-orm/core'

class Seat extends Model {
  static entity = 'seat'
  static primaryKey = '_id'

  static fields = () => {
    return {
      _id: this.attr(null),
      name: this.attr(null),
    }
  }
}

class Order extends Model {
  static entity = 'order'
  static primaryKey = '_id'

  static fields = () => {
    return {
      _id: this.attr(null),
      seat_id: this.attr(null),
      seat: this.belongsTo(Seat, 'seat_id'),
    }
  }
}
```

**2. Create data & Retrieve data**

```js
Seat.create({ data: [
  {_id: 1, name: 'Table 1'},
  {_id: 2, name: 'Table 2'},
  {_id: 3, name: 'Table 3'},
});

// results of Seat.query().get()
Seat {$id: "1", _id: "1", name: "Table 1",}
Seat {$id: "2", _id: "2", name: "Table 2",}
Seat {$id: "3", _id: "3", name: "Table 3",}
```

**Found Problem**
```js
Order.create({ 
  data: [{_id: 100, name:"Test Order", seat_id:2, seat: { _id: 2, name:" Table 2"}}],
  insertOrUpdate: ['seat'] 
})

// results of Seat.query().get()
Seat {$id: "2", _id: "2", name: "Table 2",}
problem: data miss Table 1 and Table 3
```

```js
Order.create({ 
  data: [{_id: 100, name:"Test Order", seat_id:4, seat: { _id: 4, name:" Table 4"}}],
  insert: ['seat'] 
})

// results of Seat.query().get()
Seat {$id: "4", _id: "4", name: "Table 4",}
problem: data miss Table 1-3
```

Thank you.

#### Versions
- Vuex ORM: 0.36.3
- Vue: 2.6.11

#### Additional context
I thank  can add "excludes" option to PersistOptions
if you don't need create, insert, update to relation is better

however if relation hasMany with persist option is work,

**Comment by kiaking** [comment]
This is very weird. I'm not sure the timeline here. So you do call `Seat.create` first, then calling `Order.create`? It would be nice if you can provide some working code example for this one.

**Comment by mean-cj** [comment]
Hello @kiaking 

i found this problem with  plugin-axios 
when data have been response order with seat 
seat relation is disappear.

```
export default class Order extends Model {
  static entity = 'order'
  static primaryKey = '_id'

  static fields = () => {
    return {
      _id: this.attr(null),
      seat_id: this.attr(null),
      seat: this.belongsTo(Seat, 'seat_id'),
    }
  }
}
```

**Create Seat Data**
```
Seat.create({ data: [
  {_id: 1, name: 'Table 1'},
  {_id: 2, name: 'Table 2'},
  {_id: 3, name: 'Table 3'},
});
```

**Call Order API**
```
Order.api().post('/api/fetch', {}, {
  persistBy:'create',
  persistOptions: [{ insertOrUpdate: 'seat' }]
})
```

**response example.**
[{_id: 100, name:"Test Order", seat_id:2, seat: { _id: 2, name:" Table 2"}}],

**Result of Seat.query().get()**
Seat {$id: "2", _id: "2", name: "Table 2",}
result miss Table 1-3

I found this problem with belongsTo.

Thank you.

**Comment by cuebit** [comment]
@mean-cj `persistOptions` expects an object, as per docs. So your `create` persistence is being applied to both model and relations.

This: `persistOptions: [{ insertOrUpdate: ['seat'] }]`

Should be: `persistOptions: { insertOrUpdate: ['seat'] }`

**Comment by mean-cj** [comment]
Hello @cuebit 

I will check my code is ok , i'm sorry invalid code with my example,

Please check persist not work with belongsTo relation is miss
i think this bug on vuex-orm

Example
```
Seat.create({ data: [
  {_id: 1, name: 'Table 1'},
  {_id: 2, name: 'Table 2'},
  {_id: 3, name: 'Table 3'},
});
```

```
Order.create({ 
  data: [{_id: 100, name:"Test Order", seat_id:2, seat: { _id: 2, name:" Table 2"}}],
  insertOrUpdate: ['seat'] 
})
```

Same problem with
```
Order.api().post('/api/fetch', {}, {
  persistBy:'create',
  persistOptions: { insertOrUpdate: ['seat'] }
})
```

Result of Seat.query().get()
Seat {$id: "2", _id: "2", name: "Table 2",}

Miss Table 1 and Table 3

**Comment by cuebit** [comment]
Sorry @mean-cj, I'm unable to reproduce. Doesn't seem like a bug to me.

[See reproduction](https://l9yk2.csb.app/) using your code. Am I missing something?

**Comment by mean-cj** [comment]
Hello @cuebit 
Thank you so much for help

I fork and test your code 
now i found bug , when i use underscore (_) on entity

Please follow
https://wncpu.csb.app/
https://codesandbox.io/s/wncpu

**Comment by cuebit** [comment]
@mean-cj ahh I see now. This is still not a bug. You need to provide the entity name and not the field name for the relation you wish to control. It is [documented here](https://vuex-orm.org/guide/data/inserting-and-updating.html#insert-method-for-relationships).

```js
{
  data: [...],
  insertOrUpdate: ['merchant_seat']
}
```

**Comment by mean-cj** [comment]
Ohhhh my god, i'm apologise.

I'm misunderstand persist option for enter the field name.

Why we don't enter relation field name on persist option? 
i think it make sense better than enter entity name.

@cuebit  thank you so much : )

**Comment by cuebit** [comment]
The entity name is required because the model handles persistence. So you’re instructing your entity, or model, to persist using `insertOrUpdate`. The field just forms part of the entity schema. 

Hope that helps.

**Comment by kiaking** [comment]
I think this issue has been solved? Please feel free to open another issue if there's anything 👍
