### ISSUE TITLE
Unable to remove a relationship from a model

### ISSUE THREAD

**Issue by jpoiri** [vuex-orm/vuex-orm#634]
#### Describe the bug

There doesn't seem to be a way to remove a relationship from a model.

#### Steps to reproduce the bug

1. Define models [...]
```js
import { Model } from '@vuex-orm/core'
import axios from 'axios'
import Dependent from '@/models/Dependent'

export default class Member extends Model {
  static entity = 'members'

  static fields() {
    return {
      id: this.number(null),
      firstName: this.string(null),
      lastName: this.string(null),
      gender: this.string(null),
      bio: this.string(null),
      smoker: this.boolean().nullable(),
      birthDate: this.attr(null),
      address: this.attr(null),
      dependents: this.hasMany(Dependent, 'memberId')
    }
  }
}
```
```js
import { Model } from '@vuex-orm/core'
import Member from '@/models/Member'

export default class Dependent extends Model {
  static entity = 'dependents'

  static fields() {
    return {
      id: this.string(null),
      memberId: this.attr(''),
      firstName: this.string(null),
      lastName: this.string(null),
      gender: this.string(null),
      smoker: this.boolean().nullable(),
      birthDate: this.attr(null),
      member: this.belongsTo(Member, 'memberId')
    }
  }
}
```
2. Insert mock data
```js
Member.insert({
  data: {
    id: 99,
    firstName: 'John',
    lastName: 'Doe',
    dependents: [
      {
        id: 100,
        firstName: 'Sarah',
        lastName: 'Doe'
      },
      {
        id: 101,
        firstName: 'Jessica',
        lastName: 'Doe'
      }
    ]
  }
})
```
3. Retrieve data and check number of dependents:

```js
let member = this.query().whereId(99).with('dependents').first()
// displays 2
console.log(member.dependents.length)
```
4. Update member to have zero dependents and query back the member

```js
Member.update({
  where: 99,
  data: {
    dependents: []
  }
})

let member = this.query().whereId(99).with('dependents').first()
// displays 2 but should be 0
console.log(member.dependents.length)
```

#### Expected behaviour

Expect a way to remove relationships from a model.

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.10

**Comment by cuebit** [comment]
Thanks for reporting this, @jpoiri. Unfortunately this is not how to update relations through the parent model. [More info](https://github.com/vuex-orm/vuex-orm/issues/627#issuecomment-619623531).

This should work:
```js
Member.update({
  data: {
    id: 99
    dependents: []
  }
})
```

**Comment by jpoiri** [comment]
I tried that, doesn't seem to work. I still see all the previous relationships

**Comment by cuebit** [comment]
I stand corrected. I believe on this occasion I'm incapable of following my own advice 😄

To dissociate a _1:1_ or _1:m_ relation you will want to unset the `memberId` on the related dependents (if you wish to retain the record), or delete the dependent record itself.

1. Dissociate Dependent by Member:

```js
Dependent.update({
  where: (dep) => dep.memberId === 99,
  data: {
    memberId: null
  }
})
```

2. Or remove the Dependent:

```js
const member = Member.find(99)

member.dependents.forEach((dep) => dep.$delete())
```

The choice is yours.

**Comment by jpoiri** [comment]
OK thanks, that helps clear things up. It's possible it's the pattern I trying to implement that doesn't make sense. Basically, when page load I query the Member object with all its dependents. The UI has list of dependents with a remove button.  When I click the remove button, it removes it from the Member.dependents array after that I click save and calls the API and update Vuex after using Member.update. This seems work well until I introduce delete in the mix, I am just concern if I delete from the store before calling the API I will run into issues.

**Comment by cuebit** [comment]
That seems like the most sensible and sound approach. Keeping local state separate from your Vuex state is imperative when "queuing" instructions that depend on API communication to keep your backend and store data unified.

In that case, I don't think it's feasible to delete before the API call. Perhaps you can accumulate the Member primary keys in an array that are to be removed, and once your API call is complete you can process the deletes?

**Comment by kiaking** [comment]
@jpoiri Do you have any updates on this 👀 ?

**Comment by jpoiri** [comment]
I decided to take @cuebit suggestion and keep an array of the primary keys to delete, remove the object from the store once the API call is completed.
