### ISSUE TITLE
computed property is undefined

### ISSUE THREAD

**Issue by kaushal1976** [vuex-orm/vuex-orm#638]
Hi,
I have an issue using a where() statement in a computed property of a child component (SPA). 
<template>{{conference.title}}</template>
```javascript
<script>
import Conference from "../../store/models/conference";
export default {
  data() {
    return {
      rounded: false,
      dense: false,
      btnLarge: true
    };
  },
  methods: {
    getConference() {
        let url = '/api/v1/conferences/'+this.$route.params.conferenceId
        Conference.api().get(url, { persistBy: 'create' })
        .then(response => {

        })
        .catch(error =>{
            throw new Error('Something is wrong.')
        })
    }
  },

  watch: {
        '$route': 'getConference'
    },

  beforeMount() {
      this.getConference()
  },

  computed: {
    conference (){
        const [result] = Conference.query().where('id',$route.params.conferenceId).with('themes').get()
        return result
    },
  }
};
</script>
``` 
The above code renders computed property 'conference' as undefined. (when accessed via http://(server)/conferences/21)
However, when you hard code number 21 in place of "$route.params.conferenceId"  it works fine. Also, when I console.log( $route.params.conferenceId) it return 21. 
The API call getConference() fetch data correctly all the time
What am I doing wrong? Any help is highly appreciated. Many thanks.

**Comment by cuebit** [comment]
@kaushal1976 could you try `parseInt($route.params.conferenceId)`?

It’s likely the route parameter is cast to string (verify by console logging typeof) and the id in the store is actually an integer.

**Comment by kaushal1976** [comment]
Dear @cuebit , Many thanks. that solved it. For the life of me, I couldn't figure out what was going on. Type casting $route.params.conferenceId didn't come to my mind at all. Many thanks once again, much appreciated.

**Comment by cuebit** [comment]
@kaushal1976 not your fault, I think we need to make this clearer in the documentation. Thanks for highlighting. 👍
