### ISSUE TITLE
Accessors are not in retrieved array

### ISSUE THREAD

**Issue by j5k** [vuex-orm/vuex-orm#644]
#### Describe the bug

I defined an accessor to get some computed values. If I retrieve the data, only the defined fields are in there and no accessors. To display some data the accessors works well, but my data filtering is struggling.

#### Steps to reproduce the bug

1. Define accessor (ex. `get fullname ()` )
2. Retrieve data (ex. `let tableData = User.all()` )
3. user array don't include fullname

Here my (cutted) data filtering code:
```
let tableData = User.all()

const searchString = this.searchbox.toLowerCase()
const searchKeys = ['fullname', 'street', 'streetnumber', ... ]

tableData = tableData.filter(d => {
  return Object.keys(d)
    .filter(k => searchKeys.includes(k))
    .map(k => String(d[k]))
    .join('|')
    .toLowerCase()
    .indexOf(searchString) !== -1 || !searchString
})
```

#### Expected behaviour

Accessors should be in the retrieved array.

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.11

### Thank you!

**Comment by cuebit** [comment]
Hi @j5k, thanks for opening an issue. 

Sorry for my ignorance, not sure I understand your issue entirely. Fields are physical properties on a model but accessors are not, they are virtual properties that evaluate when read. Class getters are not enumerable unless specifically described to be, so `Object.keys` will not see them during enumeration. 

If you want to retrieve virtual properties you can use `Object.getOwnPropertyNames`.

I hope I’ve understood your issue!

**Comment by j5k** [comment]
That seems to be my problem. But even with internet research I am not able to achieve this. You got any advice?

**Comment by cuebit** [comment]
My advice, try to be more explicit for better results.

For example, you know of the fields and getters defined on a model so there's little reason to enumerate properties on an instance when you've established they will always exist (what they return is a different topic).

- Explicit property lookup resolves known properties:

  ```js
  let tableData = User.all()

  const searchString = this.searchbox.toLowerCase()
  const searchKeys = ['fullname', 'street', 'streetnumber', ...]

  tableData = tableData.filter((user) => {
    return searchKeys
      .map((key) => String(user[key]))
      .join('|')
      .toLowerCase()
      .indexOf(searchString) !== -1 || !searchString
  })
  ```

- Model method resolves lookup on a model directly:

   ```js
   // User model
   filterByKeyword(keyword) {
     const modelProps = ['fullname'].concat(Object.keys(this.$fields()))

     return (
       modelProps
         .map((prop) => String(this[prop]))
         .join('|')
         .toLowerCase()
         .indexOf(keyword) !== -1 || !keyword
     )
   }

   // Search logic
   const searchString = this.searchbox.toLowerCase()

   let tableData = User.all()

   tableData = tableData.filter((user) => user.filterByKeyword(searchString))
   ```

**Comment by j5k** [comment]
Excellent. Thank you so much!
