### ISSUE TITLE
How to mutate state and react in a component

### ISSUE THREAD

**Issue by flaviotulino** [vuex-orm/vuex-orm#646]
Hi! 
I am trying to use this brilliant ORM to store a collection and use the `state` inside a component. 
The documentation makes this example:

```
static state ()  {
    return {
      fetching: false
    }
  }
```

can be mutated with 
`.commit(state => state.fetching = true)`.

However, the change appears to not be reflected in the component where I do
```
computed: {
 fetching() {
  return User.state().fetching;
 }
}
```

Am I doing something wrong? 

When doing a console.log straight after the commit, the state does look updated (it prints out the observer reference) but I didn't manage to get it working. 

Had also a look at https://github.com/vuex-orm/vuex-orm/issues/523 but it seems to be referring to accessing the state in models rather than .vue files

Cheers!

**Comment by cuebit** [comment]
For reactivity in components, use:

```js
this.$store.state.entities.users.fetching
```

**Comment by flaviotulino** [comment]
Great thanks. We should probably make it clearer in the documentation though

**Comment by cuebit** [comment]
@flaviotulino thanks for your feedback! The docs have been updated to provide more clarity. Feel free to open a PR if you feel in a contributing mood. 👍
