### ISSUE TITLE
Documentation: Using with Nuxt store modules and their actions?

### ISSUE THREAD

**Issue by drewbaker** [vuex-orm/vuex-orm#651]
I'm trying to follow along with getting this working with a complicated Nuxt app.

I have multiple store modules (index.js, users.js, tickets.js, folders.js etc). I do all my API requests using Apollo in Store actions. I really don't like the way Vue/Nuxt Apollo wants you to handle local state, so I want to move it all to Vuex ORM.

My ideal setup would be like this:

```
    // In store/folders.js

export const actions = {
    async GET_ROOT_FOLDERS({ commit }, projectSlug) {
        const client = this.app.apolloProvider.defaultClient

        return await client
            .query({
                query: FOLDER_LIST,
                variables: {
                    directoriesFilter: {
                        parent: null,
                        project: {
                            slug: { equals: projectSlug }
                        }
                    },
                    directoryId: null
                }
            })
            .then(({ data }) => {
                const folders = _get(data, "directoriesList.items", [])

                // Ideally do Folder.insertOrUpdate({ data: folders }) here

                return folders
            })
    }
}
```

Then in my component, I'd do this:

```
    async fetch() {
        await this.$store.dispatch(
            "folders/GET_ROOT_FOLDERS",
            this.$store.state.activeProject.slug
        )
    },
```

I've been following [the Nuxt example](https://github.com/vuex-orm/vuex-orm-examples-nuxt/), but I'd love to see that with multiple store modules

I haven't been able to figure out a few things:

1.    I don't know how to use `database.register(MODEL, STORE)` with Nuxt. How do I get the STORE to pass in as second param in `@/database/index.js`
1.    How to get `Folder.insertOrUpdate({ data: folders })` working from a Store action at all?

Thanks!

**Comment by petertoth** [comment]
Hello, I'm using vuex-orm with Nuxt as well. 

1.
Following the Nuxt example, to register a vuex module altogether with a model simply pass module to the register method as well like: `database.register(Model, module)`. The second argument is not an instance of vuex store but just a plain vuex module. 

Assuming you have the same directory structure as nuxt example, it's not unseen to place model's modules altogether in the same directory like:
```js
// database.js
import Todo from '@/models/Todo.js' // this is a model
import todos from '@models/todos.js' // this is a vuex store belonging to the model

const database = new Database()
database.register(Todo, todos)

export default database
```

2. To get `Folder.insertOrUpdate({ data: folders })` working from a Store action you can simply define some action in the model's module like:
```js
// folders.js
export default {
  actions: {
    myCustomInsert({ dispatch }, folders) {
       dispatch('insertOrUpdate', { data: folders })
    }
  }
}
```
Then somewhere in your app you can just do: `$store.dispatch('entities/todos/myCustomInsert', folders)`

However there are many ways how you can interact with the store when using vuex-orm. More about using vuex modules with vuex-orm can be found here: https://vuex-orm.org/guide/digging-deeper/vuex-module.html

Hope it helps ✌️

**Comment by drewbaker** [comment]
Thanks for this @petertoth. So you recommend moving the store modules out of `@/store`? Can I keep them there? I like that because it is the "Nuxt" way. Convention over configuration!  As a Nuxt store module has no `export default` I don't know how to do it.

I'm using GraphQL on this project, and I looked hard at the the GraphQL plugin, but it doesn't seem ready for production yet. I'll save my explanation for another time.

I also have a Folder model, and a User model, like so:

```
// @/models/User.js
import { Model } from "@vuex-orm/core"

export default class User extends Model {
    static entity = "users"

    static fields() {
        return {
            id: this.uid(),
            firstName: this.string(""),
            lastName: this.string(""),
            email: this.string(""),
            company: this.string(""),
            lastPasswordChange: this.string("").nullable(),
            __typename: this.string("")
        }
    }
}
```

```
// @/models/Folder.js
import { Model } from "@vuex-orm/core"
import User from "./User"

export default class Folder extends Model {
    static entity = "folders"

    static fields() {
        return {
            id: this.uid(),
            createdAt: this.string(""),
            updatedAt: this.string(""),
            createdBy: this.belongsTo(User, "user_id"),
            user_id: this.attr(null),
            name: this.string("Untitled")
        }
    }
}
```

But I have not been able to get the Folders to come back with the Users on the `createdBy` field. I'm doing this:

```
// Computed function
        folders() {
            return Folder.query()
                .with("users")
                .get()
        }
```

And `createdBy` just comes back `null` always. What am I missing here?

**Comment by petertoth** [comment]
You can keep vuex modules anywhere you like/find suitable. Why I place models together with modules is that I reuse my models with modules among multiple applications. 
I suppose you can just import vuex module as a whole like `import * as todos from '@/store/todos'` in case of nuxt vuex modules. 

**However**, [nuxt automatically imports](https://nuxtjs.org/guide/vuex-store/#activate-the-store) all vuex modules inside `@/store/` directory. If you pass a module with your model registration like: `database.register(Todo, todos)`, vuex-orm registers the vuex module as well. So what happens is that your vuex module is being registered twice and that's probably not what you want. To avoid it, you might need to take out your model-related modules from `@/store/` directory. 

To make your example work, simply change `Folder.query().with("users").get()` to `Folder.query().with("createdBy").get()`. In vuex-orm you write queries based on exact fields definitions rather than names of entities which are in relationship between each other.

**Comment by drewbaker** [comment]
Thanks again @petertoth, super helpful. 

I was under the impression I could use my Nuxt store modules with VuexORM on top of them too, good to know that is not the way to do it! I'll create a separate store file for each model like you suggested. 

And yes, that updated query did the trick! `Folder.query().with("createdBy").get()` works great!

I was going down a rabbit hole trying to make a `user_id` field on each folder before I did `insertOrUpdate`. Was doing a lot of `folders.map()` and thinking it seemed stupid. 

I'm curious why this works, when [this documentation suggests](https://vuex-orm.org/guide/data/inserting-and-updating.html#inserting-relationships) I do need to do the `folders.map()` work to make up fields to hold my relationship IDs?

**Comment by petertoth** [comment]
It's not very well documented by your foreign keys are being attached if missing on `insert` or `create`. Not fully sure of update. 

Why the documentation example includes the foreign key is that you are inserting a new record from the model itself like:
```js
// Create Post data with its related User.
Post.insert({
  data: {
    id: 1,
    user_id: 1,
    title: 'Post title.',
    author: {
      id: 1,
      name: 'John Doe '
    }
  }
})
```
If you want your post to be associated with your user you simply need to pass the foreign key.

However you could do something like this and it will work as well:
```js
User.insert({ data: { id: 1, posts: [{ title: 'Foo' }, { title: 'Bar' }] }})
// or
User.insertOrUpdate({ data: { id: 1212, posts: [{ title: 'Foo' }, { title: 'Bar' }] }})
```
Cheers!

**Comment by cuebit** [comment]
The concept of data normalization and how Vuex ORM generates foreign keys for corresponding relations is well documented in [What is Vuex ORM](https://vuex-orm.org/guide/prologue/what-is-vuex-orm.html#how-vuex-orm-handles-data). 

It’s often the case a developer is likely to experiment with code examples before reading the manual, which is common.

Nonetheless, here-in exists an incredible community that fills the void where documentation cannot always cover it’s reach. We’re here to help!
