### ISSUE TITLE
vuex 4

### ISSUE THREAD

**Issue by jfarraraains** [vuex-orm/vuex-orm#652]
Vue 3 is coming closer and I understand that will be running on Vuex 4. Is Vuex-ORM starting to test against the future there?

**Comment by cuebit** [comment]
Sure. Vuex ORM 0.36+ continues to function well with Vue 3 and Vuex 4.

**Comment by kiaking** [comment]
Yes! It's actually working with Vuex 4 already. Please feel free to raise an issue if you find anything!

**Comment by telion2** [comment]
I really advise highlighting this fact in the documentation (I would propose the install section for that). This was nearly a reason for us to stay on Vue 2.
