### ISSUE TITLE
Question: Updating all records

### ISSUE THREAD

**Issue by mcasto** [vuex-orm/vuex-orm#658]
I have a list of project records. Each record has a boolean "selected" property. If the user selects a project in the UI, I want to specify in the data that _that_ is the project record they're working with. I can set its selected property easily with `Project.update({ where: _id_, data:{ selected:true } })` but is there a way to set all _other_ records to `selected:false`?

I tried `Project.update({ data: { selected: false } })` but it didn't work. Am I missing something in the docs? Or do I have to iterate through each Project & individually set its selected property?

**Comment by mcasto** [comment]
Well ... I wound up iterating with:

```
Project.all().forEach(project => {
     Project.update({ where: project.id, data: { selected: false } });
});
```

That's reasonably succinct, and I'm satisfied with it if there's no built-in solution, but I'm curious if there _is_ built-in functionality for this that I've missed.

**Comment by eldomagan** [comment]
You could do something like this
```javascript
Project.update({ where: () => true, data: { selected: false } })
```

**Comment by mcasto** [comment]
Oh. Right. I didn't think about using a function for the where clause. I'll give that a go. Thanks.
