### ISSUE TITLE
Type error when defining global life cycle hooks

### ISSUE THREAD

**Issue by Fnxxxxo** [vuex-orm/vuex-orm#659]
#### Describe the bug

Try to declare global life cycle hook in plugin, but fails in TS compiler.

#### Steps to reproduce the bug

Define the following plugin: 
```
import { PluginComponents } from '@vuex-orm/core'

declare module '@vuex-orm/core' {
  interface Model {
    beforeUpdate: Function
  }
}

export const plugin = {
  install(components: PluginComponents) {
    // TS2339: Property 'beforeUpdate' does not exist on type 'typeof Model'.
    components.Model.beforeUpdate = () => {

    }
  }
}
```

#### Expected behaviour

I expect it to work and all models are binded with a global update hook.

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.11

**Comment by cuebit** [comment]
You can't define a static property on an interface, at least not without properly implementing both constructor and prototype interfaces (both of which compiler checks independently).

```ts
declare module '@vuex-orm/core' {
  namespace Model {
    export function beforeUpdate(model: Model): any
  }
}
```
