### ISSUE TITLE
Empty hasMany and hasManyBy relations should return an empty array instead of null

### ISSUE THREAD

**Issue by timoschwarzer** [vuex-orm/vuex-orm#66]
Example:

There are two models: Model1 and Model2.
Model1 has an attribute with a `hasMany` or `hasManyBy` relation to Model2.

When querying a Model1 with no related Model2s, the attribute is null.
I think it should be an empty array instead to match the `find()` behavior, which returns an empty array when there are no results.

**Comment by kiaking** [comment]
Yes it should! It seems like there's a missing test 👿  Needs to fix this.

**Comment by timoschwarzer** [comment]
I'll make a PR for that if you haven't already started :wink:

**Comment by kiaking** [comment]
Wow that would be amazing! I haven't worked yet! 🚀

**Comment by kiaking** [comment]
By the way, I think this is happening somewhere in the constructor at the Model class. When "many" type relation is fetched from the store by Repo class, it should been returning empty array.

Model will set `null` to its relationship if it's not **queried** (at least that was my plan :/ ). But should keep them as empty array if user did query.

So my plan was;

```js
const user = store.getters['entities/users/find](1)

user.posts // <- Should be null

const user = store.getters['entities/users].with('posts').find(1)

user.posts // <- Should be empty array
```

P.S.
I haven't look into it so I might mistaking.

**Comment by timoschwarzer** [comment]
I use
```javascript
getters['entities/forms']().with('author').with('steps').with('target_users').with('target_groups').get()
```
and `steps`, `target_users` and `target_groups` are always `null`.

**Comment by kiaking** [comment]
Yea, it must be a bug 🙅‍♂️

**Comment by timoschwarzer** [comment]
PR: #68

**Comment by kiaking** [comment]
Hooray! Now this is possible by Vuex ORM 0.17.0! Thanks you for the amazing PR 🎉
