### ISSUE TITLE
Warning in console: "entities" was overridden 

### ISSUE THREAD

**Issue by chadwtaylor** [vuex-orm/vuex-orm#670]
#### Describe the bug

Followed the instructions to the T and am receiving a warning in the browser console: `[vuex] state field "entities" was overridden by a module with the same name at "entities".  Other than that, everything is working fine and nicely and the warning is just a slight annoyance and wondering what is causing it.

We do not have any other vuex module using 'entities' and Vuex-ORM is basically the only thing consuming that name.

<img width="734" alt="Screenshot 2020-08-06 11 54 23" src="https://user-images.githubusercontent.com/350337/89553894-1dbe2900-d7dc-11ea-8c01-5469df668a65.png">

#### Steps to reproduce the bug

No steps to reproduce as it's a matter of set-up I would presume.

#### Expected behaviour

I expected not to receive any warnings.

#### Versions

- Nuxt: 2.13.3
- Vuex ORM: 0.36.3
- Vue: 2.6.11

#### Additional context

Fantastic plug-in! Thanks for all that you do.

**Comment by cuebit** [comment]
Sounds like a setup issue unrelated to Vuex ORM.

Hard to pinpoint in the blind. Check your state export(s) in your store file(s) and make sure they're functions and not POJO. If all else fails, provide a reproducible demo. 👍 

```js
// Bad
export const state = {
  counter: 0
}

// Good
export const state = () => ({
  counter: 0
})
```

**Comment by loicmarie** [comment]
@cuebit I have this issue as well, with same versions. Stores are populated server side, but at first call of `this.$db()` the field "entities" is erased and re-populated, making getters temporarily break.
I have the same warning in the console, and in Vuex devtools, I can see "Register module: entities" client side, even though module is already registered in base state.
I have recreated a new empty project, and still have the issue, so I am not sure whether it is setup related or not.
If I have the time, I will add a minimal repro.
