### ISSUE TITLE
Inserted data missing after query

### ISSUE THREAD

**Issue by szekelyisz** [vuex-orm/vuex-orm#673]
After updating a record with a relationship I'm unable to get the newly inserted related records back.

Here's my model:

```typescript
@OrmModel('devices')
export class Device extends Model {
  @StringField('New Device')
  public name!: string;

  @PrimaryKey()
  @StringField('')
  public hostname!: string;

  @HasManyField(Output, 'deviceId')
  public outputs!: Output;
}

@OrmModel('outputs')
export default class Output extends Model {
  @PrimaryKey()
  @StringField()
  public deviceId!: string;

  @PrimaryKey()
  @NumberField()
  public outputId!: number;
}
```

My store before the operation:

```json
{
	"$name": "entities",
	"outputs": {
		"$connection": "entities",
		"$name": "outputs",
		"data": {}
	},
	"devices": {
		"$connection": "entities",
		"$name": "devices",
		"data": {
			"testhost": {
				"name": "New Device",
				"hostname": "testhost",
				"outputs": [],
				"$id": "testhost"
			}
		}
	}
}
```

Then I do

```typescript
export class Device extends Model {
  // ...
  reload() {
    // ...
        const outputs = [];
        for (let c = 0; c != reply.outputs; c++)
          outputs[c] = {
            outputId: c
          };
        this.$insertOrUpdate({
          data: {
            hostname: this.hostname,
            name: reply.name,
            outputs: outputs
          }
        })
          .then(records => {
            console.log('Promise resolved to', records);
            console.log(
              'Query returns',
              Device.query()
                .whereId(this.hostname)
                .with('outputs')
                .get()
            );
            resolve();
          })
          .catch(error => console.log(error));
  }
}
```

On the console I see:

```
Promise resolved to
{
	"outputs": [{
		"$id": "0",
		"deviceId": "",
		"outputId": 0
	}, {
		"$id": "1",
		"deviceId": "",
		"outputId": 1
	}, {
		"$id": "2",
		"deviceId": "",
		"outputId": 2
	}, {
		"$id": "3",
		"deviceId": "",
		"outputId": 3
	}, {
		"$id": "4",
		"deviceId": "",
		"outputId": 4
	}, {
		"$id": "5",
		"deviceId": "",
		"outputId": 5
	}, {
		"$id": "6",
		"deviceId": "",
		"outputId": 6
	}, {
		"$id": "7",
		"deviceId": "",
		"outputId": 7
	}],
	"devices": [{
		"$id": "testhost",
		"name": "New Device 84:0d:8e:d3:66:24",
		"hostname": "testhost",
		"outputs": []
	}]
}
Query returns
[{
	"$id": "testhost",
	"name": "New Device 84:0d:8e:d3:66:24",
	"hostname": "testhost",
	"outputs": []
}]
```

My questions are:

* Why the newly inserted `Output`s don't get their `deviceId` automatically filled? They are inserted as a result of an update on a `Device` instance, so they should inherit its primary key (the value of `hostname` field in my case).
* If I fix the above issue myself by including it in the array elements, so `outputs` is generated like this:
  ```typescript
        for (let c = 0; c != reply.outputs; c++)
          outputs[c] = {
            deviceId: this.hostname,
            outputId: c
          };
  ```
  then why does the query return the same value as before (ie. all `Output`s missing although I specifically ask Vuex-ORM to include them by calling `.with('outputs')`)? I expected that if I insert the data like this (ie. with relationships included), and then query it, I should get back the original data plus the fields filled by Vuex-ORM ($id, etc).

**Comment by cuebit** [comment]
Why do you have two primary keys on `Output`?

**Comment by szekelyisz** [comment]
> Why do you have two primary keys on `Output`?

I wanted a composite primary key.

**Comment by cuebit** [comment]
I'm not aware of a property decorator property that offers composite key definitions on models. Which is why I suspect your `deviceId` is not being set correctly. Also, if your Output model was a composite key, it wouldn't work since the `hasMany` relation doesn't support composite keys.

**Comment by szekelyisz** [comment]
OK thanks, I see. It seems like it would be easy to add composite primary key support to vuex-orm-decorators. I'm not sure if `hasMany` not supporting composite primary keys would be an issue in this case. The Device model has a simple PK so when an Output refers to it it doesn't need to store a composite PK. The other way, when a Device refers to multiple Outputs, it just looks at "half" of the composite key (the `deviceId` field) that joins the respective Output records without a problem. Although later I will need a `hasMany` relation from Output to another entity which indeed will cause a problem if Output has a composite PK.

**Comment by szekelyisz** [comment]
I changed the Output model to have a simple PK:

```typescript
@OrmModel('outputs')
export default class Output extends Model {
  @PrimaryKey()
  public id!: ReturnType<typeof Model.uid>;

  @StringField()
  public deviceId!: string;

  @NumberField()
  public outputId!: number;
}
```

I'm filling in both the `deviceId` and `outputId` fields before inserting, and the Output records get inserted correctly (`$id` generated and all), but when I query them through a Device, I get an empty array as the `outputs` field despite of `with('outputs')`:

```typescript
        const outputs = [];
        for (let c = 0; c != reply.outputs; c++)
          outputs[c] = {
            deviceId: this.hostname,
            outputId: c
          };
        this.$insertOrUpdate({
          data: {
            hostname: this.hostname,
            name: reply.name,
            outputs: outputs
          }
        })
          .then(records => {
            console.log('Promise resolved to', JSON.stringify(records));
            console.log(
              'Query returns',
              JSON.stringify(
                Device.query()
                  .whereId(this.hostname)
                  .with('outputs')
                  .get()
              )
            );
            resolve();
          })
          .catch(error => console.log(error));
```

Result:

```
Promise resolved to
{
  "outputs": [
    {
      "$id": "$uid1",
      "deviceId": "testhost",
      "outputId": 0
    },
    {
      "$id": "$uid2",
      "deviceId": "testhost",
      "outputId": 1
    },
    {
      "$id": "$uid3",
      "deviceId": "testhost",
      "outputId": 2
    },
    {
      "$id": "$uid4",
      "deviceId": "testhost",
      "outputId": 3
    },
    {
      "$id": "$uid5",
      "deviceId": "testhost",
      "outputId": 4
    },
    {
      "$id": "$uid6",
      "deviceId": "testhost",
      "outputId": 5
    },
    {
      "$id": "$uid7",
      "deviceId": "testhost",
      "outputId": 6
    },
    {
      "$id": "$uid8",
      "deviceId": "testhost",
      "outputId": 7
    }
  ],
  "devices": [
    {
      "$id": "testhost",
      "name": "New Device 84:0d:8e:d3:66:24",
      "hostname": "testhost",
      "outputs": []
    }
  ]
}
Query returns
[
  {
    "$id": "testhost",
    "name": "New Device 84:0d:8e:d3:66:24",
    "hostname": "testhost",
    "outputs": []
  }
]
```

**Comment by cuebit** [comment]
After delving into this issue a little further, I discovered the attributes by the property decorators are called on the Model constructor, not the inheriting constructor itself. So this issue actually belongs to the **[vuex-property-decorators](https://github.com/Scotley/vuex-orm-decorators/)** library, not to be mistaken as an issue with Vuex ORM.

To illustrate the problem, we can evaluate the `@HasManyField` decorator which calls the constructor method as follows:

```js
function HasManyField(related, foreignKey, localKey) {
    return Field(Model.hasMany(related, foreignKey, localKey));
}
```

When `Model.hasMany` is invoked, the relation will attempt to call `Model.localKey`, thus returning the default value of `"id"` when it should be calling `Device.localkey` and returning `"hostname"`.

Meanwhile, I would recommend manually passing the local key for the relation as a workaround:

```typescript
@OrmModel('devices')
export class Device extends Model {
  @PrimaryKey()
  @AttrField(null)
  hostname!: string

  @StringField('New Device')
  name!: string

  @HasManyField(Output, 'deviceId')
  outputs!: Output[]
}
```

**Comment by szekelyisz** [comment]
Thanks @cuebit the workaround does the job. I'll see if I can fix vuex-orm-decorators.
