### ISSUE TITLE
[QUESTION] hasManyBy with object[] instead of id[]

### ISSUE THREAD

**Issue by sebastianjung** [vuex-orm/vuex-orm#675]
i was wondering if it would be possible to create hasManyBy relations using [obj: {id: '1'}] instead of ['1'] like so

#### The models

```
import { Model } from "@vuex-orm/core";
import UserRole from "./UserRole";

export default class User extends Model {
  static entity = "users";

  static fields() {
    return {
      id: this.attr(null),
      username: this.attr(),
      userRoles: this.hasManyBy(UserRole, "userRoles")
    };
  }
}

```

```
import { Model } from "@vuex-orm/core";

export default class UserRole extends Model {
  static entity = "user-roles";

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr()
    };
  }
}
```

#### The inserted data
```
await User.insertOrUpdate({
      data: [
        {
          id: "5d5a8e1e635a8b6694dd7cb0",
          username: "sebastian",
          userRoles: [
            {
              name: "Superuser",
              uid: "superuser",
              id: "5f44c5388f1f306158b06ad0"
            }
          ]
        }
      ]
    });
```
#### The outcome

`User.all();`
-> 
```
[{
$id: "5d5a8e1e635a8b6694dd7cb0"
id: "5d5a8e1e635a8b6694dd7cb0"
userRoles: [] // <--- userRoles missing
username: "sebastian"
}]
```

#### Expected behaviour
I was thinking that i could retrieve the users with userRoles with some kind of hasManyBy relation as there are no ids on the UserRole model

#### Versions

- Vuex ORM: 0.36.3

Any help is very much appreciated

**Comment by sebastianjung** [comment]
Reading the docs carefully it seems i do not need hasManyBy when there is no foreign key on my UserRole model as missing foreign keys are automatically generated.

[https://vuex-orm.org/guide/data/inserting-and-updating.html#generating-missing-foreign-keys](https://vuex-orm.org/guide/data/inserting-and-updating.html#generating-missing-foreign-keys)

So to make this work i had to change my models to:

```
import { Model } from "@vuex-orm/core";
import UserRole from "./UserRole";

export default class User extends Model {
  static entity = "users";

  static fields() {
    return {
      id: this.attr(null),
      username: this.attr(),
      userRoles: this.hasMany(UserRole, "userId") <-- change this
    };
  }
}
```

and 

```
import { Model } from "@vuex-orm/core";

export default class UserRole extends Model {
  static entity = "user-roles";

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(),
      userId: this.attr(null) <-- and add this
    };
  }
}

```

The way I was thinking here is that as long as I do not have a foreign key on my child model i can not use hasMany which is not true.

Maybe a hint section on hasManyBy in the docs could catch people's attention and get going even quicker.


Just a thought. What do you guys think?

**Comment by cuebit** [comment]
> I was wondering if it would be possible to create hasManyBy relations using [obj: {id: '1'}] instead of ['1'] like so

The `hasManyBy` is designed to work with an array of primary keys that belong to a related model so it would not be possible to insert data in this manner. This relation type is useful when you have data for the related model that has or will be added independently.

For example:

```js
await User.insertOrUpdate({
  data: {
    id: '5d5a8e1e635a8b6694dd7cb0',
    username: 'sebastian',
    userRoles: ['5f44c5388f1f306158b06ad0']
  }
})

await UserRole.insertOrUpdate({
  data: {
    id: '5f44c5388f1f306158b06ad0',
    uid: 'superuser',
    name: 'Superuser'
  }
})
```

> The way I was thinking here is that as long as I do not have a foreign key on my child model i can not use hasMany which is not true.

The `hasMany` relation requires a foreign key to exist for a relationship to be created. However, this does not mean the foreign key needs to exist in the first instance, it can be assigned to the child model at any given time.

For example, the following will generate the missing foreign key for `userId`:

```js
await User.insertOrUpdate({
  data: {
    id: '5d5a8e1e635a8b6694dd7cb0',
    username: 'sebastian',
    userRoles: [{
      id: '5f44c5388f1f306158b06ad0',
      name: 'Superuser'
    }]
  }
})

/*
--- entities/user-roles ---
{
  '5f44c5388f1f306158b06ad0': {
    id: '5f44c5388f1f306158b06ad0',
    name: 'Superuser',
    userId: '5d5a8e1e635a8b6694dd7cb0'
  }
}
*/
```

The drawback of a `hasMany` in this instance is that _Superuser_ can only exist for a single _User_. In other words, _User_'s cannot share the same _Role_.

 If you want a _Role_ to belong to one _User_ or more, a `belongsToMany` is likely your best bet.

> Maybe a hint section on hasManyBy in the docs could catch people's attention and get going even quicker.

What hint are you referring to?

**Comment by sebastianjung** [comment]
@cuebit 
Thank you very much for your quick and detailed response.

I think i'm beginning to understand how things are working.

So hasManyBy does not make sense here because at the time the data is normalized there is no userRoles[id] on my User model (and never has been, to be exact). Thanks for the clarification!


> If you want a Role to belong to one User or more, a belongsToMany is likely your best bet.

This is indeed what i came up with. Thanks!

So what i ended up with is:

#### User.js

```
import { Model } from "@vuex-orm/core";
import Role from "./Role";
import RoleUser from "./RoleUser";

export default class User extends Model {
  static entity = "users";

  static fields() {
    return {
      id: this.attr(null),
      username: this.attr(),
      userRoles: this.belongsToMany(Role, RoleUser, "userId", "roleId")
    };
  }
}
```

#### Role.js

```
import { Model } from "@vuex-orm/core";
import User from "./User";
import RoleUser from "./RoleUser";

export default class Role extends Model {
  static entity = "user-roles";

  static fields() {
    return {
      id: this.uid(null),
      uid: this.string(),
      name: this.string(),
      users: this.belongsToMany(User, RoleUser, "roleId", "userId")
    };
  }
}

```

#### RoleUser.js (pivot)

```
import { Model } from "@vuex-orm/core";

export default class RoleUser extends Model {
  static entity = "role-user-pivot";

  static primaryKey = ["roleId", "userId"];

  static fields() {
    return {
      roleId: this.attr(null),
      userId: this.attr(null)
    };
  }
}
```


> What hint are you referring to?

I was suprised to find the information about automatic generation of foreign keys at the "inserting and updating"-section of the docs.
[https://vuex-orm.org/guide/data/inserting-and-updating.html#generating-missing-foreign-keys](https://vuex-orm.org/guide/data/inserting-and-updating.html#generating-missing-foreign-keys
)
I thought this piece of information might be useful inside the 'relationship'-section. At least for me it would have been.
[https://vuex-orm.org/guide/model/relationships.html](https://vuex-orm.org/guide/model/relationships.html)

As this applies to all relations it makes sense to not put it inside on category but maybe before or after all of them like so:
![image](https://user-images.githubusercontent.com/17472892/91228676-f39bbf00-e728-11ea-94e5-1dd1b0bf1f69.png)

And with hint i mean a tip custom block like this one:
![image](https://user-images.githubusercontent.com/17472892/91228984-6e64da00-e729-11ea-8199-0a692f06cd2e.png)


Not sure. What do you think?

Thanks for your help again!

**Comment by cuebit** [comment]
Great! Seems like you're finding your feet. Best of luck!

In regards to the hint, there are often cases where the community has raised concerns about the existence of valuable information in more appealing places (such as what you've described), and we aim to resolve this by improving the documentation now and again.

In the same breath, the topic of missing foreign keys is covered in the prologue (most people skip the library concept and jump to the code) but also it's appropriately placed within _Inserting and Updating_ since this is a relevant category for it to exist in. The _Relationships_ section, however, simply touches on the topic of relations and how Vuex ORM caters for the varying types supported – and avoids delving into the mechanics of the relationships when handling its data.

The [@next](/vuex-orm/vuex-orm-next) iteration of the library aims to solve a lot of documentation woes. If anything, we would welcome all contributions over there!

👍
