### ISSUE TITLE
this context in getters results in eslint en IDE errors

### ISSUE THREAD

**Issue by gijsmooren** [vuex-orm/vuex-orm#678]
Hi all,

I am wondering if I am the only one running into this issue. When I define a getter in a model I get linting errors when calling attributes defined in the static fields method. I understand this is 'normal' behaviour when a property is not defined. However in the example [Accessors](https://vuex-orm.org/guide/model/accessors-and-mutators.html#defining-accessors) nothing is mentioned about calling these properties in respect to eslint.

```
get prefixedName() {
    return '_' + this.name; // throws an error that the property 'name' does not exist on type 'Model'
}
```

I have a workaround for now:

```
get prefixedName() {
    return '_' + this.getAttribute('name');
}

protected getAttribute(attribute: string): any {
    const context: any = this;

    return context[attribute];
}
```

I am curious how you guys resolved this.

**Comment by cuebit** [comment]
I see you're using TS. Have you declared the properties on the class at least?

Example:

```typescript
class User extends Model {
  static entity = 'users'

  static fields(): Record<string, any> {
    return {
      id: this.attr(null),
      name: this.string('')
    }
  }

  id!: number
  name!: string

  get prefixedName(): string {
    return `_${this.name}`
  }
}
```

**Comment by gijsmooren** [comment]
Thank you Cuebit. I was not sure if it was possible without declaring the properties in the class as it feels like a redundant step.
