### ISSUE TITLE
Problems with fetching parent in afterDelete from child in a hasMany relation

### ISSUE THREAD

**Issue by fractalf** [vuex-orm/vuex-orm#679]
I'm trying to delete the parent if all its children are deleted, but just doesnt seem to be working.
Things seems to be loaded (see screenshot below), but in the hook `afterDelete` it's just not there.

Shouldn't this work? Bug og just me using this incorrectly?

Example models
```js
export default class Project extends Model {
    static fields () {
        return {
            id: this.number(),
            status: this.string(''),
            tasks: this.hasMany(Task, 'project_id'),
        }
    }
}
Project.entity = 'project'
```
```js
export default class Task extends Model {
    static fields () {
        return {
            id: this.number(),
            project_id: this.number(),
            name: this.string(''),
            project: this.belongsTo(Project, 'project_id')

        }
    }
    static afterDelete (model) {
        if (model.project.tasks.length === 0) {
            model.project.$delete()
        }
    }
}
Task.entity = 'task'
```
**in afterDelete `model.project` is null**

This is how I fetch the projects data and make a loop through all the projects with its tasks
```js
        computed: {
            projects() {
                return Project.query()
                    .with('tasks.project.tasks')
                    .get()
            }
        },
```

It **seems** to be working when looking at the Task component in dev tools (I can see that the Task model has a link to its parent project.

![image](https://user-images.githubusercontent.com/5707457/92210423-f9af3f80-ee8e-11ea-81f9-ce52d4655193.png)

PS. I know I can get the project by doing `Project.find(model.project_id)` but that kind of feels like double up

**Comment by cuebit** [comment]
The `afterDelete` hook only receives the model record, without its relations. Hence why `model.project` is null and void.

If you want to handle relations inside CRUD hooks, with the exception of select hooks, you will need to query the store. So a "double up" cannot be avoided in this instance.

**Comment by fractalf** [comment]
@cuebit ok thanks for the info!  :+1: 

I'll close this issue then..
