### ISSUE TITLE
Empty result set when filtering instances with where() by id

### ISSUE THREAD

**Issue by dappiu** [vuex-orm/vuex-orm#683]
I obtain the correct list of instances if I do this:
```js
// Working
MyModel.query().where('slug', (slug) => slug !== 'some-slug').get()
```
But I always get a empty list if I replace `'slug'` with `'id'`
```js
// Not working
MyModel.query().where('id', (id) => id !== 1).get()
```
I tried logging inside the closure but it seems that the evaluation function has never been called. No errors either.

To walk around the issue I ended up doing
```js
// Working
MyModel.query().where((instance) => instance.id !== 1).get()
```
which works as intended!

I hope I'm not missing something trivial here, otherwise it may be a bug.

Edit: I forgot to say that my model declares a numeric field named solely `id`
```js
static fields() {
    return {
      id: this.number(null),
      // ...
    }
}
```
Edit 2: I also forgot to say that I'm using version 0.36.3

**Comment by cuebit** [comment]
Correct. You cannot use closures in a where clause that inspects a primary key. The moment you supply a primary key as a property lookup, Vuex ORM will take the given value as a direct key lookup – in this case a closure would be an invalid value. Something that needs to be made clear in the docs. 👍

**Comment by bestickley** [comment]
Adding this to the docs would be very helpful.
