### ISSUE TITLE
Can't define relationships by name instead of by model

### ISSUE THREAD

**Issue by IAmJulianAcosta** [vuex-orm/vuex-orm#684]
#### Describe the bug

In order to initialize some relationships and avoid circular references when classes are in different files, I had to use names instead of models.

When trying to get the model by its name, [this](github.com/vuex-orm/vuex-orm/blob/c21b5107e1f7791d5aeaad218ba17b84fe93e15f/src/model/Model.ts#L348-L350) method is called

By the time it is called, Container.store is undefined

#### Steps to reproduce the bug

1. Define a relationship using model name instead of class. Example:

```
  user: this.belongsTo('users', 'user_id'),
```

2. Register the model
3. `Uncaught TypeError: Cannot read property '$db' of undefined`. 

#### Expected behaviour

No error

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.12

#### Additional context

If the models are registered before registering the store, this problem occurs. If the models are registered **after** registering the store, when the relations are being defined, it causes a circular dependency problem as model X is requiring model Y, but model Y is still not registered

`[Vuex ORM] Could not find the model `users`. Please check if you have registered the model to the database.`

**Comment by cuebit** [comment]
I don't follow. How are you attempting to retrieve a model name? Could you demonstrate your model setup and what it is your actually doing that produces the error?

**Comment by IAmJulianAcosta** [comment]
Hi @cuebit, here you can find a repro:

store.js
```
import Vue from 'vue'
import Vuex from 'vuex'
import VuexORM from "@vuex-orm/core";
import { Model } from '@vuex-orm/core'

Vue.use(Vuex);

class Post extends Model {
  static entity = 'posts'

  static fields () {
    return {
      id: this.attr(null),
      title: this.attr(''),
      body: this.attr(''),
      comments: this.hasMany('comment', 'post_id'),
    }
  }
}

class Comment extends Model {
  static entity = 'comments'

  static fields () {
    return {
      id: this.attr(null),
      post_id: this.attr(null),
      body: this.attr(''),
      post: this.hasOne('post'),
    }
  }
}

const database = new VuexORM.Database();

database.register(Post);
database.register(Comment)


const store = new Vuex.Store({
  plugins: [VuexORM.install(database)],
  state: {
    count: 0
  },
  mutations: {
    increment (state) {
      state.count++
    }
  }
})

export default store;
```

**Comment by cuebit** [comment]
When using strings to reference models you should be using the entity value of the model. 

```
// Post
{
  comments: this.hasMany('comments', 'post_id'),
}

// Comment
{
  post: this.hasOne('posts'),
}
```

**Comment by IAmJulianAcosta** [comment]
@cuebit I don't think that is the problem (what you said was wrong, but not causing the bug).

It took me a couple of hours to get to a minimal repro, but here it is: https://github.com/IAmJulianAcosta/vuex-orm-repro

What I think that is happening:

When calling `comments: this.hasMany(Comment, 'post_id'),` `Comment` class for some reason is not getting the value for `store` defined: [here](https://github.com/vuex-orm/vuex-orm/blob/master/src/database/Database.ts#L211_L213), but instead is getting its [original one](https://github.com/vuex-orm/vuex-orm/blob/master/src/model/Model.ts#L348-L350), causing it to fail.

So I think that happens when: 

1. Parent -> hasMany(SiblingClass)
2. Sibling -> hasMany('entity')

**Comment by cuebit** [comment]
There is an underlying issue that causes problems when you mix entity strings and model classes. There are 3 solutions to your problem:

1. Use model classes consistently e.g. `this.hasOne(Comment, ...), this.hasMany(Like, ...)`
2. Use string values consistently i.e. `this.hasOne('comments'), this.hasMany('likes', ...)`
3. Order your model registration according to the order in which your relation schema exists, e.g.:
   ```js
   // 👎 
   database.register(Post)
   database.register(Comment)
   database.register(Like)

   // 👍 
   database.register(Like)
   database.register(Comment)
   database.register(Post)
   ```

**Comment by IAmJulianAcosta** [comment]
@cuebit thank you, in the end I used classes everywhere, just wanted to report what was going on, thanks for the help 👍
