### ISSUE TITLE
How to add a record to a many to many relationship?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [vuex-orm/vuex-orm#686]
I'm following the example in the docs:

```
class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.attr(null),
      roles: this.belongsToMany(Role, RoleUser, 'user_id', 'role_id')
    }
  }
}

class Role extends Model {
  static entity = 'roles'

  static fields () {
    return {
      id: this.attr(null)
    }
  }
}

class RoleUser extends Model {
  static entity = 'roleUser'

  static primaryKey = ['role_id', 'user_id']

  static fields () {
    return {
      role_id: this.attr(null),
      user_id: this.attr(null)
    }
  }
}
```

And I need to create a new role and add it to `user.roles`, I tried `User.update(1, roles: [...user.roles, newRole])`, but the user is never changed. Inserting works fine, with the `pivot` field, but I cannot find a way to make the relationship to update.

Any help o n this would be helpful

**Comment by cuebit** [comment]
To give you a low level explanation, the `update` method handles existing data, and inherently any existing relations. It does not generate new relations without being instructed to do so.

The following syntax you are using is also incorrect: 

```js
User.update(1, roles: [...user.roles, newRole]) // <-- invalid
```

The following would be the correct syntax:

```js

User.update({
  where: 1,
  data: {
    id: 1,
    roles: [newRole]
  },
  insertOrUpdate: ['roles'] // <-- this is the model entity, not to be confused with the field name
})
```

Note, when updating, you need not spread existing relations (i.e. `[...user.roles, newRole]`) unless you use the `create` for the relationship handler.

Checkout [Insert Method for Relationships](https://vuex-orm.org/guide/data/inserting-and-updating.html#insert-method-for-relationships) in the docs for more info.

**Comment by IAmJulianAcosta** [comment]
@cuebit thanks for the help, just to clarify, do I need to include the `where`?

Looks like when no [condition is present](https://github.com/vuex-orm/vuex-orm/blob/master/src/query/Query.ts#L896-L898), or [data is an array](https://github.com/vuex-orm/vuex-orm/blob/8002617130bd2d5fe42a9c248a6ca163ca030b02/src/query/Query.ts#L863-L865) the 'insertOrUpdate' is executed:

**Comment by cuebit** [comment]
To generate new relations, yes, you'll need the payload to be an object consisting of where, data and persist options, rather than a two-param invocation.
