### ISSUE TITLE
Question: entity dispatch with typescript

### ISSUE THREAD

**Issue by akadlec** [vuex-orm/vuex-orm#690]
Hi all,
I'm using vuex orm and it is great. But right now, I don't know if there is a way how to define types for dispatch methods. I have something like this:

```
        EntityName.dispatch('edit', {
          id: entityId,
          data: updateDataObject,
        })
```

so type check is not processed on this piece of code

**Comment by cuebit** [comment]
`data` can be any record(s), so there is no type-checking at this time. If you really want payload validity, at minimum, create a method on the model that conforms to a type, for example:

```ts
static edit(id: number, data: SomeType) {
  this.dispatch('edit', { id, data })
}
```

If you got any further questions, head over to the Slack channel.
