### ISSUE TITLE
No shared state across components using SSR syntax ($store.$db().model())

### ISSUE THREAD

**Issue by rigibore-charlie** [vuex-orm/vuex-orm#695]
I'm having a strange issue with the SSR syntax since switching from the ES6 static import syntax.  My components each seem to be accessing a different instance of the store bizarrely, see very simplified example: 

QuoteList (parent):
```javascript
computed: {
  Quote() {
    return this.$store.$db().model('quotes');
  },
},
mounted() {
  this.Quote.insertOrUpdate({
    data: {
      name: 'test1',
      company_id: 555,
    }
  });

  const records = this.Quote().all();
  console.log(records); // [{ name: 'test1', company_id: 555 }]
}
```

Quote (child):
```javascript
computed: {
  Quote() {
    return this.$store.$db().model('quotes');
  },
},
mounted() {
  console.log(this.Quote.all()); // [] (EMPTY)
}
```

Is this intended for the SSR way?  Seems to defeat the object of using Vuex in the first place.

Using within Quasar framework.  All dependencies up to date.

**Comment by cuebit** [comment]
This is a duplicate of #694. Which do you want to keep?

**Comment by rigibore-charlie** [comment]
> This is a duplicate of #694. Which do you want to keep?

Apologies, I got a 404 on submit so assumed it hadn't sent, have closed the other issue.

**Comment by rigibore-charlie** [comment]
The code above is obviously very simplified, in reality it's a large scale app with 20+ models but it's happening in numerous places.

This particular example is basically a data table with 50 rows (aka QuoteList), each row clickable which brings up the child (actually a spawned dialog) with the singular information for the row.

I've added some logging to demo this, but you can see things are loaded in the right order and populated correctly etc.  Is there anything I can log which could identify a given instance of a database/store?

![Console logging](https://i.imgur.com/g4l1mzS.jpg)

**Comment by rigibore-charlie** [comment]
This was caused by exporting the store as a function in Quasar framework as opposed to exporting the store itself, nothing to do with using the SSR syntax, sorry for the inconvenience.
