### ISSUE TITLE
Question: Retrieving posts that either don't have comments or comments from user_id=1 

### ISSUE THREAD

**Issue by stop-start** [vuex-orm/vuex-orm#696]
Following the examples from the doc, let's say that I want to retrieve posts that don't have any comments or that have comments from `user_id==1`.

Basically joining those two queries:
```
// Retrieve all posts that don't have comments.
Post.query().hasNot('comments').get()

// Retrieve all posts that have comments with user_id==1.
Post.query().whereHas('comments', (query) => {
  query.where('user_id', 1)
}).get()
```
 
I would like to be able to join those so I can apply `orderBy()` on the joined query.
Is there a way to achieve what I want?

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.11

**Comment by cuebit** [comment]
Unfortunately, Vuex ORM does not _join_ queries, however, it can apply constraints to queries to narrow the results where applicable.

In your case, this might be a little tricky where a join is necessary. You'd have to run two parallel queries, merge them into a single array and then apply a sort on the resulting array.

For example:
```js
posts() {
  const posts = [].concat(
    Post.query().hasNot('comments').get(),
    Post.query().whereHas('comments', (query) => { query.where('user_id', 1) }).get()
  )

  return posts.sort((a, b) => (a.id.localeCompare(b.id)))
}
```

Hope this gives you some insight.

If you have any further questions, consider joining the Vuex ORM [Slack channel](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTc1YTI2N2FjMGRlNGNmMzBkMGZlMmYxOTgzYzkzZDM2OTQ3OGExZDRkN2FmMGQ1MGJlOWM1NjU0MmRiN2VhYzQ) 👍
