### ISSUE TITLE
getters['entity/myEntity/query']().get() returns all entities as instances of myEntity

### ISSUE THREAD

**Issue by skilltryck** [vuex-orm/vuex-orm#70]
Sorry for the cryptic title.

I have a few models.
In total they have 18 different entities as of now.
One model "myEntity" only has 2 entities right now.

If I call `getter['entities/myEntity/query']().get()` I get a return of 18 entities, all forced into the format of myEntity, and therefore they have ID:s and other fields that overlap, but the other fields are null.

Is it me doing something wrong or has anyone else seen this?

**Comment by kiaking** [comment]
Hi! Thanks for the feedback.

Maybe you have same `static entity` value in different models? Not sure. Could you paste your Model definition of "myEntity"?

**Comment by skilltryck** [comment]
Sure, here are two of my definitions:
```
import { Model } from '@vuex-orm/core'

export default class sOption extends Model
{
  static entity = 'sOptions'

  static fields () {
    return {
      id: this.attr(null),
      token: this.attr(''),
      value: this.attr(''),
      version: this.attr(null),
      type: this.attr(''),
      scope: this.attr('')
    }
  }
}
```
```
import { Model } from '@vuex-orm/core'

export default class sUser extends Model
{
  static entity = 'sUsers'

  static fields () {
    return {
      id: this.attr(null),
      username: this.attr(''),
      salt: this.attr(''),
      password: this.attr(''),
      is_active: this.attr(null),
      is_superadmin: this.attr(null),
      name: this.attr(''),
      email: this.attr(''),
      last_login: this.attr('')
    }
  }
}
```

**Comment by kiaking** [comment]
Thank you for the code! The models look just fine. OK, now I'm having trouble understanding your issue here. Is it possible for you to paste the data inside state before you try to fetch data? Inside the store, it should look something like this.

```js
{
  entities: {
    sOptions: {
      data: {
        '1': { id: 1, token: ... },
        '2': { id: 2, token: ... }
      }
    },
    sUsers: {
      data: {
        '1': { id: 1, username: ... },
        '2': { id: 2, username: ... }
      }
    }
  }
}
```

If you have above structure inside your store, and if you call `getters['entity/sUsers/query']().get()`, then you should only get `sUsers` data.

**Comment by timoschwarzer** [comment]
Can you show us the code where you register the models with vuex-orm?

**Comment by timoschwarzer** [comment]
For me, this sounds like you have inserted/created data into the wrong model pool somewhere.
E.g. you wrote `myOption/insert` somewhere where it should be `sthElse/insert`.

**Comment by kiaking** [comment]
@skilltryck I'll close this issue due to inactivity. Please feel free to reopen it if you still having trouble! Thanks!
