### ISSUE TITLE
Model Relations not Linking to one another

### ISSUE THREAD

**Issue by SpedNSFW** [vuex-orm/vuex-orm#701]
#### Describe the bug

Models with defined relations are not linking to one another in a way that provides access to the linked model, however related model IDs are being populated.

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.12

#### Additional context

I started working with Vuex-ORM for the first time and I'm having issues with some simple stuff. I have three models (see below) that are all related to each other in some way. In the last code block below, I have inserted everything just for testing purposes.

Looking in the Vue devtools, I can see that each model is being added successfully however they aren't linking. For example, the Page model will have the correct `author_id` however `author` will be null. Also with the Page model, as well as the Component models, all the `components` fields are empty arrays but the `parent_id` is always correct.

As far as I can see from following the official documentation, I am doing everything correctly. Can someone please explain to me where I am going wrong and how I can resolve my issues.

Thank you.

```js
export default class User extends Model {
  static entity = 'users';

  static fields() {
    return {
      id: this.uid(),
      username: this.string(null),
      email: this.string(null)
    };
  }
}
```

```typescript
export default class Page extends Model {
  static entity = 'pages';

  static fields() {
    return {
      id: this.uid(),
      title: this.string(null).nullable(),
      author_id: this.attr(null),
      author: this.belongsTo(User, 'author_id'),
      components: this.hasMany(Component, 'parent_id')
    };
  }
}

```

```js
export default class Component extends Model {
  static entity = 'components';

  static fields() {
    return {
      id: this.uid(),
      parent_id: this.attr(null),
      type: this.string(null),
      components: this.hasMany(Component, 'parent_id')
    };
  }
}

```

```js
beforeMount() {
  Page.insert({
    data: [
      {
        title: 'Example Page',
        author: {
          username: 'exampleUser',
          email: 'example@example.com'
        },
        components: [
          {
            type: 'row',
            components: [
              { type: 'heading' }
            ]
          },
          {
            type: 'row',
            components: [
              { type: 'text' },
              { type: 'image' }
            ]
          }
        ]
      }
    ]
  });
}
```

**Comment by cuebit** [comment]
> As far as I can see from following the official documentation, I am doing everything correctly. Can someone please explain to me where I am going wrong and how I can resolve my issues.

You're doing everything by the book. Looks good.

> Looking in the Vue devtools, I can see that each model is being added successfully however they aren't linking. For example, the Page model will have the correct author_id however author will be null. Also with the Page model, as well as the Component models, all the components fields are empty arrays but the parent_id is always correct.

This is your issue. You're looking for something that doesn't exist.

Records are stored in their respective entity module. When a `Page` is inserted, the data is normalized, all relations are extracted and stored in their respective entity module. The primary key from `pages` will serve as foreign keys for those relations. The relation fields are left as `null` or `[]` (depending on the type of relation used) in the store since the relation is generated when you query a model.

For example, `Page.query().with('author').get()` will load all pages with their respective authors.

Hope this helps.

**Comment by SpedNSFW** [comment]
That helps a lot @cuebit. It seems the `#with` method was all I was missing and `#withAllRecursive` fits my needs perfectly.

**Comment by cuebit** [comment]
@SpedNSFW Great! If you have any further question, consider heading over to the Slack channel. Heaps of help there.

Happy coding!
