### ISSUE TITLE
Please provide an example of vuex-orm in combination with the new composition API

### ISSUE THREAD

**Issue by dschreij** [vuex-orm/vuex-orm#704]
#### Is your feature request related to a problem? Please describe...

The composition API is an increasingly popular method for defining components for both Vue 2 and 3. Yet there are little to no examples to be found online of how to use Vuex ORM in this new way of defining components, especially in combination with TypeScript. Even though the transition should be relatively simple, there are some peculiarities I am bumping into.

#### Describe the solution you'd like

An example of how to use Vuex ORM in a composition API/TypeScript project, in analogy to https://github.com/vuex-orm/vuex-orm-examples-ts.

#### Describe alternatives you've considered

I have tried finding examples through Google search, but there is suprisingly little to be found on this topic.

#### Additional context

In particular, I'd like to know how to use Vuex ORM with the new 'wrapper functions' of the VCA. For instance, I am trying to get a single instance from a model:

```ts
import { Model } from '@vuex-orm/core'
import User from '~/models/user'
import Shipment from '~/models/shipment'

export default class Inquiry extends Model {
  static entity = 'inquiry'

  static fields () {
    return {
      id: this.number(0),
      created_at: this.attr(''),
      updated_at: this.attr(''),
      deleted_at: this.attr(null),
      status: this.string(''),
      user_id: this.number(0),
      user: this.belongsTo(User, 'user_id'),
      shipment_id: this.number(0),
      shipment: this.belongsTo(Shipment, 'shipment_id')
    }
  }

  // Type annotations
  id!: number
  created_at!: string
  updated_at!: string
  deleted_at!: string
  status!: string
  user_id!: number
  user!: User
  shipment_id!: number
  shipment!: Shipment
}
```

```ts
export default defineComponent({
  setup (_, { root: { $route } }) {
    const { id } = $route.params
    const inquiry = computed(() => Inquiry.query()
      .with('shipment.origin|destination')
      .find(id))
    console.log(inquiry.shipment.description)
  }
}
```
However, the console.log statements causes a TypeScript error 

```ts
Property 'shipment' does not exist on type 'ComputedRef<Item<Inquiry>>'.
```

even though it is properly defined on the model. Since a queried item used to be defined in the options API as

```ts
export default {
  computed: {
    inquiry () {
      return Inquiry.query()
        .with('shipment.origin|destination')
        .find(id))
      }
   }
}
```

I would assume the query call has to be wrapped in a `computed()` function when using the composition API, yet this results in the error above. If you don't wrap the call in `computed()`, then TypeScript does not complain, but I wonder if reactivity is lost then, or if it is internally provided by vuex-orm?

I also tried a type conversion:

```ts
 const inquiry = computed(() => Inquiry.query()
      .with('shipment.origin|destination')
      .find(id)) as Item<Inquiry>
```
but that results in another error:

```
Conversion of type 'ComputedRef<Item<Inquiry>>' to type 'Item<Inquiry>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'ComputedRef<Item<Inquiry>>' is missing the following properties from type 'Inquiry': id, created_at, updated_at, deleted_at, and 35 more.
```

It would be nice to have some conventional examples of how vuex-orm should be used in combination with the composition API.

**Comment by dschreij** [comment]
Alright, I must have had a temporary lapse of thinking for a moment, because of course it needs to be
```ts
console.log(inquiry.value.shipment.description)
```
when you work with computed variables in the composition API.

Regardless, an example of vuex-orm in the Vue composition API and TypeScript would be a nice example. What do you think?

**Comment by cuebit** [comment]
This is more Vue related than it is Vuex ORM. Any ref, reactive and computed values need to be unwrapped. That is something we may describe in documentation once VCA becomes the norm but as it stands it is mostly unrelated.
