### ISSUE TITLE
question : use Vuex-orm with direct download installation

### ISSUE THREAD

**Issue by pat123456** [vuex-orm/vuex-orm#711]
Hello,
I would like to use vuex-orm in minimalist html/js project (without webpack, vite...etc) but can't figure out how to start with the "direct download" installation method. How to import the Model class from "<script src="https://unpkg.com/@vuex-orm/core"></script>" and extends it... etc. Could you provide a simple example to start with ? there is nothing in the official documentation.

**Comment by cuebit** [comment]
Vuex ORM is exposed on the `window.VuexORM` global variable.

You can extend your class models like so:
```js
class User extends VuexORM.Model {
  static entity = 'users'
  
  static fields() { ... }
}
```

Register your models to a `Database` instance and install VuexORM as a Vuex plugin:

```js
const database = new VuexORM.Database()
database.register(User)

const store = new Vuex.Store({
  plugins: [VuexORM.install(database)]
})
```

<details>
  <summary>Example HTML</summary>
  
  ```html
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/vuex"></script>
    <script src="https://unpkg.com/@vuex-orm/core"></script>
  </head>
  <body>
    <div id="app" v-cloak>
      <pre>{{ users }}</pre>
    </div>
    
    <script>
      Vue.use(Vuex)
  
      class User extends VuexORM.Model {
        static entity = 'users'
  
        static fields() {
          return {
            id: this.uid(),
            name: this.string('')
          }
        }
      }
  
      const database = new VuexORM.Database()
      database.register(User)
  
      const store = new Vuex.Store({
        plugins: [VuexORM.install(database)]
      })
  
      new Vue({
        el: '#app',
        data: {
          saved: null
        },
        computed: {
          users() {
            return User.all()
          }
        },
        created() {
          User.insert({ data: { name: 'John Doe' } })
        }
      })
    </script>
  </body>
  </html>
  ```
  
</details>

Hope this helps.

**Comment by cuebit** [comment]
If you have any further questions, consider joining the Vuex ORM [Slack channel](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTc1YTI2N2FjMGRlNGNmMzBkMGZlMmYxOTgzYzkzZDM2OTQ3OGExZDRkN2FmMGQ1MGJlOWM1NjU0MmRiN2VhYzQ) 👍

**Comment by pat123456** [comment]
Hi, thank a lot for your very simple and complete explanation ! May should be added to the documentation ?
