### ISSUE TITLE
Getting entity name in production environment

### ISSUE THREAD

**Issue by chadwtaylor** [vuex-orm/vuex-orm#712]
In production mode, the model's `constructor.name` becomes obfuscated and that's a good thing. However, I need to access the name of the entity.

Looking through the docs, I don't see a clear example on how to do it but I managed to do it this way (although I'm pretty sure there's a better way to access it):

`object.$fields().id.model.entity`

I'm curious about a better way to access the name of the entity if any?

**Comment by cuebit** [comment]
Assuming `object` is a model instance, you can access the constructor through `object.$self()` therefore having access to any constructor methods/properties including the entity string. 

```js
object.$self().entity // string
```

**Comment by chadwtaylor** [comment]
@cuebit Thanks so much, that worked -- definitely much better and simpler. :)
