### ISSUE TITLE
multiple namespaces

### ISSUE THREAD

**Issue by rbayley** [vuex-orm/vuex-orm#713]
Hi,

Is it possible to add multiple namespaces?

```
const database = new VuexORM.Database();

database.register(ModelA);
database.register(ModelB);

VuexORM.install(database, {"namespace" : "db1"});
-----------------
const database = new VuexORM.Database();

database.register(ModelC);
database.register(ModelD);

VuexORM.install(database, {"namespace" : "db2"});

```
This will be registered properly but, when
`ModelA.insertOrUpdate( {data: response.data} )`
then I will get 
`[vuex] unknown action type: db1/modelA/insertOrUpdate`

It seems its not using the proper module.

Maybe I am doing something wrong.

Any idea how to fix or sort out this issue?

warm regards

**Comment by charlie430** [comment]
Issue #515 may help provide more information on this issue.

**Comment by cuebit** [comment]
Yup, that's the best place for future reference. Closing this for now.
