### ISSUE TITLE
Massive performance decrease with a large set of models registered

### ISSUE THREAD

**Issue by ntma** [vuex-orm/vuex-orm#717]
#### Describe the bug

The overall performance of this library (operations like `.all(), .insert(), etc`) decreases with the number of models registered.

#### Steps to reproduce the bug

Model generator:
```javascript
import { Model } from '@vuex-orm/core'

function exp(ientity) {
    return class ClonedModel extends Model {
        static entity = ientity;

        static primaryKey = 'id';

        static fields() {
            return {
                id: this.number(),
                a: this.string(),
                b: this.number(),
                c: this.attr()
            }
        }
    }
}


export default exp;
```

Register models:
```javascript
import VuexORM from '@vuex-orm/core'
import VuexORMAxios from '@vuex-orm/plugin-axios'

VuexORM.use(VuexORMAxios) // <- No axios option.

const database = new VuexORM.Database()

import modelCloner from '@/models/model_cloner.js'

for (let i = 0; i < 50; i++) {
    const str = `cloned_model_${i}`;

    const cloned = modelCloner(str);

    database.register(cloned);
}
```

Generate data and test
```javascript
<template>
  <div id="app">
    <div>Number of rows: {{ rows.length }}</div>
    <div>Took {{ timeInserting }} secs inserting data</div>
    <div>Took {{ timeRetrieving }} sec retriving data</div>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      rows: [],
      model: null,

      timeInserting: 0,
      timeRetrieving: 0,
    };
  },
  created() {
    // Get one store
    this.model = this.$store.$db().model("cloned_model_0");

    // Generate some data
    this.rows = new Array(5000)
      .fill(0)
      .map(function (row, i) {
        const r = {};
        r.id = i;
        r.a = Math.random() * 6000;
        r.b = Math.random() * 6000;
        r.c = Math.random() * 6000;

        return r;
      });


    this.runTest();
  },

  methods: {
    runTest: async function () {
      const rows = this.rows;
      const model = this.model;

      let start = null,
        end = null;

      console.log("[Inserting", rows.length, "records]");

      start = new Date();
      await model.insert({ data: rows });
      end = new Date();

      this.timeInserting = (end - start) / 1000;

      console.log("Took: ", this.timeInserting, " to insert ", rows.length);

      console.log("[Retrieving data] ");
      start = new Date();
      const recs = await model.all();
      end = new Date();

      this.timeRetrieving = (end - start) / 1000;

      console.log("Took: ", this.timeRetrieving, " to retrieve ", recs.length, ' records');
    },
  },
};
</script>
```

#### Expected behaviour

Operations like `.all()` and `.insert()` should be linear to the number of records that the model contains. 

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.12

#### Link to minimal reproduction

**[WARNING] Browser may be inresponsive for some seconds**

* [Example with 50 models, inserting/reading 5000 records](https://codesandbox.io/s/magical-davinci-zdu65?file=/src/App.vue);

The number of models created can be tweeked in [this file](https://codesandbox.io/s/magical-davinci-zdu65?file=/src/store.js);

#### Additional context

Our use case requires registering 50+ models in which one of them may contain 2000+ records.
Here is some timings for the `.all()` and `.insert()` with 5000 records and 1/50/100 models registered:

| Nº models | Operation | Time (secs) |
| --------- | --------- | ----------- |
|  1        | `insert()` | 0.142 |
|  1        | `all()`    | 0.025 |
| 50        | `insert()` | 2.178 |
| 50        | `all()`    | 1.998 |
| 100 | `insert()` | 7.887 |
| 100 | `all()`  | 7.870 |

**Comment by ntma** [comment]
After some digging, it seems that the culprit may be [this](https://github.com/vuex-orm/vuex-orm/blob/7573d2fe92c45fbf455e780222e9029e7267f2cd/src/database/Database.ts#L119) step which is executed when [hydrating records](https://github.com/vuex-orm/vuex-orm/blob/7573d2fe92c45fbf455e780222e9029e7267f2cd/src/query/Query.ts#L1289) (part of the `.all()` workflow).

The `.getBaseModel(this.entity)` is called N times where N is the number of records in the model. For each call, this function reduces **twice** the list of entities registered to get a single model. In the end, we will have N * E<sup>2</sup> where E is the number of entities registered.

**Comment by cuebit** [comment]
resolved by #718

Your contribution is greatly appreciated @ntma 👍

**Comment by Maqsyo** [comment]
Would be great to have the new times as comparison. Thanks for your effort!

**Comment by ntma** [comment]
Here are the new times:
* [New example with vuex-orm@0.36.4, 50 models, inserting/reading 5000 records](https://codesandbox.io/s/eloquent-brattain-mrmxk?file=/src/App.vue)

| Nº models | Operation | Time (secs) |
| --------- | --------- | ----------- |
|  1        | `insert()` | 0.134 |
|  1        | `all()`    | 0.023 |
| 50        | `insert()` | 0.136 |
| 50        | `all()`    | 0.024 |
| 100 | `insert()` | 0.141 |
| 100 | `all()`  | 0.026 |
