### ISSUE TITLE
@vuex-orm namespace & Plugin package naming

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#72]
I wanted to publish the orm-vuex-apollo plugin with the name `@vuex-orm/plugin-apollo`, because the search plugin uses a similar name and well it made sense for me.

I got `Error: Forbidden : @vuex-orm/plugin-apollo`, which actually makes sense, due to the fact that this namespace doesn't belong to me.

Should I simply rename my plugin or does it make sense to have all plugins under the same namespace?

**Comment by kiaking** [comment]
It would be nice to add it under the vuex-orm namespace if you're OK with it! Let me email you so that I can add you to the organization and such 👍

**Comment by kiaking** [comment]
@phortx And sorry, I didn't know your email address :p  Could you send me your NPM account at kia.king.08@gmail.com ?
