### ISSUE TITLE
Vue x orm next in production?

### ISSUE THREAD

**Issue by musixite** [vuex-orm/vuex-orm#720]
I’m confused on which version to use for a new project.

readme recommends to use vuexorm next but the (next) documentation is incomplete (ex many to many relationships,...)

I’m wondering if the original doc still applies for the next version or if the undocumented parts are not implemented yet (thus using the original vuexorm for now)

a bit verbose for a simple question :)

**Comment by cuebit** [comment]
I think if your project is dependent of certain features that are currently absent from the next version then definitely stick to the current stable version. It won’t be too much work to migrate in future. 

While you can technically manufacture many to many relations with the `hasManyBy` relation, it would be considered somewhat cumbersome by many.
