### ISSUE TITLE
Updating a field on a nested computed array

### ISSUE THREAD

**Issue by musixite** [vuex-orm/vuex-orm#721]
The following code works fine but I'm wondering if there could be an easier way to do the same without having to create a loop for updating.

Quick explanation:
- Domain has many projects (domain_id in projects)
- Project List shows the project from a specific domain
- I'm using a computed property for projects with a getter and a setter
- It is the set(value) method that I think could be improved (or maybe it already exists and I don't know it!). The goal being to update the position field (which is used to sort the projects on the getter)

```vue
<template>
  <draggable
    v-model="projects"
    @start="drag = true"
    @end="drag = false"
    item-key="id"
  >
    <template #item="{element, index}">
      <div>
       {{ element.name }}
      </div>
    </template>
  </draggable>
</template>

<script>
import Project from "@/models/Project";
import draggable from "vuedraggable";
export default {
  props: ["domainId"],
  components: {
    draggable
  },
  computed: {
    projects: {
      get() {
        return Project.query()
          .where("domain_id", this.domainId)
          .orderBy("position")
          .get();
      },
      set(value) {
        value.forEach((element, key) => {
          Project.update({
            where: project => project.id === element.id,
            data: { position: key+1}
          });
        });
      }
    }
  }
};
</script>

```

**Comment by cuebit** [comment]
There is an example in the docs that illustrates updating with array values. For example, your setter may look like:

```js
set(value) {
  Project.update({
    data: value.map((element, key) => ({ id: element.id, position: key + 1 }))
  })
}
```

**Comment by musixite** [comment]
> There is an example in the docs that illustrates updating with array values. For example, your setter may look like:
> 
> ```js
> set(value) {
>   Project.update({
>     data: value.map(({ id }, key) => ({ id, position: ++key }))
>   })
> }
> ```

I knew there was a better way!
Can you please share me the link? I went through the doc and couldn't find it (using search "map").

**Comment by cuebit** [comment]
Sorry, forgot to share. In the [Updates](https://vuex-orm.org/guide/data/inserting-and-updating.html#updates) section, scroll down and it's the last example before the updating relationship section. 

The above example is not in the docs. It's how I would often write it. 👍

**Comment by musixite** [comment]
No need to be sorry :)

Wonderful. Maybe this could be added in the docs, I'm sure this will help others!

Thanks again

**Comment by cuebit** [comment]
I think in this instance the example provided is unique to your use case. The example in the docs illustrates the possibilities. But yea, I think a recipes section would be useful to demonstrate real world use cases.
