### ISSUE TITLE
has one through?

### ISSUE THREAD

**Issue by musixite** [vuex-orm/vuex-orm#726]
Model Quotes
Model Blocks
Quote optionally belongs_to Block through BlockQuote Model (has_one through)

Is it possible to do?

**Comment by cuebit** [comment]
Unfortunately not. Though [this PR](https://github.com/vuex-orm/vuex-orm/pull/614) was merged into dev, but that branch is no longer active. 

You can achieve this through `hasManyThrough`, though, it is somewhat cumbersome particularly if your API doesn't abide with the expected format of the relation. In which case you'll want to reshape your API response.
