### ISSUE TITLE
How should I load relationships from server?

### ISSUE THREAD

**Issue by Marchiuzzz** [vuex-orm/vuex-orm#727]
Hi, I'm sure this is quite a basic question and it must've been answered but I am unable to find any information on this in the docs. Let's say I have model "list" as follows
```

import { Model } from '@vuex-orm/core'
import DynamicObject from './DynamicObject'

export default class List extends Model {
  static entity = 'lists'

  static fields () {
    return {
        id: this.attr(null),
        objects: this.belongsToMany(DynamicObject , ListDynamicObject, 'list_id', 'object_id'),
    }
  }
}
```
Then I have basic DynamicObject model with some fields and then, of course, the intermediate model 'ListDynamicObject'
```
import { Model } from '@vuex-orm/core'
export default class ListDynamicObjectextends Model {
    static entity = 'list_content'
    static fields () {
        return {
            id: this.attr(null),
            object_id: this.attr(null),
            list_id: this.attr(null),
            position: this.attr(1000),
        }
    }
}
```
List can have many objects and objects can belongs to multiple lists.

How do I populate this with the data from database to be able to access objects of lists? Currently my solution was to use Vuex orm axios plugin, I created an api endpoint which returns all data from the intermediate table in the database but if I try to access objects within a list by doing so 
`List.query().withAllRecursive().where('id', 1).first().objects;` I get an empty array even though I know for a fact that this lists does have objects attached to it.

**Comment by cuebit** [comment]
Which model are you initiating the API call from and what does the response look like?

**Comment by Marchiuzzz** [comment]
Currently I have setup endpoints for all of these 3 models (including the intermediate one) and so on initiation I call those 3 APIs and data gets populated. 
Here's an example 
**/api/lists**
```
[
  {
   "id": 1,
   "title": "AAA"
  },
  {
    "id": 2,
    "title" : "BBB"
  }
]
```

**/api/objects**
```
[
  {
   "id": 1,
   "title": "Object1"
  },
  {
    "id": 2,
    "title" : "Object2"
  }
]
```
**/api/lists_objects**
```
[
  {
    "id": 1,
    "list_id": 1
    "object_id":1
  },
  {
    "id": 2,
    "list_id": 1
    "object_id":2
  }
]
```

I can, however, change the response to whatever is needed.

**Comment by musixite** [comment]
you need to fetch your list with the objects within. then the store will automatically create a store for lists, objects and list_object.

In other words, your api call is missing the relationships so vuex-orm can't create empty stores if it's missing the schema

**Comment by Marchiuzzz** [comment]
@musixite 
That makes sense, however, I tried that and it doesn't really work for some reason. I've tried this with objects and tags instead of lists and objects, but the idea is the same.
I have a tag model
```
import { Model } from '@vuex-orm/core'

export default class Tag extends Model {
  static entity = 'tags'
  static primaryKey = 'key'
  static fields () {
    return {
        key: this.attr(null),
        value: this.attr(null),
    }
  }

    static apiConfig = {
        actions: {
          fetch () {
              return this.get('/api/tags', {
                  dataKey: 'data'
              });
          }
        }
    }
}
```
**Object model:**
```
import { Model } from '@vuex-orm/core'
import Tag from './Tag'
import ObjectTag from './ObjectTag'

export default class DynamicAbstractObject extends Model {
    static entity = 'dynamicAbstractObjects'

    static fields () {
        return {
            id: this.attr(null),
            title: this.string(''),  
            tags: this.belongsToMany(Tag, ObjectTag, 'abstract_object_id', 'tag_id', 'id', 'key'),
        }
    }

    static apiConfig = {
        actions: {
            fetch () {
                return this.get('/api/dynamicobjects', {
                    dataKey: 'data'
                });
            }
        }
    }
}
```
And the **ObjectTag** model (intermediate table)
```
import { Model } from '@vuex-orm/core'

export default class ObjectTag extends Model {
    static entity = 'objects_tags'
    static fields () {
        return {
            id: this.attr(null),
            abstract_object_id: this.attr(null), 
            tag_id: this.attr(null),
        }
    }
}
```
Response from **/api/dynamicobjects** (I've crossed out irrelevant fields for this question)
![image](https://user-images.githubusercontent.com/73941456/118779530-cf25db00-b893-11eb-88de-1a52baf89f6b.png)

As you can see, the response object has tags, however, objects_tags entity in Vue ORM stays empty...what could be wrong?

**Comment by Marchiuzzz** [comment]
Okay, I've figured it out, apparently I shouldn't have id field in the intermediate table, I also needed to specify a composite primary key for the intermediate model. So once I've changed ObjectTag model to this:
```
import { Model } from '@vuex-orm/core'

export default class ObjectTag extends Model {
    static entity = 'objects_tags'
    static primaryKey = ['abstract_object_id', 'tag_id']
    static fields () {
        return {
            abstract_object_id: this.attr(null), 
            tag_id: this.attr(null),
        }
    }
}
```
Everything works fine

**Comment by Marchiuzzz** [comment]
I've noticed that using my previous method to load each data entity manually was actually much faster, could it be true that when passing objects with relationships, those relationship items get inserted into their entity tables one by one? This results in an out of memory exception eventually...

**Comment by cuebit** [comment]
@Marchiuzzz relationships are grouped then inserted so there will be a mutation for each entity, not each record. 

If you're getting a memory exception it's likely you're doing something wrong.

**Comment by Marchiuzzz** [comment]
@cuebit thanks for answering my question about how relationship data is handled, regarding memory issues, yes, it's probably an issue with my code, I'll look deeper
