### ISSUE TITLE
Question: How can I send data back to server for saving on the actual database?

### ISSUE THREAD

**Issue by Marchiuzzz** [vuex-orm/vuex-orm#730]
Another newbie question, which I can't find the answer for in the docs. After doing work on the frontend, how do I actually send all of the changes to back-end? For example, let's say I have 1000 records for table "users", I've modified a few records, now does it mean I have to get all users using User.get() and send this whole set over POST request? That doesn't really make sense, I don't want to update the whole list of 1000 users when I only changed a few. I've tried looking into this plugin https://github.com/vuex-orm/plugin-change-flags but apparently it's not compatible with the latest version of Vuex ORM? I just get `"TypeError: store.$db is not a function"` when trying to use `this.$store.getters['entities/allDirty']();` 

I'm using laravel, no Nuxt.

**Comment by cuebit** [comment]
That's entirely up to you to decide.

There are many ways to implement an alterative to `plugin-change-flags`. For example, you can create a base model that your models can extend that then inherit proponents to marking records as dirty, etc.

The model can be as simple as this:

```js
import { Model as BaseModel } from '@vuex-orm/core'

class Model extends BaseModel {
  static fields() {
    return {
      isDirty: this.boolean(false)
    }
  }

  static beforeUpdate(model) {
    model.isDirty = true
  }

  static dirty() {
    return this.query().where('isDirty', true)
  }
}
```

And you can then expand your existing models:

```js
export class User extends Model {
  static entity = 'users'

  static fields() {
    return {
      ...super.fields(),
      id: this.attr(null),
      name: this.string(''),
      posts: this.hasMany(Post, 'userId')
    }
  }
}
```

And also retrieve the dirty models:

```js
const dirty = User.dirty().get()
```

Here's a [demo](https://codesandbox.io/s/snowy-wildflower-dqwhy?file=/src/models.js).

**Comment by Marchiuzzz** [comment]
Thank you very much @cuebit for detailed answer, will try implementing this!
