### ISSUE TITLE
Question: Computed property that depends on query optimization 

### ISSUE THREAD

**Issue by Marchiuzzz** [vuex-orm/vuex-orm#732]
I have a pretty complicated system, where resources might be modified from a bunch of different places and they all need to be synchronized so if a resource is edited in one place, all the others have the same result and of course, this is solved by reactivity and this package seemed like the perfect solution. However, I must be missing something since the performance is terrible. Let's say I have an array of objects that have a bunch of relationships, sometimes even recursive relationships, this array contains 1000 items. I also have my system split into chunks, each of which use some part of this array. Now let's say component A uses the first 10 items of this array, so [0..9], component B uses [10..800] and component C uses [801..999]. All of these components use watchers for their part of the array, which is computed. I need to be able to modify data on pivot table, therefore I do a direct update of the intermediate model. Once I do that, I notice that watchers are triggered on all of these components (in this example I only provided 3 components but in reality there may be 100 of them or even more) and so if I modify the first item's pivot, I expect only the component A to update and do all the calculations in it's watchers since only the A component is using the modified data but instead, all of the components are updating, causing horrible performance... 

EDIT: 
To clarify, if I have a **List** model and intermediate table model **ListObjects** and I update the intermediate table like so ( I couldn't find Laravel's "sync" method equivalent so I'm deleting all relationships for this model and then inserting the needed ones)

```
ListObjects.delete((record) => {
    return record.id=== this.item.id;
});
var data = this.thisItems.map((el, index) => {
    return {
        id: this.item.id,
        abstract_object_id: el.id,
        position: index,
    };
});
ListObjects.insert({
    data: data
});
```

Then I have a computed property like this
```
computed: {
        list(){
            return List.query().withAllRecursive().where('id', 1).first();
        },
  },
```
If I run an update for intermediate table of List, which has id: 2, this computed property described above is still getting triggered even though nothing has changed for the list with id: 1.

I hope I managed to state my problem clearly and I would appreciate any suggestions/ideas how to tackle this issue.

**Comment by datahoecn** [comment]
I have the same problem

**Comment by Marchiuzzz** [comment]
@datahoecn I solved it with a workaround.
Originally, my code was something like this
```
...
computed: {
 neededObjects(){
  return List.query().withAllRecursive().where('id', id).first().objects;
 }
}
...
```
And then I would just use the "neededObjects" directly in my component, however, apparently this is a horrible way of doing it since it affects Vue's ability to destroy components (In my case this was a common task) significantly.

I needed to add an additional "control" field to my "List" model

Here's the idea after reworking this:
```
...
data(){
  return {
    neededObjects: []
  }
},
computed: {
  list(){
    return Lists.find(id)
  }
},
watch: {
  list: {
    handler(newValue, oldValue){
      if(newValue.control !== oldValue.control)
      {
        this.neededObjects = this.getListObjects();
      }
    }
  }
},
methods: {
  getListObjects(){
    return List.query().withAllRecursive().where('id', id).first()?.objects || [];
  }
}
...
```
So now when I want this component with this list to update, I just update the list's "control" field and instead of all the components running the object array retrieval code, only the needed component runs it, which saved me a lot of execution time.

**Comment by cuebit** [comment]
I’m curious to know how the computed property _affects Vue's ability to destroy components_. Could you elaborate?

**Comment by Marchiuzzz** [comment]
@cuebit 
Reading these articles/posts helped me come to such conclusion
https://betterprogramming.pub/6-ways-to-speed-up-your-vue-js-application-2673a6f1cde4
https://stackoverflow.com/a/66780446/6668871

Basically, the more and more complex computed properties the component has, the more time it takes to destroy it because vue attaches a bunch of watchers, which when trying to destroy a component, are removed one by one, causing unacceptable load times. I had components with Vuex Orm queries as computed properties, I've noticed there were over 100k "deps" attached to them, most of which were a result of these complex computed properties. After reworking it the way I've explained above (and also a few more similar adjustments), I managed to get loading time from ~5 minutes to less than 10 seconds. 
In conclusion, this really does seem like a great package but either I'm using it completely wrong or it has serious performance issues. For example I had a Vuex orm model "Parameter", it's a simple object with properties, no relationships, while I was using Vuex Orm queries in computed properties, the performance of my whole application was terrible (as I mentioned, up to 5 minutes of browser just hanging), after moving to pure vuex store to store these objects, the performance has improved drastically. I don't know what's under the hood of Vuex orm query builder (don't really have time to dig deeper on my own) but it's obviously not a simple items[id] situation when I run Array.find(id). Looking forward to seeing this package mature...but then again, perhaps the package is fine but I am using it in a wrong way somehow

**Comment by datahoecn** [comment]
@Marchiuzzz  thanks, brother,

**Comment by Marchiuzzz** [comment]
@datahoecn It will but only the queries that I need will be executed instead of all of them

**Comment by cuebit** [comment]
@datahoecn I think what @Marchiuzzz is exemplifying is reducing the component render cycles by watching changes to state the component is not dependent on and selectively triggering render by assignment (watch value -> data). For example, if `list` was referenced anywhere other than lifecycle hooks or watchers, the component will track it as a dependency and trigger a render when a change is detected. Since `list` is simply being watched, it is not triggering a render until it decides to update the data property, which is referenced in the template therefore change detections to that property will trigger a render.
