### ISSUE TITLE
about vue computed, only update related data

### ISSUE THREAD

**Issue by datahoecn** [vuex-orm/vuex-orm#735]
In vue computed, just like this:
users () {
      return User.find("$uid1")  // $uid1 is primary key
    }

because User.find("$uid1") is primary key
I want to make computed effective after changing  data about "$uid1"
When changing other data "$uid2", computed will not be executed

**Comment by cuebit** [comment]
Change detection in Vuex ORM is not based on a primary key. Computed properties are triggered for both `$uid1` and `$uid2` when a) both belong to the same entity, or b) have relations that connect to an entity being changed.
