### ISSUE TITLE
computed data returns null with lifecycle created()

### ISSUE THREAD

**Issue by musixite** [vuex-orm/vuex-orm#740]
Not sure if it's a bug or if I'm doing something wrong but the following returns null

### model
```
export default class Area extends Model {
  static entity = "areas";
  static fields() {
    return {
      id: this.number(null),
      name: this.string(""),
  }
}
```

### store
```
"entities": {
    "$name": "entities",
    "areas": {
      "$connection": "entities",
      "$name": "areas",
      "data": {
        "1": {
          "id": 1,
          "name": "personal",
          "projects": [],
          "$id": "1"
        },
        "2": {
          "id": 2,
          "name": "music",
          "projects": [],
          "$id": "2"
        },
        "3": {
          "id": 3,
          "name": "web",
          "projects": [],
          "$id": "3"
        }
    }
},
```
### component
```
computed: {
    areaId() {
      const $query = Area.query()
        .where("name", "personal")
        .first();
      return $query.id;
    },
  },
  created() {
    console.log(this.areaId); // returns null
  },
```

I also tried with mounted() and it gives me the same result.

**Comment by cuebit** [comment]
If you log the `$query` object and inspect its properties, what do you see?

**Comment by musixite** [comment]
The console.log doesn't show anything.
It has to do something with the lifecycle.

What's weird is that the computed property works.
```
computed: {
    areaId() {
//      const $query = Area.query()
//        .where("name", "personal")
//        .first();
//      return $query.id;
        return 1;
    },
  },
  created() {
    console.log(this.areaId); // works (returns 1)
  },
```

**Comment by cuebit** [comment]
Is the record actually in the store are the time the component is created?

**Comment by musixite** [comment]
App.vue is fetching the areas (using async created() )
```
methods: {
    fetchAreas() {
      Area.api().get("areas");
    },
  },
  created() {
    this.loading = true;
    this.fetchAreas();
    this.loading = false;
  },
```

And the nested component has the code above (and the store entities are populated with the areas)

**Comment by musixite** [comment]
To make it clear, what I'm trying to achieve is:
- fetch all areas from DB
- set the area_name in the store (hardcoded depending on the component)
- retrieve the area_id from the store (where area_name = the hardcoded value)
- save the current area_id as state in the store

**Comment by cuebit** [comment]
> App.vue is fetching the areas (using async created() )
> 
> ```
> 
> methods: {
> 
>     fetchAreas() {
> 
>       Area.api().get("areas");
> 
>     },
> 
>   },
> 
>   created() {
> 
>     this.loading = true;
> 
>     this.fetchAreas();
> 
>     this.loading = false;
> 
>   },
> 
> ```
> 
> 
> 
> And the nested component has the code above (and the store entities are populated with the areas)

Sorry for my ignorance here, I don't see any async/await in this example. Also, does the loading state impact the components instantiation? E.g. is `v-if="!loading"` applied to the/a component to ensure the data exists before the component containing the above code in the component tree renders?

**Comment by musixite** [comment]
yes sorry I copied too fast.
```
async created() {
...
}
```

and template with
```
<div v-if="loading">Loading...</div>
  <div v-else>
    <router-view></router-view>
  </div>
```

**Comment by cuebit** [comment]
See this [repro](https://codesandbox.io/s/gifted-drake-r2xvy?file=/src/App.vue).

I can't see this is being a Vuex ORM issue. Hence the request for more clarity on the workflow. I don't know why `areaId` is returning `null` for you, unless the `id` is null then it most definitely shouldn't, it should throw.

**Comment by musixite** [comment]
Pff.... Dumb mistake!

When I added async/await, I removed the commit to the store for areaId 
It works like a charm now.

Thanks again!

**Comment by cuebit** [comment]
Pleased to hear you have found a solution. Good luck 👍
