### ISSUE TITLE
Creating unit tests for components with Vuex ORM

### ISSUE THREAD

**Issue by ShockwaVee** [vuex-orm/vuex-orm#741]
I'm trying to write some unit tests using vue test utils for some components that use VuexORM. I haven't run into any examples online, so I'm opening an issue here. If I've managed to skip over something, please close this and show me the way!

I have a mocha/chai test where I mount a component like so
```
const wrapper = mount(Sidebar, {
            propsData: {
                isSidebarLoading: true,
            }
        })
```

The Sidebar component uses a query similar to this:
```
return Project.query().where((project: Project) =>
            project.projectState === 'offer' ||
            project.projectState === 'lead' ||
            project.projectState === 'order').withAllRecursive().get();
```
(If you need a reproducible example, I can provide it, but I guess it's not a bug in the library)

After I run the tests I get an error:
`TypeError: Cannot read property 'store' of undefined`

I'm assuming I have to initialize the store and add it to the Vue instance where the tests are run, but I haven't tried it since I'm not sure how to fill up the store.
Should I be doing something like this or should I register the necessary models in a beforeEach? Or something else entirely?

**Comment by cuebit** [comment]
Yes, since Vuex ORM depends on Vuex you need Vuex installed on a local Vue instance (to avoid constructor pollution), a store instantiated and Vuex ORM installed as a plugin for Vuex. The rest should fall into place.

Some form of reproduction helps. It will give people a better indication of what does/doesn't/needs to exists to get things working.

**Comment by ShockwaVee** [comment]
That was it, I knew I was missing something. I did it the way you explained and it's working as expected.
Thanks for the quick response, as well!
