### ISSUE TITLE
0.18.0 Regression?

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#75]
Seems like the new version is breaking my plugin:

```javascript
user.$dispatch('persist');
```

doesn't work: `vuex.esm.js:417 [vuex] unknown action type: entities/users/persist` :(

With 0.17 it worked.

**Comment by kiaking** [comment]
Hm... Could you give the underlining code? I couldn't find `persist` method in vuex-orm-apollo :/ From the error message, seems like action registration is broken.

**Comment by phortx** [comment]
Oh sorry I don't pushed that yet :)

From the `install` method:
```javascript
components.subActions.persist = this.persist.bind(this);
```

And the persist method:

```javascript
private async persist ({ state, dispatch }: ActionParams, { data }: ActionParams) {
    console.log('things happen');
}
```

**Comment by kiaking** [comment]
This is strange. Maybe something to do with this bindings? Because the following test passes.

```js
async function getName () {
  return 'John Doe'
}

const plugin = {
  install (components) {
    components.subActions.getName = getName
  }
}

VuexORM.use(plugin)

const store = new Vuex.Store({
  plugins: [VuexORM.install(database)]
})

const user = new User()

expect(await user.$dispatch('getName')).toBe('John Doe')
expect(await store.dispatch('entities/users/getName')).toBe('John Doe')
```

Can you check what happens when you change that code to this?

```js
components.subActions.persist = async () => {
    console.log('things happen');
}
```

**Comment by phortx** [comment]
Hmm I can't reproduce it. Now it just works. Sorry for the issue :(
