### ISSUE TITLE
Insert action should return updated object

### ISSUE THREAD

**Issue by timoschwarzer** [vuex-orm/vuex-orm#77]
When inserting an object with an ID that already exists in the store, the updated entity isn't returned. I think this would be a nice addition.

```javascript
const form = await this.$store.dispatch('entities/forms/insert', {data: response.data});
console.log(form);
```

**Comment by kiaking** [comment]
Hah, this is unexpected. I though I covered this situation too but I haven't wrote test for this. Let me check 🔥

**Comment by timoschwarzer** [comment]
Ah, okay. I thought this is intended because you wrote "**returns newly**  created entities" in the changelog. Thank you!

**Comment by timoschwarzer** [comment]
Ah, okay. I thought this is intended because you wrote "**returns newly**  created entities" in the changelog. Thank you!

**Comment by kiaking** [comment]
OK I've wrote test for this case and unfortunately it's passing.

```js
// These test passes.

it('returns the newly created entity when inserting data with existing primary key', async () => {
  class User extends Model {
    static entity = 'users'

    static fields () {
      return {
        id: this.attr(null)
      }
    }
  }

  const store = createStore([{ model: User }])

  await store.dispatch('entities/users/insert', { data: { id: 1 } })

  const data = {
    id: 1
  }

  const user = await store.dispatch('entities/users/insert', { data })

  expect(user).toBeInstanceOf(User)
  expect(user.id).toEqual(1)
})

it('returns the multiple newly created entity when inserting data with existing primary key', async () => {
  class User extends Model {
    static entity = 'users'

    static fields () {
      return {
        id: this.attr(null)
      }
    }
  }

  const store = createStore([{ model: User }])

  await store.dispatch('entities/users/insert', { data: { id: 1 } })

  const data = [{ id: 1 }, { id: 2 }]

  const users = await store.dispatch('entities/users/insert', { data })

  expect(users[0]).toBeInstanceOf(User)
  expect(users[0].id).toEqual(1)
  expect(users[1]).toBeInstanceOf(User)
  expect(users[1].id).toEqual(2)
})
```

Is it possible for you to create reproducable code?

**Comment by timoschwarzer** [comment]
I will take a look...

**Comment by timoschwarzer** [comment]
I didn't forget this, I'm just short on time... I'll take a look the next days...

**Comment by kiaking** [comment]
Thanks! Take your time though 👍  I don't think it matters but Vuex ORM 0.20.0 is just released so maybe it would be nice if you could try on that version.

**Comment by timoschwarzer** [comment]
Hmm, seems like the issue is resolved / never existed / whatever :man_shrugging: 
I'll reopen when I encounter this again.

**Comment by kiaking** [comment]
Oh well, good news then! Thank you for checking 👍
