### ISSUE TITLE
Let `update` return updated records

### ISSUE THREAD

**Issue by iNaD** [vuex-orm/vuex-orm#79]
As already discussed in #73 the `update` action should also return the updated record(s) like the other actions. This would streamline the action API.

Like the other changes this shouldn't break existing applications?

**Comment by iNaD** [comment]
While digging into a solution for the `update` action, I found some missing cases and tests belonging to composite primary keys.

I think I will create a PR for this first, before starting the Promise based update action.

**Comment by kiaking** [comment]
Merged the #85! Thanks for the PR!

**Comment by kiaking** [comment]
Implemented at #79! This will be available on next release.

**Comment by iNaD** [comment]
You meant #88 ;) great work, glad I didn't start any coding yet :)

**Comment by kiaking** [comment]
Oops, yap #88 :p Refactoring for insertOrUpdate is not started though ;)

**Comment by kiaking** [comment]
Now Vuex ORM 0.20.0 is out with this feature enabled 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.20.0
