### ISSUE TITLE
Unable to see child models within object state

### ISSUE THREAD

**Issue by clockworked247** [vuex-orm/vuex-orm#80]
Hi there, thanks for the great plugin for Vuex.  I'm still struggling to get it working, unfortunately.

Apologies in advance, I've been going through the docs and trying out the example calls to Vuex ORM: https://vuex-orm.gitbooks.io/vuex-orm/store/retrieving-data.html

I must be doing something wrong...

Given the following Models:

**App Model**

```
import { Model } from '@vuex-orm/core'
import Workspace from './Workspace'

export default class App extends Model {
  static entity = 'apps'

  static fields () {
    return {
        workspaces: this.hasMany(Workspace, 'appId'),
        workspaceLoaded: this.attr(false)
    }
  }
}
```

**Workspace Model**

```
import { Model } from '@vuex-orm/core'
import Query from './Query'
import App from './App'

export default class Workspace extends Model {
  static entity = 'workspaces'

  static fields () {
    return {
        id: this.attr(null),
        appId: this.attr(null),
        app: this.belongsTo(App, 'appId'),
        name: this.attr('Workspace'),
        active: this.attr(true),
        queries: this.hasMany(Query, 'workspaceId')
    }
  }
}
```

I create an app with two workspace objects:

```
myVue.$store.dispatch('entities/apps/create',{
        data: {
            'workspaces': [
                {
                    id: 111,
                    name: 'Workspace 1',
                    active: true,
                    queries: [
                        ... array of JSON query objects ...
                    ]
                },
                {
                    id: 222,
                    name: 'Workspace 2',
                    active: false,
                    queries: [
                        ... array of JSON query objects ...
                    ]
                }
            ]
        }
    })
```

Once this is complete, I use the getters to get the instance of the only App object state:
`myVue.$store.getters['entities/apps/all']()[0]`

When looking at the workspaces property (Array), it has no items (usually IDs).

But, if I look directly at the state, I see related child object IDs:
`myVue.$store.state.entities.apps.data._no_key_0.workspaces`
I see an array of my two workspace IDs.  

So, why can't I see these child IDs by using the getter call?

Thanks in advance!

**Comment by iNaD** [comment]
If I understand you correctly, you missed [Retrieving Relationships](https://vuex-orm.gitbooks.io/vuex-orm/relationships/retrieving-relationships.html) while reading the docs.

So the correct query should be similar to this:

`myVue.$store.getters['entities/apps/query']().with('workspaces').all()`

This retrieves all apps including the workspaces relationship. The same applies when Retrieving a single record:

`myVue.$store.getters['entities/apps/query']().with('workspaces').find(id)`

**Comment by clockworked247** [comment]
@iNaD Thanks for your comment and yes, I did miss that page.  The with() API looks very elegant and intuitive, but unfortunately, I can't get it to return the child model state with the query you posted or any of the queries seen in the documentation.   

`myVue.$store.getters['entities/apps/query']().with('workspaces').all()`
Return:

```
{
        workspaces: [],
        workspaceLoaded: false
}
```

But if I check my state, the workspaces definitely exist:

`myVue.$store.getters['entities/workspaces/query']().with('queries').all()`
Return:

```
[
                {
                    id: 111,
                    appId: null,
                    app: null,
                    name: 'Workspace 1',
                    active: true,
                    queries: []
                },
                {
                    id: 222,
                    appId: null,
                    app: null,
                    name: 'Workspace 2',
                    active: false,
                    queries: []
                }
]
```

My intuition is that I've got the relationship mapping wrong something.  

Are my belongsTo() and hasMany() statements correct?   I don't manually pass in those IDs as a part of the create call and according to the docs I don't need to.

I think I might be referencing the wrong properties between the parent and the child.

I'll keep working on it, but if you happen to see something in the relationship definition that stands out as wrong, I'll appreciate the help.

**Comment by clockworked247** [comment]
I removed the belongsTo() definition (redundant) in the child Workspace model and made sure to add an when creating the app.  ie.

```
myVue.$store.dispatch('entities/apps/create',{
        data: {
            id: 1,
            'workspaces': [
                {
                    id: 111,
                    name: 'Workspace 1',
                    active: true,
                    queries: [
                        ... array of JSON query objects ...
                    ]
                },
                {
                    id: 222,
                    name: 'Workspace 2',
                    active: false,
                    queries: [
                        ... array of JSON query objects ...
                    ]
                }
            ]
        }
    })
```

When I call:
qconsole.Vue.$store.getters['entities/workspaces/query']().all()

Both workspaces come back in the query, but neither of them  has it's "appId" property set to 1, the parent's ID.

Isn't that something that should happen automatically, linking the two models together at create time?

**Comment by clockworked247** [comment]
https://vuex-orm.gitbooks.io/vuex-orm/relationships/inserting-relationships.html

You have to specify the parent IDs within the JSON data.

*facepalm*  Ok, yea.  I should have read deeper.  Apologies for the noise.

**Comment by kiaking** [comment]
@clockworked247 Hi just wanted to follow you up on this.

Yes, it is recommended to explicitly define parent ID in JSON data.

However, Vex ORM will define correspond id automatically when ever possible. For example;

```js
class Post extends Model {
  static entity = 'posts'

  static fields () {
    return {
      id: this.attr(null),
      user_id: this.attr(null),
      author: this.belongsTo(User, 'user_id')
    }
  }
}

store.dispatch('entities/posts/create', {
  data: {
    id: 1,
    author: { id: 1 }
  }
})

// Then the created records will be;
{
  users: {
    data: {
      '1': { id: 1 }
    }
  },
  posts: {
    data: {
      '1': { id: 1, user_id: 1, author: 1 }
    }
  }
}
```

See how `user_id` and `author` field is filled with users id. So you could define your Post model like following and belongsTo relation will still work.

```js
class Post extends Model {
  static entity = 'posts'

  static fields () {
    return {
      id: this.attr(null),
      author: this.belongsTo(User, 'author')
    }
  }
}
```

But, this is going to break if you create record separately. Because there's no way for Vex ORM to guess these two data is related to each other.

```js
store.dispatch('entities/users/create', {
  data: { id: 1 }
})

store.dispatch('entities/posts/create', {
  data: { id: 1 }
})

// Then the created records will be;
{
  users: {
    data: {
      '1': { id: 1 }
    }
  },
  posts: {
    data: {
      '1': { id: 1, user_id: null, author: null } // <- author is null!
    }
  }
}
```

Therefore, it is always good practice to define your relation in the JSON data so you always get correct relationship resolving.

**Comment by clockworked247** [comment]
Hi @kiaking, thanks for clarifying.   

I inferred from the first example in these docs:
https://vuex-orm.gitbooks.io/vuex-orm/relationships/inserting-relationships.html
that the children needed their own IDs defined as seen in the example JSON used in the create statement.

```
{
  id: 1,
  name: 'John Doe',
  posts: [
    { id: 1, user_id: 1, title: '...' },
    { id: 2, user_id: 1, title: '...' },
    { id: 3, user_id: 1, title: '...' }
  ]
}
```

Anyway, once I took out the explicit definition in the data, the ORM did it's magic and created the ID from the relationship in the JSON.  Very nice.  👍    

Thanks again!  Time to get productive.

**Comment by clockworked247** [comment]
@kiaking, would you expect the create method to work with parent->child->grandchild relationships represented in the data?   I'm not seeing the IDs be generated by the ORM for the grandchild.

**Comment by kiaking** [comment]
Yes `create` method work with grandchild nested relation (it can go deep as you can get). However, ID generation wouldn't always work regardless how deep the nests are. It has several reasons why not (depending on relation type too), but again, it is recommended to provide related id manually for the best consistent result.
