### ISSUE TITLE
Delete not working / not reactive?

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#81]
See https://jsfiddle.net/51vrmud1/12/ and click on one of the `X`s.

Expectation: User will be removed from the list.
Actual behavior: Nothing happens.

**Comment by iNaD** [comment]
Found the bug. It has to be `user.$dispatch('delete', {where: id})` or `user.$dispatch('delete', id)`.

`user.$dispatch('delete', {id})` which equals `user.$dispatch('delete', {id: id})` won't work 😉

**Comment by phortx** [comment]
@iNaD Thank you dear! That seems to work :)
