### ISSUE TITLE
Many to Many Relationship insert data without relational data breaks

### ISSUE THREAD

**Issue by GERJohnson** [vuex-orm/vuex-orm#87]
I looked at your documentation and tried to implemented the Many to Many relationship. 

It seems to break if I want to insert new data that does not have the relationships included.

Here is a sample code I forked from another post :-)

https://codesandbox.io/s/n7kvyzrj8p

**Comment by kiaking** [comment]
Hi! Thank you so much for the report! Yes this is a bug and I've fixed it at this commit 8116b60fe5fbe6f9f439951fb91a7a350f836ac3. It will be fixed at next version. Was missing this test.

**Comment by kiaking** [comment]
This is fixed at Vuex ORM 0.20.0.
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.20.0

Sorry for the inconvenience and thank you again for reporting this issue!
