### ISSUE TITLE
Add the ability to hide row if item has a deleted_at column and its not null

### ISSUE THREAD

**Issue by tjsteinhaus** [vuex-orm/vuex-orm#89]
Like the title says, it would be great if we could tell it to not display a row if the deleted_at column isn't null. Just like Laravel and other frameworks.

Currently I would have to add a where clause, it would be great if it does this automatically if it's set.

**Comment by cjcrawford** [comment]
This would be a good case for a soft delete plugin. I can throw one together quick.

**Comment by tjsteinhaus** [comment]
@cjcrawford Yes, soft delete. Couldn't think of the term!

**Comment by kiaking** [comment]
This is quite good idea I think. Maybe it can be included in Vuex ORM Core though. @cjcrawford Do you have any idea on how the API should look like? Maybe `static softDelete` property on model might be good...? I like the idea of following Laravel API though.

```js
class User extends Model {
  static entity = 'users'

  static softDelete = true

  static fields () {
    id: this.attr(),
    deleted_at: this.attr('')
  }
}
```

**Comment by tjsteinhaus** [comment]
@kiaking The way you have it in your example is the way I would expect it to be.

**Comment by kiaking** [comment]
Just wanted to let you know that plugin implementation has started at https://github.com/vuex-orm/plugin-soft-delete 🎉

**Comment by tvillaren** [comment]
Hello, 

I build another version of a soft-delete plugin for Vuex ORM, based on @cjcrawford 's version but I didn't want to overwrite the Vuex ORM `delete` method so instead I implemented a `softDelete` method (with the same signature).
I also needed a `$isDeleted` boolean flag to be set so added that in.

My plugin is available at https://github.com/tvillaren/vuexorm-softdelete-plugin if anybody is interested.
It's probably possible to add a plugin option to overwrite the `delete` method and have the same behavior as the original plugin (which compatible with last version of Vuex ORM).

I'm happy to discuss (here or on Slack) possibilities of merging the 2 plugins (current "official" plugin needs some update to be compatible with last version of Vuex ORM: it still uses the `beforeProcess` hook which has been renamed).

**Comment by kiaking** [comment]
@tvillaren This is wonderful! Great job 🎉 

> I'm happy to discuss (here or on Slack) possibilities of merging the 2 plugins (current "official" plugin needs some update to be compatible with last version of Vuex ORM: it still uses the beforeProcess hook which has been renamed).

I'm really on to this. If you don't mind let's merge them together.

**Comment by kiaking** [comment]
Now Vuex ORM Soft Delete plugin is refreshed! It has v1.1.0 release. Due to that, I'll be closing this issue. If you find anything, please open an issue at the plugin repo! 🤝
