### ISSUE TITLE
How to use with nuxt.js

### ISSUE THREAD

**Issue by soutarrr7** [vuex-orm/vuex-orm#91]
Thank you for make vuex-orm.
I wanna use it with nuxt.js and mode of nuxt-store is module.

I wanna know that how to register  vuex-orm database on vuex plugin.

**Comment by soutarrr7** [comment]
I'm so sorry.
solution of this problem is on document of nuxt.

**Comment by kiaking** [comment]
Glad you could find the solution! Please feel free to open an issue if you encounter some trouble : )
