### ISSUE TITLE
Can't access getters from module action 

### ISSUE THREAD

**Issue by clockworked247** [vuex-orm/vuex-orm#92]
I want to have much of my application logic in the store modules.   I am attempting to make use of the Vuex-ORM getters to retrieve a field from the model:

ServerInteractions Model
```
import { Model } from '@vuex-orm/core'

export default class ServerInteraction extends Model {
  static entity = 'serverInteractions'

  static fields () {
    return {
        id:                       this.attr(null),
        appId:                    this.attr(null),
        queriesExecuting:         this.attr([]), 
        serverConnectionDown:     this.attr(false),
        appPath:          this.attr('/my-path/')
    }
  }
}
```

serverInteractions Module (just the actions)
```
const actions = {
    pullServerInfo: ({getters}) => {
               let root = getters['entities/serverInteractions/query']().limit(1).get()[0].appPath;
               var workspaceURL = root + 'endpoints/workspaces.xqy';
               ... async http call ...
    },
   ...
```
This code throws an error since this getter function does not exist.  

Looking at the getters object, it only contains the getters local to my module + a few additional defined methods "all", "find", "query" (I believe created by Vuex-ORM).

Unfortunately, our example at:  https://github.com/vuex-orm/vuex-orm-examples doesn't illustrate how to use this ORM library for these types of common use cases.   Most of the logic in that app lives in the components.

Thanks for the help.

**Comment by kiaking** [comment]
You don't need `entities/serverInteractions` in your actions because it's namespaced.

Use it like this.

```js
const actions = {
    pullServerInfo: ({getters}) => {
               let root = getters.query().limit(1).get()[0].appPath;
               var workspaceURL = root + 'endpoints/workspaces.xqy';
               ... async http call ...
    },
   ...

// Or you could use `rootGetters` if you want.

const actions = {
    pullServerInfo: ({rootGetters}) => {
               let root = rootGetters['entities/serverInteractions/query']().limit(1).get()[0].appPath;
               var workspaceURL = root + 'endpoints/workspaces.xqy';
               ... async http call ...
    },
   ...
```

By the way, if you want to fetch the first record, you could use `first` method.

```js
getters.query().limit(1).first().appPath;
```

**Comment by clockworked247** [comment]
Perfect, thanks.  I was going in circles trying to get that working.  Your last suggestion is much cleaner code too.   Thanks for the tip!

**Comment by kiaking** [comment]
No problem! Glad I could help. Feel free to open an issue if you have any other trouble 😃
