### ISSUE TITLE
Module pre-seeded with state?

### ISSUE THREAD

**Issue by clockworked247** [vuex-orm/vuex-orm#94]
If there's a forum I can ask questions on, I'm happy to go there.  Apologies for continuing to post here.  I'm still struggling with use of this library.

Background: I am porting over a vanilla JS + jQuery app to Vue and am struggling with the shift from a pure JS Object hierarchy in which my objects have their own state and methods for acting on that state.   

In the Vue + Vuex paradigm we're dealing with state completely separate from the Modules which define mutations, actions & getters.  I'm probably missing something... but is there a way to combine the state with its module methods?

Here's an example.  

Vanilla JS
-------------
```
function Person(first, last) {
    this.firstName = first;
    this.lastName = last;
}
Person.prototype.name = function() {
    return this.firstName + " " + this.lastName
};

let people = [];
people.push(new Person("John", "Doe"));
people.push(new Person("Sally", "Doe"));
people.push(new Person("Suzie", "Doe"));
console.log(people[0].name());  // John Doe
```

VueORM - assuming I defined a "Person" Model and Module with "name" getter.
------------
        
```
// Person Model
import { Model } from '@vuex-orm/core'

export default class Pane extends Model {
  static entity = 'persons'

  static fields () {
    return {
        id:           this.attr(null),
        firstName:  this.attr(''),
        lastName:  this.attr('')
    }
  }
}
```

```
// person Module
const mutations = {};
const actions = {};
const getters = {
    name: (state) => {
        // ???  How to give this getter access to the correct state?  
    }
};

export default {
    mutations,
    actions,
    getters
};
```

```
// code executed from within another Module (not "person")
let people = [
  { id: 0, firstName: "John", lastName: "Doe" },
  { id: 1, firstName: "Sally", lastName: "Doe" },
  { id: 2, firstName: "Suzie", lastName: "Doe" }
]

// create store
dispatch('entities/persons/create',{
  data: people
}, {root:true}).then(() => {
  console.log(rootGetters['entities/persons/name']())  // but wait.. how do I get the full name of the correct state object?
})

```

---
I would bet I'm completely missing something here... 

This library is really powerful for retrieving the state via the powerful query language and, separately, invoking getters and actions within the namespaced Modules.   I'm just struggling to work with the two together in a way that's as intuitive as the vanilla JS example.

Thanks in advance.

**Comment by kiaking** [comment]
No worry about forum. We don't have one so you can just use issue for the questions ❤️ 

For your case, simply define `name` method in the model.

```js
import { Model } from '@vuex-orm/core'

export default class Pane extends Model {
  static entity = 'persons'

  static fields () {
    return {
      id: this.attr(null),
      firstName: this.attr(''),
      lastName: this.attr('')
    }
  }

  name () {
    return this.firstName + " " + this.lastName
  }
}

dispatch('entities/persons/create', {
  data: people
}, { root:true }).then((people) => { // <- Create action returns created object.
  // If people is single item.
  console.log(people.name()) // <- Full name

  // If people is many items.
  console.log(people[0].name())

  // Or use getter to fetch object you need.
  
  const people = rootGetters['entities/persons/all']()

  people[0].name()
})
```

**Comment by clockworked247** [comment]
@kiaking Thanks.  That's so simple.

Follow-up: This may be bad design, but can these class methods get access to the rootState and/or other Module actions/getters?  

Use case:  Person hasMany Books

```
import { Model } from '@vuex-orm/core'
import Book from './Book'

export default class Person extends Model {
  static entity = 'persons'

  static fields () {
    return {
      id: this.attr(null),
      firstName: this.attr(''),
      lastName: this.attr(''),
      books: hasMany(Book, 'personId'),
    }
  }

  name () {
    return this.firstName + " " + this.lastName
  }
  read ( id, numPages ) {
    // read increments the current page read in the book
    this.books[id].readPages(numPages);  // readPages should be Module action?  Or method on the Model?  Not fully clear how this would work.
  }
}
```


```
import { Model } from '@vuex-orm/core'
import Person from './Person'

export default class Book extends Model {
  static entity = 'books'

  static fields () {
    return {
      id: this.attr(null),
      personId: this.attr(null),
      currentPage: this.attr(1)
    }
  }

  readPages (num) {
    this.currentPage += num;
  }
}
```

Code creating and calling method
```
dispatch('entities/persons/create', {
  data: people
}, { root:true }).then((people) => { // <- Create action returns created object.
  people[0].read(1, 100) // read 100 pages of the book with ID 1
})

```

So in this example, the child object is accessible (I think...), but it's possible I might also want to access unrelated objects (ie. the app state or any other unrelated object).

Hopefully, I'm making some sense...  I'm still trying to reconcile the use of your ORM library with the use of Vuex module getter/actions/mutation definitions.

**Comment by kiaking** [comment]
When using Vuex, you should almost always avoid mutating the value outside of mutation handler. Which means when you want to update the value, use actions.

When using Vuex ORM, you may do that through the model method as well because the model has `$dispatch` method which dispatches actions.

```js
import { Model } from '@vuex-orm/core'
import Book from './Book'

export default class Person extends Model {
  static entity = 'persons'

  static fields () {
    return {
      id: this.attr(null),
      firstName: this.attr(''),
      lastName: this.attr(''),
      books: hasMany(Book, 'personId')
    }
  }

  name () {
    return this.firstName + " " + this.lastName
  }

  read (id, numPages) {
    // Call method on book that updatets the page. You have to walk through
    // books because it's array.
    this.books.forEach((book) => {
      book.id === id && book.readPages(numPages)
    })
  }
}


import { Model } from '@vuex-orm/core'
import Person from './Person'

export default class Book extends Model {
  static entity = 'books'

  static fields () {
    return {
      id: this.attr(null),
      personId: this.attr(null),
      currentPage: this.attr(1)
    }
  }

  readPages (num) {
    this.$dispatch('update', {
      id: this.id,
      currentPage: num
    })
  }
}


dispatch('entities/persons/create', {
  data: people
}, { root:true }).then(() => {
  // I don't think you need people here. Just call book maybe?
  getters.find(1).readPages(100)
})
```

I think this does what you want, but I'm not 100% sure because I don't know the actual specification of the app you're trying to build.

Especially for me, it's not very clear what you're trying to do after dispatching `entities/persons/create`. Is it possible for you to [email me](kia.king.08@gmail.com) to explain what exactly your app does? Maybe I can give you much better advice then!

**Comment by clockworked247** [comment]
> When using Vuex, you should almost always avoid mutating the value outside of mutation handler. Which means when you want to update the value, use actions.

@kiaking Yes, thanks.  I know this.  I should have left out the mutations comment.  I meant just actions and getters.

Thanks for the example use of getter & dispatch.  My app is quite complex, so I just tried to create a simple example here to illustrate the issue I was facing.

I'll play around a bit more with this today and will eventually close this issue.  I just want to make sure I don't have any follow-ups before closing.

**Comment by kiaking** [comment]
OK, great. Feel free to ask here if you have any other trouble!

**Comment by clockworked247** [comment]
@kiaking is there a shortcut way to return all objects in a hierarchy?   For instance:

Current code containing statements that go 4 levels deep:

```
Vue.$store.getters['entities/workspaces/query']()
            .with('queries.pane.query').with('queries.pane.explore.obj').with('queries.pane.profile')
            .where('active', true)
            .limit(1).get()[0];
```

written like:

```
Vue.$store.getters['entities/workspaces/query']()
            .withAll()
            .where('active', true)
            .limit(1).get()[0];
```

It'd be nice to just shortcut all the explicit "with" calls and just return the full object hierarchy.

Thanks.

**Comment by kiaking** [comment]
`withAll` method could be a good feature addition! All create a new issue for that 👍 

However, be careful with your use of with, you can't do that. You have to nest queries if you want to call nested `with` which have same top level name.

Vue.$store.getters['entities/workspaces/query']()
  .with('queries', (query) => {
    query.with('pane', (query) => {
      query.with('query').with('explore.obj').with('profile')
    })
  })
  .where('active', true)
  .first()

**Comment by clockworked247** [comment]
Thanks @kiaking   Closing this issue.

**Comment by kiaking** [comment]
Glad to help!
