### ISSUE TITLE
belongsTo relationship is broken since 0.20.0

### ISSUE THREAD

**Issue by timoschwarzer** [vuex-orm/vuex-orm#96]
I have a Message with an author field, which is a User entity. When fetching the Message with `.with('author')` the author field is null since vuex-orm 0.20.0.

I wrote a test for this case. It fails in 0.20.0 and passes in 0.19.0.
https://github.com/vuex-orm/vuex-orm/pull/95/commits/977b4ea11fdf89e3d3faa45aa1dcfd891c4236a6

I'll try to bisect the commit that causes the problem.

**Comment by timoschwarzer** [comment]
This is the first commit where the test fails:
https://github.com/vuex-orm/vuex-orm/commit/4f6cb71dc46e9b67b900c251885c1dac653116f9

**Comment by kiaking** [comment]
Damn sorry this is my bad. When refactoring largely on 0.20.0, I forgot to implement auto relational filed generation. I'll fix this soon with more complete solution. Before the id generation woke only with `belongsTo` relation with certain order ob nested data.

For a short time before I fix this, you have to manually set `user_id` for the Message model :(

**Comment by timoschwarzer** [comment]
No problem! Take your time, I can just stay on 0.19.0 for the time being. :sweat_smile: 
Keep up the great work! :smile:

**Comment by kiaking** [comment]
This is fixed at Vuex ORM 0.20.2! 🔥 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.20.2

Sorry for the inconvenient!

**Comment by timoschwarzer** [comment]
No problem and thank you for your work! :smile:

**Comment by kiaking** [comment]
👍
